import {test} from 'node:test';import assert from 'node:assert/strict';
import {isolatedCancellation} from '../support/h4-cancellation-isolated.ts';import {cancellationFixture} from '../support/h4-cancellation-fixtures.ts';
test('H4-014-F07 minimal missing Administrator reason cannot admit D019 partial base',async()=>{const h=await isolatedCancellation('crm_f14_reason',56805);try{const f=await cancellationFixture(h,{scopeKind:'service'}),q=await f.command(),base:any=await f.base('200.00');delete base.administratorDecision.reason;await assert.rejects(f.run(await f.command({facts:{...q.facts!,base}})),/ADMIN_BASE_REQUIRED/);assert.equal(await f.see(),null);}finally{await h.close();}});
import {modificationFixture} from '../support/h4-modification-fixtures.ts';
import {read} from '../support/h4-cancellation-isolated.ts';
test('H4-014-F14 D020 same civil day hour change does not invalidate independent cancellation interval',async()=>{const h=await isolatedCancellation('crm_f14_hour',56806);try{const f=await cancellationFixture(h),q=await f.command();await f.run(q);const m=await modificationFixture(h,f.conf);await m.run(await m.request([{id:m.partId,scope:m.scope,expectedScopeRevision:1,desired:{schedule:{requested:'11:00',final:'12:30:00+02:00',sourceRef:'SYNTHETIC explicit same-date hour agreement'}},aspects:['time'],dependencies:[]} ]));await m.run(await m.evaluate());await m.run(await m.approve());await m.run(await m.apply());const projection=await h.cancellations.read(await h.auth(),read,f.b.bookingId,f.did,'right');assert.equal(projection.currentlyApplicable,true);assert.equal(projection.right,'50.01');}finally{await h.close();}});

import {randomUUID as uid} from 'node:crypto';
test('H4-014-F17 overlapping determinations cannot mint duplicate participation rights',async()=>{const h=await isolatedCancellation('crm_f14_portion',56807);try{const f=await cancellationFixture(h,{count:3}),q=await f.command();await f.run(await f.command({facts:{...q.facts!,base:{...q.facts!.base,count:2,start:0}}}));await assert.rejects(f.run(await f.command({determinationId:uid(),facts:{...q.facts!,base:{...q.facts!.base,count:2,start:1}}})),/PORTION_CONFLICT/);assert.equal((await h.observer`select count(*)::int n from crm_private.b06_cancellation_determinations where booking_id=${f.b.bookingId}::uuid`)[0]!.n,1);}finally{await h.close();}});
