import {test}from'node:test';import assert from'node:assert/strict';import {randomUUID as uid}from'node:crypto';
import {isolatedPreparation,read,write}from'../support/h4-booking-preparation-isolated.ts';
import {preparationFixture}from'../support/h4-booking-preparation-fixtures.ts';
import {observePreparation}from'../support/h4-booking-preparation-observation.ts';
import {H0005PostgresAdapter}from'../../src/infrastructure/postgres/h0-005-adapter.ts';
import {H4020BookingPreparationAdapter}from'../../src/infrastructure/postgres/h4-booking-preparation-adapter.ts';
import {verifyAuth}from'../../src/application/verified-auth.ts';
import {requirementFixture}from'../support/h4-requirement-fixtures.ts';
import {modificationFixture}from'../support/h4-modification-fixtures.ts';
import {H4009ConfirmationAdapter}from'../../src/infrastructure/postgres/h4-confirmation-adapter.ts';
import {H4001RequirementAdapter}from'../../src/infrastructure/postgres/h4-requirement-adapter.ts';
import {H4011ModificationAdapter}from'../../src/infrastructure/postgres/h4-modification-adapter.ts';
import {H3003PaymentAdapter}from'../../src/infrastructure/postgres/h3-payment-adapter.ts';
test('H4-021 both orders observed after compatible F2 admission on real Booking root',async t=>{const h=await isolatedPreparation('crm_h4021_races',58203);try{
 const access=new H0005PostgresAdapter(h.connect('crm_h0_runtime'),h.f1,h.f2),subject=h.subject;const first=await verifyAuth({verify:async()=>({subject,passwordVerified:true,mfaVerified:true})},uid());const sessionId=(await access.establish(first)).sessionId;
 const other=()=>verifyAuth({verify:async()=>({subject,sessionId,passwordVerified:true,mfaVerified:true})},uid());const second=h.connect('crm_h0_runtime'),prep=new H4020BookingPreparationAdapter(second,h.f1,h.f2),conf=new H4009ConfirmationAdapter(second,h.f1,h.f2),requirements=new H4001RequirementAdapter(second,h.f1,h.f2),payments=new H3003PaymentAdapter(second,h.f1,h.f2);
 const modifications=new H4011ModificationAdapter(second,h.f1,h.f2);
 const sessions=[h.sessionId,sessionId];
 for(const order of [[0,1],[1,0]]){
  await t.test('B54 two confirmations order'+order,async()=>{const f=await preparationFixture(h);await f.confirm();await f.pay();const a=await f.command(),b=await f.attest({...a,operationId:uid()});const r=await observePreparation(h,f.bid,[()=>f.run(a),async()=>prep.apply(await other(),write,b)],order,sessions);assert.equal(r.filter(x=>x.ok).length,1);assert.equal((await f.see())!.history.length,1);});
  await t.test('B52/B54 same-operation replay order'+order,async()=>{const f=await preparationFixture(h);await f.confirm();await f.pay();const q=await f.command();const r=await observePreparation(h,f.bid,[()=>f.run(q),async()=>prep.apply(await other(),write,q)],order,sessions);assert.ok(r.every(x=>x.ok));assert.equal((await f.see())!.history.length,1);});
  await t.test('B55 confirmation versus critical loss order'+order,async()=>{const f=await preparationFixture(h);await f.confirm();await f.pay();await f.run(await f.command('start'));const q=await f.command(),change=await f.conf.review();const r=await observePreparation(h,f.bid,[()=>f.run(q),async()=>conf.apply(await other(),write,change)],order,sessions);assert.equal(r.filter(x=>x.ok).length,order[0]===0?2:1);const v=(await f.see())!;assert.equal(v.phase,'En confirmación con proveedores');if(order[0]===0)assert.equal(v.historicalPhase,'Confirmada operativamente');});
  await t.test('B56 confirmation versus new indispensable documentary need order'+order,async()=>{const f=await preparationFixture(h);await f.confirm();await f.pay();const d=await requirementFixture(h,{bookingId:f.bid,b:{detail:f.o.detail}}as any),q=await f.command(),need=await d.need();const r=await observePreparation(h,f.bid,[()=>f.run(q),async()=>requirements.apply(await other(),write,need)],order,sessions);assert.equal(r.filter(x=>x.ok).length,order[0]===0?2:1);assert.equal((await f.see())!.phase,order[0]===0?'Parcialmente confirmada':'Pendiente de preparación');});
  await t.test('B57 confirmation versus applied date change order'+order,async()=>{const f=await preparationFixture(h);await f.confirm();await f.pay();await f.run(await f.command('start'));const m=await modificationFixture(h,f.conf);await m.run(await m.request());await m.run(await m.evaluate());await m.run(await m.approve());const q=await f.command(),change=await m.apply();const r=await observePreparation(h,f.bid,[()=>f.run(q),async()=>modifications.apply(await other(),write,change)],order,sessions);assert.equal(r.filter(x=>x.ok).length,order[0]===0?2:1);assert.notEqual((await f.see())!.phase,'Confirmada operativamente');});
  await t.test('B59 exact TTE approval versus critical material change order'+order,async()=>{const f=await preparationFixture(h);await f.confirm();await f.pay();await f.run(await f.command('start'));const q=await f.command('evaluate',{origin:'ai'}),a=await f.approval(q),change=await f.conf.review();const r=await observePreparation(h,f.bid,[()=>a.execute(),async()=>conf.apply(await other(),write,change)],order,sessions);assert.equal(r.filter(x=>x.ok).length,order[0]===0?2:1);assert.equal((await f.see())!.phase,'En confirmación con proveedores');assert.equal((await h.observer`select count(*) n from crm_ha.reservations where reservation_id=${a.reserve}`)[0]!.n,order[0]===0?'1':'0');});
  await t.test('B58 confirmation versus legitimate reconciliation discrepancy order'+order,async()=>{const f=await preparationFixture(h);await f.confirm();const p=await f.pay();const q=await f.command(),change=await p.attestPay({...p.base,sourceEvidenceId:undefined,action:'discrepancy',operationId:uid(),expectedRevision:4,incidentId:uid(),reconciliationId:p.reconciliationId,start:'0.00',amount:'100.00'});const r=await observePreparation(h,f.bid,[()=>f.run(q),async()=>payments.apply(await other(),write,change)],order,sessions);assert.equal(r.filter(x=>x.ok).length,order[0]===0?2:1);assert.notEqual((await f.see())!.phase,'Confirmada operativamente');});
 }
}finally{await h.close();}});
