// Expected frozen before implementation in evidence H2-004, commit 69a0ef1.
// Independent normative inputs/oracles; helper provisions cluster/auth/H1 adapters only.
import assert from "node:assert/strict";
import {before,after,test} from "node:test";
import {randomUUID} from "node:crypto";
import {readFile} from "node:fs/promises";
import {isolatedProposal,proposalMigration,write,read} from "../support/h2-proposal-isolated.ts";
import {H2003ProposalAdapter,type ProposalCommand} from "../../src/infrastructure/postgres/h2-proposal-adapter.ts";
import {H0005PostgresAdapter} from "../../src/infrastructure/postgres/h0-005-adapter.ts";
import {verifyAuth} from "../../src/application/verified-auth.ts";
import {createF1Issuer,encodeF1Fields} from "../../src/infrastructure/postgres/f1-codec.ts";
import {createF2Issuer} from "../../src/infrastructure/postgres/f2-codec.ts";
import {issueTrustedContext} from "../../src/application/trusted-context.ts";
import {postgresF1Binding} from "../../src/infrastructure/postgres/transaction.ts";
import {reconstructCalculation,captureCalculation} from "../../src/domain/exact-money.ts";
import type {ProposalContent} from "../../src/domain/proposal-version.ts";
let h:Awaited<ReturnType<typeof isolatedProposal>>,migrationBefore:unknown,migrationAfter:unknown,oldPermissionBefore:unknown,oldPermissionAfter:unknown;
const uid=randomUUID;
async function snapshot(tables?:string[]){const out:Record<string,unknown>={};for(const t of tables??['b03_proposals','b03_preparations','b03_proposal_versions','b03_proposal_modalities','b03_proposal_lines','b03_proposal_operations','b03_proposal_history','b03_opportunities','b03_history','b03_operations','identity_codes','identity_code_counters','identity_history','identity_operations'])out[t]=(await h.observer.unsafe(`select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]') data from crm_private.${t} t`))[0]!.data;return out;}
async function permissions(){return {
 tables:await h.observer`select c.oid,c.relname,c.relacl::text,c.relowner::regrole::text,c.relrowsecurity,c.relforcerowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('crm_private','crm_f1','crm_f2') and c.relkind='r' and c.relname not like 'b03_proposal%' and c.relname<>'b03_preparations' order by c.oid`,
 columns:await h.observer`select c.relname,a.attname,a.attacl::text from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='crm_private' and c.relkind='r' and c.relname not like 'b03_proposal%' and c.relname<>'b03_preparations' and a.attnum>0 order by c.relname,a.attnum`,
 policies:await h.observer`select c.relname,p.polname,p.polroles::text,pg_get_expr(p.polqual,p.polrelid) q,pg_get_expr(p.polwithcheck,p.polrelid) w from pg_policy p join pg_class c on c.oid=p.polrelid where c.relname not like 'b03_proposal%' and c.relname<>'b03_preparations' order by c.relname,p.polname`,
 functions:await h.observer`select p.oid,p.oid::regprocedure::text,p.proacl::text,p.proowner::regrole::text,md5(pg_get_functiondef(p.oid)) hash from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('crm_api','crm_private','crm_f1','crm_f2') and p.proname not like 'proposal_%' order by p.oid`,
 roles:await h.observer`select rolname,rolsuper,rolbypassrls,rolcreaterole,rolcreatedb from pg_roles order by rolname`,
 schemas:await h.observer`select nspname,nspacl::text from pg_namespace where nspname like 'crm_%' order by nspname`,
 memberships:await h.observer`select roleid::regrole::text,member::regrole::text,admin_option,inherit_option,set_option from pg_auth_members order by roleid,member`
};}
async function fixture(){
 const service=await h.cat('service',{name:'FORMAL SYNTHETIC rafting',nature:'external'}),unit=await h.cat('unit',{name:'FORMAL fixed group',definition:'entire group; never per-person'}),form=await h.cat('pricing_form',{name:'FORMAL fixed price',definition:'fixed group'});
 const def={label:'FORMAL source',price_state:'confirmed',amount:'900.00',cost_state:'confirmed',cost_amount:'700.00',vat_treatment:'included',unit_revision_id:unit.revision,pricing_form_revision_id:form.revision};
 const tariff=await h.com('tariff',def,service),pack=await h.com('custom_pack',{name:'FORMAL custom',components:[{service_revision_id:service.revision,unit_revision_id:unit.revision,quantity:'1',included:true}],conditions:'FORMAL terms'});
 const opp=h.input({sourceRef:'FORMAL leadless opportunity',reason:'FORMAL verified three minima'});await h.adapter.apply(await h.auth(),write,opp);
 const content:ProposalContent={scope:'FORMAL group scope',terms:{version:'FORMAL T1',text:'FORMAL conditions; mandate unknown',sourceRef:'FORMAL terms source'},pending:['mandate','availability'],modalities:[{id:uid(),name:'FORMAL A',participants:10,independent:true,selectable:true,packRevisionId:pack.revision,conditions:'FORMAL modality conditions',finalPersonPrice:'100.01',manualReason:'FORMAL manual price decision',definitive:true,lines:[{id:uid(),serviceRevisionId:service.revision,unitRevisionId:unit.revision,tariffRevisionId:tariff.revision,quantity:'1',included:true,independent:false,selectable:false,date:null,datePending:true,priceBasis:'fixed',costMaterial:true,sourceRef:'FORMAL quantity source'}]}]};
 const cmd:ProposalCommand={action:'prepare',operationId:uid(),proposalId:uid(),opportunityId:opp.targetId,expectedRevision:0,expectedOpportunityRevision:1,sourceRef:'FORMAL origin',reason:'FORMAL intent',content};return {service,unit,form,tariff,def,pack,opp,content,cmd};
}
async function prepare(f:Awaited<ReturnType<typeof fixture>>){await h.proposal.apply(await h.auth(),write,f.cmd);return f;}
function fix(f:Awaited<ReturnType<typeof fixture>>,change:Partial<ProposalCommand>={}):ProposalCommand{return {...f.cmd,action:'fix',content:undefined,operationId:uid(),versionId:uid(),expectedRevision:1,...change};}
async function fixed(){const f=await prepare(await fixture()),x=fix(f);await h.proposal.apply(await h.auth(),write,x);return {...f,x,v:await internal(f.cmd.proposalId,x.versionId)};}
async function internal(p:string,v?:string){return await h.proposal.read(await h.auth(),read,p,'internal',v) as any;}
async function reject(cmd:ProposalCommand,raw=false){const before=await snapshot();await assert.rejects(raw?rawApply({...cmd}):h.proposal.apply(await h.auth(),write,cmd));assert.deepEqual(await snapshot(),before);}
async function rawApply(input:Record<string,unknown>,scopeOverride?:string,tamper=false){
 const auth=await h.auth(),f1=createF1Issuer(h.f1),f2=createF2Issuer(h.f2);
 return h.runtime.begin(async tx=>{
  const row=(await tx`select actor_id::text,admin_scope,access_generation::text,epoch_id::text from crm_api.f2_lookup(${auth.subject}::uuid,${auth.sessionId!}::uuid)`)[0]!;
  const scope=scopeOverride??row.admin_scope,binding=await postgresF1Binding(tx),identity={actorId:row.actor_id,scope,accessGeneration:row.access_generation,sessionId:auth.sessionId!,epochId:row.epoch_id};
  const context=(purpose:string)=>issueTrustedContext({identityId:'formal independent signer',identityKind:'technical',purpose,scope,requestId:uid(),serverTime:new Date().toISOString()});
  const q=encodeF1Fields(['CRM-H2-PROP-1',JSON.stringify(input)]),human=f2(auth,identity,binding,'evidence_write',q,write),technical=f1(context('h1-evidence'),binding,'C03',q,{resource:'evidence',action:'write_evidence'});
  const cq=encodeF1Fields(['CRM-H1-RESOLVE1','assign_code',String(input.proposalId),String(input.proposalId),'','PR',String(input.sourceRef),String(input.sourceRef),String(input.reason),'0']),ch=f2(auth,identity,binding,'identity_write',cq,write),ct=f1(context('h1-identities'),binding,'C03',cq,{resource:'identities',action:'write_identity'});
  return tx.unsafe('select * from crm_api.proposal_apply($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[human.payload,tamper?Buffer.alloc(32):human.mac,technical.payload,technical.mac,q,ch.payload,ch.mac,ct.payload,ct.mac,cq]);
 });
}
async function revise(f:Awaited<ReturnType<typeof fixed>>,content:ProposalContent){const c={...f.cmd,operationId:uid(),expectedRevision:2,expectedOpportunityRevision:2,content,baseVersionId:f.x.versionId,reviewed:true};await h.proposal.apply(await h.auth(),write,c);const x=fix(f,{expectedRevision:3});await h.proposal.apply(await h.auth(),write,x);assert.deepEqual(await internal(f.cmd.proposalId,f.x.versionId),f.v);const v=await internal(f.cmd.proposalId,x.versionId);assert.equal(v.version_number,2);assert.equal(v.replaces_version_id,f.x.versionId);return v;}
before(async()=>{
 h=await isolatedProposal('crm_h2_004',55467,true);
 const old=await fixture();const ev=h.req('evidence',{claim:'FORMAL prior reviewed fact',coverage:'synthetic-scope',certainty:'reviewed',source_kind:'manual'},old.opp.targetId);await h.evidence.apply(await h.auth(),write,ev);
 await h.evidence.apply(await h.auth(),write,h.req('communication',{direction:'incoming',channel:'manual',recipient_ref:'synthetic-client',sender_ref:'synthetic-client',coverage:'synthetic-scope',initial_fact:'received'},old.opp.targetId));
 const lead=h.input({action:'lead',material:{contact:null,need:null,commercialPossible:null,pending:['contact','need','possibility']}});await h.adapter.apply(await h.auth(),write,lead);
 await h.identities.apply(await h.auth(),write,{action:'create_entity',operationId:uid(),targetId:uid(),kind:'contact',expectedVersion:0,sourceRef:'FORMAL prior contact',reason:'FORMAL fixture',verified:false,displayName:'FORMAL SYNTHETIC CONTACT'});
 await h.tasks.apply(await h.auth(),write,{action:'receive',operationId:uid(),taskId:uid(),expectedRevision:0,identity:{causeKind:'review',causeId:uid(),contextKind:'opportunity',contextId:old.opp.targetId,scopeRef:'synthetic-scope',relatedKind:null,relatedId:null,effect:'review-only'},material:{title:'FORMAL prior task',deadline:{kind:'unknown',reason:'pending'},priority:{kind:'pending',reason:'pending'},sourceRef:'FORMAL prior',sourceVersion:'v1',triggerRef:'manual',triggerVersion:'v1'},reason:'FORMAL prior need'});
 const tables=(await h.observer`select c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='crm_private' and c.relkind='r' order by c.relname`).map(x=>x.relname as string);
 migrationBefore=await snapshot(tables);oldPermissionBefore=await permissions();
 await h.migration.unsafe(await readFile(new URL(`../../supabase/migrations/${proposalMigration}`,import.meta.url),'utf8'));
 migrationAfter=await snapshot(tables);oldPermissionAfter=await permissions();
});after(async()=>{await h?.close();});
test('R01 preparation real Opportunity, PR and atomic commercial progress',async()=>{const f=await prepare(await fixture());const o=(await h.observer`select state,revision from crm_private.b03_opportunities where opportunity_id=${f.opp.targetId}::uuid`)[0]!;assert.equal(o.state,'Propuesta en preparación');assert.equal(o.revision,'2');assert.equal((await h.observer`select count(*)::int n from crm_private.b03_proposals where proposal_id=${f.cmd.proposalId}::uuid`)[0]!.n,1);assert.match((await h.observer`select human_code from crm_private.identity_codes where target_id=${f.cmd.proposalId}::uuid`)[0]!.human_code,/^PR-/);});
test('R02 each preparation guard removed, no side effect',async()=>{const f=await fixture();for(const c of [{...f.cmd,opportunityId:uid()},{...f.cmd,sourceRef:''},{...f.cmd,content:{...f.content,scope:''}},{...f.cmd,content:{...f.content,pending:undefined}},{...f.cmd,content:{...f.content,terms:{...f.content.terms,sourceRef:''}}}])await reject(c as ProposalCommand);});
test('R03 independent alternatives retained',async()=>{const f=await prepare(await fixture());const p={...f.cmd,proposalId:uid(),operationId:uid(),expectedOpportunityRevision:2};await h.proposal.apply(await h.auth(),write,p);assert.equal((await h.observer`select count(*)::int n from crm_private.b03_proposals where opportunity_id=${f.opp.targetId}::uuid`)[0]!.n,2);});
test('R04 fixed v1 exact linked preparation; not sent or verified',async()=>{const f=await fixed();assert.equal(f.v.version_number,1);assert.deepEqual(f.v.content,f.content);assert.equal(f.v.preparation_id,f.cmd.operationId);assert.equal(f.v.actor_id,h.actorId);assert.equal('sent_at' in f.v,false);});
test('R05 individual fixed guards quantities/participants/composition/conditions/sources',async()=>{for(const guard of ['quantity','participants','composition','conditions','sources','terms']){const f=await fixture();const c=structuredClone(f.content) as any;if(guard==='quantity')c.modalities[0].lines[0].quantity=null;if(guard==='participants')c.modalities[0].participants=null;if(guard==='composition')c.modalities=[];if(guard==='conditions')c.modalities[0].conditions='';if(guard==='sources')c.modalities[0].lines[0].serviceRevisionId=uid();if(guard==='terms')c.terms.text='';f.cmd={...f.cmd,content:c};if(['quantity','participants'].includes(guard)){await prepare(f);await reject(fix(f));}else await reject(f.cmd);}});
test('R06 ordinary contract cannot edit fixed v1',async()=>{const f=await fixed();await reject({...fix(f),expectedRevision:2,content:{...f.content,scope:'EDIT'}});assert.deepEqual(await internal(f.cmd.proposalId,f.x.versionId),f.v);});
for(const [r,field] of [[7,'price'],[8,'composition'],[9,'terms'],[10,'selectability']] as const)test(`R${String(r).padStart(2,'0')} material ${field} creates v2 and keeps v1`,async()=>{const f=await fixed(),c=structuredClone(f.content) as any;if(field==='price')c.modalities[0].finalPersonPrice='110.00';if(field==='composition')c.modalities[0].lines[0].quantity='2';if(field==='terms')c.terms={...c.terms,version:'T2',text:'REVISED terms'};if(field==='selectability'){c.modalities[0].lines[0].independent=true;c.modalities[0].lines[0].selectable=true;}await revise(f,c);});
test('R11 SM-PV06 before/after/review/motive/base individually guarded',async()=>{const f=await fixed(),c={...f.content,scope:'reviewed new scope'},cmd={...f.cmd,operationId:uid(),expectedRevision:2,expectedOpportunityRevision:2,baseVersionId:f.x.versionId,reviewed:true,content:c};for(const bad of [{...cmd,reason:''},{...cmd,baseVersionId:uid()},{...cmd,reviewed:false},{...cmd,content:f.content},{...cmd,baseVersionId:undefined}])await reject(bad);await h.proposal.apply(await h.auth(),write,cmd);const history=await h.proposal.read(await h.auth(),read,f.cmd.proposalId,'history') as any[];const {human_code,...base}=f.v;assert.deepEqual(history.at(-1).before_data,base);assert.deepEqual(history.at(-1).after_data.content,c);assert.equal(history.at(-1).reason,cmd.reason);});
test('R12 AC013 nonselectable partial request recorded no historical repair',async()=>{const f=await fixed(),ev=h.req('evidence',{claim:'client requests only rafting',coverage:'synthetic-scope',certainty:'reviewed',source_kind:'manual'},f.opp.targetId);await h.evidence.apply(await h.auth(),write,ev);const c={...fix(f),action:'partial_request' as const,expectedRevision:2,versionId:f.x.versionId,partId:f.content.modalities[0]!.lines[0]!.id,requestEvidenceId:ev.targetId};await h.proposal.apply(await h.auth(),write,c);const hist=await h.proposal.read(await h.auth(),read,f.cmd.proposalId,'history') as any[];assert.equal(hist.at(-1).after_data.requiresNewVersion,true);assert.equal(hist.at(-1).after_data.acceptanceCreated,false);assert.deepEqual(await internal(f.cmd.proposalId,f.x.versionId),f.v);await reject({...c,operationId:uid(),requestEvidenceId:uid()});});
test('R13 modalities preserve rafting10/cena12/night12/night10 contributions',async()=>{const f=await fixture(),a=f.content.modalities[0]!,base=a.lines[0]!;const line=(date:string|null,q:string)=>({...base,id:uid(),date,datePending:date===null,quantity:q,priceBasis:'quantity' as const});const c={...f.content,modalities:[{...a,lines:[line(null,'10'),line('2026-12-01','10'),line('2026-12-02','10'),line(null,'10')]},{...a,id:uid(),name:'B without rafting',participants:2,lines:[line('2026-12-01','2'),line(null,'2')]}]};f.cmd={...f.cmd,content:c};await prepare(f);const x=fix(f);await h.proposal.apply(await h.auth(),write,x);const rows=await h.observer`select service_date::text d,sum(quantity)::text q from crm_private.b03_proposal_lines where version_id=${x.versionId!}::uuid and service_date is not null group by service_date order by service_date`;assert.deepEqual(rows.map(x=>[x.d,x.q]),[['2026-12-01','12'],['2026-12-02','10']]);assert.equal((await internal(f.cmd.proposalId)).content.modalities[1].lines.length,2);});
test('R14 exact PM02 100.01 x10 =1000.10',async()=>{const f=await fixed();assert.equal(f.v.economics[0].finalCalculation.output.amount,'1000.10');assert.equal(f.v.economics[0].finalCalculation.input.finalPersonPrice,'100.01');});
test('R15 calculated90/manual100.01/difference10.01 actor and immutable costs',async()=>{const f=await fixed(),e=f.v.economics[0];assert.equal(e.calculated,'90.00');assert.equal(e.final,'100.01');assert.equal(e.difference,'10.01');assert.equal(e.manual.actorRef,h.actorId);assert.equal(e.manual.reason,f.content.modalities[0]!.manualReason);assert.equal(e.components[0].cost,'700.00');assert.equal(e.components[0].quantity,'1');});
test('R16 commercial projection excludes economics outside UI',async()=>{const f=await fixed(),data=await h.proposal.read(await h.auth(),read,f.cmd.proposalId,'commercial') as any[];assert.deepEqual(Object.keys(data[0]!).sort(),['finalPersonPrice','included','participants']);assert.equal(data[0].finalPersonPrice,'100.01');const json=JSON.stringify(data);for(const secret of ['700.00','900.00','calculated','cost','manual','actorRef','reason','unit_revision'])assert.equal(json.includes(secret),false);await assert.rejects(h.runtime`select economics from crm_private.b03_proposal_versions`,/permission denied/);});
test('R17 unknown material cost only dependent fixation blocked, independent work allowed',async()=>{const f=await fixture(),t=await h.com('tariff',{...f.def,cost_state:'unknown',cost_amount:undefined},f.service);const c=structuredClone(f.content) as any;c.modalities[0].lines[0].tariffRevisionId=t.revision;f.cmd={...f.cmd,content:c};await prepare(f);const p=await h.proposal.read(await h.auth(),read,f.cmd.proposalId,'preparation') as any;assert.equal(p.economics[0].components[0].cost,null);await reject(fix(f));c.modalities[0].definitive=false;await h.proposal.apply(await h.auth(),write,{...f.cmd,operationId:uid(),expectedRevision:1,expectedOpportunityRevision:2,content:c});await h.proposal.apply(await h.auth(),write,fix(f,{expectedRevision:2}));const independent=await fixed();assert.equal(independent.v.economics[0].components[0].cost,'700.00');});
test('R18 exact unit/tariff/pack references preserved structurally',async()=>{const f=await fixed(),l=(await h.observer`select * from crm_private.b03_proposal_lines where version_id=${f.x.versionId!}::uuid`)[0]!;assert.equal(l.unit_revision_id,f.unit.revision);assert.equal(l.tariff_revision_id,f.tariff.revision);assert.equal(l.service_revision_id,f.service.revision);assert.equal(f.v.sources.find((s:any)=>s.id===f.pack.revision).kind,'custom_pack');});
test('R19 masters changed later preserve v1',async()=>{const f=await fixed();await h.commercial.apply(await h.auth(),write,{action:'publish',operationId:uid(),targetId:f.tariff.id,kind:'tariff',catalogItemId:f.service.id,catalogRevisionId:f.service.revision,definition:{...f.def,amount:'2000.00'},sourceRef:'later synthetic price',evidenceRef:'later proof',reason:'changed master',expectedVersion:1});await h.catalog.apply(await h.auth(),write,{action:'publish_version',operationId:uid(),targetId:f.service.id,kind:'service',definition:{name:'later synthetic service',nature:'external'},sourceRef:'later source',evidenceRef:'later proof',reason:'later master',expectedVersion:1});assert.deepEqual(await internal(f.cmd.proposalId,f.x.versionId),f.v);});
test('R20 PM09 replay historical calculation and unknown is not zero',async()=>{const f=await fixed();assert.equal((reconstructCalculation(f.v.economics[0].finalCalculation) as any).amount,'1000.10');assert.equal((reconstructCalculation(f.v.economics[0].calculation) as any).amount,'90.00');const trace=f.v.economics[0].calculation.trace;for(const input of [{kind:'percentage',base:'1000.01',percent:'50'},{kind:'percentage',base:'100.01',percent:'50'},{kind:'participations',baseEach:'100.01',participations:3,percent:'50'},{kind:'remaining',fixedRight:'50.01',paid:['20.00']},{kind:'fixed',total:'900.00',previousParticipants:10,currentParticipants:8},{kind:'reversal',originalRef:'original',originalAmount:'500.01',reason:'inverse'}] as const){const record=captureCalculation(input,trace);assert.deepEqual(reconstructCalculation(record),record.output);}});
test('R21 direct SQL runtime/API roles denied and private FORCE RLS',async()=>{const f=await fixed();for(const role of ['crm_h0_runtime','anon','authenticated']){const sql=h.connect(role);await assert.rejects(sql`update crm_private.b03_proposal_versions set scope='injected' where version_id=${f.x.versionId!}::uuid`,/permission denied/);await assert.rejects(sql`delete from crm_private.b03_proposal_versions`,/permission denied/);}const rows=await h.observer`select relrowsecurity,relforcerowsecurity from pg_class where relname in ('b03_proposals','b03_preparations','b03_proposal_versions','b03_proposal_modalities','b03_proposal_lines','b03_proposal_operations','b03_proposal_history')`;assert.equal(rows.length,7);assert.ok(rows.every(r=>r.relrowsecurity&&r.relforcerowsecurity));const role=(await h.observer`select rolsuper,rolbypassrls from pg_roles where rolname='crm_h0_runtime'`)[0]!;assert.equal(role.rolsuper,false);assert.equal(role.rolbypassrls,false);});
test('R22 missing context denied with no writes',async()=>{const before=await snapshot();await assert.rejects(h.runtime.unsafe('select * from crm_api.proposal_apply(null,null,null,null,null,null,null,null,null,null)'));assert.deepEqual(await snapshot(),before);});
test('R23 forged context/signature denied with no writes',async()=>{const f=await fixture(),before=await snapshot();await assert.rejects(rawApply({...fix(f)},'forged-scope'));await assert.rejects(rawApply({...fix(f)},undefined,true));assert.deepEqual(await snapshot(),before);});
test('R24 disabled actor denies write/read/replay',async()=>{const f=await fixed(),before=await snapshot();await h.admin`update crm_private.crm_actors set enabled=false where actor_id=${h.actorId}::uuid`;try{await assert.rejects(h.proposal.apply(await h.auth(),write,f.x));await assert.rejects(h.proposal.read(await h.auth(),read,f.cmd.proposalId,'internal'));}finally{await h.admin`update crm_private.crm_actors set enabled=true where actor_id=${h.actorId}::uuid`;}assert.deepEqual(await snapshot(),before);});
test('R25 ordinary role/unprovisioned actor cannot use authorized contract',async()=>{const f=await fixture(),stranger=await verifyAuth({verify:async()=>({subject:uid(),sessionId:uid(),passwordVerified:true,mfaVerified:true})},uid()),before=await snapshot();await assert.rejects(h.proposal.apply(stranger,write,f.cmd));const anon=h.connect('authenticated');await assert.rejects(anon.unsafe('select * from crm_api.proposal_apply(null,null,null,null,null,null,null,null,null,null)'));assert.deepEqual(await snapshot(),before);});
async function fault(table:string,cmd:ProposalCommand){const before=await snapshot();await h.admin.unsafe(`create function crm_private.formal_proposal_fault() returns trigger language plpgsql as $$ begin raise exception 'FORMAL_ROLLBACK';end $$;create trigger formal_fault before insert on crm_private.${table} for each row execute function crm_private.formal_proposal_fault()`);try{await assert.rejects(h.proposal.apply(await h.auth(),write,cmd));assert.deepEqual(await snapshot(),before);}finally{await h.admin.unsafe(`drop trigger formal_fault on crm_private.${table};drop function crm_private.formal_proposal_fault()`);}}
test('R26 prewrite fault rolls back whole T01',async()=>{const f=await fixture();await fault('b03_proposals',f.cmd);});
test('R27 late history fault rolls back version/modalities/lines/result',async()=>{const f=await prepare(await fixture());await fault('b03_proposal_history',fix(f));});
test('R28 lost response after commit recovers equivalent original',async()=>{const f=await prepare(await fixture()),x=fix(f);await h.proposal.apply(await h.auth(),write,x);try{throw new Error('FORMAL_LOST_RESPONSE');}catch{}const before=await snapshot(),r=await h.proposal.apply(await h.auth(),write,x);assert.equal(r.replayed,true);assert.equal(r.id,x.versionId);assert.deepEqual(await snapshot(),before);const p=await h.proposal.apply(await h.auth(),write,f.cmd);assert.equal(p.replayed,true);assert.deepEqual(await snapshot(),before);});
test('R29 same key changed content is conflict not overwrite',async()=>{const f=await prepare(await fixture());await reject({...f.cmd,reason:'changed same key'});});
test('R30 two authorized sessions concurrent revision one winner',async()=>{const f=await fixed(),access=new H0005PostgresAdapter(h.connect('crm_h0_runtime'),h.f1,h.f2),first=await verifyAuth({verify:async()=>({subject:h.subject,passwordVerified:true,mfaVerified:true})},uid()),session=(await access.establish(first)).sessionId,auth=await verifyAuth({verify:async()=>({subject:h.subject,sessionId:session,passwordVerified:true,mfaVerified:true})},uid()),other=new H2003ProposalAdapter(h.connect('crm_h0_runtime'),h.f1,h.f2);for(const order of [false,true]){const p=order?await fixed():f;const a={...p.cmd,operationId:uid(),expectedRevision:2,expectedOpportunityRevision:2,baseVersionId:p.x.versionId,reviewed:true,content:{...p.content,scope:'A current reviewed'}},b={...a,operationId:uid(),content:{...p.content,scope:'B current reviewed'}};const requests=order?[other.apply(auth,write,b),h.proposal.apply(await h.auth(),write,a)]:[h.proposal.apply(await h.auth(),write,a),other.apply(auth,write,b)];const results=await Promise.allSettled(requests);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.deepEqual(await internal(p.cmd.proposalId,p.x.versionId),p.v);}});
test('R31 numbering race fixes only one v1, alternative unaffected',async()=>{const f=await prepare(await fixture()),x=fix(f),y=fix(f);const r=await Promise.allSettled([h.proposal.apply(await h.auth(),write,x),h.proposal.apply(await h.auth(),write,y)]);assert.equal(r.filter(r=>r.status==='fulfilled').length,1);const rows=await h.observer`select version_number from crm_private.b03_proposal_versions where proposal_id=${f.cmd.proposalId}::uuid`;assert.equal(rows.length,1);assert.equal(rows[0]!.version_number,'1');});
test('R32 independent observer sees complete history and results',async()=>{const f=await fixed();const rows=await h.observer`select h.history_id,o.result_ref,o.action from crm_private.b03_proposal_history h join crm_private.b03_proposal_operations o on o.operation_id=h.history_id where h.proposal_id=${f.cmd.proposalId}::uuid`;assert.equal(rows.length,2);assert.equal(rows.filter(r=>r.result_ref===f.x.versionId).length,1);});
test('R33 explicit SM-FORB02 SQL and ordinary edit both denied',async()=>{const f=await fixed(),before=await snapshot();await assert.rejects(h.runtime`update crm_private.b03_proposal_versions set economics='[]',content='{}',terms_text='ALTER' where version_id=${f.x.versionId!}::uuid`);await reject({...fix(f),expectedRevision:2,content:{...f.content,scope:'ALTER'}});assert.deepEqual(await snapshot(),before);});
test('R34 no Acceptance/Ganada/Booking/economic/operational effects',async()=>{const rows=await h.observer`select count(*)::int n from crm_private.b03_opportunities where state='Aceptada / Ganada'`;assert.equal(rows[0]!.n,0);const tables=await h.observer`select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='crm_private' and c.relkind='r' and (relname like '%acceptance%' or relname like '%booking%' or relname like '%refund%' or relname like '%payment%' or relname like '%provider_confirmation%')`;assert.equal(tables.length,0);});
test('R35 future commands rejected, no H2-005 capacities',async()=>{const f=await fixed();for(const action of ['send','expire','revalidate','reject','accept','win','book'])await reject({...fix(f),action:action as never,expectedRevision:2});assert.equal((await h.observer`select count(*)::int n from pg_proc where proname in ('proposal_send','proposal_accept','proposal_revalidate')`)[0]!.n,0);});
test('R36 SM-OP04 real preparation, origin/guards/pause forbid fake progress',async()=>{const f=await fixture();await reject({...f.cmd,expectedOpportunityRevision:99});await h.adapter.apply(await h.auth(),write,{action:'progress',operationId:uid(),targetId:f.opp.targetId,expectedRevision:1,sourceRef:'FORMAL pause',reason:'FORMAL pause',event:{type:'pause',sourceRef:'FORMAL pause',decision:'pause',context:'followup pending',followup:'manual decision'}});await reject({...f.cmd,expectedOpportunityRevision:2});const o=(await h.observer`select state from crm_private.b03_opportunities where opportunity_id=${f.opp.targetId}::uuid`)[0]!;assert.equal(o.state,'En pausa');});
test('R37 V-MIG prior fixtures/data/ACL and empty full chain',async()=>{assert.deepEqual(migrationAfter,migrationBefore);assert.deepEqual(oldPermissionAfter,oldPermissionBefore);await h.admin.unsafe('create database crm_h2_004_empty owner crm_h0_migration');const migration=h.connect('crm_h0_migration','crm_h2_004_empty'),admin=h.connect('h2_bootstrap','crm_h2_004_empty');await h.applyChain(migration,admin,proposalMigration);assert.equal((await migration`select count(*)::int n from crm_private.b03_proposal_versions`)[0]!.n,0);assert.equal((await migration`select count(*)::int n from pg_class where relname='b03_proposal_lines' and relforcerowsecurity`)[0]!.n,1);});
test('R38 exact sources, authorized estimates and unknown boundaries',async()=>{const f=await fixture();const wrong={...f.content,modalities:[{...f.content.modalities[0]!,lines:[{...f.content.modalities[0]!.lines[0]!,unitRevisionId:f.service.revision}]}]};await reject({...f.cmd,content:wrong});const t=await h.com('tariff',{...f.def,price_state:'estimated'},f.service);const c=structuredClone(f.content) as any;c.modalities[0].lines[0].tariffRevisionId=t.revision;await reject({...f.cmd,content:c});
 const e=h.req('evidence',{claim:'BR-ECON-001:approved-hotel-estimation',coverage:'synthetic-scope',certainty:'reviewed',source_kind:'manual'},f.opp.targetId);await h.evidence.apply(await h.auth(),write,e);c.modalities[0].lines[0].estimateRuleEvidenceId=e.targetId;c.modalities[0].definitive=false;
 await h.proposal.apply(await h.auth(),write,{...f.cmd,content:c});const x=fix(f);await h.proposal.apply(await h.auth(),write,x);
 const external=await h.proposal.read(await h.auth(),read,f.cmd.proposalId,'commercial') as any[];assert.equal(external[0].finalPersonPrice.certainty,'estimated');
});
