/** Independent expected 0b2ec96. Assertions derive from normative rows, never product decision helpers. */
import {test,before,after} from 'node:test';import assert from 'node:assert/strict';
import {randomUUID as uid} from 'node:crypto';import {readFile,readdir} from 'node:fs/promises';import {spawnSync} from 'node:child_process';
import {isolatedIncident,incidentMigration,incidentTables,write,read} from '../support/h4-incident-isolated.ts';
import {incidentFixture,type H} from '../support/h4-incident-fixtures.ts';
import {invoiceFixture} from '../support/h3-invoice-fixtures.ts';
import {requirementFixture} from '../support/h4-requirement-fixtures.ts';
import {H4003IncidentAdapter} from '../../src/infrastructure/postgres/h4-incident-adapter.ts';
import type {IncidentCommand} from '../../src/domain/incident.ts';
let h:H,shared:Awaited<ReturnType<typeof invoiceFixture>>;
type F=Awaited<ReturnType<typeof incidentFixture>>;
const tables=[...incidentTables,'identity_codes','identity_code_counters','identity_operations','identity_history'];
const apply=async(q:IncidentCommand)=>h.incidents.apply(await h.auth(),write,q);
const fixture=()=>incidentFixture(h,shared);
async function staged(status='Abierta'){const f=await fixture();await apply(await f.detect());if(status==='En gestión')await apply(await f.manage());if(['Resuelta','Cerrada'].includes(status))await apply(await f.resolve());if(status==='Cerrada')await apply(await f.close());return f;}
async function snapshot(x:H,names=tables){const out:Record<string,unknown>={};for(const name of names)out[name]=(await x.observer.unsafe(`select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]') d from crm_private.${name} t`))[0]!.d;return out;}
async function inventory(x:H){return {
 tables:Array.from(await x.observer`select c.oid,c.relname,c.relowner,c.relacl,c.relrowsecurity,c.relforcerowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname like 'crm%' and c.relkind in ('r','p') order by c.oid`),
 functions:Array.from(await x.observer`select p.oid,p.proname,p.proowner,p.proacl,p.proconfig,p.prosecdef from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname like 'crm%' order by p.oid`),
 policies:Array.from(await x.observer`select oid,polrelid,polname,polroles,polqual::text,polwithcheck::text from pg_policy order by oid`),
 triggers:Array.from(await x.observer`select oid,tgrelid,tgname,tgfoid,tgenabled from pg_trigger where not tgisinternal order by oid`),
 roles:Array.from(await x.observer`select oid,rolname,rolsuper,rolcanlogin,rolbypassrls,rolcreaterole,rolcreatedb from pg_roles order by oid`)};}
async function deny(q:IncidentCommand){const old=await snapshot(h);await assert.rejects(apply(q));assert.deepEqual(await snapshot(h),old);}
async function missing(f:F,q:IncidentCommand,keys:string[],scope='data'){
 for(const key of keys){for(const nullValue of [false,true]){const next=structuredClone(q) as unknown as Record<string,unknown>,obj=scope==='data'?next.data as Record<string,unknown>:next;if(nullValue)obj[key]=null;else delete obj[key];await deny(await f.attest(next as unknown as IncidentCommand));}}
}
const evaluate=async(f:F,purpose='complete-close',scope=f.impact.scope)=>h.incidents.evaluate(await h.auth(),read,f.bookingId,scope,purpose);
async function race(f:F,a:IncidentCommand,b:IncidentCommand){
 const other=new H4003IncidentAdapter(h.connect('crm_h0_runtime'),h.f1,h.f2),auth=await h.auth();
 const results=await Promise.allSettled([apply(a),other.apply(auth,write,b)]);
 assert.equal(results.filter(x=>x.status==='fulfilled').length,a.operationId===b.operationId?2:1);
 if(a.operationId!==b.operationId)assert.match(String((results.find(x=>x.status==='rejected') as PromiseRejectedResult).reason),/CONFLICT/);
 const view=(await f.state())!;assert.equal(view.history!.length,view.revision);return view;
}
async function fault(table:string,q:IncidentCommand,mode:'before'|'after'|'commit'='before'){
 const old=await snapshot(h);
 await h.admin.unsafe(`create function crm_private.h4004_fault() returns trigger language plpgsql as $$begin raise exception 'SYNTHETIC_H4_FAULT';end$$;create ${mode==='commit'?'constraint ':''}trigger h4004_fault ${mode==='before'?'before':'after'} insert on crm_private.${table} ${mode==='commit'?'deferrable initially deferred ':''}for each row execute function crm_private.h4004_fault()`);
 try{await assert.rejects(apply(q));assert.deepEqual(await snapshot(h),old);}finally{await h.admin.unsafe(`drop trigger h4004_fault on crm_private.${table};drop function crm_private.h4004_fault()`);}
 const result=await apply(q);assert.ok(result.result.id);
}
before(async()=>{h=await isolatedIncident('crm_h4004_matrix',56202);shared=await invoiceFixture(h);});after(async()=>{await h?.close();});
const cases:Record<string,()=>Promise<void>>={
 R01:async()=>{const f=await fixture();await apply(await f.detect());const v=(await f.state())!;assert.equal(v.status,'Abierta');assert.equal(v.severity,'Crítica');assert.equal(v.solution,null);assert.equal(v.facts,f.data.facts);assert.equal(v.hypothesis,f.data.hypothesis);assert.equal(v.happenedAt,f.data.happenedAt);assert.ok(v.history![0]!.recordedAt);assert.equal(v.history![0]!.before,null);},
 R02:async()=>{const f=await fixture(),q=await f.detect();await missing(f,q,['detectorId','happenedAt','description','facts','hypothesis','severity','impact','knownEvidence','effectLinks','context']);await missing(f,q,['sourceRef','reason','bookingId','at'], 'root');await deny(await f.attest({...q,bookingId:uid()}));await deny(await f.attest({...q,data:{...q.data,detectorId:uid()}}));},
 R03:async()=>{const f=await staged(),g=await staged();const a=(await f.state())!,b=(await g.state())!;assert.notEqual(a.id,b.id);assert.notEqual(a.code,b.code);const ledger=await h.observer`select code_kind,code_year,serial_number::int,assigned_at from crm_private.identity_codes where target_id in (${f.incidentId}::uuid,${g.incidentId}::uuid) order by serial_number`;assert.equal(ledger.length,2);assert.equal(ledger[1]!.serial_number,ledger[0]!.serial_number+1);assert.equal(ledger[0]!.code_kind,'INC');assert.notEqual(ledger[0]!.code_year,2024);assert.equal(a.code,`INC-${ledger[0]!.code_year}-${String(ledger[0]!.serial_number).padStart(4,'0')}`);},
 R04:async()=>{assert.deepEqual(Array.from(await h.observer`select crm_private.code_year_at('2026-12-31T22:59:59Z') a,crm_private.code_year_at('2026-12-31T23:00:00Z') b,crm_private.code_year_at('2026-07-01T22:00:00Z') c`),[{a:2026,b:2027,c:2026}]);const f=await staged();const old=(await f.state())!;await apply(await f.resolve());await apply(await f.close());await apply(await f.reopen());const v=(await f.state())!;assert.equal(v.code,old.code);assert.equal(v.assignedAt,old.assignedAt);},
 R05:async()=>{const f=await staged();await apply(await f.manage());const v=(await f.state())!;assert.equal(v.status,'En gestión');assert.equal(v.severity,'Crítica');assert.equal(v.solution,null);assert.equal((await evaluate(f))!.incidentGuardAllowed,false);},
 R06:async()=>{const f=await staged();await missing(f,await f.manage(),['responsibleId','action']);await deny(await f.command('manage',{responsibleId:uid(),action:'repair'}));for(const status of ['Resuelta','Cerrada']){const g=await staged(status);await deny(await g.manage());}},
 R07:async()=>{for(const status of ['Abierta','En gestión']){const f=await staged(status);await apply(await f.resolve());const v=(await f.state())!;assert.equal(v.status,'Resuelta');assert.equal(v.severity,'Crítica');assert.deepEqual(v.solution,f.solution);assert.equal((await evaluate(f))!.incidentGuardAllowed,true);}},
 R08:async()=>{const f=await staged();const q=await f.command('resolve',{...f.solution,cause:null,causeVerified:false,uncertainty:'SYNTHETIC unknown initiating cause, component replacement verified',uncertaintyCompatible:true});await apply(q);assert.equal((await f.state())!.status,'Resuelta');const g=await staged();await deny(await g.command('resolve',{...q.data,uncertaintyCompatible:false}));},
 R09:async()=>{const f=await staged();await missing(f,await f.resolve(),Object.keys(f.solution));for(const key of ['resultVerified','scopeResolved','effectsIdentified','causeVerified'])await deny(await f.command('resolve',{...f.solution,[key]:false}));const g=await staged('Cerrada');await deny(await g.resolve());},
 R10:async()=>{const f=await staged('Resuelta');await apply(await f.close());const v=(await f.state())!;assert.equal(v.status,'Cerrada');assert.equal(v.severity,'Crítica');assert.ok(v.solution);assert.ok(v.closure);},
 R11:async()=>{const f=await staged('Resuelta');await missing(f,await f.close(),['solutionVerified','recordSufficient','effectsIdentified']);for(const key of ['solutionVerified','recordSufficient','effectsIdentified'])await deny(await f.command('close',{solutionVerified:true,recordSufficient:true,effectsIdentified:true,[key]:false}));for(const status of ['Abierta','En gestión']){const g=await staged(status);await deny(await g.close());}},
 R12:async()=>{for(const status of ['Resuelta','Cerrada'])for(const action of [null,'SYNTHETIC inspecting recurrence']){const f=await staged(status),v=(await f.state())!;await apply(await f.command('reopen',{sameProblem:true,basis:'recurrence',action,responsibleId:action?h.actorId:null}));const after=(await f.state())!;assert.equal(after.status,action?'En gestión':'Abierta');assert.equal(after.code,v.code);assert.deepEqual(after.solution,v.solution);assert.deepEqual(after.closure,v.closure);assert.equal((await evaluate(f))!.incidentGuardAllowed,false);}},
 R13:async()=>{const f=await staged('Cerrada');await missing(f,await f.reopen(),['sameProblem','basis','action','responsibleId']);await deny(await f.command('reopen',{sameProblem:false,basis:'recurrence',action:null,responsibleId:null}));await deny(await f.command('reopen',{sameProblem:true,basis:'recurrence',action:'inspect',responsibleId:null}));},
 R14:async()=>{for(const status of ['Abierta','En gestión','Resuelta','Cerrada']){const f=await staged(status);await apply(await f.severity());const v=(await f.state())!;assert.equal(v.status,status);assert.equal(v.severity,'Importante');assert.equal(v.history!.at(-1)!.before!.severity,'Crítica');}},
 R15:async()=>{const f=await staged();await missing(f,await f.severity(),['severity','basis','evasion']);await deny(await f.command('severity',{severity:'Leve',basis:'convenience',evasion:true}));assert.equal((await evaluate(f))!.incidentGuardAllowed,false);},
 R16:async()=>{const old=await snapshot(h,['b04_bookings','b04_services','b04_nights','b04_participants','b04_assignments']);const f=await staged();assert.equal((await evaluate(f,'preparation'))!.incidentGuardAllowed,false);const scope={...f.impact.scope,serviceId:f.b.b.detail.services[1]!.id};assert.equal((await evaluate(f,'preparation',scope))!.incidentGuardAllowed,true);assert.deepEqual(await snapshot(h,['b04_bookings','b04_services','b04_nights','b04_participants','b04_assignments']),old);},
 R17:async()=>{const f=await staged(),g=await staged();await apply(await f.resolve());const pending=(await evaluate(f,'preparation'))!.pending;assert.ok(pending.some(x=>x.incidentId===g.incidentId));assert.ok(!pending.some(x=>x.incidentId===f.incidentId));await apply(await g.resolve());assert.ok(!(await evaluate(f,'preparation'))!.pending.some(x=>[f.incidentId,g.incidentId].includes(x.incidentId)));},
 R18:async()=>{const f=await fixture();for(const key of ['scope','effect','material','coverageReviewed','basis']){const impact={...f.impact} as Record<string,unknown>;delete impact[key];await deny(await f.detect({data:{...f.data,impact}}));}await deny(await f.detect({data:{...f.data,impact:{...f.impact,scope:{...f.impact.scope,serviceId:uid()}}}}));await deny(await f.detect({data:{...f.data,impact:{...f.impact,coverageReviewed:false}}}));},
 R19:async()=>{for(const status of ['Abierta','En gestión']){const f=await staged(status);assert.equal((await evaluate(f))!.incidentGuardAllowed,false);await deny(await f.command('close',{solutionVerified:true,recordSufficient:true,effectsIdentified:true}));await deny(await f.command('justify',{scope:f.impact.scope,responsibleId:h.actorId,purpose:'complete-close',basis:''}));}},
 R20:async()=>{const f=await staged();const old=(await f.state())!;await apply(await f.justify());const v=(await f.state())!;assert.equal(v.status,old.status);assert.equal(v.severity,'Crítica');const assessed=(await evaluate(f))!;assert.ok(assessed.active.find(x=>x.incidentId===f.incidentId)!.justified);assert.ok(!assessed.pending.some(x=>x.incidentId===f.incidentId));await missing(await staged(),await (await staged()).justify(),['scope','responsibleId','purpose','basis']);},
 R21:async()=>{const f=await staged();const names=(await h.observer`select tablename from pg_tables where schemaname='crm_private' and (tablename like 'b05_%' or tablename like 'b07_requirement_%' or tablename='b07_requirements')`).map(x=>x.tablename as string),old=await snapshot(h,names);await apply(await f.justify());await deny(await f.command('justify',{scope:f.impact.scope,responsibleId:h.actorId,purpose:'complete-close',basis:'specific',paymentSatisfied:true,documentSatisfied:true,refundExecuted:true}));assert.deepEqual(await snapshot(h,names),old);assert.equal((await evaluate(f))!.completeClosureImplemented,false);},
 R22:async()=>{const f=await staged();const names=(await h.observer`select tablename from pg_tables where schemaname='crm_private' and tablename like 'b05_%'`).map(x=>x.tablename as string),old=await snapshot(h,names);await apply(await f.resolve());await deny(await f.command('resolve',{...f.solution,refundExecuted:true}));await deny(await f.attest({...await f.resolve(),action:'refund' as never}));assert.deepEqual(await snapshot(h,names),old);},
 R23:async()=>{const f=await staged();await apply(await f.justify());await apply(await f.severity());assert.equal((await f.state())!.justification,null);await apply(await f.command('severity',{severity:'Crítica',basis:'SYNTHETIC renewed hazard',evasion:false}));await apply(await f.justify());await apply(await f.resolve());await apply(await f.reopen());assert.equal((await f.state())!.justification,null);assert.ok((await evaluate(f))!.pending.some(x=>x.incidentId===f.incidentId));assert.ok((await f.state())!.history!.some(x=>x.after.justification!==null));},
 R24:async()=>{const f=await fixture(),d=await f.b.document();await apply(await f.detect({data:{...f.data,knownEvidence:[d.documentId]}}));const v=(await f.state())!;assert.deepEqual(v.knownEvidence,[d.documentId]);await deny(await f.detect({data:{...f.data,audio:true,retentionDays:30,consent:true}}));assert.equal((await h.observer`select material->>'relation' relation from crm_private.b07_records where record_id=${d.documentId}::uuid`)[0]!.relation,'original');await deny(await (await fixture()).detect({data:{...f.data,knownEvidence:[uid()]}}));},
 R25:async()=>{const f=await staged(),v=(await f.state())!;assert.equal((await h.incidents.byCode(await h.auth(),read,v.code,f.bookingId))!.id,f.incidentId);assert.equal(await h.incidents.byCode(await h.auth(),read,v.code,uid()),null);assert.equal(await h.incidents.read(await h.auth(),read,f.incidentId,uid()),null);assert.equal(await h.incidents.read(await h.auth(),read,uid(),f.bookingId),null);const result=JSON.stringify(await evaluate(f));for(const text of [f.data.description,f.data.facts,f.data.hypothesis,'actorId','sourceRef'])assert.ok(!result.includes(text));},
 R26:async()=>{for(const role of ['crm_h0_runtime','anon','authenticated']){const db=h.connect(role);for(const table of incidentTables)for(const sql of [`select * from crm_private.${table}`,`delete from crm_private.${table}`,`update crm_private.${table} set admin_scope='fake'`,`insert into crm_private.${table} default values`])await assert.rejects(db.unsafe(sql));}for(const [name,n] of [['incident_read',5],['incident_apply',10]] as const){await assert.rejects(h.runtime.unsafe(`select crm_api.${name}(${Array(n).fill("'fake'::bytea").join(',')})`));await assert.rejects(h.runtime.unsafe(`select crm_api.${name}(${Array(n).fill('null::bytea').join(',')})`));}for(const mode of ['actor','session']){const u=await isolatedIncident('crm_h4004_'+mode,mode==='actor'?56203:56204);try{const f=await incidentFixture(u),q=await f.detect();await u.incidents.apply(await u.auth(),write,q);if(mode==='actor')await u.admin`update crm_private.crm_actors set enabled=false where actor_id=${u.actorId}::uuid`;else await u.admin`update crm_private.crm_sessions set revoked_at=clock_timestamp() where session_id=${u.sessionId}::uuid`;await assert.rejects(f.state());await assert.rejects(u.incidents.apply(await u.auth(),write,q));}finally{await u.close();}}},
 R27:async()=>{const rows=await h.observer`select c.relname,c.relrowsecurity,c.relforcerowsecurity,r.rolname owner from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_roles r on r.oid=c.relowner where n.nspname='crm_private' and c.relname=any(${incidentTables})`;assert.equal(rows.length,3);for(const r of rows){assert.equal(r.relrowsecurity,true);assert.equal(r.relforcerowsecurity,true);assert.equal(r.owner,'crm_h0_f2_owner');}const funcs=await h.observer`select p.proname,p.proconfig,has_function_privilege('crm_h0_runtime',p.oid,'EXECUTE') runtime from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.proname like 'incident_%' and n.nspname in ('crm_api','crm_private')`;assert.equal(funcs.length,5);for(const r of funcs){assert.ok(r.proconfig.includes('search_path=pg_catalog, pg_temp'));assert.equal(r.runtime,['incident_apply','incident_read'].includes(r.proname));}assert.equal((await h.observer`select count(*)::int n from pg_policies where schemaname='crm_private' and tablename=any(${incidentTables})`)[0]!.n,6);assert.equal((await h.observer`select count(*)::int n from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where p.proname like 'incident_%' and a.grantee=0`)[0]!.n,0);const role=(await h.observer`select rolsuper,rolbypassrls from pg_roles where rolname='crm_h0_runtime'`)[0]!;assert.equal(role.rolsuper,false);assert.equal(role.rolbypassrls,false);for(const table of incidentTables){await assert.rejects(h.migration.unsafe(`update crm_private.${table} set admin_scope=admin_scope`));await assert.rejects(h.migration.unsafe(`delete from crm_private.${table}`));}},
 R28:async()=>{const f=await fixture();for(const make of [f.detect,f.manage,f.resolve,f.close,f.reopen,f.severity,f.justify]){const q=await make(),old=await apply(q),before=await snapshot(h);const replay=await apply(q);assert.deepEqual(replay.result,old.result);assert.equal(replay.replayed,true);assert.deepEqual(await snapshot(h),before);}const g=await fixture(),q=await g.detect();await apply(q);await apply(await g.detect());assert.equal((await g.state())!.history!.length,1);},
 R29:async()=>{const f=await fixture(),q=await f.detect();await apply(q);await deny(await f.attest({...q,reason:'SYNTHETIC different material'}));const stale=await f.manage();await apply(stale);await deny(await f.attest({...stale,operationId:uid()}));},
 R30:async()=>{const f=await fixture(),q=await f.detect();const committed=await apply(q);const before=await snapshot(h);const replay=await apply(q);assert.equal(replay.result.code,committed.result.code);assert.equal(replay.replayed,true);assert.deepEqual(await snapshot(h),before);},
 R31:async()=>{const f=await fixture(),q=await f.detect();await race(f,q,q);assert.equal((await f.state())!.history!.length,1);const g=await fixture(),r=await g.detect();await race(g,r,{...r,operationId:uid()});},
 R32:async()=>{for(const order of [false,true]){const f=await staged();const a=await f.manage(),b=await f.severity();await race(f,...(order?[b,a]:[a,b]) as [IncidentCommand,IncidentCommand]);const g=await staged();const c=await g.resolve(),d=await g.severity();await race(g,...(order?[d,c]:[c,d]) as [IncidentCommand,IncidentCommand]);const i=await staged('Resuelta'),e=await i.close(),k=await i.reopen();await race(i,...(order?[k,e]:[e,k]) as [IncidentCommand,IncidentCommand]);}const f=await staged('Resuelta'),a=await f.reopen();await apply(a);const stale=await f.command('resolve',f.solution,{expectedRevision:1});await deny(stale);},
 R33:async()=>{const f=await staged(),g=await staged(),a=await f.resolve(),b=await g.manage();const other=new H4003IncidentAdapter(h.connect('crm_h0_runtime'),h.f1,h.f2);await Promise.all([apply(a),other.apply(await h.auth(),write,b)]);assert.ok((await evaluate(f,'preparation'))!.pending.some(x=>x.incidentId===g.incidentId));},
 R34:async()=>{for(const [table,mode] of [['identity_codes','before'],['b07_incidents','before'],['b07_incidents','after'],['b07_incident_revisions','before'],['b07_incident_operations','commit']] as const){const f=await fixture();await fault(table,await f.detect(),mode);}for(const status of ['manage','resolve','severity','justify','close','reopen'] as const){const f=await staged(status==='close'?'Resuelta':status==='reopen'?'Cerrada':'Abierta');await fault('b07_incident_revisions',await f[status]());}},
 R35:async()=>{const u=await isolatedIncident('crm_h4004_upgrade',56205,true);try{const b=await invoiceFixture(u),r=await requirementFixture(u,b);await u.requirements.apply(await u.auth(),write,await r.need());await u.requirements.apply(await u.auth(),write,await r.receive());await u.requirements.apply(await u.auth(),write,await r.review());const names=(await u.observer`select tablename from pg_tables where schemaname='crm_private'`).map(x=>x.tablename as string),old=await snapshot(u,names),catalog=await inventory(u);await u.migration.unsafe(await readFile(new URL('../../supabase/migrations/'+incidentMigration,import.meta.url),'utf8'));assert.deepEqual(await snapshot(u,names),old);const current=await inventory(u);for(const k of ['tables','functions','policies','triggers'] as const){const ids=new Set(catalog[k].map(x=>x.oid));assert.deepEqual(current[k].filter(x=>ids.has(x.oid)),catalog[k]);}assert.deepEqual(current.roles,catalog.roles);assert.equal((await r.see())!.status,'Revisado');const f=await incidentFixture(u,b);await u.incidents.apply(await u.auth(),write,await f.detect({data:{...f.data,effectLinks:[{kind:'requirement',id:r.requirementId}]}}));assert.equal((await f.state())!.status,'Abierta');}finally{await u.close();}const files=(await readdir(new URL('../../supabase/migrations/',import.meta.url))).filter(x=>x.endsWith('.sql'));assert.equal(files.length,39);assert.equal(files.filter(x=>x<incidentMigration).length,38);for(const file of [...files.filter(x=>x<incidentMigration).map(x=>'supabase/migrations/'+x),'supabase/operations/20261002225221_crm_supabase_daily_health.sql','tests/operations/supabase-health.test.mjs','docs/SUPABASE-KEEPALIVE.md']){const base=spawnSync('git',['show','2f27ae3b5cd8a8d7f510ee32072fda0ddbc33d25:'+file],{encoding:'utf8'});assert.equal(base.status,0);assert.equal(await readFile(new URL('../../'+file,import.meta.url),'utf8'),base.stdout);}},
 R36:async()=>{const u=await isolatedIncident('crm_h4004_rollback',56206,true);try{const sql=await readFile(new URL('../../supabase/migrations/'+incidentMigration,import.meta.url),'utf8'),old=await inventory(u);await assert.rejects(u.migration.unsafe(sql.replace(/commit;\s*$/,`do $$begin raise exception 'SYNTHETIC_DDL_FAULT';end$$;commit;`)));await u.migration.unsafe('rollback');assert.deepEqual(await inventory(u),old);await u.migration.unsafe(sql);assert.equal((await u.observer`select count(*)::int n from pg_tables where schemaname='crm_private' and tablename=any(${incidentTables})`)[0]!.n,3);}finally{await u.close();}const db=await h.connect('crm_h0_runtime').reserve();try{await assert.rejects(db.unsafe(await readFile(new URL('../../supabase/migrations/'+incidentMigration,import.meta.url),'utf8')));}finally{await db.unsafe('rollback');await db.release();}},
 R37:async()=>{const frozen=spawnSync('git',['show','0b2ec96:specs/001-core-crm/expected-TSK-H4-003-004.md'],{encoding:'utf8'}),expected=await readFile(new URL('../../specs/001-core-crm/expected-TSK-H4-003-004.md',import.meta.url),'utf8');assert.equal(expected,frozen.stdout);assert.equal((expected.match(/^\| R\d+/gm)??[]).length,38);},
 R38:async()=>{const expected=await readFile(new URL('../../specs/001-core-crm/expected-TSK-H4-003-004.md',import.meta.url),'utf8');for(const s of ['H4-021/023','H5-016','H6-007/E2E-07','H4-005+','DM-PENDING-005','Production','STOP'])assert.ok(expected.includes(s));const f=await fixture();await deny(await f.detect({origin:'ai'}));await deny(await f.attest(await f.detect(),'candidate'));}
};
for(const [id,run] of Object.entries(cases))test(id,run);
