// Reuse accredited H4-019 assertions unchanged, against fresh52 instead of49.
// Only harness/port and report labels adapted; historical source remains byte exact.
import {observeFunds} from '../support/h4-019-observation.ts';
import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID as uid} from 'node:crypto';
import {isolatedReality as isolatedDeposit,read,write} from '../support/h4-reality-isolated.ts';
import {allocationFixture} from '../support/h3-allocation-fixtures.ts';
import {jointRefundFixture} from '../support/h4-joint-refund-fixtures.ts';
import {depositFixture} from '../support/h4-deposit-fixtures.ts';
import {providerPaymentFixture} from '../support/h3-provider-payment-fixtures.ts';
import {H0005PostgresAdapter} from '../../src/infrastructure/postgres/h0-005-adapter.ts';
import {verifyAuth} from '../../src/application/verified-auth.ts';
let h:Awaited<ReturnType<typeof isolatedDeposit>>,other:()=>ReturnType<typeof h.auth>,otherSession:string;
before(async()=>{h=await isolatedDeposit('crm_h4024_joint',58600);const access=new H0005PostgresAdapter(h.connect('crm_h0_runtime'),h.f1,h.f2);const subject=h.subject;const first=await verifyAuth({verify:async()=>({subject,passwordVerified:true,mfaVerified:true})},uid());const sessionId=(await access.establish(first)).sessionId;otherSession=sessionId;other=()=>verifyAuth({verify:async()=>({subject,sessionId,passwordVerified:true,mfaVerified:true})},uid());console.log('H4-024 current52: two sessions of the single actor, independent transaction binding',h.actorId,h.sessionId,sessionId);});
after(async()=>{await h?.close();});
// Existing cases/assertions unchanged; stronger observation now requires BOTH business frontiers.
async function overlap(paymentId:string,jobs:(()=>Promise<any>)[],order:number[]){return observeFunds(h,paymentId,jobs,order,[h.sessionId,otherSession]);}
async function refund(existing?:Awaited<ReturnType<typeof allocationFixture>>,amount='100.00'){const f=await jointRefundFixture(h,amount,amount,'provider',existing);await f.run(await f.determine());await(await f.approval(await f.authorization(amount))).execute();return f;}
async function internal(a:Awaited<ReturnType<typeof allocationFixture>>,retained='0.00'){const f=await depositFixture(h,{q:a.f.b,detail:a.f.detail,f:a.f.f});await f.initialize('100.00',true);const assigned=await a.assign('100.00','0.00',{bookingId:f.bid,purpose:'deposit',reference:'SYNTHETIC actual guarantee',serviceId:f.sid});await h.allocations.apply(await h.auth(),write,assigned);const portion=async(amount:string,start:string)=>{const p=await a.see();return {paymentId:a.paymentId,reconciliationId:a.p.reconciliationId!,allocationId:assigned.allocationId!,paymentRevision:p.paymentRevision,fundRevision:p.revision,start,amount};};const d=await f.delivery();d.delivery={...d.delivery!,custody:'internal',recipientId:h.actorId,method:'bank_transfer',fund:await portion('100.00','0.00')};await f.run(await f.attest(d));await f.run(await f.evaluate());const q=await f.determination(retained);q.resolution!.method='bank_transfer';await(await f.approval(await f.attest(q))).execute();const fact=async(action:'retain'|'return',amount:string,start:string)=>{const q=await f.fact(action,amount,start);q.fact={...q.fact!,recipientId:action==='retain'?h.actorId:q.fact!.recipientId,method:'bank_transfer',fundPortions:[await portion(amount,start)]};return f.attest(q);};return {f,assigned,portion,fact};}
for(const order of [[0,1],[1,0]])test('H4-02452 J07 T08 exact authorization vs competing Allocation80 on100 '+order,async()=>{
 const funding=await allocationFixture(h,'100.00','100.00','verified','900.00');const f=await jointRefundFixture(h,'100.00','100.00','provider',funding);await f.run(await f.determine());const q=await f.authorization('80.00'),approval=await f.approval(q),allocation=await f.a.assign('80.00');
 const outcomes=await overlap(f.a.paymentId,[async()=>approval.execute(),async()=>h.allocations.apply(await other(),write,allocation)],order);
 assert.equal(outcomes[order.indexOf(1)]!.ok,true,'ordinary Allocation is independent of mere authorization');
 const view=await f.view();assert.equal(view.executed,'0.00');assert.equal(view.uncertain,'0.00');assert.equal((await f.a.see()).summary.assigned,'80.00');
 if(order[0]===1){assert.equal(outcomes[order.indexOf(0)]!.ok,false,'stale fund material cannot consume exact Human Approval');assert.equal(view.authorized,'0.00');}
 else {assert.equal(outcomes[order.indexOf(0)]!.ok,true);assert.equal(view.authorized,'80.00');}
 console.log('F06 J07 T08 outcomes',JSON.stringify({order,outcomes,refund:view,funds:await f.a.see(),proposal:approval.proposal}));
});
for(const order of [[0,1],[1,0]]){
 test('H4-02452 J01 Allocation80 vs Refund80 on100 '+order,async()=>{const f=await refund(),a=await f.a.assign('80.00'),r=await f.movement('80.00');assert.equal((await f.a.see()).allocations.length,0);const result=await overlap(f.a.paymentId,[async()=>h.allocations.apply(await h.auth(),write,a),async()=>h.refunds.apply(await other(),write,r)],order);assert.equal(result.filter(x=>x.ok).length,1);assert.equal((await h.payments.read(await h.auth(),read,f.a.paymentId))!.summary.grossReceived,'100.00');const v=await f.a.see();console.log('J01 observed',JSON.stringify({result,view:v,refund:await f.view()}));assert.ok(['0.00','80.00'].includes(String(v.summary.representedReturned)));await assert.rejects(h.allocations.apply(await h.auth(),write,await f.a.assign('80.00')));});
 test('H4-02452 J02 two first assignments80 on100 '+order,async()=>{const a=await allocationFixture(h,'100.00','100.00','verified','900.00'),q=await a.assign('80.00'),r=await a.assign('80.00');assert.equal((await a.see()).allocations.length,0);const result=await overlap(a.paymentId,[async()=>h.allocations.apply(await h.auth(),write,q),async()=>h.allocations.apply(await other(),write,r)],order);assert.equal(result.filter(x=>x.ok).length,1);assert.equal((await a.see()).allocations.length,1);await assert.rejects(h.allocations.apply(await h.auth(),write,await a.assign('80.00')));});
 test('H4-02452 J03 Refund vs guarantee restitution shared internal100 '+order,async()=>{const a=await allocationFixture(h,'100.00','100.00','verified','900.00'),d=await internal(a),f=await jointRefundFixture(h,'100.00','100.00','provider',a);await f.run(await f.determine());await(await f.approval(await f.authorization('100.00',[await f.portion('100.00','0.00',d.assigned.allocationId)]))).execute();const q:any=await f.movement('80.00');q.movement!.portions=[await f.portion('80.00','0.00',d.assigned.allocationId)];const r=await d.fact('return','80.00','0.00');const rq=await f.attest(q);const result=await overlap(a.paymentId,[async()=>h.refunds.apply(await h.auth(),write,rq),async()=>h.deposits.apply(await other(),write,r)],order);assert.equal(result.filter(x=>x.ok).length,1);assert.equal((await a.see()).summary.representedReturned,'80.00');assert.equal((await h.observer`select count(*)::int n from crm_private.b05_refund_movements where material->'portions'->0->>'paymentId'=${a.paymentId}`)[0]!.n,1);});
 test('H4-02452 J04 Refund vs Provider Payment shared managed funds '+order,async()=>{const pp=await providerPaymentFixture(h,'100.00','100.00');await h.providerPayments.apply(await h.auth(),write,await pp.open());const assigned=await pp.assign('100.00'),a=pp.su.funds;const f=await jointRefundFixture(h,'100.00','100.00','provider',a);await f.run(await f.determine());await(await f.approval(await f.authorization('100.00',[await f.portion('100.00','0.00',assigned.allocationId)]))).execute();const r:any=await f.movement('80.00');r.movement!.portions=[await f.portion('80.00','0.00',assigned.allocationId)];const q=await pp.movement([await pp.portion(assigned,'80.00','0.00')],'80.00');const rq=await f.attest(r);const result=await overlap(a.paymentId,[async()=>h.refunds.apply(await h.auth(),write,rq),async()=>h.providerPayments.apply(await other(),write,q)],order);assert.equal(result.filter(x=>x.ok).length,1);console.log('J04 outcome',JSON.stringify({result,funds:await a.see(),refund:await f.view(),provider:await pp.view()}));});
 for(const mode of ['retain','return']as const)test('H4-02452 J05 guarantee '+mode+' vs Allocation consume '+order,async()=>{const a=await allocationFixture(h,'100.00','100.00','verified','900.00'),d=await internal(a,mode==='retain'?'100.00':'0.00'),q=await d.fact(mode,'80.00','0.00'),r=await a.consume(d.assigned,'80.00','0.00');const result=await overlap(a.paymentId,[async()=>h.deposits.apply(await h.auth(),write,q),async()=>h.allocations.apply(await other(),write,r)],order);assert.equal(result.filter(x=>x.ok).length,1);console.log('J05 actual',JSON.stringify({result,funds:await a.see(),deposit:await d.f.view()}));});
 test('H4-02452 J06 disjoint Allocation20 and Refund20 plus safe revaluation '+order,async()=>{const f=await refund(),a=await f.a.assign('20.00','0.00'),r=await f.movement('20.00','20.00');const result=await overlap(f.a.paymentId,[async()=>h.allocations.apply(await h.auth(),write,a),async()=>h.refunds.apply(await other(),write,r)],order);assert.equal(result.filter(x=>x.ok).length,1);if(!result[order.indexOf(0)]!.ok)await h.allocations.apply(await h.auth(),write,await f.a.assign('20.00','0.00'));else await f.run(await f.movement('20.00','20.00'));assert.equal((await f.view()).executed,'20.00');assert.equal((await f.a.see()).allocations.length,1);});
}
async function uncertain(){const f=await refund(undefined,'200.00'),inc=await f.incident(),attempt={id:uid(),sourceRef:'SYNTHETIC uncertain transfer',portion:await f.portion('80.00')};await f.run(await f.command('uncertain',{attempt,incidentId:inc.incidentId}));return {f,inc,attempt};}
async function partial(f:Awaited<ReturnType<typeof jointRefundFixture>>,attempt:{id:string},amount='20.00',start='0.00'){const move=await f.movement(amount,start);return f.command('resolve',{attemptId:attempt.id,resolution:'occurred',movement:move.movement});}
for(const order of [[0,1],[1,0]])for(const mode of ['sameFact','overlap','disjoint','rest','allocation'])test('H4-02452 J10-13 public concurrent uncertainty '+mode+' '+order,async()=>{const{f,attempt}=await uncertain();if(mode==='allocation')await f.run(await partial(f,attempt));const q=await partial(f,attempt,'20.00',mode==='allocation'?'20.00':'0.00');let b=await partial(f,attempt,'20.00',mode==='disjoint'?'20.00':'0.00');if(mode==='sameFact')b=await f.attest({...q,operationId:uid()});if(mode==='rest')b=await f.command('resolve',{attemptId:attempt.id,resolution:'not_occurred'});const alloc=mode==='allocation'?await f.a.assign('20.00','20.00'):null;const result=await overlap(f.a.paymentId,[async()=>h.refunds.apply(await h.auth(),write,q),async()=>alloc?h.allocations.apply(await other(),write,alloc):h.refunds.apply(await other(),write,b)],order);assert.equal(result.filter(x=>x.ok).length,mode==='sameFact'?2:1);let p=await f.view();if(mode==='disjoint'){const start=order[0]===0?'20.00':'0.00';await f.run(await partial(f,attempt,'20.00',start));p=await f.view();assert.equal(p.executed,'40.00');assert.equal(p.uncertain,'40.00');}else if(mode==='rest'&&order[0]===1){assert.equal(p.executed,'0.00');assert.equal(p.uncertain,'0.00');}else{assert.equal(p.executed,mode==='allocation'?'40.00':'20.00');assert.equal(p.uncertain,mode==='allocation'?'40.00':'60.00');}console.log('J uncertainty exact',JSON.stringify({result,refund:p,funds:await f.a.see()}));});
for(const result of ['not_occurred','occurred']as const)test('H4-02452 J10/J12 exact partial20 rest60 '+result,async()=>{const{f,attempt}=await uncertain();await f.run(await partial(f,attempt));let p=await f.view();assert.equal(p.executed,'20.00');assert.equal(p.pendingRight,'180.00');assert.equal(p.pendingAuthorized,'180.00');assert.equal(p.uncertain,'60.00');await assert.rejects(f.run(await f.movement('60.00','20.00')));await f.run(result==='occurred'?await partial(f,attempt,'60.00','20.00'):await f.command('resolve',{attemptId:attempt.id,resolution:result}));p=await f.view();assert.equal(p.executed,result==='occurred'?'80.00':'20.00');assert.equal(p.pendingRight,result==='occurred'?'120.00':'180.00');assert.equal(p.uncertain,'0.00');});
for(const mode of ['outside','attemptId','incident'])test('H4-02452 J11 F13/F24 absence inference '+mode,async()=>{const{f,attempt,inc}=await uncertain();await f.run(await partial(f,attempt));const before=await f.view();if(mode==='incident'){await h.incidents.apply(await h.auth(),write,await inc.resolve());await assert.rejects(f.run(await f.movement('60.00','20.00')));}else if(mode==='attemptId')await assert.rejects(f.run(await f.movement('20.00','20.00',{attemptId:attempt.id})));else await assert.rejects(f.run(await partial(f,attempt,'20.00','100.00')));assert.deepEqual(await f.view(),before);});
for(const order of [[0,1],[1,0]])test('H4-02452 J08 canonical Deposit/Refund shared concurrent reference '+order,async()=>{const a=await allocationFixture(h,'100.00','100.00','verified','900.00'),d=await internal(a),q=await d.fact('return','20.00','0.00'),r=await d.f.attest({...q,operationId:uid()});const result=await overlap(a.paymentId,[async()=>h.deposits.apply(await h.auth(),write,q),async()=>h.refunds.applyGuarantee(await other(),write,r)],order);assert.equal(result.filter(x=>x.ok).length,2);assert.equal((await d.f.view()).amounts.returned,'20.00');assert.equal((await a.see()).summary.representedReturned,'20.00');assert.equal((await h.observer`select count(*)::int n from crm_private.b05_refund_movements where refund_id=${(await d.f.view()).refundId}::uuid`)[0]!.n,1);const fresh=await d.f.attest({...q,operationId:uid(),expectedRevision:(await d.f.view()).revision,fact:{...q.fact!,fundPortions:[await d.portion('20.00','0.00')]}});assert.equal((await h.refunds.applyGuarantee(await h.auth(),write,fresh)).replayed,true);await assert.rejects(h.refunds.applyGuarantee(await h.auth(),write,await d.f.attest({...fresh,fact:{...fresh.fact!,reference:'SYNTHETIC conflicting identity material'}})),/CONFLICT:E2/);});
for(const [total,weights,expected,internal]of [['100.00',['1','1','1'],['33.34','33.33','33.33'],['33.333333333333','33.333333333333','33.333333333333']],['0.05',['1','1','2'],['0.01','0.01','0.03'],['0.0125','0.0125','0.025']]]as const)test('H4-02452 J16-18 persisted exact D029 +/- '+total,async()=>{const a=await allocationFixture(h,total,total),parts=weights.map((weight,order)=>({id:uid(),order,weight,reconciliationId:a.p.reconciliationId!,expectedReconciliationRevision:2,destination:{...a.destination,reference:['A','B','C'][order]!}}));const q=await a.command('distribute',{distributionId:uid(),start:'0.00',total,parts});await h.allocations.apply(await h.auth(),write,q);let p=await a.see();const calc:any=p.distributions[0]!.calculation;assert.deepEqual(calc.output.parts.map((x:any)=>x.amount),expected);assert.equal(calc.output.total,total);assert.equal(p.summary.assigned,total);console.log('J D029 independently fixed expected actual record',JSON.stringify(calc));await h.allocations.apply(await h.auth(),write,await a.command('reverse_distribution',{distributionId:q.distributionId,total:'-'+total,parts}));p=await a.see();assert.deepEqual((p.distributions.at(-1)!.calculation.output as any).parts.map((x:any)=>x.amount),expected.map(x=>'-'+x));assert.equal(p.summary.assigned,'0.00');});
test('H4-02452 J15 PM08 exact materialized inversions preserve originals',async()=>{const a=await allocationFixture(h,'500.01','500.01','verified','1000.02'),q=await a.assign();await h.allocations.apply(await h.auth(),write,q);let p=await a.see();const original=p.acts[0]!;await h.allocations.apply(await h.auth(),write,await a.reverse(String(original.act_id)));p=await a.see();assert.equal(p.acts[1]!.signed_amount,'-500.01');assert.equal(p.summary.received,'500.01');const b=await allocationFixture(h,'100.00','100.00','verified','900.00'),r=await b.assign();await h.allocations.apply(await h.auth(),write,r);await h.allocations.apply(await h.auth(),write,await b.consume(r,'20.00'));const act=(await b.see()).acts.find(x=>x.kind==='consume')!;await h.allocations.apply(await h.auth(),write,await b.reverse(String(act.act_id)));assert.equal((await b.see()).acts.find(x=>x.original_act_id===act.act_id)!.signed_amount,'20.00');assert.equal((await b.see()).summary.consumed,'0.00');});
const tables=['b05_fund_operations','b05_fund_history','b05_fund_revisions','b05_allocation_acts','b05_allocations','b05_allocation_revisions','b05_coverage_evaluations','b05_refunds','b05_refund_operations','b05_refund_revisions','b05_refund_movements','b05_deposit_operations','b05_deposit_revisions','b05_deposit_facts'];
const snap=async()=>Object.fromEntries(await Promise.all(tables.map(async t=>[t,(await h.observer.unsafe(`select to_jsonb(x)::text v from crm_private.${t} x order by to_jsonb(x)::text`)).map(x=>x.v)])));
for(const table of ['b05_refund_movements','b05_refund_operations','b05_refund_revisions','b05_fund_revisions','b05_deposit_operations','b05_deposit_revisions'])test('H4-02452 J20 linked internal restitution atomic fault '+table,async()=>{const a=await allocationFixture(h,'100.00','100.00','verified','900.00'),d=await internal(a),q=await d.fact('return','20.00','0.00'),before=await snap();await h.admin.unsafe("create function crm_private.j19_fault() returns trigger language plpgsql as $$begin raise exception 'SYNTHETIC_J19_WRITE';end$$");await h.admin.unsafe(`create trigger j19_fault before insert on crm_private.${table} for each row execute function crm_private.j19_fault()`);try{await assert.rejects(d.f.run(q));assert.deepEqual(await snap(),before);}finally{await h.admin.unsafe(`drop trigger j19_fault on crm_private.${table}`);await h.admin.unsafe('drop function crm_private.j19_fault()');}await d.f.run(q);assert.equal((await d.f.view()).amounts.returned,'20.00');assert.equal((await a.see()).summary.representedReturned,'20.00');});
test('H4-02452 J20 COMMIT failure exact rollback shared movement, then retry',async()=>{const a=await allocationFixture(h,'100.00','100.00','verified','900.00'),d=await internal(a),q=await d.fact('return','20.00','0.00'),before=await snap();await h.admin.unsafe("create function crm_private.j19_commit() returns trigger language plpgsql as $$begin raise exception 'SYNTHETIC_J19_COMMIT';end$$");await h.admin.unsafe('create constraint trigger j19_commit after insert on crm_private.b05_deposit_operations deferrable initially deferred for each row execute function crm_private.j19_commit()');try{await assert.rejects(d.f.run(q));assert.deepEqual(await snap(),before);}finally{await h.admin.unsafe('drop trigger j19_commit on crm_private.b05_deposit_operations');await h.admin.unsafe('drop function crm_private.j19_commit()');}await d.f.run(q);assert.equal((await a.see()).summary.representedReturned,'20.00');});
import {H4017DepositAdapter} from '../../src/infrastructure/postgres/h4-deposit-adapter.ts';
test('H4-02452 J21 response loss after real COMMIT shared Deposit/Refund durable recovery',async()=>{const a=await allocationFixture(h,'100.00','100.00','verified','900.00'),d=await internal(a),q=await d.fact('return','20.00','0.00');const lost={begin:async(o:any,w:any)=>{await h.runtime.begin(o,w);throw new Error('SYNTHETIC_AFTER_REAL_COMMIT');}}as unknown as typeof h.runtime;await assert.rejects(new H4017DepositAdapter(lost,h.f1,h.f2).apply(await h.auth(),write,q));assert.equal((await d.f.view()).amounts.returned,'20.00');const before=await snap();assert.equal((await d.f.run(q)).replayed,true);assert.deepEqual(await snap(),before);assert.equal((await h.refunds.applyGuarantee(await h.auth(),write,await d.f.attest({...q,operationId:uid(),expectedRevision:(await d.f.view()).revision}))).replayed,true);assert.equal((await a.see()).summary.representedReturned,'20.00');});
for(const guard of ['actor','session'])test('H4-02452 J19 replay reauthorized '+guard,async()=>{const f=await refund(),q=await f.movement('20.00');await f.run(q);const before=await snap(),auth=await h.auth();try{if(guard==='actor')await h.admin`update crm_private.crm_actors set enabled=false where actor_id=${h.actorId}::uuid`;else await h.admin`update crm_private.crm_sessions set revoked_at=clock_timestamp() where session_id=${h.sessionId}::uuid`;await assert.rejects(h.refunds.apply(auth,write,q));assert.deepEqual(await snap(),before);}finally{if(guard==='actor')await h.admin`update crm_private.crm_actors set enabled=true where actor_id=${h.actorId}::uuid`;else await h.admin`update crm_private.crm_sessions set revoked_at=null where session_id=${h.sessionId}::uuid`;}});
for(const guard of ['context','F1','F2','evidence','booking','payment','recipient','method','amount'])test('H4-02452 J19 individual ordinary write guard '+guard,async()=>{const f=await refund(),q=await f.movement('20.00');let api=h.refunds,auth=await h.auth(),interaction:any=write;let input:any=q;if(guard==='context')interaction={};else if(guard==='F1')api=new (await import('../../src/infrastructure/postgres/h4-refund-adapter.ts')).H4015RefundAdapter(h.runtime,{...h.f1,key:Buffer.alloc(32)},h.f2);else if(guard==='F2')api=new (await import('../../src/infrastructure/postgres/h4-refund-adapter.ts')).H4015RefundAdapter(h.runtime,h.f1,{...h.f2,key:Buffer.alloc(32)});else if(guard==='evidence')input={...q,evidenceId:uid()};else{input=structuredClone(q);if(guard==='booking')input.bookingId=uid();if(guard==='payment')input.movement!.portions[0]!.paymentId=uid();if(guard==='recipient')input.movement!.recipientId=uid();if(guard==='method')input.movement!.method='cash';if(guard==='amount')input.movement!.amount='21.00';input=await f.attest(input);}const before=await snap();await assert.rejects(api.apply(auth,interaction,input));assert.deepEqual(await snap(),before);});
test('H4-02452 J19 private catalogue runtime/anon/authenticated CRUD denied and minimal scope reads',async()=>{for(const role of ['crm_h0_runtime','anon','authenticated']){const db=h.connect(role);for(const table of ['b05_deposits','b05_refunds','b05_refund_movements','b05_allocations']){await assert.rejects(db.unsafe(`select * from crm_private.${table}`));await assert.rejects(db.unsafe(`delete from crm_private.${table} where false`));}await assert.rejects(db.unsafe("select crm_private.refund_blocks(null,null)"));await db.end();}const rels=await h.observer`select c.relname,c.relrowsecurity,c.relforcerowsecurity,pg_get_userbyid(c.relowner) owner from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='crm_private' and c.relname in('b05_deposits','b05_refunds','b05_refund_movements','b05_allocations')`;assert.equal(rels.length,4);assert.ok(rels.every(x=>x.relrowsecurity&&x.relforcerowsecurity&&x.owner==='crm_h0_f2_owner'));const helpers=await h.observer`select p.proname,p.proconfig,pg_get_userbyid(p.proowner)owner,p.proacl::text acl from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='crm_private' and p.proname in('refund_core','deposit_core','refund_portions','fund_refresh')`;assert.ok(helpers.every(x=>x.owner==='crm_h0_f2_owner'&&x.proconfig.includes('search_path=pg_catalog, pg_temp')));const f=await refund();await f.run(await f.movement('20.00'));const summary=await h.refunds.read(await h.auth(),read,f.bid,f.id,'summary');assert.deepEqual(Object.keys(summary).sort(),['id','revision','right','authorized','executed','pendingRight','pendingAuthorized','uncertain','status'].sort());assert.equal(await h.refunds.read(await h.auth(),read,uid(),f.id),null);assert.equal(await h.refunds.read(await h.auth(),read,f.bid,uid()),null);console.log('J19 catalogue',JSON.stringify({rels,helpers}));});
test('H4-02452 J07 exact Human Approval material changes rejected, no fund reservation',async()=>{const f=await jointRefundFixture(h,'100.00');await f.run(await f.determine());const q=await f.authorization(),approval=await f.approval(q),before=await snap();await assert.rejects(approval.execute({...q,reason:'SYNTHETIC material changed'}),/MATERIAL_CHANGED/);assert.deepEqual(await snap(),before);});
import {cancellationFixture} from '../support/h4-cancellation-fixtures.ts';
test('H4-02452 J14 AC040 operational cancellation legitimate while economic base remains pending',async()=>{const f=await cancellationFixture(h,{scopeKind:'service'}),q=await f.command();await f.run(await f.command({facts:{...q.facts!,base:await f.base(null)}}));assert.equal((await f.see()).computed.status,'pending');await f.applyOperational();assert.equal((await f.see()).computed.right,null);const a=await allocationFixture(h,'100.00','100.00','verified','900.00'),r=await a.assign('80.00');for(const cause of ['cancellation','refund','new_obligation','modification']as const){const before=await snap();await assert.rejects(h.allocations.apply(await h.auth(),write,await a.attest({...r,cause})),/ALLOCATION_DENIED/);assert.deepEqual(await snap(),before);}await h.allocations.apply(await h.auth(),write,r);assert.equal((await a.see()).summary.assigned,'80.00');});
for(const guard of ['source','destination','portion','evidence','reconciliation'])test('H4-02452 J14 SM-RC02 individual guard '+guard,async()=>{const a=await allocationFixture(h,'100.00','100.00','verified','900.00');let q:any=await a.assign('80.00');if(guard==='source')q.sourceRef='';if(guard==='destination')q.destination.bookingId=uid();if(guard==='portion')q.amount='101.00';if(guard==='evidence')q=await a.attest(q,'candidate');if(guard==='reconciliation')q.reconciliationId=uid();if(guard!=='evidence')q=await a.attest(q);const before=await snap();await assert.rejects(h.allocations.apply(await h.auth(),write,q));assert.deepEqual(await snap(),before);});
