// Expected 0950781 was frozen before any product inspection. Assertions below are normative literals.
import assert from 'node:assert/strict';import {test} from 'node:test';import {randomUUID as uid,createHash} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';import {spawnSync} from 'node:child_process';
import {isolatedProviderPayment,providerPaymentMigration,write,read} from '../support/h3-provider-payment-isolated.ts';
import {providerPaymentFixture,type ProviderPaymentCommand} from '../support/h3-provider-payment-fixtures.ts';
import {H3011ProviderPaymentAdapter} from '../../src/infrastructure/postgres/h3-provider-payment-adapter.ts';
import {H0011PostgresAdapter} from '../../src/infrastructure/postgres/h0-011-adapter.ts';
import {createProviderPaymentExecutor} from '../../src/infrastructure/postgres/human-approval-executor.ts';
import {reverseExact} from '../../src/domain/exact-money.ts';
import {issueTrustedContext} from '../../src/application/trusted-context.ts';import {verifyAuth} from '../../src/application/verified-auth.ts';
import {canonicalCommercial} from '../../src/domain/commercial-progress.ts';
import {createF1Issuer,encodeF1Fields} from '../../src/infrastructure/postgres/f1-codec.ts';import {createF2Issuer} from '../../src/infrastructure/postgres/f2-codec.ts';import {postgresF1Binding} from '../../src/infrastructure/postgres/transaction.ts';
type H=Awaited<ReturnType<typeof isolatedProviderPayment>>;type F=Awaited<ReturnType<typeof providerPaymentFixture>>;
const tables=['b05_provider_payments','b05_provider_payment_operations','b05_provider_payment_revisions','b05_provider_outgoing_movements','b05_provider_outgoing_correspondences','b05_provider_payment_corrections'];
async function apply(h:H,q:ProviderPaymentCommand,adapter=h.providerPayments){return adapter.apply(await h.auth(),write,q);}
async function staged(h:H,received='700.00',due='500.00'){const f=await providerPaymentFixture(h,received,due);await apply(h,await f.open());return f;}
async function deny(h:H,f:F,q:ProviderPaymentCommand){const before=await f.view();await assert.rejects(apply(h,q));assert.deepEqual(await f.view(),before);}
async function change(f:F,q:ProviderPaymentCommand,delta:Record<string,unknown>){return f.attest({...q,...delta} as ProviderPaymentCommand);}
async function funded(h:H,due='500.00'){const f=await staged(h,'700.00',due),a=await f.assign();return {f,a};}
async function programmed(h:H){const {f,a}=await funded(h),q=await f.schedule([await f.portion(a)]),approval=await f.approval(q);await approval.execute();return {f,a,q,approval};}
async function complete(h:H,invoice=true){const x=await programmed(h);if(invoice)await h.suplidos.apply(await h.auth(),write,await x.f.su.attachInvoice());await apply(h,await x.f.movement([await x.f.portion(x.a)],'500.00'));return x;}
async function incident(h:H,f:F,result:'uncertain'|'failed_verified'|'discrepancy'='uncertain'){const q=await f.command('incident',{incident:{id:uid(),sourceRef:'SYNTHETIC prior attempt evidence',attemptRef:uid(),result,scope:'SYNTHETIC known provider/service scope'}});await apply(h,q);return q;}
async function snapshots(h:H,names:string[]){const out:Record<string,unknown>={};for(const t of names)out[t]=(await h.observer.unsafe(`select coalesce(jsonb_agg(x order by x::text),'[]'::jsonb) value from (select to_jsonb(t) x from crm_private.${t} t) z`))[0]!.value;return out;}
async function snapshot(h:H){return snapshots(h,[...tables,'b05_allocation_acts','b05_fund_operations','b05_fund_revisions','b05_fund_history','b05_coverage_evaluations','b05_suplido_revisions','b05_suplido_operations','b07_pending_tasks']);}
async function fault(h:H,table:string,deferred=false,body="raise exception 'SYNTHETIC_PROVIDER_PAYMENT_FAULT';",kind='before'){
 await h.admin.unsafe(`create function crm_private.h3012_fault() returns trigger language plpgsql security definer set search_path=pg_catalog,pg_temp as $$begin ${body} return new;end$$;create ${deferred?'constraint ':''}trigger h3012_fault ${deferred?'after':kind} insert on crm_private.${table} ${deferred?'deferrable initially deferred ':''}for each row execute function crm_private.h3012_fault()`);
}
async function clear(h:H,table:string){await h.admin.unsafe(`drop trigger h3012_fault on crm_private.${table};drop function crm_private.h3012_fault()`);}
async function waitLock(h:H){for(let i=0;i<150;i++){if((await h.admin`select count(*)::int n from pg_stat_activity where datname=current_database() and usename in ('crm_h0_runtime','crm_h0_ha_tx') and wait_event_type='Lock'`)[0]!.n>0)return;await new Promise(r=>setTimeout(r,10));}throw new Error('SYNTHETIC_CONCURRENCY_NOT_OBSERVED');}
async function hold(h:H,key:string){const conn=h.connect('h2_bootstrap');await conn.unsafe('begin');await conn`select pg_advisory_xact_lock(hashtextextended(${key},0))`;return ()=>conn.unsafe('commit');}
async function race(h:H,f:F,q1:ProviderPaymentCommand,q2:ProviderPaymentCommand){const b=new H3011ProviderPaymentAdapter(h.connect('crm_h0_runtime'),h.f1,h.f2),release=await hold(h,'provider-payment-root:'+f.id);const jobs=[apply(h,q1),apply(h,q2,b)];await waitLock(h);await release();return Promise.allSettled(jobs);}
async function forged(h:H,qinput:ProviderPaymentCommand,kind:'f1'|'f2'|'scope'|'read'){
 const auth=await h.auth();return h.runtime.begin(async tx=>{
  const row=(await tx`select actor_id::text,admin_scope,access_generation::text,epoch_id::text from crm_api.f2_lookup(${auth.subject}::uuid,${auth.sessionId!}::uuid)`)[0]!;
  const binding=await postgresF1Binding(tx),q=encodeF1Fields([kind==='read'?'CRM-H3-PROVIDER-PAYMENT-READ1':'CRM-H3-PROVIDER-PAYMENT1',canonicalCommercial(qinput)]);
  const context=issueTrustedContext({identityId:'synthetic-pp',identityKind:'technical',purpose:'h1-evidence',scope:kind==='scope'?'SYNTHETIC-OTHER':row.admin_scope,requestId:uid(),serverTime:new Date().toISOString()});
  const human=createF2Issuer(h.f2)(auth,{actorId:row.actor_id,scope:row.admin_scope,accessGeneration:row.access_generation,sessionId:auth.sessionId!,epochId:row.epoch_id},binding,kind==='read'?'evidence_read':'evidence_write',q,kind==='read'?read:write);
  const tech=createF1Issuer(h.f1)(context,binding,kind==='read'?'C01':'C03',q,{resource:'evidence',action:kind==='read'?'read_evidence':'write_evidence'});
  return tx.unsafe(`select crm_api.${kind==='read'?'provider_payment_read':'provider_payment_apply'}($1,$2,$3,$4,$5)`,[human.payload,kind==='f2'?Buffer.alloc(32):human.mac,tech.payload,kind==='f1'?Buffer.alloc(32):tech.mac,q]);
 });
}

test('H3-012 independent frozen matrix R001–R100',async t=>{
 const h=await isolatedProviderPayment('crm_h3_012',55712);
 const cases:Record<string,()=>Promise<void>>={};
 const add=(n:number,fn:()=>Promise<void>)=>{cases[`R${String(n).padStart(3,'0')}`]=fn;};
 add(1,async()=>{const f=await staged(h);const s=(await f.view())!;assert.equal(s.status,'Pendiente');assert.equal(s.paid,'0.00');assert.equal(s.basis.confirmedAmount,null);assert.equal((await f.su.funds.see()).summary.consumed,'0.00');});
 for(const [i,key] of ['providerRevisionId','serviceId','obligationRef','expectedAmount','sourceRef'].entries())add(i+2,async()=>{const f=await providerPaymentFixture(h);const basis={...f.basis,[key]:key==='expectedAmount'?null:''};await deny(h,f,await f.command('open',{basis}));});
 add(7,async()=>{const f=await providerPaymentFixture(h),internal=await (await import('../support/h3-invoice-fixtures.ts')).invoiceFixture(h,'internal');const q=await f.open();const changed={...q,bookingId:internal.bookingId,basis:{...f.basis,serviceId:internal.basis.serviceIds[0]!}};delete changed.suplidoId;await deny(h,f,await f.attest(changed));});
 add(8,async()=>{const f=await staged(h);await apply(h,await f.command('confirm',{confirmedAmount:'600.00'}));const s=(await f.view())!;assert.equal(s.basis.expectedAmount,'500.00');assert.equal(s.basis.confirmedAmount,'600.00');assert.equal(s.history[0]!.after!==null,true);assert.equal(s.paid,'0.00');});
 add(9,async()=>{const {f}=await programmed(h);assert.equal((await f.view())!.status,'Programado');assert.equal((await f.view())!.paid,'0.00');assert.equal((await f.su.funds.see()).summary.consumed,'0.00');});
 for(const [i,key] of ['amount','recipientId','method','scheduledDate','service','provider','evidence','fundsKind'].entries())add(i+10,async()=>{
  const f=await staged(h),q=await f.schedule();let bad:ProviderPaymentCommand;
  if(key==='service')bad=await change(f,q,{bookingId:uid()});else if(key==='provider')bad=await change(f,q,{providerPaymentId:uid()});else if(key==='evidence')bad={...q,evidenceId:uid()};else bad=await change(f,q,{schedule:{...q.schedule,[key]:''}});
  const before=await f.view();await assert.rejects(async()=>{const a=await f.approval(bad);await a.execute();});assert.deepEqual(await f.view(),before);
 });
 add(18,async()=>{const f=await staged(h);await deny(h,f,await f.command('schedule',{origin:'ai'}));});
 add(19,async()=>{const {f,approval}=await programmed(h);assert.equal((await f.view())!.schedule!.approvalReservation,approval.reserve);const r=await h.admin`select count(*)::int n from crm_ha.reservations where reservation_id=${approval.reserve}`;assert.equal(r[0]!.n,1);assert.equal((await f.view())!.paid,'0.00');const ai=await staged(h),q=await change(ai,await ai.schedule(),{origin:'ai'}),authorized=await ai.approval(q);await authorized.execute();assert.equal((await ai.view())!.status,'Programado');assert.equal((await ai.view())!.paid,'0.00');});
 add(20,async()=>{const f=await staged(h),q=await f.schedule(),a=await f.approval(q);for(const [key,value] of Object.entries({amount:'400.00',recipientId:uid(),conditions:'SYNTHETIC changed',method:'SYNTHETIC changed',scheduledDate:'2026-10-06'}))await assert.rejects(a.execute(await change(f,q,{schedule:{...q.schedule,[key]:value}})));for(const field of ['action','contentVersion','content','scope','effect'] as const){const altered={...a.material,[field]:'SYNTHETIC material changed'};await assert.rejects(async()=>h.tte.scheduleProviderPayment(await h.auth(),write,a.reserve,a.proposal,a.decision,a.part,(await import('../../src/infrastructure/postgres/h0-011-adapter.ts')).fingerprintHumanApprovalMaterial(a.material),(await import('../../src/infrastructure/postgres/h0-011-adapter.ts')).fingerprintHumanApprovalPart(a.material.parts[0]!),altered,q));}assert.equal((await f.view())!.status,'Pendiente');});
 add(21,async()=>{const f=await staged(h);await deny(h,f,await f.schedule());await assert.rejects(h.runtime`select crm_api.provider_payment_finalize('synthetic')`);const facade=createProviderPaymentExecutor({databaseUrl:`postgresql://crm_h0_ha_tx@127.0.0.1:55712/crm_h3_012`,capability:h.f1,humanAuthorization:h.f2,ssl:false});try{assert.deepEqual(Object.keys(facade).sort(),['close','scheduleProviderPayment']);assert.equal(Object.isFrozen(facade),true);}finally{await facade.close();}});
 add(22,async()=>{const {f,a}=await funded(h);const q=await f.schedule([await f.portion(a)]),until=new Date(Date.now()+1800).toISOString(),evidence={reference:'synthetic-authorized-outgoing-source',fingerprint:'a'.repeat(64),expiresAt:until},approval=await f.approval(q,evidence),before=await snapshot(h);
  const executor=new H0011PostgresAdapter(h.connect('crm_h0_ha_tx'),h.f1,h.f2,{revalidate:async()=>({reference:evidence.reference,fingerprint:evidence.fingerprint,checkedAt:new Date().toISOString(),validUntil:until,verifierIdentity:'synthetic-bank-observer',verifierKind:'synthetic-manual',outcome:'verified'})});
  await fault(h,'b05_provider_payment_operations',true,'perform pg_sleep(1.9);');try{await assert.rejects(approval.execute(q,approval.reserve,executor));assert.deepEqual(await snapshot(h),before);assert.equal((await h.admin`select count(*)::int n from crm_ha.reservations where proposal_id=${approval.proposal}`)[0]!.n,0);}finally{await clear(h,'b05_provider_payment_operations');}
 });
 add(23,async()=>{const {f,a}=await funded(h),q=await f.schedule([await f.portion(a)]),approval=await f.approval(q),b=new H0011PostgresAdapter(h.connect('crm_h0_ha_tx'),h.f1,h.f2);const r=await Promise.allSettled([approval.execute(),approval.execute(q,approval.reserve,b)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,2);assert.equal((await f.view())!.history.length,2);assert.equal((await h.admin`select count(*)::int n from crm_ha.reservations where proposal_id=${approval.proposal}`)[0]!.n,1);});
 add(24,async()=>{const {f,a}=await funded(h),q=await f.schedule([await f.portion(a)]),approval=await f.approval(q);const before=await snapshot(h);
  await fault(h,'b05_provider_payment_operations',true,`insert into crm_private.b05_fund_revisions select payment_id,revision+1,payment_revision,admin_scope,snapshot,actor_id,'SYNTHETIC final check change',cause_ref,cause_revision,clock_timestamp() from crm_private.b05_fund_revisions where payment_id='${f.su.funds.paymentId}'::uuid order by revision desc limit 1;`);
  try{await assert.rejects(approval.execute());assert.deepEqual(await snapshot(h),before);}finally{await clear(h,'b05_provider_payment_operations');}
 });
 add(25,async()=>{const {f,a}=await programmed(h);await apply(h,await f.movement([await f.portion(a,'200.00')],'200.00'));const s=(await f.view())!;assert.equal(s.paid,'200.00');assert.equal(s.remaining,'300.00');assert.equal(s.complete,false);assert.equal((await f.su.funds.see()).summary.consumed,'200.00');});
 for(const [i,key] of ['identity','providerId','amount','occurredAt','method','reference','sourceRef','serviceId','portions'].entries())add(i+26,async()=>{
  const {f,a}=await funded(h),q=await f.movement([await f.portion(a)]);const movement={...q.movement};delete (movement as Record<string,unknown>)[key];await deny(h,f,await change(f,q,{movement}));
 });
 add(35,async()=>{const {f,a}=await programmed(h);await apply(h,await f.movement([await f.portion(a,'200.00')],'200.00'));await apply(h,await f.movement([await f.portion(a,'300.00','200.00')],'300.00'));const s=(await f.view())!;assert.equal(s.paid,'500.00');assert.equal(s.movements.length,2);assert.equal(s.remaining,'0.00');});
 add(36,async()=>{const {f,a}=await programmed(h);await apply(h,await f.movement([await f.portion(a,'200.00')],'200.00'));await apply(h,await f.movement([await f.portion(a,'200.00','200.00')],'200.00'));assert.equal((await f.view())!.paid,'400.00');assert.equal((await f.view())!.remaining,'100.00');assert.equal((await f.view())!.movements.length,2);});
 for(const n of [37,38,39])add(n,async()=>{const {f,a}=await funded(h),q=await f.movement([await f.portion(a,'200.00')],'200.00');await apply(h,q);const before=await f.view(),funds=await f.su.funds.see();if(n===39){await deny(h,f,await change(f,q,{operationId:uid(),movement:{...q.movement,amount:'201.00'}}));}else{const r=await apply(h,n===37?q:await change(f,q,{operationId:uid()}));assert.equal(r.replayed,true);assert.deepEqual(await f.view(),before);assert.deepEqual(await f.su.funds.see(),funds);}});
 add(40,async()=>{const f=await staged(h);const q1=await incident(h,f),q2=await incident(h,f);assert.notEqual(q1.incident!.id,q2.incident!.id);assert.equal((await f.view())!.incidents.length,2);assert.equal((await f.view())!.paid,'0.00');});
 add(41,async()=>{const {f,a}=await funded(h),q=await f.movement([await f.portion(a)]);for(const [certainty,source] of [['presented','manual'],['reviewed','client'],['unknown','manual']]){const before=await f.view();await assert.rejects(async()=>apply(h,await f.attest(q,certainty,source)));assert.deepEqual(await f.view(),before);}});
 add(42,async()=>{const {f,a}=await funded(h);await apply(h,await f.movement([await f.portion(a,'200.00')],'200.00'));const s=(await f.view())!;assert.equal(s.movements[0]!.correspondenceVerified,true);assert.equal((await f.su.see())!.components.payment!==null,true);assert.equal((await f.su.funds.see()).summary.consumed,'200.00');const rows=await h.observer`select count(*)::int n from crm_private.b05_provider_outgoing_correspondences where movement_id=${s.movements[0]!.id as string}::uuid`;assert.equal(rows[0]!.n,1);});
 add(43,async()=>{const {f,a}=await funded(h,'100.00'),q=await f.schedule([await f.portion(a,'200.00')],'200.00');const ap=await f.approval(q);await assert.rejects(ap.execute());assert.equal((await f.su.funds.see()).summary.consumed,'0.00');});
 add(44,async()=>{const {f,a}=await funded(h,'100.00');await apply(h,await f.movement([await f.portion(a)],'200.00'));const s=(await f.view())!;assert.equal(s.paid,'200.00');assert.equal(s.status,'Incidencia');assert.equal(s.movements[0]!.correspondenceVerified,false);assert.equal((await f.su.funds.see()).summary.consumed,'0.00');assert.ok(s.incidents.some(z=>z.kind==='funding_unresolved'));});
 add(45,async()=>{for(const kind of ['fee','used','suspended','other']){const f=await staged(h),a=await f.assign('500.00','0.00',kind==='fee'?'fee':'managed_client_funds');if(kind==='used')await h.allocations.apply(await h.auth(),write,await f.su.funds.consume(a));if(kind==='suspended'){const q=await f.su.funds.paymentAttest({...await f.su.funds.discrepancy(4,'0.00','500.00'),start:'0.00',amount:'500.00'});await h.payments.apply(await h.auth(),write,q);}let part=await f.portion(a);if(kind==='other')part={...part,allocationId:uid()};const old=(await f.su.funds.see()).summary.consumed;await apply(h,await f.movement([part],'500.00'));assert.equal((await f.view())!.movements[0]!.correspondenceVerified,false);assert.equal((await f.su.funds.see()).summary.consumed,old);}});
 add(46,async()=>{for(const order of ['AB','BA','simultaneous']){const {f,a}=await funded(h,'100.00');const one=await f.movement([await f.portion(a,'80.00')],'80.00'),two=await f.movement([await f.portion(a,'80.00')],'80.00');if(order==='simultaneous'){const r=await race(h,f,one,two);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);}else{await apply(h,order==='AB'?one:two);const second=order==='AB'?two:one;await assert.rejects(apply(h,second));await apply(h,await change(f,second,{expectedRevision:(await f.view())!.revision,movement:{...second.movement,portions:[await f.portion(a,'80.00')]}}));}assert.equal((await f.su.funds.see()).summary.consumed,'80.00');assert.equal(((await f.su.funds.see()).summary.byPurpose as any).managed_client_funds.availableForPurpose,'20.00');}});
 add(47,async()=>{const {f}=await programmed(h);await h.suplidos.apply(await h.auth(),write,await f.su.attachInvoice(2));assert.equal((await f.su.see())!.components.invoice && ((await f.su.see())!.components.invoice as any).status,'Recibida');assert.equal((await f.view())!.paid,'0.00');await deny(h,f,await change(f,await f.command('record'),{status:'Pagado'}));});
 add(48,async()=>{const {f}=await complete(h,false);assert.equal((await f.view())!.paid,'500.00');assert.equal((await f.su.see())!.status,'Gestión abierta');assert.ok((await f.su.see())!.pending.includes('invoice'));assert.ok((await f.su.see())!.followUpIds.length>0);});
 add(49,async()=>{const {f}=await complete(h,false);const before=await f.view(),funds=await f.su.funds.see();await h.suplidos.apply(await h.auth(),write,await f.su.attachInvoice());await h.suplidos.apply(await h.auth(),write,await f.su.command('evaluate'));assert.deepEqual(await f.view(),before);assert.deepEqual(await f.su.funds.see(),funds);assert.equal((await f.su.see())!.status,'Documentalmente resuelto');});
 add(50,async()=>{const {f}=await complete(h);const su=(await f.su.see())!;assert.equal(su.status,'Documentalmente resuelto');assert.equal(su.components.mandate,null);assert.equal(su.evaluation!.fiscalValidation,false);assert.equal(su.evaluation!.bookingClosureInferred,false);});
 add(51,async()=>{const {f,a}=await programmed(h);await h.suplidos.apply(await h.auth(),write,await f.su.attachInvoice());await apply(h,await f.movement([await f.portion(a,'200.00')],'200.00'));assert.equal((await f.view())!.remaining,'300.00');assert.equal((await f.su.see())!.status,'Gestión abierta');assert.equal(((await f.su.see())!.components.invoice as any).linked,true);});
 add(52,async()=>{for(const stage of ['invoice','payment','correspondence','amount','service']){const {f,a}=await programmed(h);if(stage!=='invoice')await h.suplidos.apply(await h.auth(),write,await f.su.attachInvoice());if(stage!=='payment')await apply(h,await f.movement(stage==='correspondence'?[]:[await f.portion(a)],'500.00'));if(stage==='amount')await h.suplidos.apply(await h.auth(),write,await f.su.command('component',{component:'amount',confirmedAmount:'600.00'}));if(stage==='service')await h.suplidos.apply(await h.auth(),write,await f.su.command('discrepancy',{component:'obligation',incidentId:uid()}));await h.suplidos.apply(await h.auth(),write,await f.su.command('evaluate'));assert.notEqual((await f.su.see())!.status,'Documentalmente resuelto');}});
 add(53,async()=>{const {f}=await complete(h),before=(await f.su.see())!.history;await incident(h,f,'discrepancy');const su=(await f.su.see())!;assert.equal(su.status,'Revisión');assert.deepEqual(su.history.slice(0,before.length),before);assert.equal((su.components.invoice as any).linked,true);});
 add(54,async()=>{const {f}=await complete(h,false);for(const field of ['ownIncome','ownCost','documentaryResolved'])await deny(h,f,await change(f,await f.command('confirm',{confirmedAmount:'500.00'}),{[field]:true}));assert.notEqual((await f.su.see())!.status,'Documentalmente resuelto');});
 add(55,async()=>{const {f}=await programmed(h);await incident(h,f);assert.equal((await f.view())!.status,'Incidencia');assert.equal((await f.view())!.paid,'0.00');assert.equal((await f.view())!.incidents[0]!.result,'uncertain');assert.equal((await f.view())!.schedule!==null,true);});
 add(56,async()=>{const {f}=await programmed(h);await incident(h,f);await deny(h,f,await f.command('withdraw',{noExecution:true,noPendingExecution:true,noUnknownResult:true}));const approval=await f.approval(await f.schedule());await assert.rejects(approval.execute());});
 add(57,async()=>{const f=await staged(h);for(const key of ['sourceRef','attemptRef','result','scope']){const v={id:uid(),sourceRef:'SYNTHETIC source',attemptRef:uid(),result:'uncertain',scope:'SYNTHETIC known'};delete (v as Record<string,unknown>)[key];await deny(h,f,await change(f,await f.command('incident'),{incident:v}));}});
 add(58,async()=>{const {f,a}=await funded(h);const q=await f.movement([await f.portion(a)] ,'500.00');await apply(h,q);const s=(await f.view())!;assert.equal(s.paid,'500.00');assert.equal(s.status,'Incidencia');assert.equal(s.movements[0]!.approvalReservation,null);assert.equal((s.movements[0]!.material as any).occurredAt,q.movement!.occurredAt);assert.ok(s.incidents.some(x=>x.kind==='unapproved_real'));});
 add(59,async()=>{const {f,a}=await funded(h);await apply(h,await f.movement([await f.portion(a)],'500.00'));await deny(h,f,await change(f,await f.command('resolve'),{approvalReservation:'SYNTHETIC retroactive'}));assert.equal((await f.view())!.movements[0]!.approvalReservation,null);});
 add(60,async()=>{const {f,a}=await funded(h);await apply(h,await f.movement([await f.portion(a)],'500.00'));const id=(await f.view())!.incidents[0]!.id as string;await apply(h,await f.command('resolve',{incidentId:id,previousEffectCheck:'occurred_verified'}));assert.equal((await f.view())!.status,'Pagado');assert.equal((await f.view())!.movements[0]!.approvalReservation,null);});
 add(61,async()=>{const f=await staged(h),i=await incident(h,f);await deny(h,f,await f.command('resolve',{incidentId:i.incident!.id}));await deny(h,f,await f.command('resolve',{incidentId:i.incident!.id,previousEffectCheck:'occurred_verified'}));assert.equal((await f.view())!.paid,'0.00');});
 add(62,async()=>{const {f,a}=await funded(h,'20.00');await apply(h,await f.movement([await f.portion(a)],'20.00'));const s=(await f.view())!;await apply(h,await f.command('correct',{originalMovementId:s.movements[0]!.id as string,previousEffectCheck:'occurred_verified'}));const corrected=(await f.view())!;assert.equal(corrected.corrections[0]!.signedAdjustment,'20.00');assert.equal(reverseExact('SYNTHETIC advance','500.01','SYNTHETIC correction').amount,'-500.01');assert.equal((await f.su.funds.see()).summary.consumed,'20.00');});
 add(63,async()=>{const {f,a}=await funded(h,'20.00');await apply(h,await f.movement([await f.portion(a)],'20.00'));const before=(await f.view())!;await apply(h,await f.command('correct',{originalMovementId:before.movements[0]!.id as string,previousEffectCheck:'occurred_verified'}));assert.deepEqual((await f.view())!.movements,before.movements);assert.equal((await f.view())!.corrections[0]!.bankReversalInferred,false);const act=before.movements[0]!.consumptionActIds as string[];await assert.rejects(h.allocations.apply(await h.auth(),write,await f.su.funds.reverse(act[0]!)));});
 add(64,async()=>{const {f}=await programmed(h);await apply(h,await f.command('withdraw',{noExecution:true,noPendingExecution:true,noUnknownResult:true}));assert.equal((await f.view())!.status,'Pendiente');assert.equal((await f.view())!.schedule!.withdrawn,true);assert.equal((await f.view())!.history.length,3);});
 add(65,async()=>{const {f}=await programmed(h);for(const key of ['noExecution','noPendingExecution','noUnknownResult','reason']){const q=await f.command('withdraw',{noExecution:true,noPendingExecution:true,noUnknownResult:true});const v={...q};delete(v as unknown as Record<string,unknown>)[key];await deny(h,f,await f.attest(v));}});
 add(66,async()=>{const {f}=await complete(h);await deny(h,f,await f.command('withdraw',{noExecution:true,noPendingExecution:true,noUnknownResult:true}));});
 add(67,cases.R035!);
 add(68,async()=>{const {f,approval}=await programmed(h);const before=await f.view();assert.equal((await approval.execute()).commandState,'previous');assert.deepEqual(await f.view(),before);});
 add(69,async()=>{const {f,q,approval}=await programmed(h);await assert.rejects(approval.execute(await change(f,q,{schedule:{...q.schedule,amount:'400.00'}})));assert.equal((await f.view())!.schedule!.amount,'500.00');});
 add(70,cases.R037!);
 add(71,async()=>{const {f,a}=await funded(h),q=await f.movement([await f.portion(a)]);await apply(h,q);await deny(h,f,await change(f,q,{bookingId:uid()}));const falseAuth=await verifyAuth({verify:async()=>({subject:uid(),sessionId:uid(),passwordVerified:true,mfaVerified:true})},uid());await assert.rejects(h.providerPayments.apply(falseAuth,write,q));});
 add(72,async()=>{const {f,a}=await funded(h),q=await f.schedule([await f.portion(a)]),ap1=await f.approval(q),q2=await change(f,q,{operationId:uid()}),ap2=await f.approval(q2);const b=new H0011PostgresAdapter(h.connect('crm_h0_ha_tx'),h.f1,h.f2),r=await Promise.allSettled([ap1.execute(),ap2.execute(q2,ap2.reserve,b)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal((await f.view())!.history.length,2);});
 add(73,async()=>{for(const sameKey of [true,false]){const {f,a}=await funded(h),q=await f.movement([await f.portion(a,'200.00')]);const r=await race(h,f,q,sameKey?q:await change(f,q,{operationId:uid()}));assert.equal(r.filter(x=>x.status==='fulfilled').length,2);assert.equal((await f.view())!.movements.length,1);assert.equal((await f.su.funds.see()).summary.consumed,'200.00');}});
 add(74,async()=>{const {f,a}=await programmed(h),q=await f.movement([await f.portion(a,'200.00')],'200.00'),q2=await f.movement([await f.portion(a,'300.00','200.00')],'300.00');const r=await race(h,f,q,q2);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);const failed=r[0]!.status==='rejected'?q:q2;await apply(h,await change(f,failed,{expectedRevision:(await f.view())!.revision,movement:{...failed.movement,portions:[await f.portion(a,failed.movement!.amount,failed.movement!.portions[0]!.start)]}}));assert.equal((await f.view())!.paid,'500.00');assert.equal((await f.su.funds.see()).summary.consumed,'500.00');});
 add(75,async()=>{const {f,a}=await funded(h),q=await f.movement([await f.portion(a,'200.00')]),i=await f.command('incident',{incident:{id:uid(),sourceRef:'SYNTHETIC discrepancy',attemptRef:uid(),result:'uncertain',scope:'SYNTHETIC known'}});const r=await race(h,f,q,i);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal((await f.view())!.history.length,2);});
 add(76,async()=>{const {f,a}=await programmed(h),q=await f.movement([await f.portion(a,'200.00')]),w=await f.command('withdraw',{noExecution:true,noPendingExecution:true,noUnknownResult:true});const r=await race(h,f,q,w);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal((await f.view())!.history.length,3);});
 add(77,async()=>{const {f,a}=await funded(h),q=await f.movement([await f.portion(a,'200.00')]),consume=await f.su.funds.consume(a,'200.00'),controller=h.connect('h2_bootstrap');
  await controller.unsafe('begin');await controller`select actor_id from crm_private.crm_actors where actor_id=${h.actorId}::uuid for update`;
  const pending=apply(h,q).then(()=>null,e=>e);try{await waitLock(h);
   // A privileged synthetic controller owns the actor lock; the independent runtime cannot pass F2 yet.
   const tx=controller,op=uid(),act=uid(),allocation=(await tx`select snapshot from crm_private.b05_allocation_revisions where allocation_id=${a.allocationId!}::uuid order by revision desc limit 1`)[0]!.snapshot;
   await tx`insert into crm_private.b05_fund_operations values(${op}::uuid,${f.su.funds.paymentId}::uuid,${h.scope},${h.actorId}::uuid,'SYNTHETIC source change',${tx.json(consume as any)},${tx.json({})},clock_timestamp())`;
   await tx`insert into crm_private.b05_allocation_acts values(${act}::uuid,${op}::uuid,${a.allocationId!}::uuid,${f.su.funds.paymentId}::uuid,${h.scope},'consume',0,-200,null,${tx.json(allocation)},${tx.json(allocation)},${h.actorId}::uuid,${consume.reason},${consume.sourceRef},${consume.evidenceId}::uuid,${consume.at}::timestamptz,clock_timestamp())`;
   await tx`select crm_private.fund_refresh(${f.su.funds.paymentId}::uuid,${h.scope},${h.actorId}::uuid,'SYNTHETIC source change',${op}::uuid,null)`;
   await tx`insert into crm_private.b05_fund_history values(${op}::uuid,${f.su.funds.paymentId}::uuid,${h.scope},'{}','{}',${h.actorId}::uuid,${consume.reason},${consume.sourceRef},${consume.evidenceId}::uuid,${consume.at}::timestamptz,clock_timestamp())`;
   await tx.unsafe('commit');assert.ok(await pending instanceof Error);assert.equal((await f.view())!.paid,'0.00');assert.equal((await f.su.funds.see()).summary.consumed,'200.00');
  }finally{await controller.unsafe('rollback');await pending;}
 });
 add(78,async()=>{const {f,a}=await programmed(h);for(const action of ['confirm','record','incident','withdraw','correct','resolve'] as const){const q=action==='record'?await f.movement([await f.portion(a,'200.00')]):await f.command(action,{confirmedAmount:'600.00'});await deny(h,f,await change(f,q,{expectedRevision:0}));}});
 add(79,async()=>{const {f,a}=await funded(h),q=await f.movement([await f.portion(a,'200.00')]);const lock=h.connect('h2_bootstrap');await lock`select pg_advisory_lock(301279)`;await fault(h,'b05_provider_outgoing_movements',false,'perform pg_advisory_xact_lock(301279);','after');const before=await f.view();const pending=apply(h,q),settled=pending.then(v=>({v}),e=>({e}));let readCompleted=false;try{await waitLock(h);
  const visible=(await h.observer`select after_data from crm_private.b05_provider_payment_revisions where provider_payment_id=${f.id}::uuid order by revision desc limit 1`)[0]!.after_data;assert.equal(visible.paid,'0.00');assert.equal(visible.revision,before!.revision);
  const reader=h.providerPayments.read(await h.auth(),read,f.id,f.su.bookingId).then(x=>{readCompleted=true;return x;});await new Promise(r=>setTimeout(r,20));assert.equal(readCompleted,false,'single Admin F2 correctly serializes interactive access');await lock`select pg_advisory_unlock(301279)`;assert.ok('v' in await settled);assert.equal((await reader)!.paid,'200.00');
 }finally{await lock`select pg_advisory_unlock_all()`;await settled;await clear(h,'b05_provider_outgoing_movements');}});
 for(const [i,table] of ['b05_provider_payments','b05_provider_payment_revisions','b05_provider_outgoing_movements','b05_fund_history','b05_provider_payment_operations','b05_provider_outgoing_correspondences','b05_provider_payment_revisions','b05_provider_payment_corrections','b05_provider_payment_revisions','b05_suplido_revisions','b05_provider_payment_operations'].entries())add(i+80,async()=>{
  const {f,a}=await programmed(h);let q=await f.movement([await f.portion(a,'200.00')]);let execute=()=>apply(h,q);
  if(i===0){const fresh=await providerPaymentFixture(h);q=await fresh.open();execute=()=>apply(h,q);}
  if(i===1){const fresh=await staged(h),sq=await fresh.schedule(),approval=await fresh.approval(sq);execute=()=>approval.execute() as never;}
  if(i===6)q=await f.command('incident',{incident:{id:uid(),sourceRef:'SYNTHETIC discrepancy',attemptRef:uid(),result:'uncertain',scope:'SYNTHETIC known'}});
  if(i===7){await apply(h,q);q=await f.command('correct',{originalMovementId:(await f.view())!.movements[0]!.id as string,previousEffectCheck:'occurred_verified'});}
  if(i===8)q=await f.command('withdraw',{noExecution:true,noPendingExecution:true,noUnknownResult:true});
  const before=await snapshot(h);await fault(h,table,i===10);try{await assert.rejects(execute());assert.deepEqual(await snapshot(h),before);}finally{await clear(h,table);}
 });
 add(91,async()=>{const f=await staged(h),q=await f.command('confirm',{confirmedAmount:'500.00'});for(const kind of ['f1','f2','scope'] as const)await assert.rejects(forged(h,q,kind));await deny(h,f,await change(f,q,{origin:'ai'}));await h.admin`update crm_private.crm_actors set enabled=false where actor_id=${h.actorId}::uuid`;try{await assert.rejects(apply(h,q));}finally{await h.admin`update crm_private.crm_actors set enabled=true where actor_id=${h.actorId}::uuid`;}});
 add(92,async()=>{for(const user of ['crm_h0_runtime','anon','authenticated','crm_h0_ha_tx'])for(const table of tables){const sql=h.connect(user);await assert.rejects(sql.unsafe(`select * from crm_private.${table}`));await assert.rejects(sql.unsafe(`delete from crm_private.${table}`));}await assert.rejects(h.runtime.unsafe('set role crm_h0_ha_tx'));assert.equal((await h.admin`select count(*)::int n from pg_auth_members m join pg_roles r on r.oid=m.roleid where r.rolname='crm_h0_ha_tx'`)[0]!.n,0);});
 add(93,async()=>{for(const table of tables)await assert.rejects(h.admin.unsafe(`update crm_private.${table} set admin_scope=admin_scope`));});
 add(94,async()=>{const f=await staged(h);assert.equal(await h.providerPayments.read(await h.auth(),read,f.id,uid()),null);assert.equal(await h.providerPayments.read(await h.auth(),read,uid(),f.su.bookingId),null);for(const field of ['reference','amount','providerId','filename']){const q=encodeF1Fields(['CRM-H3-PROVIDER-PAYMENT-READ1',canonicalCommercial({providerPaymentId:f.id,bookingId:f.su.bookingId,[field]:'SYNTHETIC enumerate'})]);assert.ok(q.length>0);await assert.rejects(forged(h,{providerPaymentId:f.id,bookingId:f.su.bookingId,[field]:'SYNTHETIC enumerate'} as unknown as ProviderPaymentCommand,'read'));}});
 add(95,async()=>{const files=(await readdir(new URL('../../supabase/migrations',import.meta.url))).filter(f=>f.endsWith('.sql'));assert.equal(files.length,36);for(const table of tables){const r=(await h.admin`select relrowsecurity,relforcerowsecurity,pg_get_userbyid(relowner) owner from pg_class where oid=${'crm_private.'+table}::regclass`)[0]!;assert.equal(r.relrowsecurity,true);assert.equal(r.relforcerowsecurity,true);assert.equal(r.owner,'crm_h0_f2_owner');assert.equal((await h.admin`select has_table_privilege('crm_h0_runtime',${'crm_private.'+table},'INSERT') yes`)[0]!.yes,false);}const funcs=await h.admin`select p.proname,p.prosecdef,p.proconfig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='crm_api' and p.proname like 'provider_payment_%'`;assert.equal(funcs.length,4);for(const f of funcs)assert.ok(f.proconfig.includes('search_path=pg_catalog, pg_temp'));});
 add(96,async()=>{const u=await isolatedProviderPayment('crm_h3_012_upgrade',55713,true);try{const f=await (await import('../support/h3-suplido-fixtures.ts')).suplidoFixture(u);await u.suplidos.apply(await u.auth(),write,await f.open());const a=await f.assign();await u.suplidos.apply(await u.auth(),write,await f.fundsCommand([a.allocationId!]));await u.suplidos.apply(await u.auth(),write,await f.attachInvoice());const original=(await u.invoices.read(await u.auth(),read,f.invoice.invoiceId,f.bookingId))!.document as any,objectContext={contextKind:'booking' as const,contextId:f.bookingId,purpose:'provider-invoice-documentary'},bytes=await u.objects.download(await u.auth(),read,original.objectVersionId,objectContext);const names=(await u.admin`select tablename from pg_tables where schemaname='crm_private' order by tablename`).map(r=>r.tablename as string),before=await snapshots(u,names);await u.migration.unsafe(await readFile(new URL('../../supabase/migrations/'+providerPaymentMigration,import.meta.url),'utf8'));assert.deepEqual(await snapshots(u,names),before);assert.equal((await f.see())!.components.payment,null);assert.deepEqual(await u.objects.download(await u.auth(),read,original.objectVersionId,objectContext),bytes);}finally{await u.close();}});
 add(97,async()=>{const u=await isolatedProviderPayment('crm_h3_012_rollback',55714,true);try{const before=(await u.admin`select oid,pg_get_functiondef(oid) def from pg_proc where pronamespace in ('crm_private'::regnamespace,'crm_api'::regnamespace) order by oid`);await u.admin.unsafe("create function public.h3012_mig_fault() returns event_trigger language plpgsql as $$declare x record;begin for x in select * from pg_event_trigger_ddl_commands() loop if x.object_identity='crm_private.b05_provider_payment_revisions' then raise exception 'SYNTHETIC_MIGRATION_FAILURE';end if;end loop;end$$;create event trigger h3012_mig_fault on ddl_command_end when tag in ('CREATE TABLE') execute function public.h3012_mig_fault()");await assert.rejects(u.migration.unsafe(await readFile(new URL('../../supabase/migrations/'+providerPaymentMigration,import.meta.url),'utf8')));await u.migration.unsafe('rollback');assert.equal((await u.admin`select to_regclass('crm_private.b05_provider_payments') is null missing`)[0]!.missing,true);assert.deepEqual(await u.admin`select oid,pg_get_functiondef(oid) def from pg_proc where pronamespace in ('crm_private'::regnamespace,'crm_api'::regnamespace) order by oid`,before);}finally{await u.close();}});
 add(98,async()=>{const path='specs/001-core-crm/expected-TSK-H3-011-012.md',raw=await readFile(path,'utf8');assert.equal(raw,spawnSync('git',['show','0950781:'+path],{encoding:'utf8'}).stdout);const cases=raw.match(/^\|R\d{3}\|/gm)!;assert.equal(cases.length,100);assert.equal(new Set(cases).size,100);const migrationFiles=(await readdir('supabase/migrations')).filter(f=>f.endsWith('.sql')&&f<providerPaymentMigration);assert.equal(migrationFiles.length,35);for(const file of migrationFiles){const live=await readFile('supabase/migrations/'+file),base=spawnSync('git',['show','028cbae:supabase/migrations/'+file]).stdout;assert.equal(createHash('sha256').update(live).digest('hex'),createHash('sha256').update(base).digest('hex'));}});
 add(99,async()=>{const {f}=await complete(h);const s=(await f.su.see())!;assert.equal(s.evaluation!.fiscalValidation,false);assert.equal(s.evaluation!.bookingClosureInferred,false);assert.equal(s.components.mandate,null);for(const field of ['fiscalValidation','mandate','bookingClosure','ownCost'])await deny(h,f,await change(f,await f.command('confirm',{confirmedAmount:'500.00'}),{[field]:true}));});
 add(100,async()=>{const {f}=await complete(h);const su=(await f.su.see())!;assert.equal((su.components.outgoingReconciliation as any).direction,'outgoing');assert.equal((su.components.outgoingReconciliation as any).verified,true);assert.equal(su.components.reconciliation,null);assert.ok((su.components.outgoingReconciliation as any).providerPaymentId);});
 try{assert.equal(Object.keys(cases).length,100);for(const [id,fn] of Object.entries(cases))await t.test(id,fn);}finally{await h.close();}
});
