import {readFile,readdir} from 'node:fs/promises';import {spawnSync} from 'node:child_process';
import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID as uid} from 'node:crypto';
import {isolatedSuplido,write} from '../support/h3-suplido-isolated.ts';
import {suplidoFixture} from '../support/h3-suplido-fixtures.ts';
test('H3-010-F01 minimal seeded historical revision retains stale protection',async()=>{const h=await isolatedSuplido('crm_h3_010_f',55714);try{const f=await suplidoFixture(h);await h.suplidos.apply(await h.auth(),write,await f.open());const a=await f.assign();await h.suplidos.apply(await h.auth(),write,await f.fundsCommand([a.allocationId!]));const before=(await f.see())!;const op=uid(),rev=before.revision+1,q=await f.command('evaluate'),next={...before,revision:rev,status:'Documentalmente resuelto'};
 const raw=JSON.stringify(next);assert.equal((await h.observer`select jsonb_typeof(${raw}::jsonb) type`)[0]!.type,'string');
 await h.migration.begin(async tx=>{
  await tx.unsafe('insert into crm_private.b05_suplido_operations values($1::uuid,$2::uuid,$3,$4::uuid,$5,$6::text::jsonb,$7,clock_timestamp())',[op,f.suplidoId,h.scope,h.actorId,'SYNTHETIC',JSON.stringify({id:f.suplidoId,result:next}),rev]);
  await tx.unsafe("insert into crm_private.b05_suplido_revisions values($1::uuid,$2,$3,$4::uuid,'evaluate','{}',$5::text::jsonb,$6::text::jsonb,$7::uuid,$8::uuid,$9,$10,$11::timestamptz,clock_timestamp())",[f.suplidoId,rev,h.scope,op,JSON.stringify(before),JSON.stringify(next),h.actorId,q.evidenceId,'SYNTHETIC','SYNTHETIC',f.at]);
 });
 const seen=(await f.see())!,fresh=await f.command('discrepancy',{component:'invoice',incidentId:uid()});assert.equal(seen.revision,rev);assert.equal(fresh.expectedRevision,rev);await h.suplidos.apply(await h.auth(),write,fresh);
 }finally{await h.close();}});

test('H3-010-F02 prebuilt command becomes stale; current attestation succeeds',async()=>{const h=await isolatedSuplido('crm_h3_010_f2',55715);try{const f=await suplidoFixture(h);await h.suplidos.apply(await h.auth(),write,await f.open());const old=await f.command('evaluate');await h.suplidos.apply(await h.auth(),write,await f.command('component',{component:'amount',confirmedAmount:'500.00'}));await assert.rejects(h.suplidos.apply(await h.auth(),write,old),/REVISION_CONFLICT/);await h.suplidos.apply(await h.auth(),write,await f.command('evaluate'));assert.equal((await f.see())!.revision,3);}finally{await h.close();}});
test('H3-010-F03 pre-migration fixture does not call an absent API',async()=>{const h=await isolatedSuplido('crm_h3_010_f3',55716,true);try{const f=await suplidoFixture(h);await assert.rejects(f.command('evaluate'));const open=await f.open();assert.equal(open.expectedRevision,0);await f.attachInvoice(4,{},0);assert.equal((await h.observer`select count(*)::int n from crm_private.b05_provider_invoices where invoice_id=${f.invoice.invoiceId}::uuid`)[0]!.n,1);}finally{await h.close();}});
test('H3-010-F04 changed funds cannot be presented as current usable snapshot',async()=>{const h=await isolatedSuplido('crm_h3_010_f4',55717);try{const f=await suplidoFixture(h);await h.suplidos.apply(await h.auth(),write,await f.open());const a=await f.assign();await h.suplidos.apply(await h.auth(),write,await f.fundsCommand([a.allocationId!]));await h.suplidos.apply(await h.auth(),write,await f.command('evaluate'));const previous=(await f.see())!;await h.payments.apply(await h.auth(),write,await f.funds.discrepancy(4,'0.00','100.00'));const currentSql=await readFile(new URL('../../supabase/migrations/20261004175435_h3_managed_client_funds_documentary.sql',import.meta.url),'utf8');
 const originalSql=spawnSync('git',['show','93a1432:supabase/migrations/20261004175435_h3_managed_client_funds_documentary.sql'],{encoding:'utf8'});assert.equal(originalSql.status,0);
 const func=(sql:string)=>sql.slice(sql.indexOf('create function crm_api.suplido_read'),sql.indexOf('end$$;',sql.indexOf('create function crm_api.suplido_read'))+7).replace('create function','create or replace function');
 await h.admin.unsafe(func(originalSql.stdout));try{const old=await f.see() as any;assert.equal(old.sourceRevalidationRequired,undefined);assert.equal(old.components.funds.usable,'300.00');assert.throws(()=>assert.equal(old.currentComponents?.funds.usable,'200.00'));}finally{await h.admin.unsafe(func(currentSql));}
 const now=await f.see() as any;assert.deepEqual(now.sourceRevalidationRequired,['funds']);assert.equal(now.currentComponents.funds.usable,'200.00');assert.equal(now.components.funds.usable,'300.00');assert.equal(now.history.length,previous.history.length);assert.equal(now.status,'Revisión');await h.suplidos.apply(await h.auth(),write,await f.command('evaluate'));assert.deepEqual((await f.see() as any).sourceRevalidationRequired,[]);}finally{await h.close();}});

test('H3-010-F05 historical migration inventory must exclude subsequent forward migrations',async()=>{const {invoiceMigration}=await import('../support/h3-invoice-isolated.ts');const {suplidoMigration}=await import('../support/h3-suplido-isolated.ts');const all=(await readdir('supabase/migrations')).filter(x=>x.endsWith('.sql')&&x<=suplidoMigration);assert.equal(all.length,35);assert.throws(()=>assert.equal(all.length,34),/35 !== 34/);assert.equal(all.filter(x=>x<=invoiceMigration).length,34);const verifier=await readFile(new URL('./postgres-h3-008-defects.test.ts',import.meta.url),'utf8');assert.ok(verifier.includes('x<=invoiceMigration'));});
