/** Independent normative oracle fixed in expected-TSK-H2-009-010.md before38793e6. */
import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID as uid} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import {isolatedBooking,bookingMigration,write,read} from '../support/h2-booking-isolated.ts';
import {bookingFixture} from '../support/h2-booking-fixtures.ts';
import {now} from '../support/h2-acceptance-fixtures.ts';
import type {BookingCommand} from '../../src/infrastructure/postgres/h2-booking-adapter.ts';
import type {BookingDetail} from '../../src/domain/booking-conversion.ts';
import {createF1Issuer,encodeF1Fields} from '../../src/infrastructure/postgres/f1-codec.ts';
import {createF2Issuer} from '../../src/infrastructure/postgres/f2-codec.ts';
import {issueTrustedContext} from '../../src/application/trusted-context.ts';
import {postgresF1Binding} from '../../src/infrastructure/postgres/transaction.ts';
import {canonicalCommercial} from '../../src/domain/commercial-progress.ts';
import {verifyAuth} from '../../src/application/verified-auth.ts';
let h:Awaited<ReturnType<typeof isolatedBooking>>,prior:unknown,upgraded:unknown;
type B=Awaited<ReturnType<typeof bookingFixture>>;
async function snapshot(){const d:Record<string,unknown>={};for(const {tablename:t} of await h.observer`select tablename from pg_tables where schemaname='crm_private' order by tablename`){d[t]=(await h.observer.unsafe(`select coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]') d from crm_private.${t} x`))[0]!.d;}return d;}
async function baseline(){const d=await snapshot();for(const t of Object.keys(d))if(t.startsWith('b04_'))delete d[t];return d;}
async function counts(opp:string){return Number((await h.observer`select count(*) n from crm_private.b04_bookings where opportunity_id=${opp}::uuid`)[0]!.n);}
async function apply(q:BookingCommand){return h.booking.apply(await h.auth(),write,q);}
async function negative(q:BookingCommand,raw=false){const old=await snapshot();await assert.rejects(raw?rawApply(q):apply(q));assert.deepEqual(await snapshot(),old);}
async function amended(b:B,change:(d:BookingDetail)=>void){const d=structuredClone(b.detail);change(d);return {...b.q,detail:d,evidenceId:await b.proof(d)};}
async function rawApply(q:BookingCommand,scope=h.scope,bad=false){const auth=await h.auth();return h.runtime.begin(async tx=>{
 const row=(await tx`select actor_id::text,admin_scope,access_generation::text,epoch_id::text from crm_api.f2_lookup(${auth.subject}::uuid,${auth.sessionId!}::uuid)`)[0]!,binding=await postgresF1Binding(tx),identity={actorId:row.actor_id,scope:row.admin_scope,sessionId:auth.sessionId!,accessGeneration:row.access_generation,epochId:row.epoch_id};
 const sign=(q:Buffer,purpose='h1-evidence')=>{const identities=purpose==='h1-identities',t=createF1Issuer(h.f1)(issueTrustedContext({identityId:'H2010 independent verifier',identityKind:'technical',purpose,scope,requestId:uid(),serverTime:now()}),binding,'C03',q,{resource:identities?'identities':'evidence',action:identities?'write_identity':'write_evidence'}),a=createF2Issuer(h.f2)(auth,identity,binding,identities?'identity_write':'evidence_write',q,write);return {t,a};};
 const data=encodeF1Fields(['CRM-H2-BOOKING1',canonicalCommercial(q)]),x=sign(data),cq=encodeF1Fields(['CRM-H1-RESOLVE1','assign_code',q.bookingId,q.bookingId,'','RES',q.sourceRef,q.evidenceId,q.reason,'0']),c=sign(cq,'h1-identities');
 return tx`select crm_api.booking_apply(${x.a.payload},${bad?Buffer.alloc(32):x.a.mac},${x.t.payload},${x.t.mac},${data},${c.a.payload},${c.a.mac},${c.t.payload},${c.t.mac},${cq}) r`;
 });}
async function rectification(b:B){const at=now(),e=await b.f.proof(`acceptance:error:${b.r.acceptanceId}`,b.r.coverage,at),review=await b.f.proof(`acceptance:reevaluate:${b.r.acceptanceId}:Necesidad definida`,b.r.coverage,at);return b.f.q({action:'rectify',acceptanceId:b.r.acceptanceId,coverage:b.r.coverage,at,evidenceId:e,humanReviewed:true,reevaluation:{destination:'Necesidad definida',evidenceId:review,dependentEffects:['verification','commercial']}});}
before(async()=>{h=await isolatedBooking('crm_h2_010',55483,true);await bookingFixture(h);prior=await baseline();await h.migration.unsafe(await readFile(new URL(`../../supabase/migrations/${bookingMigration}`,import.meta.url),'utf8'));upgraded=await baseline();});
after(async()=>{await h?.close();});
test('R01 normal valid chain exact immutable Booking',async()=>{const b=await bookingFixture(h);await apply(b.q);assert.equal(await counts(b.q.opportunityId),1);const row=(await h.observer`select * from crm_private.b04_bookings where booking_id=${b.q.bookingId}::uuid`)[0]!;assert.equal(row.state,'Pendiente de preparación');assert.deepEqual(row.terms,b.q.terms);assert.equal(row.acceptance_id,b.r.acceptanceId);assert.equal(row.verification_id,b.vq.operationId);assert.equal((row.chain_snapshot as Record<string,unknown>).acceptance!==undefined,true);});
test('R02 direct reuses existing real chain without Lead or fake sends',async()=>{const b=await bookingFixture(h),old=await baseline();await h.booking.direct(await h.auth(),write,[],{...b.q,route:'direct'});const after=await baseline();delete old.identity_contexts;delete after.identity_contexts;delete old.identity_codes;delete after.identity_codes;delete old.identity_code_counters;delete after.identity_code_counters;delete old.identity_resolutions;delete after.identity_resolutions;delete old.identity_resolution_history;delete after.identity_resolution_history;delete old.identification_epochs;delete after.identification_epochs;assert.equal(await counts(b.q.opportunityId),1);assert.equal((await h.observer`select lead_id from crm_private.b03_opportunities where opportunity_id=${b.q.opportunityId}::uuid`)[0]!.lead_id,null);for(const t of ['b03_acceptances','b03_proposal_versions','b07_records','b07_facts','b07_links'])assert.deepEqual(after[t],old[t]);});
test('R03 direct composes real T02 then T03 atomically; missing agreement retains preparation',async()=>{const b=await bookingFixture(h,'total',false),q={...b.q,route:'direct' as const,expectedRevision:b.q.expectedRevision+1,expectedOpportunityRevision:b.q.expectedOpportunityRevision+1};await h.booking.direct(await h.auth(),write,[{kind:'acceptance',command:b.vq}],q);assert.equal(await counts(q.opportunityId),1);const n=await bookingFixture(h,'total',false);await negative({...n.q,route:'direct'});assert.ok((await h.observer`select version_id from crm_private.b03_proposal_versions where version_id=${n.q.versionId}::uuid`).length);});
test('R04 uniqueness at database boundary',async()=>{const b=await bookingFixture(h);await apply(b.q);await assert.rejects(h.migration`insert into crm_private.b04_bookings select * from crm_private.b04_bookings where booking_id=${b.q.bookingId}::uuid`,/duplicate key/);assert.equal(await counts(b.q.opportunityId),1);});
for(const [number,same] of [[5,true],[6,false]] as const)test(`R${String(number).padStart(2,'0')} concurrent ${same?'same':'different'} keys both dispatch orders`,async()=>{for(const reverse of [false,true]){const b=await bookingFixture(h),auth=await h.auth(),q={...b.q,...(!same?{operationId:uid(),bookingId:uid()}: {})};const requests=reverse?[q,b.q]:[b.q,q],out=await Promise.allSettled(requests.map(x=>h.booking.apply(auth,write,x)));assert.equal(out.filter(x=>x.status==='fulfilled').length,2);assert.equal(await counts(q.opportunityId),1);const ids=out.map(x=>x.status==='fulfilled'?x.value.id:null);assert.equal(ids[0],ids[1]);}});
test('R07 exact replay retains root code detail and history',async()=>{const b=await bookingFixture(h);await apply(b.q);const old=await snapshot();delete old.identification_epochs;assert.equal((await apply(b.q)).replayed,true);const after=await snapshot();delete after.identification_epochs;assert.deepEqual(after,old);});
test('R08 committed result survives lost response',async()=>{const b=await bookingFixture(h);await rawApply(b.q);const q=await apply(b.q);assert.equal(q.id,b.q.bookingId);assert.equal(q.replayed,true);assert.equal(await counts(b.q.opportunityId),1);});
test('R09 changed replay conflicts E2',async()=>{const b=await bookingFixture(h);await apply(b.q);await negative({...b.q,reason:'material changed'});});
test('R10 unverified Acceptance no Booking',async()=>{const b=await bookingFixture(h,'total',false);await negative(b.q);assert.equal(await counts(b.q.opportunityId),0);});
test('R11 textual Ganada cannot substitute exact chain',async()=>{const b=await bookingFixture(h);await negative({...b.q,acceptanceId:uid()});await negative({...b.q,proposalId:uid()});});
test('R12 rectified Acceptance does not permit conversion',async()=>{const b=await bookingFixture(h);await h.acceptance.apply(await h.auth(),write,await rectification(b));await negative(b.q);assert.ok((await h.observer`select * from crm_private.b03_acceptances where acceptance_id=${b.q.acceptanceId}::uuid`).length);});
test('R13 exact modality A leaves B uncontracted',async()=>{const b=await bookingFixture(h,'modality');await apply(b.q);const rows=await h.observer`select modality_id from crm_private.b04_contributions where booking_id=${b.q.bookingId}::uuid`;assert.deepEqual(rows.map(x=>x.modality_id),[b.f.mid]);});
test('R14 exact selectable line only',async()=>{const b=await bookingFixture(h,'line');await apply(b.q);assert.deepEqual((await h.observer`select line_id from crm_private.b04_contributions where booking_id=${b.q.bookingId}::uuid`).map(x=>x.line_id),[b.f.line]);});
test('R15 no unselected/nonselectable part sneaks into Booking',async()=>{const b=await bookingFixture(h,'modality');const q=await amended(b,d=>{(d.services as unknown[]).push({...d.services[0],id:uid(),contributions:[{...d.services[0]!.contributions[0],id:uid(),lineId:b.f.content.modalities[1]!.lines[0]!.id,modalityId:b.f.other}]});});await negative(q);});
test('R16 wrong version and terms reject atomically',async()=>{const b=await bookingFixture(h);for(const q of [{...b.q,versionId:uid()},{...b.q,terms:{text:'changed'}},{...b.q,coverage:uid()}])await negative(q);});
test('R17 incomplete detail no fictitious complete Booking',async()=>{const b=await bookingFixture(h),q=await amended(b,d=>{(d.services as unknown[]).pop();});await negative(q);await negative({...b.q,detail:{...b.detail,services:[]}});});
async function multimodal(){
 const b=await bookingFixture(h,'total',false),unit=b.f.content.modalities[0]!.lines[0]!.unitRevisionId,form=await h.cat('pricing_form',{name:'SYNTHETIC fixed',definition:'fixed'});
 const serviceRefs:{svc:{id:string;revision:string};tariff:{id:string;revision:string}}[]=[];
 for(const name of ['Rafting','Cena','Casa completa']){const svc=await h.cat('service',{name:`SYNTHETIC ${name}`,nature:'external'}),tariff=await h.com('tariff',{label:'SYNTHETIC',price_state:'confirmed',amount:'900.00',cost_state:'confirmed',cost_amount:'700.00',vat_treatment:'included',unit_revision_id:unit,pricing_form_revision_id:form.revision},svc);serviceRefs.push({svc,tariff});}
 const modalities=[10,2].map((participants,i)=>({id:uid(),name:i?'B':'A',participants,independent:true,selectable:true,conditions:'SYNTHETIC',finalPersonPrice:'100.01',manualReason:'SYNTHETIC',definitive:true,lines:[...[{kind:0,date:'2026-10-20'}].filter(()=>i===0),{kind:1,date:'2026-10-20'},{kind:2,date:'2026-10-20'},...[{kind:2,date:'2026-10-21'}].filter(()=>i===0)].map(x=>({id:uid(),serviceRevisionId:serviceRefs[x.kind]!.svc.revision,unitRevisionId:unit,tariffRevisionId:serviceRefs[x.kind]!.tariff.revision,quantity:'1',included:true,independent:false,selectable:false,date:x.date,datePending:false,priceBasis:'fixed' as const,costMaterial:true,sourceRef:'SYNTHETIC explicit contribution'}))}));
 const content={scope:'SYNTHETIC AC017 accepted scope',terms:b.f.content.terms,pending:[],modalities},proposalId=uid(),versionId=uid(),opp=b.q.opportunityId;
 const revision=async()=>({expectedRevision:Number((await h.observer`select revision from crm_private.b03_proposals where proposal_id=${proposalId}::uuid`)[0]?.revision??0),expectedOpportunityRevision:Number((await h.observer`select revision from crm_private.b03_opportunities where opportunity_id=${opp}::uuid`)[0]!.revision)});
 const cmd={action:'prepare' as const,operationId:uid(),proposalId,opportunityId:opp,...await revision(),sourceRef:'SYNTHETIC',reason:'SYNTHETIC',content};await h.proposal.apply(await h.auth(),write,cmd);await h.proposal.apply(await h.auth(),write,{...cmd,action:'fix',operationId:uid(),versionId,content:undefined,...await revision()});
 const proof=async(claim:string,at=now())=>b.f.proof(claim,content.scope,at),issued=now();await h.offer.apply(await h.auth(),write,{action:'issue',operationId:uid(),proposalId,opportunityId:opp,versionId,...await revision(),sourceRef:'SYNTHETIC',reason:'SYNTHETIC',coverage:content.scope,at:issued,issuance:{issuedAt:issued,limits:[]},evidenceId:await proof(`offer:issue:${versionId}:${issued}:7`,issued)});
 const acceptanceId=uid(),at=now(),r={action:'register' as const,operationId:uid(),acceptanceId,proposalId,opportunityId:opp,versionId,...await revision(),sourceRef:'SYNTHETIC',reason:'SYNTHETIC',coverage:content.scope,at,accepterId:b.f.accepterId,designationId:b.f.designationId,channel:'phone',terms:content.terms,authorityEvidenceId:await proof(`acceptance:authority:${versionId}:${b.f.accepterId}:${b.f.designationId}`,at),evidenceId:await proof(`acceptance:agree:${versionId}:${acceptanceId}:${b.f.accepterId}:phone`,at)};await h.acceptance.apply(await h.auth(),write,r);
 const reviewEvidence:Record<string,string>={};for(const aspect of ['prices','availability','conditions','capacity'])reviewEvidence[aspect]=await proof(`offer:review:${versionId}:${acceptanceId}:accept:${aspect}`,at);
 await h.acceptance.apply(await h.auth(),write,{action:'verify',operationId:uid(),acceptanceId,proposalId,opportunityId:opp,versionId,...await revision(),sourceRef:'SYNTHETIC',reason:'SYNTHETIC',coverage:content.scope,at,reviewEvidence,won:true});
 const services=serviceRefs.map(({svc},kind)=>{const contributions=modalities.flatMap(m=>m.lines.filter(l=>l.serviceRevisionId===svc.revision).map(l=>({id:uid(),lineId:l.id,modalityId:m.id,quantity:l.quantity,attendees:m.participants,certainty:'estimated' as const})));return {id:uid(),serviceRevisionId:svc.revision,nature:'external' as const,variant:null,provider:null,place:null,schedule:null,contributions,nights:kind===2?['2026-10-20','2026-10-21'].map(date=>({id:uid(),date,contributionIds:contributions.filter(c=>modalities.flatMap(m=>m.lines).find(l=>l.id===c.lineId)!.date===date).map(c=>c.id)})):[]};});
 const detail:BookingDetail={services,participants:[],assignments:[]};const detailProof=async(d:BookingDetail)=>{const hash=(await h.observer`select encode(crm_crypto.digest(convert_to(${JSON.stringify(d)}::text::jsonb::text,'UTF8'),'sha256'),'hex') hash`)[0]!.hash;return proof(`booking:detail:${acceptanceId}:${hash}`);};
 const q:BookingCommand={operationId:uid(),bookingId:uid(),opportunityId:opp,proposalId,versionId,acceptanceId,coverage:content.scope,terms:content.terms,...await revision(),sourceRef:'SYNTHETIC AC017',reason:'SYNTHETIC',evidenceId:await detailProof(detail),detail,route:'normal'};
 return {q,detail,detailProof,proof};
}
test('R18 AC017 rafting10 dinner12 nights12/10 with contributions',async()=>{const b=await multimodal();await apply(b.q);assert.equal(await counts(b.q.opportunityId),1);const services=await h.observer`select s.service_id,sum(c.attendees)::int people from crm_private.b04_services s join crm_private.b04_contributions c using(service_id) where s.booking_id=${b.q.bookingId}::uuid group by s.service_id`;assert.equal(services.find(s=>s.service_id===b.detail.services[0]!.id)!.people,10);assert.equal(services.find(s=>s.service_id===b.detail.services[1]!.id)!.people,12);const nights=await h.observer`select n.night_date::text date,sum(c.attendees)::int people from crm_private.b04_nights n join crm_private.b04_night_occupancies o using(night_id) join crm_private.b04_contributions c using(contribution_id) where c.booking_id=${b.q.bookingId}::uuid group by n.night_date order by n.night_date`;assert.deepEqual(Array.from(nights),[{date:'2026-10-20',people:12},{date:'2026-10-21',people:10}]);});
test('R19 exact inclusions only no extra contribution',async()=>{const b=await bookingFixture(h),q=await amended(b,d=>(d.services[0]!.contributions as unknown[]).push({...d.services[0]!.contributions[0],id:uid(),lineId:uid()}));await negative(q);});
test('R20 same catalog does not merge incompatible prestations',async()=>{const b=await bookingFixture(h);const q=await amended(b,d=>{(d.services[0] as {schedule:unknown}).schedule={requested:'morning',sourceRef:'synthetic'};(d.services[1] as {schedule:unknown}).schedule={requested:'evening',sourceRef:'synthetic'};});await apply(q);assert.equal((await h.observer`select count(*)::int n from crm_private.b04_services where booking_id=${q.bookingId}::uuid`)[0]!.n,2);});
test('R21 unit and quantity remain distinct from estimated attendees',async()=>{const b=await bookingFixture(h);await apply(b.q);const rows=await h.observer`select quantity::text,attendees::int,certainty,source_snapshot from crm_private.b04_contributions where booking_id=${b.q.bookingId}::uuid`;assert.ok(rows.every(r=>r.quantity==='1'&&r.attendees===10&&r.certainty==='estimated'));});
test('R22 night occupancy independent no rooms or person-night pricing inferred',async()=>{const b=await multimodal();await apply(b.q);assert.equal((await h.observer`select count(*)::int n from crm_private.b04_nights where service_id=${b.detail.services[2]!.id}::uuid`)[0]!.n,2);assert.deepEqual(b.detail.services[2]!.variant,null);});
async function nominal(b:Awaited<ReturnType<typeof multimodal>>,count=4){const d=structuredClone(b.detail),service=d.services[2]!,night=service.nights[0]!;const necessity=await b.proof(`booking:nominal:${b.q.acceptanceId}:${service.id}:${night.id}`);for(let i=0;i<count;i++){const id=uid(),e=await b.proof(`booking:participant:${b.q.acceptanceId}:${id}`);(d.participants as unknown[]).push({id,name:`SYNTHETIC Participant ${i}`,contactId:null,evidenceId:e,sourceRef:'SYNTHETIC identity proof'});(d.assignments as unknown[]).push({participantId:id,serviceId:service.id,nightId:night.id,necessity:'SYNTHETIC accommodation scoped requirement',evidenceId:necessity});}return {...b.q,detail:d,evidenceId:await b.detailProof(d)};}
test('R23 partial nominal4 explains12 without double count or fictitious8',async()=>{const b=await multimodal(),q=await nominal(b);await apply(q);assert.equal((await h.observer`select count(*)::int n from crm_private.b04_participants where booking_id=${q.bookingId}::uuid`)[0]!.n,4);const sum=(await h.observer`select sum(c.attendees)::int n from crm_private.b04_night_occupancies o join crm_private.b04_contributions c using(contribution_id) where night_id=${b.detail.services[2]!.nights[0]!.id}::uuid`)[0]!.n;assert.equal(sum,12);});
test('R24 nominal necessity required',async()=>{const b=await multimodal(),q=await nominal(b);const d=structuredClone(q.detail);(d.assignments[0] as {necessity:string}).necessity='';await negative({...q,detail:d,evidenceId:await b.detailProof(d)});});
test('R25 unverified Contact cannot become verified Participant association',async()=>{const b=await multimodal(),q=await nominal(b),id=uid();await h.identities.apply(await h.auth(),write,{action:'create_entity',operationId:uid(),targetId:id,kind:'contact',expectedVersion:0,sourceRef:'SYNTHETIC',evidenceRef:'SYNTHETIC',reason:'SYNTHETIC',verified:false,displayName:'SYNTHETIC unverified'});const d=structuredClone(q.detail);(d.participants[0] as {contactId:string|null}).contactId=id;await negative({...q,detail:d,evidenceId:await b.detailProof(d)});});
test('R26 duplicate nominal assignment rejected',async()=>{const b=await multimodal(),q=await nominal(b),d=structuredClone(q.detail);(d.assignments as unknown[]).push(d.assignments[0]);await negative({...q,detail:d,evidenceId:await b.detailProof(d)});});
test('R27 accepter and actor not nominal participants by default',async()=>{const b=await bookingFixture(h);await apply(b.q);assert.equal((await h.observer`select count(*)::int n from crm_private.b04_participants where booking_id=${b.q.bookingId}::uuid`)[0]!.n,0);const root=(await h.observer`select chain_snapshot,actor_id from crm_private.b04_bookings where booking_id=${b.q.bookingId}::uuid`)[0]!;assert.equal((root.chain_snapshot as {acceptance:{accepter_id:string}}).acceptance.accepter_id,b.f.accepterId);assert.equal(root.actor_id,h.actorId);});
test('R28 changing Primary Contact preserves Acceptance and Booking chain',async()=>{const b=await bookingFixture(h);await apply(b.q);const old=(await h.observer`select chain_snapshot from crm_private.b04_bookings where booking_id=${b.q.bookingId}::uuid`)[0]!.chain_snapshot,id=uid();await h.identities.apply(await h.auth(),write,{action:'create_entity',operationId:uid(),targetId:id,kind:'contact',expectedVersion:0,sourceRef:'SYNTHETIC',evidenceRef:'SYNTHETIC',reason:'SYNTHETIC',verified:true,displayName:'SYNTHETIC later contact'});await h.identities.apply(await h.auth(),write,{action:'designate',operationId:uid(),targetId:uid(),relatedId:id,contextId:b.q.opportunityId,kind:'primary_contact',expectedVersion:1,sourceRef:'SYNTHETIC',evidenceRef:'SYNTHETIC',reason:'SYNTHETIC',verified:true,happenedAt:now()});assert.deepEqual((await h.observer`select chain_snapshot from crm_private.b04_bookings where booking_id=${b.q.bookingId}::uuid`)[0]!.chain_snapshot,old);});
async function fault(table:string,late=false){const b=await bookingFixture(h),old=await snapshot();await h.admin.unsafe(`create function crm_private.h2010_fault() returns trigger language plpgsql as $$ begin raise exception 'H2010 injected fault';end $$;create ${late?'constraint ':''}trigger h2010_fault ${late?'after':'before'} insert on crm_private.${table} ${late?'deferrable initially deferred ':''}for each row execute function crm_private.h2010_fault()`);try{await assert.rejects(apply(b.q));assert.deepEqual(await snapshot(),old);}finally{await h.admin.unsafe(`drop trigger h2010_fault on crm_private.${table};drop function crm_private.h2010_fault()`);}}
for(const [r,t,late] of [[29,'identity_contexts',false],[30,'b04_services',false],[31,'b04_contributions',false],[32,'b04_modalities',false],[33,'b04_contributions',false],[34,'b04_history',false],[35,'b04_operations',true]] as const)test(`R${r} fault ${t} ${late?'at COMMIT':'material write'} rolls back all`,()=>fault(t,late));
test('R36 concurrent revision change rejects stale conversion',async()=>{for(const reverse of [false,true]){const b=await bookingFixture(h),q=await rectification(b),auth=await h.auth();const work=[()=>h.booking.apply(auth,write,b.q),()=>h.acceptance.apply(auth,write,q)];if(reverse)work.reverse();const out=await Promise.allSettled(work.map(f=>f()));assert.ok(out.some(x=>x.status==='fulfilled'));assert.ok(await counts(b.q.opportunityId)<=1);}});
test('R37 rectification first prevents conversion; original never erased',async()=>{const b=await bookingFixture(h),q=await rectification(b);await h.acceptance.apply(await h.auth(),write,q);await negative({...b.q,...await b.f.revisions()});});
test('R38 no trusted auth context or null SQL envelope',async()=>{const b=await bookingFixture(h);await assert.rejects(h.booking.apply({} as Awaited<ReturnType<typeof h.auth>>,write,b.q));await assert.rejects(h.runtime`select crm_api.booking_apply(null,null,null,null,null,null,null,null,null,null)`);});
test('R39 forged context and signature fail closed',async()=>{const b=await bookingFixture(h),old=await snapshot();await assert.rejects(rawApply(b.q,'forged-scope'));await assert.rejects(rawApply(b.q,h.scope,true));assert.deepEqual(await snapshot(),old);});
test('R40 disabled and unprovisioned actor including replay',async()=>{const b=await bookingFixture(h);await apply(b.q);const old=await snapshot(),auth=await verifyAuth({verify:async()=>({subject:uid(),sessionId:uid(),passwordVerified:true,mfaVerified:true})},uid());await assert.rejects(h.booking.apply(auth,write,b.q));await h.migration`update crm_private.crm_actors set enabled=false where actor_id=${h.actorId}::uuid`;try{await assert.rejects(apply(b.q));}finally{await h.migration`update crm_private.crm_actors set enabled=true where actor_id=${h.actorId}::uuid`;}assert.deepEqual(await snapshot(),old);});
test('R41 ordinary SQL roles ACL/FORCE RLS and authorized direct SQL',async()=>{const b=await bookingFixture(h);await rawApply(b.q);for(const role of ['anon','authenticated']){const c=h.connect(role);await assert.rejects(c`select * from crm_private.b04_bookings`);await assert.rejects(c`select crm_api.booking_apply(null,null,null,null,null,null,null,null,null,null)`);}const rows=await h.observer`select c.relname,c.relrowsecurity,c.relforcerowsecurity,c.relowner::regrole::text owner from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='crm_private' and c.relkind='r' and c.relname like 'b04_%'`;assert.equal(rows.length,10);assert.ok(rows.every(x=>x.relrowsecurity&&x.relforcerowsecurity&&x.owner==='crm_h0_f2_owner'));assert.equal((await h.runtime`select rolsuper,rolbypassrls from pg_roles where rolname=current_user`)[0]!.rolbypassrls,false);});
test('R42 append-only immutable facts visible independently',async()=>{const b=await bookingFixture(h);await apply(b.q);for(const t of ['b04_bookings','b04_services','b04_contributions','b04_history','b03_acceptances','b03_proposal_versions']){await assert.rejects(h.runtime.unsafe(`update crm_private.${t} set admin_scope='forged'`));await assert.rejects(h.runtime.unsafe(`delete from crm_private.${t}`));}assert.equal(await counts(b.q.opportunityId),1);});
test('R43 RES reuses H1 allocator Madrid year stable replay',async()=>{const b=await bookingFixture(h);await apply(b.q);const c=(await h.observer`select * from crm_private.identity_codes where target_id=${b.q.bookingId}::uuid and code_kind='RES'`)[0]!;assert.equal(c.code_year,2026);assert.match(String(c.human_code),/^RES-2026-\d{4,}$/);assert.equal((await apply({...b.q,operationId:uid(),bookingId:uid()})).id,b.q.bookingId);assert.equal((await h.observer`select count(*)::int n from crm_private.identity_codes where target_id=${b.q.bookingId}::uuid and code_kind='RES'`)[0]!.n,1);});
test('R44 empty database full migration chain',async()=>{await h.admin.unsafe('create database h2010_empty owner crm_h0_migration');await h.applyChain(h.connect('crm_h0_migration','h2010_empty'),h.connect('h2_bootstrap','h2010_empty'),bookingMigration);assert.equal((await h.connect('crm_h0_migration','h2010_empty')`select count(*)::int n from crm_private.b04_bookings`)[0]!.n,0);});
test('R45 predecessor upgrade retains all prior fixtures',()=>assert.deepEqual(upgraded,prior));
test('R46 migration fault rolls back objects and privileges',async()=>{await h.admin.unsafe('create database h2010_fault owner crm_h0_migration');const m=h.connect('crm_h0_migration','h2010_fault'),a=h.connect('h2_bootstrap','h2010_fault');await h.applyChain(m,a,'20261001172433_h2_exact_acceptance.sql');const sql=await readFile(new URL(`../../supabase/migrations/${bookingMigration}`,import.meta.url),'utf8');await assert.rejects(m.unsafe(sql.replace('commit;',"do $$ begin raise exception 'H2010 migration injected fault';end $$;commit;")));await m.unsafe('rollback');assert.equal((await m`select count(*)::int n from pg_tables where schemaname='crm_private' and tablename like 'b04_%'`)[0]!.n,0);assert.equal((await m`select has_schema_privilege('crm_h0_f2_executor','crm_api','CREATE') p`)[0]!.p,false);});
test('R47 optional anon/authenticated roles absent migration',async()=>{await h.admin.unsafe('create database h2010_optional owner crm_h0_migration');const m=h.connect('crm_h0_migration','h2010_optional'),a=h.connect('h2_bootstrap','h2010_optional');await h.applyChain(m,a,'20261001172433_h2_exact_acceptance.sql');await h.admin.unsafe('alter role anon rename to h2010_anon;alter role authenticated rename to h2010_authenticated');try{await m.unsafe(await readFile(new URL(`../../supabase/migrations/${bookingMigration}`,import.meta.url),'utf8'));assert.equal((await m`select count(*)::int n from crm_private.b04_bookings`)[0]!.n,0);}finally{await h.admin.unsafe('alter role h2010_anon rename to anon;alter role h2010_authenticated rename to authenticated');}});
test('R48 SM-FORB04 tempting Ganada cannot confirm or reconcile',async()=>{const b=await bookingFixture(h);await negative({...b.q,state:'Confirmada',paymentState:'Conciliado'} as BookingCommand);await apply(b.q);assert.equal((await h.observer`select state from crm_private.b04_bookings where booking_id=${b.q.bookingId}::uuid`)[0]!.state,'Pendiente de preparación');});
test('R49 SM-FORB10 global quantity/gratuity cannot overwrite scope',async()=>{const b=await multimodal(),d=structuredClone(b.detail);(d.services[0]!.contributions[0] as {attendees:number}).attendees=12;await negative({...b.q,detail:d,evidenceId:await b.detailProof(d)});await negative({...b.q,groupCount:12,freeParticipants:1} as BookingCommand);});
test('R50 SM-FORB31 split/merge or second distinct Booking rejected',async()=>{const b=await bookingFixture(h);await apply(b.q);await negative({...b.q,operationId:uid(),bookingId:uid(),reason:'different agreement effect'});await negative({...b.q,split:true} as BookingCommand);await negative({...b.q,mergeOpportunityId:uid()} as BookingCommand);});
async function independentEffects(q:BookingCommand){const old=await baseline();await apply(q);const after=await baseline();for(const t of ['b07_records','b07_facts','b07_links','b03_acceptances','b03_acceptance_verifications','b03_proposals','b03_proposal_versions','b03_offer_operations','b03_leads','b05_operations','b07_tasks'])if(old[t]!==undefined)assert.deepEqual(after[t],old[t]);const forbidden=await h.observer`select tablename from pg_tables where schemaname='crm_private' and (tablename ilike '%payment%' or tablename ilike '%refund%' or tablename ilike '%provider_confirmation%' or tablename ilike '%reconciliation%')`;assert.equal(forbidden.length,0);}
test('R51 no Payment funds reconciliation Refund invoice',async()=>{const b=await bookingFixture(h);await independentEffects(b.q);});
test('R52 no provider availability confirmation execution',async()=>{const b=await bookingFixture(h);await independentEffects(b.q);assert.ok((await h.observer`select state,applied from crm_private.b04_services where booking_id=${b.q.bookingId}::uuid`).every(x=>x.state==='Pendiente'));});
test('R53 no fake Lead Proposal Acceptance Communications Human Approval or external effect',async()=>{const b=await bookingFixture(h);await independentEffects(b.q);});
test('R54 SM-BK01 each material guard withdrawn',async()=>{const b=await bookingFixture(h);for(const key of ['opportunityId','acceptanceId','proposalId','versionId'] as const)await negative({...b.q,[key]:uid()});await negative({...b.q,evidenceId:uid()});await negative({...b.q,expectedRevision:b.q.expectedRevision+1});await negative({...b.q,expectedOpportunityRevision:b.q.expectedOpportunityRevision+1});});
test('R55 SM-BS01 each source detail guard withdrawn',async()=>{for(const key of ['serviceRevisionId','nature','contributions','nights'] as const){const b=await bookingFixture(h),d=structuredClone(b.detail);delete (d.services[0] as unknown as Record<string,unknown>)[key];await negative({...b.q,detail:d,evidenceId:await b.proof(d)});}const b=await bookingFixture(h);for(const key of ['lineId','modalityId','quantity','attendees','certainty'] as const){const d=structuredClone(b.detail);delete (d.services[0]!.contributions[0] as unknown as Record<string,unknown>)[key];await negative({...b.q,detail:d,evidenceId:await b.proof(d)});}});
test('R56 AI creation without exact Human Approval denied G3',async()=>{const b=await bookingFixture(h);await negative({...b.q,origin:'ai'});await negative({...b.q,origin:'ai',humanApproval:true} as BookingCommand);});
test('R57 retained sources after catalog change not reinterpreted',async()=>{const b=await bookingFixture(h);await apply(b.q);const old=(await h.observer`select chain_snapshot from crm_private.b04_bookings where booking_id=${b.q.bookingId}::uuid`)[0]!.chain_snapshot;await h.cat('service',{name:'SYNTHETIC unrelated later configuration',nature:'internal'});assert.deepEqual((await h.observer`select chain_snapshot from crm_private.b04_bookings where booking_id=${b.q.bookingId}::uuid`)[0]!.chain_snapshot,old);});
test('R58 authorized C01 read reauthorizes result',async()=>{const b=await bookingFixture(h);await apply(b.q);assert.ok(await h.booking.read(await h.auth(),read,b.q.bookingId));await h.migration`update crm_private.crm_actors set enabled=false where actor_id=${h.actorId}::uuid`;try{await assert.rejects(h.booking.read(await h.auth(),read,b.q.bookingId));}finally{await h.migration`update crm_private.crm_actors set enabled=true where actor_id=${h.actorId}::uuid`;}});
test('R59 H1/H2 historical migrations unchanged and previous persisted fixtures retained',async()=>{assert.deepEqual(upgraded,prior);for(const file of (await readdir(new URL('../../supabase/migrations',import.meta.url))).filter(x=>x.endsWith('.sql')&&x<bookingMigration)){assert.ok((await readFile(new URL(`../../supabase/migrations/${file}`,import.meta.url),'utf8')).length>0);}assert.ok((await h.observer`select * from crm_private.b03_acceptance_operations`).length>0);});
test('R60 scope limits no future operation economy external module',async()=>{const tables=await h.observer`select tablename from pg_tables where schemaname='crm_private'`;assert.ok(!tables.some(x=>/payment|refund|provider_confirmation/.test(x.tablename)));assert.ok((await h.observer`select state from crm_private.b04_bookings`).every(x=>x.state==='Pendiente de preparación'));});

test('R61 duplicate known Contact identity must not count as two Participants',async()=>{const b=await multimodal(),q=await nominal(b),d=structuredClone(q.detail),contact=(await h.observer`select accepter_id from crm_private.b03_acceptances where acceptance_id=${b.q.acceptanceId}::uuid`)[0]!.accepter_id;for(const p of d.participants.slice(0,2))(p as {contactId:string|null}).contactId=contact;await negative({...q,detail:d,evidenceId:await b.detailProof(d)});});

test('R62 Organization and payer contextual stay distinct from participant and internal actor',async()=>{const b=await bookingFixture(h),org=uid(),other=uid(),base={operationId:uid(),targetId:org,kind:'organization',expectedVersion:0,sourceRef:'SYNTHETIC company',evidenceRef:'SYNTHETIC proof',reason:'SYNTHETIC',verified:true};await h.identities.apply(await h.auth(),write,{...base,action:'create_entity',displayName:'SYNTHETIC COMPANY'});await h.identities.apply(await h.auth(),write,{...base,action:'create_entity',operationId:uid(),targetId:other,kind:'contact',displayName:'SYNTHETIC OTHER'});for(const relatedId of [b.f.accepterId,other])await h.identities.apply(await h.auth(),write,{...base,action:'link_organization_contact',operationId:uid(),targetId:uid(),contextId:org,relatedId,kind:'contact'});await h.identities.apply(await h.auth(),write,{...base,action:'designate',operationId:uid(),targetId:uid(),contextId:b.q.opportunityId,relatedId:org,kind:'payer',expectedVersion:1});await apply(b.q);await h.identities.apply(await h.auth(),write,{...base,action:'designate',operationId:uid(),targetId:uid(),contextId:b.q.opportunityId,relatedId:other,kind:'primary_contact',expectedVersion:2});assert.equal((await h.observer`select count(*)::int n from crm_private.b04_participants where booking_id=${b.q.bookingId}::uuid`)[0]!.n,0);assert.equal((await h.observer`select count(*)::int n from crm_private.crm_actors where auth_subject=${org}::uuid or auth_subject=${other}::uuid`)[0]!.n,0);const a=(await h.observer`select chain_snapshot from crm_private.b04_bookings where booking_id=${b.q.bookingId}::uuid`)[0]!.chain_snapshot;assert.equal(a.acceptance.accepter_id,b.f.accepterId);});
test('R63 actual nights occupancy participant assignment fault rollbacks',async()=>{for(const table of ['b04_nights','b04_night_occupancies','b04_participants','b04_assignments']){const b=await multimodal(),q=await nominal(b),old=await snapshot();await h.admin.unsafe(`create function crm_private.h2010_detail_fault() returns trigger language plpgsql as $$ begin raise exception 'H2010 detail injected fault';end $$;create trigger h2010_detail_fault before insert on crm_private.${table} for each row execute function crm_private.h2010_detail_fault()`);try{await assert.rejects(apply(q));assert.deepEqual(await snapshot(),old);}finally{await h.admin.unsafe(`drop trigger h2010_detail_fault on crm_private.${table};drop function crm_private.h2010_detail_fault()`);}}});
async function directChain(){const b=await bookingFixture(h,'total',false),proposalId=uid(),versionId=uid(),acceptanceId=uid(),at=now(),o=b.q.expectedOpportunityRevision;const common={proposalId,opportunityId:b.q.opportunityId,sourceRef:'SYNTHETIC actual direct agreement',reason:'SYNTHETIC',expectedOpportunityRevision:o+1};const proof=(claim:string)=>b.f.proof(claim,b.q.coverage,at);
 const prepare={...common,action:'prepare' as const,operationId:uid(),expectedRevision:0,expectedOpportunityRevision:o,content:b.f.content},fix={...common,action:'fix' as const,operationId:uid(),expectedRevision:1,versionId};
 const issue={...common,action:'issue' as const,operationId:uid(),expectedRevision:2,versionId,coverage:b.q.coverage,at,issuance:{issuedAt:at,limits:[]},evidenceId:await proof(`offer:issue:${versionId}:${at}:7`)};
 const register={...common,action:'register' as const,operationId:uid(),expectedRevision:3,versionId,acceptanceId,coverage:b.q.coverage,at,accepterId:b.f.accepterId,designationId:b.f.designationId,channel:'phone',terms:b.q.terms,authorityEvidenceId:await proof(`acceptance:authority:${versionId}:${b.f.accepterId}:${b.f.designationId}`),evidenceId:await proof(`acceptance:agree:${versionId}:${acceptanceId}:${b.f.accepterId}:phone`)};
 const reviewEvidence:Record<string,string>={};for(const aspect of ['prices','availability','conditions','capacity'])reviewEvidence[aspect]=await proof(`offer:review:${versionId}:${acceptanceId}:accept:${aspect}`);
 const verify={...common,action:'verify' as const,operationId:uid(),expectedRevision:4,versionId,acceptanceId,coverage:b.q.coverage,at,reviewEvidence,won:true};
 const hash=(await h.observer`select encode(crm_crypto.digest(convert_to(${JSON.stringify(b.detail)}::text::jsonb::text,'UTF8'),'sha256'),'hex') hash`)[0]!.hash,q={...b.q,proposalId,versionId,acceptanceId,expectedRevision:5,expectedOpportunityRevision:o+2,evidenceId:await proof(`booking:detail:${acceptanceId}:${hash}`),route:'direct' as const};
 const stages:import('../../src/infrastructure/postgres/h2-booking-adapter.ts').DirectStage[]=[{kind:'proposal',command:prepare},{kind:'proposal',command:fix},{kind:'offer',command:issue},{kind:'acceptance',command:register},{kind:'acceptance',command:verify}];return {b,q,stages};}
test('R64 direct composes T01 T02 T03 same commit with full late rollback',async()=>{const d=await directChain(),old=await snapshot();await h.admin.unsafe(`create function crm_private.h2010_direct_fault() returns trigger language plpgsql as $$ begin raise exception 'H2010 direct fault';end $$;create constraint trigger h2010_direct_fault after insert on crm_private.b04_history deferrable initially deferred for each row execute function crm_private.h2010_direct_fault()`);try{await assert.rejects(h.booking.direct(await h.auth(),write,d.stages,d.q));assert.deepEqual(await snapshot(),old);}finally{await h.admin.unsafe('drop trigger h2010_direct_fault on crm_private.b04_history;drop function crm_private.h2010_direct_fault()');}await h.booking.direct(await h.auth(),write,d.stages,d.q);assert.equal(await counts(d.q.opportunityId),1);assert.ok((await h.observer`select * from crm_private.b03_acceptances where acceptance_id=${d.q.acceptanceId}::uuid`).length);assert.equal((await h.booking.direct(await h.auth(),write,d.stages,d.q)).id,d.q.bookingId);});
test('R65 distinct conflicting keys two authorized sessions both orders',async()=>{const {H0005PostgresAdapter}=await import('../../src/infrastructure/postgres/h0-005-adapter.ts');const first=await verifyAuth({verify:async()=>({subject:h.subject,passwordVerified:true,mfaVerified:true})},uid()),session=(await new H0005PostgresAdapter(h.runtime,h.f1,h.f2).establish(first)).sessionId,second=await verifyAuth({verify:async()=>({subject:h.subject,sessionId:session,passwordVerified:true,mfaVerified:true})},uid());for(const reverse of [false,true]){const b=await bookingFixture(h),auth=await h.auth(),q={...b.q,operationId:uid(),bookingId:uid(),reason:'conflicting material content'},work=[()=>h.booking.apply(auth,write,b.q),()=>h.booking.apply(second,write,q)];if(reverse)work.reverse();const results=await Promise.allSettled(work.map(f=>f()));assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(await counts(b.q.opportunityId),1);}});
test('R66 actual stale revision plus FK and historical source invariance',async()=>{const b=await bookingFixture(h),q=await rectification(b);await h.acceptance.apply(await h.auth(),write,q);await negative(b.q);const {execFileSync}=await import('node:child_process');for(const file of (await readdir(new URL('../../supabase/migrations/',import.meta.url))).filter(x=>x.endsWith('.sql')&&x<bookingMigration)){const path=`supabase/migrations/${file}`;assert.deepEqual(await readFile(new URL(`../../${path}`,import.meta.url)),execFileSync('git',['show',`fd1c1e1b06bffbef786383e98827ade4b13c919d:${path}`]));}assert.ok((await h.observer`select count(*)::int n from pg_constraint where contype='f' and conrelid='crm_private.b04_bookings'::regclass`)[0]!.n>=8);});
