// R001-R093 from independent expected 14a1aa8; immutable literal normative assertions.
import assert from 'node:assert/strict';import {test} from 'node:test';import {randomUUID as uid,createHash} from 'node:crypto';import {readFile,readdir} from 'node:fs/promises';
import {isolatedOwnEconomics,ownEconomicsMigration,write,read} from '../support/h3-own-economics-isolated.ts';
import {ownEconomicsFixture,fact,promotion,type OwnEconomicsCommand} from '../support/h3-own-economics-fixtures.ts';
import {normativePure} from '../support/h3-own-economics-normative.ts';import {allocationFixture} from '../support/h3-allocation-fixtures.ts';
import {H3013OwnEconomicsAdapter} from '../../src/infrastructure/postgres/h3-own-economics-adapter.ts';
import {verifyAuth} from '../../src/application/verified-auth.ts';import {providerPaymentMigration} from '../support/h3-provider-payment-isolated.ts';
import {providerPaymentFixture} from '../support/h3-provider-payment-fixtures.ts';
type H=Awaited<ReturnType<typeof isolatedOwnEconomics>>;type F=Awaited<ReturnType<typeof ownEconomicsFixture>>;
const tables=['b05_own_economies','b05_own_economic_operations','b05_own_economic_revisions','b05_own_economic_components'];
const protectedTables=['b04_bookings','b04_services','b04_contributions','b05_payment_schedules','b05_expected_payments','b05_customer_payments','b05_payment_revisions','b05_allocation_acts','b05_fund_revisions','b05_provider_invoices','b05_invoice_revisions','b05_suplidos','b05_suplido_revisions','b05_provider_payments','b05_provider_outgoing_movements'];
async function snapshot(h:H,names=tables){const out:Record<string,unknown>={};for(const t of names)out[t]=(await h.observer.unsafe(`select coalesce(jsonb_agg(x order by x::text),'[]'::jsonb) value from (select to_jsonb(t) x from crm_private.${t} t) z`))[0]!.value;return out;}
async function apply(h:H,c:OwnEconomicsCommand,adapter=h.ownEconomics){return adapter.apply(await h.auth(),write,c);}
async function deny(h:H,c:OwnEconomicsCommand){const before=await snapshot(h);await assert.rejects(apply(h,c));assert.deepEqual(await snapshot(h),before);}
async function faults(h:H,table:string,deferred=false,body="raise exception 'SYNTHETIC_OWN_ECONOMIC_FAULT';",when='before'){
 await h.admin.unsafe(`create function crm_private.h3014_fault() returns trigger language plpgsql security definer set search_path=pg_catalog,pg_temp as $$begin ${body} return new;end$$;create ${deferred?'constraint ':''}trigger h3014_fault ${deferred?'after':when} insert on crm_private.${table} ${deferred?'deferrable initially deferred ':''}for each row execute function crm_private.h3014_fault()`);
}
async function clear(h:H,table:string){await h.admin.unsafe(`drop trigger h3014_fault on crm_private.${table};drop function crm_private.h3014_fault()`);}
async function waitLock(h:H){for(let i=0;i<150;i++){if((await h.admin`select count(*)::int n from pg_stat_activity where datname=current_database() and usename='crm_h0_runtime' and wait_event_type='Lock'`)[0]!.n>0)return;await new Promise(r=>setTimeout(r,10));}throw new Error('SYNTHETIC_CONCURRENCY_NOT_OBSERVED');}
async function race(h:H,f:F,a:OwnEconomicsCommand,b:OwnEconomicsCommand){const hold=h.connect('h2_bootstrap');await hold.unsafe('begin');await hold`select pg_advisory_xact_lock(hashtextextended(${'own-economic-scope:'+h.scope+':'+f.bookingId+':'+a.scope},0))`;const other=new H3013OwnEconomicsAdapter(h.connect('crm_h0_runtime'),h.f1,h.f2),jobs=[apply(h,a),apply(h,b,other)];await waitLock(h);await hold.unsafe('commit');return Promise.allSettled(jobs);}
async function approved(h:H,f:F){const c=await f.command();Object.assign(c.input,{promotion:{...promotion(f.b.f.mid),revisionId:f.promo.revision}});return f.attest(c);}
async function updateMasters(h:H,f:F){
 for(const [kind,ref,definition] of [['unit',f.unit,{name:'NEW future unit',definition:'NEW future unit'}],['pricing_form',f.form,{name:'NEW future pricing',definition:'NEW future pricing'}]] as const)await h.catalog.apply(await h.auth(),write,{action:'publish_version',operationId:uid(),targetId:ref.id,kind,expectedVersion:1,sourceRef:'SYNTHETIC future configuration',evidenceRef:'SYNTHETIC explicit',reason:'SYNTHETIC future use only',definition});
 const definition={policy:'novio_gratis',minimum_attendees:'15',required_lodging:'1',required_activity:'1',required_restaurant:'1',required_tarari_drinks:'2',effect_basis:'honoree_modality_final_person_price',label:'NEW future label'};
 await h.commercial.apply(await h.auth(),write,{action:'publish',operationId:uid(),targetId:f.promo.id,kind:'promotion',expectedVersion:1,sourceRef:'SYNTHETIC future promotion',evidenceRef:'SYNTHETIC',reason:'SYNTHETIC future only',definition});
}
test('H3-014 independent R001-R093',async t=>{
 const h=await isolatedOwnEconomics('crm_h3_014',55932);try{
 const common=await ownEconomicsFixture(h);
 for(let n=1;n<=93;n++){if(n===91||n===92)continue;await t.test('R'+String(n).padStart(3,'0'),async()=>{
 if(normativePure(n))return;
 const f=common;
 switch(n){
 case 2:await deny(h,await f.command({scope:''}));break;
 case 4:case 14:{const c=await f.command();Object.assign(c.input.fees[0]!.rule,{approvalEvidenceId:uid()});await deny(h,await f.attest(c));break;}
 case 9:await deny(h,await f.command({reason:''}));break;
 case 20:{const a=await allocationFixture(h,'500.00','500.00','verified','2000.00');const s=await a.assign('300.00','0.00',{bookingId:a.f.b.bookingId,purpose:'managed_client_funds',serviceId:a.f.detail.services[0]!.id,reference:'SYNTHETIC managed client portion'}),fee=await a.assign('200.00','300.00',{bookingId:a.f.b.bookingId,purpose:'fee',serviceId:a.f.detail.services[0]!.id,reference:'SYNTHETIC own Fee portion'});await h.allocations.apply(await h.auth(),write,s);await h.allocations.apply(await h.auth(),write,await a.attest({...fee,expectedRevision:(await a.see()).revision}));const c=await f.command({bookingId:a.f.b.bookingId,scope:'SYNTHETIC AC044'});for(const x of [...c.input.fees,...c.input.costs])Object.assign(x,{serviceId:a.f.detail.services[0]!.id});for(const p of Object.values(c.input.fees[0]!.phases))Object.assign(p,fact('200.00'));for(const p of Object.values(c.input.costs[0]!.phases))Object.assign(p,fact('0.00'));const before=await snapshot(h,['b05_allocation_acts','b05_fund_revisions']);const r=await apply(h,await f.attest(c));assert.equal(r.result.computed.totals.real.fee,'200.00');assert.equal(r.result.computed.totals.real.cost,'0.00');assert.deepEqual(await snapshot(h,['b05_allocation_acts','b05_fund_revisions']),before);break;}
 case 21:{const c=await f.command();Object.assign(c.input.costs[0]!,{providerPaymentId:uid(),providerInvoiceId:uid()});await deny(h,await f.attest(c));break;}
 case 61:case 62:case 63:case 64:case 65:{const c=await f.command();Object.assign(c,{[({61:'inferredVatRate',62:'humanApprovalFiscalOverride',63:'aiAutoApproved',64:'legalInvoice',65:'mandate'} as Record<number,string>)[n]!]:true});await deny(h,c);break;}
 case 66:case 67:{const x=await ownEconomicsFixture(h),c=await approved(h,x);Object.assign(c.input.costs[0]!.phases.real,fact(null));const q=await x.attest(c);await apply(h,q);const old=await x.see();await updateMasters(h,x);assert.deepEqual(await x.see(),old);assert.equal((await apply(h,q)).replayed,true);assert.equal((await x.see())!.computed.totals.real.profit,null);break;}
 case 71:case 75:{const x=await ownEconomicsFixture(h),q=await approved(h,x);await apply(h,q);const before=await snapshot(h);assert.equal((await apply(h,q)).replayed,true);assert.deepEqual(await snapshot(h),before);break;}
 case 72:{const x=await ownEconomicsFixture(h),q=await x.command();await apply(h,q);await deny(h,{...q,reason:'different material'});break;}
 case 73:{const x=await ownEconomicsFixture(h);await apply(h,await x.command());const c=await x.command();Object.assign(c.input.costs[0]!.phases.real,{...fact('25.00'),version:'SYNTHETIC-2'});await apply(h,await x.attest(c));const r=(await x.see())!;assert.equal(r.revision,2);assert.equal(r.history.length,2);assert.equal(r.computed.totals.real.profit,'75.00');break;}
 case 74:{const x=await ownEconomicsFixture(h),q=await x.command();await apply(h,q);await deny(h,await x.command({expectedRevision:0}));break;}
 case 76:{const x=await ownEconomicsFixture(h),q=await x.command();await apply(h,q);const unauth=await verifyAuth({verify:async()=>({subject:uid(),sessionId:uid(),passwordVerified:true,mfaVerified:true})},uid());await assert.rejects(h.ownEconomics.apply(unauth,write,q));await assert.rejects(h.ownEconomics.read(unauth,read,x.economyId,x.bookingId));break;}
 case 77:case 78:case 79:{const x=await ownEconomicsFixture(h);if(n===79)await apply(h,await x.command());const a=await approved(h,x),b=await x.attest({...structuredClone(a),operationId:uid()});if(n===79){Object.assign(b.input.costs[0]!.phases.real,fact('25.00'));}const outcomes=await race(h,x,a,await x.attest(b));assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);assert.equal((await x.see())!.history.length,n===79?2:1);assert.equal((await x.see())!.revision,n===79?2:1);break;}
 case 80:{const x=await ownEconomicsFixture(h),q=await approved(h,x);await updateMasters(h,x);const r=await apply(h,q);assert.equal(r.result.computed.promotion!.amount,'150.00');assert.equal(r.result.computed.fees[0]!.phases.real.calculation!.algorithmVersion,'h1-money-d023-d028-d029-v1');assert.equal(r.result.computed.fees[0]!.component.unitRevisionId,x.unit.revision);break;}
 case 81:case 82:case 83:case 84:case 85:case 86:case 87:{const x=await ownEconomicsFixture(h),q=await approved(h,x),table=n===81?tables[0]!:n===86?tables[2]!:n===87?tables[1]!:tables[3]!;const condition=n===83?"if new.kind='promotion' then raise exception 'SYNTHETIC_PROMOTION_FAULT';end if;":n===84?"if new.kind='fee' then raise exception 'SYNTHETIC_FEE_FAULT';end if;":n===85?"if new.kind='cost' then raise exception 'SYNTHETIC_COST_FAULT';end if;":undefined;const before=await snapshot(h);await faults(h,table,n===87,condition,n===82?'after':'before');try{await assert.rejects(apply(h,q));assert.deepEqual(await snapshot(h),before);}finally{await clear(h,table);}await apply(h,q);assert.equal((await x.see())!.revision,1);break;}
 case 89:{for(const table of tables){for(const op of ['select *','insert into','update','delete from']){const statement=op==='select *'?`select * from crm_private.${table}`:op==='insert into'?`insert into crm_private.${table} default values`:op==='update'?`update crm_private.${table} set admin_scope='OTHER'`:`delete from crm_private.${table}`;await assert.rejects(h.runtime.unsafe(statement));}assert.equal((await h.observer`select relrowsecurity,relforcerowsecurity from pg_class where oid=${'crm_private.'+table}::regclass`)[0]!.relforcerowsecurity,true);}break;}
 case 90:{const files=(await readdir(new URL('../../supabase/migrations',import.meta.url))).filter(x=>x.endsWith('.sql'));assert.equal(files.length,37);for(const table of tables){const r=(await h.admin`select c.relrowsecurity,c.relforcerowsecurity,pg_get_userbyid(c.relowner) owner from pg_class c where c.oid=${'crm_private.'+table}::regclass`)[0]!;assert.equal(r.owner,'crm_h0_f2_owner');assert.equal(r.relrowsecurity,true);assert.equal(r.relforcerowsecurity,true);}assert.equal((await h.admin`select count(*)::int n from pg_policies where schemaname='crm_private' and tablename=any(${tables})`)[0]!.n,8);const funcs=await h.admin`select p.prosecdef,p.proconfig,pg_get_userbyid(p.proowner) owner from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='crm_api' and p.proname like 'own_economics_%'`;assert.equal(funcs.length,3);for(const r of funcs){assert.equal(r.prosecdef,true);assert.equal(r.owner,'crm_h0_f2_executor');assert.deepEqual(r.proconfig,['search_path=pg_catalog, pg_temp']);}break;}
 case 91:case 92:break; // Executed as real separate populated upgrade/rollback tests below; associated IDs retained.
 case 93:{const expected=await readFile(new URL('../../specs/001-core-crm/expected-TSK-H3-013-014.md',import.meta.url),'utf8');assert.equal(expected.match(/^\|R\d{3}\|/gm)!.length,93);const old=(await readdir(new URL('../../supabase/migrations',import.meta.url))).filter(x=>x.endsWith('.sql')&&x<=providerPaymentMigration);assert.equal(old.length,36);const before=await snapshot(h,protectedTables);const x=await ownEconomicsFixture(h);const baseline=await snapshot(h,protectedTables);await apply(h,await approved(h,x));assert.deepEqual(await snapshot(h,protectedTables),baseline);assert.ok(before);break;}
 default:throw new Error('EXPECTED_CASE_NOT_IMPLEMENTED:'+n);
 }
 });}
 }catch(e){console.error((await readFile(h.temporary+'/postgres.log','utf8')).split('\n').filter(l=>/ERROR:|CONTEXT:/.test(l)).join('\n'));throw e;}finally{await h.close();}
});
test('R091 V-MIG populated upgrade from 36 migrations preserves H0-H3-012',async()=>{
 const h=await isolatedOwnEconomics('crm_h3_014_upgrade',55933,true);try{
 const b=await (await import('../support/h3-own-booking-fixtures.ts')).economyBookingFixture(h,'total',true,'internal');await h.booking.apply(await h.auth(),write,b.q);
 const pp=await providerPaymentFixture(h);await h.providerPayments.apply(await h.auth(),write,await pp.open());const allocation=await pp.assign();const approval=await pp.approval(await pp.schedule([await pp.portion(allocation)]));await approval.execute();await h.suplidos.apply(await h.auth(),write,await pp.su.attachInvoice());await h.providerPayments.apply(await h.auth(),write,await pp.movement([await pp.portion(allocation)],'500.00'));assert.equal((await pp.view())!.paid,'500.00');
 const before=await snapshot(h,protectedTables);await h.migration.unsafe(await readFile(new URL('../../supabase/migrations/'+ownEconomicsMigration,import.meta.url),'utf8'));assert.deepEqual(await snapshot(h,protectedTables),before);
 const f=await ownEconomicsFixture(h);await apply(h,await approved(h,f));assert.equal((await f.see())!.computed.promotion!.amount,'150.00');
 }finally{await h.close();}
});
test('R092 V-MIG migration failure rolls back all objects and privilege grants',async()=>{
 const h=await isolatedOwnEconomics('h3014_rb',55934,true);try{
 const sql=await readFile(new URL('../../supabase/migrations/'+ownEconomicsMigration,import.meta.url),'utf8'),before=await snapshot(h,protectedTables);
 await assert.rejects(h.migration.unsafe(sql.replace('commit;',"select 1/0;commit;")));await h.migration.unsafe('rollback');assert.equal((await h.admin`select to_regclass('crm_private.b05_own_economies') r`)[0]!.r,null);assert.equal((await h.admin`select count(*)::int n from pg_proc where proname like 'own_economic%'`)[0]!.n,0);assert.deepEqual(await snapshot(h,protectedTables),before);await h.migration.unsafe(sql);
 }finally{await h.close();}
});
test('H3-014 C01/F1/F2 and economic history cannot be forged or rewritten',async()=>{
 const h=await isolatedOwnEconomics('h3014_auth',55937);try{const f=await ownEconomicsFixture(h);await apply(h,await f.command());
 for(const role of ['anon','authenticated','crm_h0_ha_tx']){const c=h.connect(role);for(const table of tables)await assert.rejects(c.unsafe(`select * from crm_private.${table}`));await assert.rejects(c.unsafe("select crm_api.own_economics_read(''::bytea,''::bytea,''::bytea,''::bytea,''::bytea)"));}
 for(const table of tables){await assert.rejects(h.admin.unsafe(`update crm_private.${table} set admin_scope='SYNTHETIC altered'`),/IMMUTABLE/);await assert.rejects(h.admin.unsafe(`delete from crm_private.${table}`),/IMMUTABLE/);}
 const {createF1Issuer,encodeF1Fields}=await import('../../src/infrastructure/postgres/f1-codec.ts'),{createF2Issuer}=await import('../../src/infrastructure/postgres/f2-codec.ts'),{postgresF1Binding}=await import('../../src/infrastructure/postgres/transaction.ts'),{issueTrustedContext}=await import('../../src/application/trusted-context.ts'),{canonicalCommercial}=await import('../../src/domain/commercial-progress.ts');
 for(const kind of ['F1','F2','scope'])await assert.rejects(h.runtime.begin(async tx=>{const auth=await h.auth(),r=(await tx`select actor_id::text,admin_scope,access_generation::text,epoch_id::text from crm_api.f2_lookup(${auth.subject}::uuid,${auth.sessionId!}::uuid)`)[0]!,binding=await postgresF1Binding(tx),q=encodeF1Fields(['CRM-H3-OWN-READ1',canonicalCommercial({economyId:f.economyId,bookingId:f.bookingId})]),human=createF2Issuer(h.f2)(auth,{actorId:r.actor_id,scope:r.admin_scope,accessGeneration:r.access_generation,sessionId:auth.sessionId!,epochId:r.epoch_id},binding,'evidence_read',q,read),ctx=issueTrustedContext({identityId:'SYNTHETIC internal',identityKind:'technical',purpose:'h1-evidence',scope:kind==='scope'?'OTHER':r.admin_scope,requestId:uid(),serverTime:new Date().toISOString()}),tech=createF1Issuer(h.f1)(ctx,binding,'C01',q,{resource:'evidence',action:'read_evidence'});return tx.unsafe('select crm_api.own_economics_read($1,$2,$3,$4,$5)',[human.payload,kind==='F2'?Buffer.alloc(32):human.mac,tech.payload,kind==='F1'?Buffer.alloc(32):tech.mac,q]);}));
 await h.migration`update crm_private.crm_actors set enabled=false where actor_id=${h.actorId}::uuid`;await assert.rejects(f.see());
 }finally{await h.close();}
});
test('H3-014 other session sees no partial root/components/history before COMMIT',async()=>{
 const h=await isolatedOwnEconomics('h3014_read',55938);try{const f=await ownEconomicsFixture(h),q=await approved(h,f);await faults(h,tables[3]!,false,"perform pg_advisory_xact_lock(hashtextextended('h3014-read-gate',0));");const gate=h.connect('h2_bootstrap');await gate.unsafe('begin');await gate`select pg_advisory_xact_lock(hashtextextended('h3014-read-gate',0))`;const job=apply(h,q);await waitLock(h);for(const table of tables)assert.equal((await h.observer.unsafe(`select count(*)::int n from crm_private.${table}`))[0]!.n,0);await gate.unsafe('commit');await job;await clear(h,tables[3]!);assert.equal((await f.see())!.history.length,1);}finally{await h.close();}
});
