/** Independent normative verifier. R01-R78 frozen in 4909f63 before product. */
import {test,before,after} from 'node:test';import assert from 'node:assert/strict';
import {randomUUID as uid,createHash} from 'node:crypto';import {readFile,readdir} from 'node:fs/promises';import {execFileSync} from 'node:child_process';
import {isolatedPayment,paymentMigration,write,read} from '../support/h3-payment-isolated.ts';
import {paymentFixture} from '../support/h3-payment-fixtures.ts';
import {H3003PaymentAdapter,type PaymentCommand} from '../../src/infrastructure/postgres/h3-payment-adapter.ts';
import {createF1Issuer,encodeF1Fields} from '../../src/infrastructure/postgres/f1-codec.ts';import {createF2Issuer} from '../../src/infrastructure/postgres/f2-codec.ts';
import {issueTrustedContext} from '../../src/application/trusted-context.ts';import {postgresF1Binding} from '../../src/infrastructure/postgres/transaction.ts';
import {canonicalCommercial} from '../../src/domain/commercial-progress.ts';import {H0005PostgresAdapter} from '../../src/infrastructure/postgres/h0-005-adapter.ts';
import {verifyAuth} from '../../src/application/verified-auth.ts';import {obligationFixture} from '../support/h3-obligation-fixtures.ts';
import {paymentSummary} from '../../src/domain/customer-payment.ts';
let h:Awaited<ReturnType<typeof isolatedPayment>>;
type F=Awaited<ReturnType<typeof paymentFixture>>;
const tables=['b05_customer_payments','b05_movement_keys','b05_payment_revisions','b05_payment_receipts','b05_reconciliations','b05_reconciliation_acts','b05_payment_operations','b05_payment_history'];
async function snapshot(target=h){const out:Record<string,unknown>={};for(const t of tables)out[t]=(await target.observer.unsafe(`select coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]') d from crm_private.${t} x`))[0]!.d;return out;}
async function apply(q:PaymentCommand){return h.payments.apply(await h.auth(),write,q);}
async function see(f:F){return (await h.payments.read(await h.auth(),read,f.paymentId))!;}
async function neg(q:PaymentCommand,raw=false,pattern?:RegExp){const old=await snapshot();const promise=raw?rawApply(q):apply(q);if(pattern)await assert.rejects(promise,pattern);else await assert.rejects(promise);assert.deepEqual(await snapshot(),old);}
async function rawApply(input:unknown,scope=h.scope,bad=false,reading=false){const auth=await h.auth();return h.runtime.begin(async tx=>{
 const row=(await tx`select actor_id::text,admin_scope,access_generation::text,epoch_id::text from crm_api.f2_lookup(${auth.subject}::uuid,${auth.sessionId!}::uuid)`)[0]!,binding=await postgresF1Binding(tx),identity={actorId:row.actor_id,scope:row.admin_scope,sessionId:auth.sessionId!,accessGeneration:row.access_generation,epochId:row.epoch_id};
 const q=encodeF1Fields([reading?'CRM-H3-PAYMENT-READ1':'CRM-H3-PAYMENT1',canonicalCommercial(input)]),t=createF1Issuer(h.f1)(issueTrustedContext({identityId:'H3004 independent verifier',identityKind:'technical',purpose:'h1-evidence',scope,requestId:uid(),serverTime:new Date().toISOString()}),binding,reading?'C01':'C03',q,{resource:'evidence',action:reading?'read_evidence':'write_evidence'}),a=createF2Issuer(h.f2)(auth,identity,binding,reading?'evidence_read':'evidence_write',q,reading?read:write);
 return tx.unsafe(`select crm_api.${reading?'payment_read':'payment_apply'}($1,$2,$3,$4,$5) r`,[a.payload,bad?Buffer.alloc(32):a.mac,t.payload,t.mac,q]);
});}
async function secondSession(){const sql=h.connect('crm_h0_runtime'),a=new H0005PostgresAdapter(sql,h.f1,h.f2),first=await verifyAuth({verify:async()=>({subject:h.subject,passwordVerified:true,mfaVerified:true})},uid()),session=(await a.establish(first)).sessionId,auth=await verifyAuth({verify:async()=>({subject:h.subject,sessionId:session,passwordVerified:true,mfaVerified:true})},uid()),adapter=new H3003PaymentAdapter(sql,h.f1,h.f2);return (q:PaymentCommand)=>adapter.apply(auth,write,q);}
async function detected(amount='500.00',known=true){const f=await paymentFixture(h,amount,known);await apply(f.detect);return f;}
async function received(amount='500.00'){const f=await detected(amount);await apply(await f.receive());return f;}
async function reconciled(amount='200.00'){const f=await received(),p=await f.propose(2,amount);await apply(p);const v=await f.verify(p);await apply(v);return {f,p,v};}
async function fault(table:string,q:PaymentCommand,deferred=false){
 await h.admin.unsafe("create function crm_private.h3004_fault() returns trigger language plpgsql as $$begin raise exception 'H3004_INJECTED_FAULT';end$$;");
 await h.admin.unsafe(deferred?`create constraint trigger h3004_fault after insert on crm_private.${table} deferrable initially deferred for each row execute function crm_private.h3004_fault()`:`create trigger h3004_fault before insert on crm_private.${table} for each row execute function crm_private.h3004_fault()`);
 try{await neg(q);}finally{await h.admin.unsafe(`drop trigger h3004_fault on crm_private.${table}`);await h.admin.unsafe('drop function crm_private.h3004_fault()');}
}
async function inventory(target=h){return {
 tables:await target.observer`select c.oid,c.relname,c.relowner,c.relacl::text,c.relrowsecurity,c.relforcerowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('crm_private','crm_api','crm_f1','crm_f2') and c.relkind in ('r','p','v','S') order by c.oid`,
 funcs:await target.observer`select p.oid,p.proowner,p.proacl::text,pg_get_functiondef(p.oid) def from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('crm_private','crm_api','crm_f1','crm_f2') order by p.oid`,
 policies:await target.observer`select oid,polname,polrelid,polroles::text,pg_get_expr(polqual,polrelid) qual,pg_get_expr(polwithcheck,polrelid) ck from pg_policy order by oid`,
 triggers:await target.observer`select oid,pg_get_triggerdef(oid) def from pg_trigger order by oid`,
 roles:await target.observer`select rolname,rolsuper,rolinherit,rolcreaterole,rolcreatedb,rolcanlogin,rolbypassrls from pg_roles order by rolname`};}
async function priorData(target=h){const out:Record<string,unknown>={};for(const {tablename:t} of await target.observer`select tablename from pg_tables where schemaname='crm_private' and not(tablename=any(${tables})) order by tablename`)out[t]=(await target.observer.unsafe(`select coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]') d from crm_private.${t} x`))[0]!.d;return out;}
before(async()=>{h=await isolatedPayment('crm_h3_004',55681);});after(async()=>{await h?.close();});
test('R01 Expected exists independently, no movement created',async()=>{const f=await obligationFixture(h);const old=await snapshot();await h.obligations.apply(await h.auth(),write,f.q);assert.deepEqual(await snapshot(),old);});
test('R02 notice or promise detection is not money',async()=>{const f=await paymentFixture(h,'500.00',false);await apply(await f.attest({...f.detect,sourceRef:'SYNTHETIC WhatsApp he pagado'},f.paymentId,'candidate','communication'));const r=await see(f);assert.equal(r.summary.grossReceived,null);assert.equal(r.receipts.length,0);assert.equal(r.summary.base,'detected');});
test('R03 customer proof alone cannot receive',async()=>{const f=await detected('500.00',false);await neg(await f.attest({...await f.receive(),sourceEvidenceId:undefined},f.paymentId,'reviewed','communication'));});
test('R04 unknown movement data stays unknown without invalidating signal',async()=>{const f=await paymentFixture(h,'500.00',false);await apply(await f.attest({...f.detect,detection:{amount:null,payerRef:null,date:null,method:null,reference:null,bookingId:null,identity:null}}));const r=await see(f);assert.deepEqual(r.current.detection,{amount:null,payerRef:null,date:null,method:null,reference:null,bookingId:null,identity:null});assert.equal(r.summary.grossReceived,null);});
test('R05 detection each missing source/evidence/material rejects without effects',async()=>{const f=await paymentFixture(h);for(const key of ['sourceRef','reason','at','evidenceId','detection']){const q={...f.detect};delete (q as unknown as Record<string,unknown>)[key];await neg(q,true);}for(const key of ['amount','payerRef','date','method','reference','bookingId','identity']){const q={...f.detect,detection:{...f.detect.detection!}};delete (q.detection as unknown as Record<string,unknown>)[key];await neg(key==='evidenceId'?q:await f.attest(q),true);}});
test('R06 repeated identical signal links prior without double money',async()=>{const f=await detected('500.00',false),r=await apply({...f.detect,operationId:uid(),paymentId:uid()});assert.equal(r.id,f.paymentId);assert.equal((await see(f)).current.revision,1);});
test('R07 reliable movement retry other key keeps one root',async()=>{const f=await detected(),r=await apply({...f.detect,operationId:uid(),paymentId:uid()});assert.equal(r.id,f.paymentId);assert.equal((await see(f)).receipts.length,0);});
test('R08 same reliable identity different material conflicts E2',async()=>{const f=await detected();await neg(await f.attest({...f.detect,operationId:uid(),detection:{...f.detect.detection!,amount:'501.00'}}),false,/E2/);});
test('R09 two real transfers same amount date payer reference remain two',async()=>{const a=await received(),b=await paymentFixture(h);const q=await b.attest({...b.detect,detection:{...a.detect.detection!,identity:b.identity}});await apply(q);await apply(await b.receive());assert.notEqual(a.paymentId,b.paymentId);assert.equal((await see(a)).summary.grossReceived,'500.00');assert.equal((await see(b)).summary.grossReceived,'500.00');assert.equal((await h.observer`select sum((fact->>'amount')::numeric)::text total from crm_private.b05_payment_receipts where payment_id=any(${[a.paymentId,b.paymentId]}::uuid[])`)[0]!.total,'1000.00');});
test('R10 no reliable identity retains similar signals for review',async()=>{const a=await detected('500.00',false),b=await paymentFixture(h,'500.00',false);await apply(await b.attest({...b.detect,detection:a.detect.detection}));assert.equal((await see(a)).summary.grossReceived,null);assert.equal((await see(b)).summary.grossReceived,null);await neg(await b.attest({...await b.receive(),identity:undefined}),false);});
test('R11 authorized receipt separate from correspondence',async()=>{const f=await received(),r=await see(f);assert.equal(r.summary.grossReceived,'500.00');assert.equal(r.summary.verifiedCorrespondence,'0.00');assert.equal(r.current.correspondences.length,0);assert.equal(r.summary.base,'detected');assert.equal(r.receipts.length,1);});
test('R12 missing authorized source blocks receipt',async()=>{const f=await detected();await neg({...await f.receive(),sourceEvidenceId:undefined});await neg({...await f.receive(),sourceEvidenceId:f.detect.evidenceId});});
test('R13 he pagado or expected reference is not source authority',async()=>{const f=await detected(),proof=await f.proof(f.paymentId,`payment-source:${f.identity.sourceRef}`,'candidate','communication');await neg({...await f.receive(),sourceEvidenceId:proof});});
test('R14 wrong root source/evidence rejected',async()=>{const f=await detected(),other=await paymentFixture(h);await neg({...await f.receive(),sourceEvidenceId:other.sourceEvidenceId});await neg({...await f.receive(),evidenceId:other.detect.evidenceId});});
test('R15 discrepancy receipt retains detected and gross amounts explicitly',async()=>{const f=await detected();await neg(await f.receive(1,'499.00'));await apply(await f.attest({...await f.receive(1,'499.00'),discrepancy:'SYNTHETIC bank differs; receipt disputed'}));const r=await see(f);assert.equal(r.current.detection.amount,'500.00');assert.equal(r.summary.grossReceived,'499.00');assert.equal(r.summary.suspended,'499.00');assert.equal(r.summary.incidence,true);});
test('R16 repeated receipt other operation does not add money or revision',async()=>{const f=await detected(),q=await f.receive();await apply(q);const r=await apply({...q,operationId:uid()});assert.equal(r.result.revision,2);assert.equal((await see(f)).receipts.length,1);});
test('R17 changed receipt never overwrites original',async()=>{const f=await received();await neg(await f.receive(2,'500.01'),false,/E2/);assert.equal((await see(f)).summary.grossReceived,'500.00');});
test('R18 later contrast links duplicated unidentified signal without second receipt',async()=>{const a=await received(),b=await detected('500.00',false);const source=await b.proof(b.paymentId,`payment-source:${a.identity.sourceRef}`);await apply(await b.attest({...await b.receive(),identity:a.identity,sourceEvidenceId:source}));const r=await see(b);assert.equal(r.current.duplicateOf,a.paymentId);assert.equal(r.receipts.length,0);assert.equal(r.summary.grossReceived,null);assert.equal((await see(a)).summary.grossReceived,'500.00');});
test('R19 proposal before receipt is distinct pending act',async()=>{const f=await detected();await apply(await f.propose(1));const r=await see(f);assert.equal(r.summary.base,'pending_reconciliation');assert.equal(r.summary.grossReceived,null);assert.equal(r.acts.length,1);assert.equal(r.current.correspondences[0]!.status,'proposed');});
test('R20 proposal guards missing candidate/amount/source block only dependent scope',async()=>{const f=await received(),p=await f.propose();for(const key of ['reconciliationId','start','amount','bookingId','scheduleId','slot','sourceRef','evidenceId']){const q={...p};delete (q as unknown as Record<string,unknown>)[key];await neg(key==='evidenceId'?q:await f.attest(q),true);}assert.equal((await see(f)).summary.grossReceived,'500.00');});
test('R21 AI may propose only',async()=>{const f=await received();await apply(await f.attest({...await f.propose(),origin:'ai'}));const r=await see(f);assert.equal(r.current.correspondences[0]!.status,'proposed');assert.equal(r.summary.verifiedCorrespondence,'0.00');});
test('R22 proposal without receipt cannot verify',async()=>{const f=await detected(),p=await f.propose(1);await apply(p);await neg(await f.verify(p,2));});
test('R23 reference match alone not correspondence check',async()=>{const f=await received(),p=await f.propose();await apply(p);await neg({...await f.verify(p),evidenceId:f.detect.evidenceId});await neg(await f.attest(await f.verify(p),f.paymentId,'candidate'));});
test('R24 each material verification guard necessary',async()=>{const f=await received(),p=await f.propose();await apply(p);for(const key of ['reason','sourceRef','at','evidenceId','sourceEvidenceId','reconciliationId']){const q={...await f.verify(p)};delete (q as unknown as Record<string,unknown>)[key];await neg(key==='evidenceId'?q:await f.attest(q),true);}});
test('R25 AI cannot verify or rectify',async()=>{const {f,p}=await reconciled();const i=await f.discrepancy(4,'0.00','100.00',p.reconciliationId);await apply(i);await neg(await f.attest({...await f.rectify(p,i),origin:'ai'}));const v=await f.verify(p,5);await neg(await f.attest({...v,origin:'ai'}));});
test('R26 normative 500 received 200 identified 300 unresolved',async()=>{const {f}=await reconciled(),r=await see(f);assert.equal(r.summary.grossReceived,'500.00');assert.equal(r.summary.verifiedCorrespondence,'200.00');assert.equal(r.summary.unreconciled,'300.00');assert.equal(r.summary.base,'pending_reconciliation');assert.equal(r.acts.length,2);assert.equal(r.current.correspondences.length,1);assert.deepEqual(paymentSummary(r.current),r.summary);});
test('R27 complete correspondence500 does not confirm Booking',async()=>{const {f}=await reconciled('500.00'),r=await see(f);assert.equal(r.summary.base,'reconciled');assert.equal(r.summary.unreconciled,'0.00');assert.equal((await h.booking.read(await h.auth(),read,f.f.b.bookingId) as {booking:{state:string}}).booking.state,'Pendiente de preparación');});
test('R28 known context cannot transfer correspondence to another Booking',async()=>{const f=await received(),other=await paymentFixture(h);await neg(await f.attest({...await f.propose(),bookingId:other.f.b.bookingId,scheduleId:other.f.q.scheduleId}));});
test('R29 wrong obligation or slot cannot fabricate destination',async()=>{const f=await received(),p=await f.propose();for(const q of [{...p,scheduleId:uid()},{...p,slot:'invented'},{...p,bookingId:uid()}])await neg(await f.attest(q as PaymentCommand),true);});
test('R30 overlapping correspondence cannot count same portion twice',async()=>{const {f}=await reconciled(),p=await f.propose(4,'200.00','100.00');await apply(p);await neg(await f.verify(p,5));});
test('R31 excessive/negative portion rejected preserving receipt',async()=>{const f=await received();for(const q of [{...await f.propose(),amount:'500.01'},{...await f.propose(),start:'-0.01'},{...await f.propose(),amount:'0.00'}])await neg(await f.attest(q),true);});
test('R32 incident suspends only100 of verified200',async()=>{const {f,p}=await reconciled();await apply(await f.discrepancy(4,'0.00','100.00',p.reconciliationId));const r=await see(f);assert.equal(r.summary.grossReceived,'500.00');assert.equal(r.current.correspondences[0]!.amount,'200.00');assert.equal(r.summary.verifiedCorrespondence,'100.00');assert.equal(r.summary.suspended,'100.00');assert.equal(r.summary.unreconciled,'400.00');assert.equal(r.acts.length,3);});
test('R33 incident on unresolved300 leaves200 verified',async()=>{const {f}=await reconciled();await apply(await f.discrepancy(4,'200.00','300.00'));const r=await see(f);assert.equal(r.summary.verifiedCorrespondence,'200.00');assert.equal(r.summary.suspended,'300.00');});
test('R34 discrepancy preserves prior proposal and checked correspondence',async()=>{const {f,p}=await reconciled(),before=await see(f);await apply(await f.discrepancy(4,'0.00','100.00',p.reconciliationId));const r=await see(f);assert.deepEqual(r.acts.slice(0,2),before.acts);assert.deepEqual(r.receipts,before.receipts);assert.deepEqual(r.current.correspondences,before.current.correspondences);});
test('R35 discrepancy each material guard without side effect',async()=>{const {f,p}=await reconciled();const i=await f.discrepancy(4,'0.00','100.00',p.reconciliationId);for(const key of ['incidentId','amount','start','reason','sourceRef','evidenceId']){const q={...i};delete (q as unknown as Record<string,unknown>)[key];await neg(key==='evidenceId'?q:await f.attest(q),true);}await neg(await f.attest({...i,amount:'201.00'}));});
test('R36 human linked rectification preserves original and checked result',async()=>{const {f,p}=await reconciled(),before=await see(f),i=await f.discrepancy(4,'0.00','100.00',p.reconciliationId);await apply(i);await apply(await f.rectify(p,i));const r=await see(f);assert.equal(r.summary.verifiedCorrespondence,'200.00');assert.equal(r.current.incidents[0]!.resolved,true);assert.equal(r.acts.length,4);assert.deepEqual(r.acts.slice(0,2),before.acts);assert.deepEqual(r.receipts,before.receipts);});
test('R37 rectification all authority cause evidence context guards required',async()=>{const {f,p}=await reconciled(),i=await f.discrepancy(4,'0.00','100.00',p.reconciliationId);await apply(i);const r=await f.rectify(p,i);for(const key of ['reason','sourceRef','sourceEvidenceId','evidenceId','incidentId','reconciliationId','bookingId','scheduleId','slot']){const q={...r};delete (q as unknown as Record<string,unknown>)[key];await neg(key==='evidenceId'?q:await f.attest(q),true);}});
test('R38 later error preserves bank receipt and reconciliation history',async()=>{const {f,p}=await reconciled('500.00'),old=await see(f),i=await f.discrepancy(4,'0.00','100.00',p.reconciliationId);await apply(i);const r=await see(f);assert.equal(r.summary.base,'reconciled');assert.equal(r.summary.incidence,true);assert.equal(r.summary.grossReceived,'500.00');assert.deepEqual(r.receipts,old.receipts);assert.equal(r.summary.verifiedCorrespondence,'400.00');});
test('R39 Refund remains explicit unavailable boundary',async()=>{const f=await received();for(const action of ['refund','return','reverse_bank'])await neg({...await f.receive(2),action} as PaymentCommand,true);assert.equal((await h.observer`select count(*)::int n from pg_tables where schemaname='crm_private' and tablename ilike '%refund%'`)[0]!.n,0);});
test('R40 common evidence can link Acceptance and payment with separate verification',async()=>{const f=await paymentFixture(h),original=(await h.observer`select evidence_id::text id from crm_private.b03_acceptances where acceptance_id=${f.f.b.acceptanceId}::uuid`)[0]!.id;
 await h.evidence.apply(await h.auth(),write,{action:'link',operationId:uid(),targetId:uid(),originalId:original,contextKind:'other',contextId:f.paymentId,coverage:f.paymentId,sourceRef:'SYNTHETIC same advance evidence',purpose:'SYNTHETIC separate payment review',reason:'SYNTHETIC shared underlying proof, not bank receipt'});
 const q=await f.attest({...f.detect,presentedEvidenceId:original} as PaymentCommand);await apply(q);const r=await see(f);assert.equal((r.current as unknown as {presentedEvidenceId:string}).presentedEvidenceId,original);assert.equal(r.summary.grossReceived,null);assert.equal(r.receipts.length,0);await apply(await f.receive());assert.equal((await see(f)).summary.grossReceived,'500.00');
});
test('R41 H2 states remain independent',async()=>{const f=await received();const r=await h.booking.read(await h.auth(),read,f.f.b.bookingId) as {booking:{state:string}};assert.equal(r.booking.state,'Pendiente de preparación');const services=await h.observer`select state from crm_private.b04_services where booking_id=${f.f.b.bookingId}::uuid`;assert.ok(services.every(x=>x.state==='Pendiente'));});
test('R42 forbidden paid/covered/allocation/Refund inference attempted and denied',async()=>{const f=await received();for(const key of ['paid','covered','allocated','consumed','refund','mandate','providerConfirmed'])await neg({...await f.receive(2),[key]:true},true);});
test('R43 verified correspondence still no integrated obligation coverage',async()=>{const {f}=await reconciled();const r=await h.obligations.evaluate(await h.auth(),read,f.f.b.bookingId,f.f.q.scheduleId!,f.f.q.at);assert.ok(r!.every(x=>x.verifiedAmount==='0.00'&&x.state==='pending'));assert.equal((await see(f)).summary.unreconciled,'300.00');});
test('R44 odd cents exactly0.03 received0.01 reconciled0.02 pending',async()=>{const f=await received('0.03'),p=await f.propose(2,'0.01');await apply(p);await apply(await f.verify(p));const r=await see(f);assert.equal(r.summary.grossReceived,'0.03');assert.equal(r.summary.verifiedCorrespondence,'0.01');assert.equal(r.summary.unreconciled,'0.02');});
test('R45 direct signed definitive number/nondecimal authority rejected',async()=>{const f=await detected();for(const amount of [500,0.1,'NaN','500.001','-1.00','1e2'])await neg(await f.attest({...await f.receive(),amount} as PaymentCommand),true);});
test('R46 equivalent same identity key-order replay no new history',async()=>{const f=await detected(),old=await snapshot(),q=Object.fromEntries(Object.entries(f.detect).reverse()) as unknown as PaymentCommand;assert.equal((await apply(q)).replayed,true);assert.deepEqual(await snapshot(),old);});
test('R47 same operation different material E2',async()=>{const f=await detected();await neg({...f.detect,reason:'SYNTHETIC changed'},false,/E2/);});
test('R48 lost committed response replays without duplicate receipt',async()=>{const f=await detected(),q=await f.receive();await rawApply(q);const old=await snapshot();assert.equal((await apply(q)).replayed,true);assert.deepEqual(await snapshot(),old);});
test('R49 replay actor/scope unauthorized denied',async()=>{const f=await detected();await assert.rejects(rawApply(f.detect,uid()));const old=await snapshot();const auth=await verifyAuth({verify:async()=>({subject:uid(),sessionId:h.sessionId,passwordVerified:true,mfaVerified:true})},uid());await assert.rejects(h.payments.apply(auth,write,f.detect));assert.deepEqual(await snapshot(),old);});
test('R50 absent forged disabled and MFA-less contexts fail closed',async()=>{const f=await detected();await assert.rejects(h.runtime`select crm_api.payment_apply(null,null,null,null,null)`);await assert.rejects(rawApply(f.detect,h.scope,true));await assert.rejects(h.payments.read({subject:'forged'} as never,read,f.paymentId));const auth=await verifyAuth({verify:async()=>({subject:h.subject,sessionId:uid(),passwordVerified:true,mfaVerified:false})},uid());await assert.rejects(h.payments.apply(auth,write,f.detect));await h.migration`update crm_private.crm_actors set enabled=false where actor_id=${h.actorId}::uuid`;try{await assert.rejects(apply(f.detect));await assert.rejects(see(f));}finally{await h.migration`update crm_private.crm_actors set enabled=true where actor_id=${h.actorId}::uuid`;}});
test('R51 narrow authorized projection only exact root',async()=>{const a=await received(),b=await received(),r=await see(a);assert.ok(!JSON.stringify(r).includes(b.paymentId));assert.ok(!JSON.stringify(r).includes(b.f.b.bookingId));for(const key of ['costs','margin','fees','bankAccount','profit'])assert.ok(!(key in r));assert.equal(await h.payments.read(await h.auth(),read,uid()),null);});
test('R52 third parties no economic read or reference search enumeration',async()=>{const f=await received();for(const role of ['anon','authenticated']){const sql=h.connect(role);await assert.rejects(sql`select crm_api.payment_read(null,null,null,null,null)`);}await assert.rejects(rawApply({paymentId:f.paymentId,reference:f.detect.detection!.reference},h.scope,false,true));await assert.rejects(rawApply({amount:'500.00'},h.scope,false,true));await assert.rejects(h.payments.read({subject:'client'} as never,read,f.paymentId));});
test('R53 direct DML and historical alteration unavailable ordinary roles',async()=>{const old=await snapshot();for(const t of tables){for(const role of ['crm_h0_runtime','anon','authenticated']){const sql=h.connect(role);for(const query of [`select * from crm_private.${t}`,`delete from crm_private.${t}`,`update crm_private.${t} set admin_scope='forged'`,`insert into crm_private.${t} default values`,`truncate crm_private.${t}`])await assert.rejects(sql.unsafe(query));}await assert.rejects(h.admin.begin(async tx=>{await tx.unsafe('set local role crm_h0_f2_executor');await tx.unsafe(`delete from crm_private.${t}`);}));await assert.rejects(h.admin.unsafe(`update crm_private.${t} set admin_scope=admin_scope`));}assert.deepEqual(await snapshot(),old);});
test('R54 owner ACL RLS FORCE RLS search_path narrowly controlled',async()=>{for(const t of tables){const r=(await h.observer`select c.relrowsecurity,c.relforcerowsecurity,c.relowner::regrole::text owner from pg_class c where c.oid=${'crm_private.'+t}::regclass`)[0]!;assert.equal(r.owner,'crm_h0_f2_owner');assert.ok(r.relrowsecurity&&r.relforcerowsecurity);assert.equal((await h.observer`select count(*)::int n from pg_policy where polrelid=${'crm_private.'+t}::regclass`)[0]!.n,2);}const roles=await h.observer`select rolname,rolsuper,rolbypassrls,rolcanlogin from pg_roles where rolname in ('crm_h0_f2_executor','crm_h0_f2_owner','crm_h0_runtime')`;assert.ok(roles.every(x=>!x.rolsuper&&!x.rolbypassrls));assert.ok(roles.filter(x=>x.rolname!=='crm_h0_runtime').every(x=>!x.rolcanlogin));const fns=await h.observer`select p.prosecdef,p.proconfig::text,p.proowner::regrole::text owner,has_function_privilege('anon',p.oid,'execute') anonymous from pg_proc p where p.proname in ('payment_apply','payment_read')`;assert.equal(fns.length,2);assert.ok(fns.every(x=>x.prosecdef&&x.owner==='crm_h0_f2_executor'&&!x.anonymous&&x.proconfig.includes('pg_catalog, pg_temp')));});
async function concurrent(q1:PaymentCommand,q2:PaymentCommand){
 const other=await secondSession(),stats=h.connect('h2_bootstrap');let release!:()=>void,held!:()=>void;
 const lockReady=new Promise<void>(r=>held=r),unlock=new Promise<void>(r=>release=r);
 const blocker=h.admin.begin(async tx=>{await tx`select pg_advisory_xact_lock(hashtextextended(${'payment-root:'+q1.paymentId},0))`;held();await unlock;});
 await lockReady;const p1=apply(q1),p2=other(q2);const results=Promise.allSettled([p1,p2]);
 try{let waiting=false;for(let i=0;i<250;i++){const r=(await stats`select count(*)::int n from pg_stat_activity where wait_event_type='Lock' and query like '%crm_api.payment_apply%'`)[0]!;if(r.n>=2){waiting=true;break;}await new Promise(r=>setTimeout(r,10));}assert.ok(waiting,'two independent sessions actually overlap on movement/key locks');}
 finally{release();await blocker;}return results;
}
test('R55 same movement simultaneous different keys one root both orders',async()=>{for(const reverse of [false,true]){const f=await paymentFixture(h),alias={...f.detect,operationId:uid()},r=await concurrent(reverse?alias:f.detect,reverse?f.detect:alias);assert.ok(r.every(x=>x.status==='fulfilled'));assert.equal((await see(f)).current.revision,1);assert.equal((await h.observer`select count(*)::int n from crm_private.b05_customer_payments where payment_id=${f.paymentId}::uuid`)[0]!.n,1);}});
test('R56 simultaneous same operation exactly one durable result',async()=>{const f=await paymentFixture(h),r=await concurrent(f.detect,f.detect);assert.ok(r.every(x=>x.status==='fulfilled'));assert.equal(r.filter(x=>x.status==='fulfilled'&&x.value.replayed).length,1);assert.equal((await see(f)).history.length,1);});
test('R57 simultaneous similar real transfers stay separate',async()=>{const a=await paymentFixture(h),b=await paymentFixture(h),q=await b.attest({...b.detect,detection:{...a.detect.detection!,identity:b.identity}}),other=await secondSession(),r=await Promise.all([apply(a.detect),other(q)]);assert.notEqual(r[0]!.id,r[1]!.id);await Promise.all([apply(await a.receive()),other(await b.receive())]);assert.equal((await see(a)).summary.grossReceived,'500.00');assert.equal((await see(b)).summary.grossReceived,'500.00');});
test('R58 proposal concurrent same revision one conflict both orders',async()=>{for(const reverse of [false,true]){const f=await received(),a=await f.propose(),b=await f.propose(),r=await concurrent(reverse?b:a,reverse?a:b);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal((await see(f)).acts.length,1);assert.equal((await see(f)).current.revision,3);}});
test('R59 same proposal concurrent validation one fact and conflict/replay',async()=>{const f=await received(),p=await f.propose();await apply(p);const a=await f.verify(p),b={...a,operationId:uid()},r=await concurrent(a,b);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal((await see(f)).acts.length,2);assert.equal((await see(f)).receipts.length,1);const f2=await received(),p2=await f2.propose();await apply(p2);const v=await f2.verify(p2),r2=await concurrent(v,v);assert.ok(r2.every(x=>x.status==='fulfilled'));assert.equal(r2.filter(x=>x.status==='fulfilled'&&x.value.replayed).length,1);});
test('R60 obsolete root revision detected without overwrite',async()=>{const f=await received();await neg(await f.propose(1),false,/E2/);});
test('R61 rectification concurrent same revision one result both orders',async()=>{for(const reverse of [false,true]){const {f,p}=await reconciled(),i=await f.discrepancy(4,'0.00','100.00',p.reconciliationId);await apply(i);const a=await f.rectify(p,i),b=await f.rectify(p,i,5,'199.00'),r=await concurrent(reverse?b:a,reverse?a:b);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);const s=await see(f);assert.equal(s.acts.length,4);assert.equal(s.current.revision,6);assert.equal(s.receipts.length,1);}});
test('R62 read another session during receipt written before COMMIT sees prior snapshot',async()=>{
 const f=await detected(),q=await f.receive(),stats=h.connect('h2_bootstrap'),lock=h.connect('h2_bootstrap');let release!:()=>void,held!:()=>void;const ready=new Promise<void>(r=>held=r),unlock=new Promise<void>(r=>release=r);
 await h.admin.unsafe("create function crm_private.h3004_wait() returns trigger language plpgsql as $$begin perform pg_advisory_xact_lock(hashtextextended('H3004_VISIBILITY',0));return new;end$$;create trigger h3004_wait before insert on crm_private.b05_payment_history for each row execute function crm_private.h3004_wait();");
 const blocker=lock.begin(async tx=>{await tx`select pg_advisory_xact_lock(hashtextextended('H3004_VISIBILITY',0))`;held();await unlock;});await ready;
 const other=await secondSession(),work=other(q);let readResult:ReturnType<typeof h.payments.read>|undefined;
 try{let waiting=false;for(let i=0;i<250;i++){const r=(await stats`select count(*)::int n from pg_stat_activity where wait_event_type='Lock' and query like '%crm_api.payment_apply%'`)[0]!;if(r.n>0){waiting=true;break;}await new Promise(r=>setTimeout(r,10));}assert.ok(waiting);
 // Existing F2 actor locking can block C01 until COMMIT. Observe the earlier
 // committed ledger through an independent authorized inspection connection.
 const auth=await h.auth();readResult=h.payments.read(auth,read,f.paymentId);
 const old=(await h.observer`select snapshot from crm_private.b05_payment_revisions where payment_id=${f.paymentId}::uuid order by revision desc limit 1`)[0]!.snapshot;
 assert.equal(old.receipt,null);assert.equal((await h.observer`select count(*)::int n from crm_private.b05_payment_receipts where payment_id=${f.paymentId}::uuid`)[0]!.n,0);
 assert.equal((await h.observer`select count(*)::int n from crm_private.b05_payment_history where payment_id=${f.paymentId}::uuid`)[0]!.n,1);
 }finally{release();await blocker;try{await work;if(readResult){const r=await readResult;assert.equal(r!.summary.grossReceived,'500.00');assert.equal(r!.receipts.length,1);}}finally{await h.admin.unsafe('drop trigger h3004_wait on crm_private.b05_payment_history;drop function crm_private.h3004_wait()');}}

 const s=await see(f);assert.equal(s.summary.grossReceived,'500.00');assert.equal(s.receipts.length,1);assert.equal(s.history.length,2);
});
test('R63 fail before first movement write rolls all back',async()=>{const f=await paymentFixture(h);await fault('b05_customer_payments',f.detect);await apply(f.detect);});
test('R64 fail after movement before history no incomplete root',async()=>{for(const t of ['b05_movement_keys','b05_payment_revisions','b05_payment_operations','b05_payment_history']){const f=await paymentFixture(h);await fault(t,f.detect);await apply(f.detect);}});
test('R65 receipt writes fail atomically at every insert',async()=>{for(const t of ['b05_payment_receipts','b05_payment_revisions','b05_payment_operations','b05_payment_history']){const f=await detected();await fault(t,await f.receive());}});
test('R66 proposal rollback all dependent writes',async()=>{for(const t of ['b05_reconciliations','b05_reconciliation_acts','b05_payment_revisions','b05_payment_operations','b05_payment_history']){const f=await received();await fault(t,await f.propose());}});
test('R67 validation rollback act revision history result together',async()=>{for(const t of ['b05_reconciliation_acts','b05_payment_revisions','b05_payment_operations','b05_payment_history']){const f=await received(),p=await f.propose();await apply(p);await fault(t,await f.verify(p));}});
test('R68 rectification rollback retains original and pending review',async()=>{for(const t of ['b05_reconciliation_acts','b05_payment_revisions','b05_payment_operations','b05_payment_history']){const {f,p}=await reconciled(),i=await f.discrepancy(4,'0.00','100.00',p.reconciliationId);await apply(i);await fault(t,await f.rectify(p,i));assert.equal((await see(f)).current.incidents[0]!.resolved,false);}});
test('R69 deferred COMMIT fault no durable result',async()=>{const f=await detected(),q=await f.receive();await fault('b05_payment_operations',q,true);await apply(q);assert.equal((await see(f)).receipts.length,1);});
test('R70 fresh install least objects triggers ACL roles',async()=>{assert.equal((await h.observer`select count(*)::int n from pg_tables where schemaname='crm_private' and tablename=any(${tables})`)[0]!.n,8);assert.equal((await h.observer`select count(*)::int n from pg_trigger where tgrelid=any(select oid from pg_class where relname=any(${tables})) and not tgisinternal`)[0]!.n,8);for(const r of ['crm_h0_f2_owner','crm_h0_f2_executor'])assert.equal((await h.observer`select has_schema_privilege(${r},'crm_api','create') p`)[0]!.p,false);});
test('R71 upgrade from populated H3-002 preserves all old data objects and privileges',async()=>{const u=await isolatedPayment('crm_h3_004_upgrade',55682,true);try{const f=await obligationFixture(u);await u.obligations.apply(await u.auth(),write,f.q);const old=await priorData(u),i=await inventory(u);await u.migration.unsafe(await readFile(new URL(`../../supabase/migrations/${paymentMigration}`,import.meta.url),'utf8'));assert.deepEqual(await priorData(u),old);const a=await inventory(u);for(const k of ['tables','funcs','policies','triggers'] as const){const ids=new Set(i[k].map(x=>x.oid));assert.deepEqual(Array.from(a[k].filter(x=>ids.has(x.oid))),Array.from(i[k]));}assert.deepEqual(a.roles,i.roles);}finally{await u.close();}});
test('R72 failed migration rollback restores preceding schema grants and roles',async()=>{const u=await isolatedPayment('crm_h3_004_rollback',55683,true);try{const i=await inventory(u),sql=await readFile(new URL(`../../supabase/migrations/${paymentMigration}`,import.meta.url),'utf8');await assert.rejects(u.migration.unsafe(sql.replace(/commit;\s*$/,'select 1/0;commit;')));await u.migration.unsafe('rollback');assert.deepEqual(await inventory(u),i);}finally{await u.close();}});
test('R73 optional roles absent installs with no implicit PUBLIC grant',async()=>{const u=await isolatedPayment('crm_h3_004_no_roles',55684,true);try{await u.admin.unsafe('drop owned by anon;drop owned by authenticated;drop role anon;drop role authenticated');await u.migration.unsafe(await readFile(new URL(`../../supabase/migrations/${paymentMigration}`,import.meta.url),'utf8'));assert.equal((await u.observer`select count(*)::int n from pg_tables where schemaname='crm_private' and tablename=any(${tables})`)[0]!.n,8);}finally{await u.close();}});
test('R74 exact prior migrations health-check and expected preserved; future absent',async()=>{const base='a127da1b736844237d04d691f265b2cee214531e',files=(await readdir(new URL('../../supabase/migrations',import.meta.url))).filter(x=>x.endsWith('.sql')&&x<paymentMigration);assert.equal(files.length,31);for(const f of files){const path='supabase/migrations/'+f;assert.equal(await readFile(path,'utf8'),execFileSync('git',['show',`${base}:${path}`],{encoding:'utf8'}));}const paths=execFileSync('git',['ls-tree','-r','--name-only',base],{encoding:'utf8'}).split('\n').filter(p=>/health|KEEPALIVE/.test(p));for(const p of paths)assert.deepEqual(await readFile(p),execFileSync('git',['show',`${base}:${p}`]));const names=(await h.observer`select tablename from pg_tables where schemaname='crm_private'`).map(x=>x.tablename);assert.ok(!names.some(t=>/allocation|refund|provider_confirmation|invoice/.test(t)));const expected=await readFile('specs/001-core-crm/expected-TSK-H3-003-004.md');assert.deepEqual(expected,execFileSync('git',['show','4909f63:specs/001-core-crm/expected-TSK-H3-003-004.md']));assert.ok(createHash('sha256').update(expected).digest('hex'));});
test('R75 payload authorized boolean cannot certify source contrast',async()=>{const f=await detected();await neg({...await f.receive(),authorizedSource:true} as PaymentCommand,true);const candidate=await f.proof(f.paymentId,`payment-source:${f.identity.sourceRef}`,'candidate','external');await neg({...await f.receive(),sourceEvidenceId:candidate});});
test('R76 overlapping doubts suspend union not sum twice',async()=>{const {f}=await reconciled();await apply(await f.discrepancy(4,'0.00','100.00'));await apply(await f.discrepancy(5,'50.00','100.00'));const r=await see(f);assert.equal(r.summary.suspended,'150.00');assert.equal(r.summary.verifiedCorrespondence,'50.00');assert.deepEqual(paymentSummary(r.current),r.summary);});
test('R77 human resolution only affected receipt portion, no bank reversal',async()=>{const {f}=await reconciled();const i=await f.discrepancy(4,'0.00','100.00');await apply(i);const q=await f.attest({action:'resolve',operationId:uid(),paymentId:f.paymentId,expectedRevision:5,sourceRef:'SYNTHETIC new source verification',reason:'SYNTHETIC doubts resolved',at:f.at,evidenceId:uid(),incidentId:i.incidentId,sourceEvidenceId:f.sourceEvidenceId});await neg({...q,sourceEvidenceId:undefined});await apply(q);const r=await see(f);assert.equal(r.summary.grossReceived,'500.00');assert.equal(r.summary.verifiedCorrespondence,'200.00');assert.equal(r.current.incidents[0]!.resolved,true);});
test('R78 retained movement acts survive changed catalog/policy versions',async()=>{const {f}=await reconciled(),old=await see(f);const q=await f.f.attest({...f.f.publish,operationId:uid(),expectedRevision:1,policyVersion:2,reason:'SYNTHETIC revised current policy'});await h.obligations.apply(await h.auth(),write,q);assert.deepEqual(await see(f),old);});
