/** Minimal preserved historical reproducers. Expected errors are regression assertions, not open FAIL. */
import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {randomUUID as uid} from 'node:crypto';
import {isolatedAllocation,allocationMigration,write} from '../support/h3-allocation-isolated.ts';import {allocationFixture} from '../support/h3-allocation-fixtures.ts';
let h:Awaited<ReturnType<typeof isolatedAllocation>>;before(async()=>{h=await isolatedAllocation('crm_h3_006_defects',55691);});after(async()=>{await h?.close();});
test('H3-006-F01 historical reserved full fails42601; current migration installs',async()=>{const u=await isolatedAllocation('crm_h3_006_f01',55692,true);try{await assert.rejects(u.migration.unsafe(await readFile('tests/fixtures/h3-006/first-product.sql.txt','utf8')),{code:'42601'});await u.migration.unsafe('rollback');assert.equal((await u.observer`select count(*)::int n from pg_tables where tablename='b05_allocations'`)[0]!.n,0);await u.migration.unsafe(await readFile(`supabase/migrations/${allocationMigration}`,'utf8'));}finally{await u.close();}});
test('H3-006-F02 historical ambiguous revision42702; qualified current reproduces coverage',async()=>{const f=await allocationFixture(h,'100.00','100.00');await h.allocations.apply(await h.auth(),write,await f.assign());const old=(await h.observer`select pg_get_functiondef('crm_private.fund_coverage(uuid,text)'::regprocedure) def`)[0]!.def as string;const historical=await readFile('tests/fixtures/h3-006/second-product.sql.txt','utf8');const start=historical.indexOf('create function crm_private.fund_coverage('),end=historical.indexOf('create function crm_private.fund_summary(',start);await h.migration.unsafe(historical.slice(start,end).replace('create function','create or replace function'));try{await assert.rejects(h.observer`select crm_private.fund_coverage(${f.f.q.scheduleId!}::uuid,${h.scope})`,{code:'42702'});}finally{await h.migration.unsafe(old);}assert.equal((await f.see()).coverage[0]!.verifiedAmount,'100.00');});
test('H3-006-F03 separate plan/verification identities and rejection independent of text',async()=>{const f=await allocationFixture(h,'100.00','100.00'),q=await f.assign(),p=await f.attest({...q,action:'plan'});await h.allocations.apply(await h.auth(),write,p);const r=await f.see(),v=await f.attest({...q,action:'verify',expectedRevision:r.revision});await assert.rejects(h.allocations.apply(await h.auth(),write,v),/E2/);await h.allocations.apply(await h.auth(),write,await f.attest({...v,operationId:uid()}));const g=await allocationFixture(h,'100.00','100.00'),bad=await g.attest({...await g.assign(),cause:'modification'});await assert.rejects(h.allocations.apply(await h.auth(),write,bad));assert.equal((await g.see()).summary.assigned,'0.00');});
test('H3-006-F04 historical NULL basis accepted; current mandatory typed fields reject',async()=>{const current=(await h.observer`select pg_get_functiondef(p.oid) def from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='crm_api' and p.proname='allocation_apply'`)[0]!.def as string;const historical=await readFile('tests/fixtures/h3-006/third-product.sql.txt','utf8'),start=historical.indexOf('create function crm_api.allocation_apply('),end=historical.indexOf('end$$;',start)+7;
 const nullBasis=async(f:Awaited<ReturnType<typeof allocationFixture>>)=>{const q=await f.assign('80.00'),b={kind:null,amount:'80.00',originalRef:f.f.q.scheduleId!,sourceRef:'SYNTHETIC prior right',version:'1'},hash=(await h.observer`select encode(crm_crypto.digest(convert_to(${JSON.stringify(b)}::text::jsonb::text,'UTF8'),'sha256'),'hex') hash`)[0]!.hash;return f.attest({...q,cause:'modification',economicBasis:{...b,evidenceId:await f.proof(f.paymentId,`fund-right:${hash}`)}} as never);};
 const f=await allocationFixture(h,'100.00','100.00'),q=await nullBasis(f);await h.migration.unsafe(historical.slice(start,end).replace('create function','create or replace function'));try{await h.allocations.apply(await h.auth(),write,q);assert.equal((await f.see()).summary.assigned,'80.00');}finally{await h.migration.unsafe(current);}const g=await allocationFixture(h,'100.00','100.00');await assert.rejects(h.allocations.apply(await h.auth(),write,await nullBasis(g)));assert.equal((await g.see()).summary.assigned,'0.00');});
test('H3-006-F06 historical NULL Schedule revision accepted current rejects typed stale guard',async()=>{const current=(await h.observer`select pg_get_functiondef(p.oid) def from pg_proc p where p.proname='fund_assign'`)[0]!.def as string,historical=await readFile('tests/fixtures/h3-006/fourth-product.sql.txt','utf8'),start=historical.indexOf('create function crm_private.fund_assign('),end=historical.indexOf('end$$;',start)+7;
 const f=await allocationFixture(h,'100.00','100.00'),q=await f.attest({...await f.assign('80.00'),expectedScheduleRevision:null} as never);await h.migration.unsafe(historical.slice(start,end).replace('create function','create or replace function'));try{await h.allocations.apply(await h.auth(),write,q);assert.equal((await f.see()).summary.assigned,'80.00');}finally{await h.migration.unsafe(current);}const g=await allocationFixture(h,'100.00','100.00');await assert.rejects(h.allocations.apply(await h.auth(),write,await g.attest({...await g.assign('80.00'),expectedScheduleRevision:null} as never)));assert.equal((await g.see()).summary.assigned,'0.00');});
test('H3-006-F07 Customer Payment independent does not remove verified Reconciliation context',async()=>{const f=await allocationFixture(h,'100.00','100.00','received'),candidate={...await f.propose(2,'100.00')};delete(candidate as unknown as Record<string,unknown>).scheduleId;delete(candidate as unknown as Record<string,unknown>).slot;await assert.rejects(h.payments.apply(await h.auth(),write,await f.paymentAttest(candidate)),/PAYMENT_CONTEXT_REQUIRED/);assert.equal((await f.see()).summary.received,'100.00');assert.equal((await f.see()).summary.verifiedCorrespondence,'0.00');});
