import {randomUUID as uid}from'node:crypto';
import {test}from'node:test';import assert from'node:assert/strict';
import {isolatedPreparation,read,write}from'../support/h4-booking-preparation-isolated.ts';
import {preparationFixture,preparationCommands,futureCivil}from'../support/h4-booking-preparation-fixtures.ts';
import {quantityFixture,nominalFixture}from'../support/h2-quantities-fixtures.ts';
import {confirmationFixture}from'../support/h4-confirmation-fixtures.ts';
import {modificationFixture}from'../support/h4-modification-fixtures.ts';
import {requirementFixture}from'../support/h4-requirement-fixtures.ts';
import {obligationFixture}from'../support/h3-obligation-fixtures.ts';
import {availabilityFixture}from'../support/h4-availability-fixtures.ts';
import {holdFixture}from'../support/h4-hold-fixtures.ts';
import {incidentFixture}from'../support/h4-incident-fixtures.ts';
import {invoiceFixture}from'../support/h3-invoice-fixtures.ts';
import type {ObligationCommand}from'../../src/infrastructure/postgres/h3-obligation-adapter.ts';

test('H4-021 concrete dimensions and civil-time cases',async t=>{const h=await isolatedPreparation('crm_h4021_concrete',58208);try{
 await t.test('B05/B06/B35/B42 AC022 S1 call S2 pending S3 internal; N1=12 N2=10 four nominal',async()=>{
  // Catalog and Booking both record S3 internal before conversion, through ordinary contracts.
  const b=await quantityFixture({...h,cat:async(kind,...args)=>{if(kind==='service'&&args[0]?.name==='SYNTHETIC Casa completa')args[0]={...args[0],nature:'internal'};return h.cat(kind,...args);}}as typeof h);
  const nominal=await nominalFixture(h,b);(nominal.detail.services[2]as {nature:string}).nature='internal';const q={...nominal,evidenceId:await b.detailProof(nominal.detail)};await h.booking.apply(await h.auth(),write,q);
  const d=q.detail,p=await preparationCommands(h,q.bookingId),provider=await h.cat('provider',{name:'SYNTHETIC S1 actual call provider'}),shared={b:{detail:d},bookingId:q.bookingId,provider}as Parameters<typeof confirmationFixture>[1];
  const s1=await confirmationFixture(h,shared,0),s2=await confirmationFixture(h,shared,1),s3=await confirmationFixture(h,shared,2,'internal');
  const manifest=[await p.classify(d.services[0]!.id),await p.classify(d.services[1]!.id),...await Promise.all(d.services[2]!.nights.map(n=>p.classify(d.services[2]!.id,n.id)))];
  await s1.apply(await s1.register({coverage:{...s1.coverage,quantity:'1'}}));await s1.apply(await s1.evaluate());let r=(await p.run(await p.command(manifest))).result;assert.equal(r.phase,'Parcialmente confirmada');assert.equal(r.coverage.find(x=>(x.scope as {serviceId:string}).serviceId===s1.service.id)!.confirmed,true);assert.equal(r.coverage.find(x=>(x.scope as {serviceId:string}).serviceId===s2.service.id)!.confirmed,false);
  const n=(await p.read())!.coverage.filter(x=>(x.scope as {nightId:string|null}).nightId);assert.deepEqual(n.map(x=>(x.scope as {quantity:number}).quantity).sort((a,b)=>b-a),[12,10]);assert.equal((await h.observer`select count(*)n from crm_private.b04_participants where booking_id=${q.bookingId}::uuid`)[0]!.n,'4');assert.equal((await h.observer`select count(*)n from crm_private.b04_participants where booking_id=${q.bookingId}::uuid and contact_id is not null`)[0]!.n,'0');
  const night=d.services[2]!.nights[0]!,occupants=(await h.observer`select contribution_id::text id from crm_private.b04_night_occupancies where night_id=${night.id}::uuid`).map(x=>x.id),coverage={...s3.coverage,nightId:night.id,date:night.date,quantity:'11',commercialBasis:{...s3.coverage.commercialBasis,contributions:s3.coverage.commercialBasis.contributions.filter(c=>occupants.includes(c.id as string))}};await s3.apply(await s3.register({coverage}));await s3.apply(await s3.evaluate());r=(await p.run(await p.command(manifest))).result;assert.equal(r.coverage.find(x=>(x.scope as {nightId:string}).nightId===night.id)!.confirmed,false);
  await s3.apply(await s3.review());await s3.apply(await s3.rectify({coverage:{...coverage,quantity:'12'}}));await s3.apply(await s3.evaluate());r=(await p.run(await p.command(manifest))).result;assert.equal(r.coverage.find(x=>(x.scope as {nightId:string}).nightId===night.id)!.confirmed,true);assert.equal(s3.source.kind,'internal');assert.equal(s3.source.offeringRevisionId,null);
  await s2.apply(await s2.register({coverage:{...s2.coverage,quantity:'2'}}));await s2.apply(await s2.evaluate());await s1.apply(await s1.review());r=(await p.run(await p.command(manifest))).result;assert.equal(r.phase,'Parcialmente confirmada');assert.equal(r.coverage.find(x=>(x.scope as {serviceId:string}).serviceId===s2.service.id)!.confirmed,true);assert.equal(r.coverage.find(x=>(x.scope as {serviceId:string}).serviceId===s1.service.id)!.confirmed,false);
  for(const name of ['b05_provider_invoices','b05_suplidos','b05_provider_payments'])assert.equal((await h.observer.unsafe(`select count(*)n from crm_private.${name} where booking_id='${q.bookingId}'`))[0]!.n,'0');
 });
 await t.test('B18/B19/B20/B47 SQL civil assessment full deadline day and following day; H3 same boundary',async()=>{const f=await preparationFixture(h,7);await f.confirm();await f.pay();await f.run(await f.command());const date=futureCivil(0),next=futureCivil(1),instants=[date+'T00:00:00+02:00',date+'T23:59:59.999999+02:00',next+'T00:00:00+02:00'],before=(await f.see())!;
  for(const [i,at]of instants.entries()){const r=(await h.observer`select crm_private.booking_preparation_assess(crm_private.booking_preparation_inputs(${f.bid}::uuid,${h.scope}),(select state->'command'from crm_private.b04_preparation_evaluations where booking_id=${f.bid}::uuid order by revision desc limit 1),${f.bid}::uuid,${h.scope},${at}::timestamptz)r`)[0]!.r as {complete:boolean;economics:{demand:{required:boolean}[];daysBefore:number}[]};assert.equal(r.complete,i<2);assert.equal(r.economics[0]!.demand[1]!.required,i===2);assert.equal(r.economics[0]!.daysBefore,i<2?7:6);const old=await h.obligations.evaluate(await h.auth(),read,f.bid,f.o.q.scheduleId!,at);assert.equal(old![1]!.expired,i===2);}
  assert.deepEqual((await f.see())!.history,before.history);console.log('B18/19 observation: explicit SQL function time input; no clock or business mutation');
 });
 await t.test('B22 valid contractual specific H3 portions retained and evaluated',async()=>{const f=await preparationFixture(h,6,{definition:{exception:{reason:'SYNTHETIC authorized case-specific contractual terms',parts:[{slot:'initial',amount:'500.00',due:{kind:'at_confirmation'}},{slot:'balance',amount:'500.00',due:{kind:'civil',date:futureCivil(2)}}]}}});await f.confirm();await f.pay('500.00');const r=(await f.run(await f.command())).result;assert.equal(r.phase,'Confirmada operativamente');assert.deepEqual(r.economics[0]!.parts,[{slot:'initial',amount:'500.00',due:{kind:'at_confirmation'}},{slot:'balance',amount:'500.00',due:{kind:'civil',date:futureCivil(2)}}]);});
 await t.test('B23/B24 missing source reference/zone blocked; ordinary H3 rejects no invention',async()=>{for(const key of ['reference','zone']){const o=await obligationFixture(h,'1000.00',new Date().toISOString(),[futureCivil(10),futureCivil(10)]);const d=structuredClone(o.q.definition!);if(key==='reference')delete(d as any).reference;else delete(d.reference as any).zone;await assert.rejects(h.obligations.apply(await h.auth(),write,await o.attest({...o.q,definition:d})));const p=await preparationCommands(h,o.b.bookingId),manifest=[await p.classify(o.detail.services[0]!.id)],r=(await p.run(await p.command(manifest))).result;assert.ok(r.missing.includes('economy-definition'));assert.notEqual(r.phase,'Confirmada operativamente');}});
 await t.test('B30/B31 actual A→B andV1→V2 preserve corrected contracts and reject old HA',async()=>{for(const kind of ['provider','variant']){const f=await preparationFixture(h);await f.confirm();await f.pay();await f.run(await f.command());const approval=await f.approval(await f.command('evaluate',{origin:'ai'})),m=await modificationFixture(h,f.conf),serviceItem=String((await h.observer`select item_id::text id from crm_private.catalog_revisions where revision_id=${f.conf.service.serviceRevisionId}::uuid`)[0]!.id),replacement=kind==='provider'?await h.cat('provider',{name:'SYNTHETIC real Provider B'}):await(async()=>{const targetId=uid(),base={kind:'variant' as const,targetId,expectedVersion:0,sourceRef:'SYNTHETIC V2',evidenceRef:'SYNTHETIC V2 source',reason:'SYNTHETIC V2'};await h.catalog.apply(await h.auth(),write,{...base,operationId:uid(),action:'create_item',parentId:serviceItem});const r=await h.catalog.apply(await h.auth(),write,{...base,operationId:uid(),action:'publish_version',parentId:f.conf.service.serviceRevisionId,definition:{name:'SYNTHETIC V2'}});return {id:targetId,revision:r.id};})();await m.run(await m.request([{id:m.partId,scope:m.scope,expectedScopeRevision:1,desired:{[kind]:replacement.revision},aspects:[kind,'capacity','conditions'],dependencies:[]}]));await m.run(await m.evaluate());await m.run(await m.approve());await m.run(await m.apply());assert.equal((await f.see())!.historicalPhase,'Confirmada operativamente');assert.notEqual((await f.see())!.phase,'Confirmada operativamente');await assert.rejects(approval.execute(),/H0_011_RESERVE_DENIED/);assert.equal((await h.observer`select count(*)n from crm_private.b04_preparation_evaluations where booking_id=${f.bid}::uuid`)[0]!.n,'1');}});
 await t.test('B38 no-apply cannot erase obligatory need or use unsourced context',async()=>{const f=await preparationFixture(h),d=await requirementFixture(h,{bookingId:f.bid,b:{detail:f.o.detail}}as any);await h.requirements.apply(await h.auth(),write,await d.need());await f.confirm();await f.pay();await assert.rejects(h.requirements.apply(await h.auth(),write,await d.command('no_apply',{context:{...d.basis.context,sourceRef:''}})));await assert.rejects(h.requirements.apply(await h.auth(),write,await d.command('no_apply',{context:d.basis.context})));assert.notEqual((await f.run(await f.command())).result.phase,'Confirmada operativamente');});
 await t.test('B41 documented optional service absent is no universal block',async()=>{const f=await preparationFixture(h);await f.pay();assert.equal((await f.run(await f.command('evaluate',{criticalScopes:[await f.classify(false)]}))).result.phase,'Confirmada operativamente');});
 await t.test('B42 distinct dates are pertinent contributions, no aggregate dated fact covers both',async()=>{const o=await obligationFixture(h,'1000.00',new Date().toISOString(),[futureCivil(10),futureCivil(11)],true);await h.obligations.apply(await h.auth(),write,o.q);const provider=await h.cat('provider',{name:'SYNTHETIC contribution provider'}),f=await confirmationFixture(h,{bookingId:o.b.bookingId,b:{detail:o.detail},provider}as any),p=await preparationCommands(h,o.b.bookingId),cs=o.detail.services[0]!.contributions,manifest=await Promise.all(cs.map(c=>p.classify(f.service.id,null,true,c.id))),c=cs[0]!,coverage={...f.coverage,date:futureCivil(10),quantity:'1',contributionId:c.id,commercialBasis:{...f.coverage.commercialBasis,contributions:f.coverage.commercialBasis.contributions.filter(x=>x.id===c.id)}};await f.apply(await f.register({coverage}));await f.apply(await f.evaluate());const r=(await p.run(await p.command(manifest))).result;assert.equal(r.phase,'Parcialmente confirmada');assert.equal(r.coverage.length,2);assert.equal(r.coverage.filter(x=>x.confirmed).length,1);assert.equal((r.coverage.find(x=>x.confirmed)!.scope as {contributionId:string}).contributionId,c.id);});
 await t.test('B32 historical confirmed Booking retains independent S2 whenS1 loses current coverage',async()=>{const f=await preparationFixture(h),b=await invoiceFixture(h),p=await preparationCommands(h,b.bookingId),at=new Date().toISOString(),unsigned:ObligationCommand={...f.o.q,operationId:uid(),bookingId:b.bookingId,scheduleId:uid(),scopeId:b.bookingId,at,definition:{...f.o.q.definition!,base:{amount:'2000.20',sourceRef:b.b.q.versionId,version:'1'},reference:{...f.o.q.definition!.reference,date:'2026-10-20' as never,scopeId:b.bookingId,sourceRef:b.b.q.versionId},at}};const q={...unsigned,evidenceId:await b.b.f.proof('obligation:determine:'+await p.hash(Object.fromEntries(Object.entries(unsigned).filter(([k,v])=>!['operationId','evidenceId','computed'].includes(k)&&v!==undefined))),b.b.q.coverage,at)};await h.obligations.apply(await h.auth(),write,q);
  const s1=await confirmationFixture(h,b,0),s2=await confirmationFixture(h,b,1);for(const s of [s1,s2]){await s.apply(await s.register({coverage:{...s.coverage,quantity:'1'}}));await s.apply(await s.evaluate());}const manifest=[await p.classify(s1.service.id),await p.classify(s2.service.id)],economy={reason:'SYNTHETIC Administrator waiver only economic initial portion',scopeIds:[q.scheduleId!]},command={...await p.command(manifest),economicException:{...economy,evidenceId:await p.proof('booking-preparation:exception:'+await p.hash(economy))}};command.evidenceId=await p.proof('booking-preparation:evaluate:'+await p.hash(Object.fromEntries(Object.entries(command).filter(([k])=>!['operationId','evidenceId'].includes(k)))));await(await f.approval(command)).execute();assert.equal((await p.read())!.phase,'Confirmada operativamente');await s1.apply(await s1.review());const r=(await p.read())!;assert.equal(r.historicalPhase,'Confirmada operativamente');assert.equal(r.phase,'Parcialmente confirmada');assert.equal(r.coverage.find(x=>(x.scope as {serviceId:string}).serviceId===s2.service.id)!.confirmed,true);assert.equal(r.history.length,1);});
 await t.test('B10 removing capacity eligibility proof forbids a critical fact becoming usable',async()=>{const f=await preparationFixture(h);await f.conf.apply(await f.conf.register({coverage:f.coverage}));const q=await f.conf.evaluate();const data={...q.data};delete data.eligibilityProofId;await assert.rejects(f.conf.apply(await f.conf.attest({...q,data})));await f.pay();assert.notEqual((await f.run(await f.command())).result.phase,'Confirmada operativamente');});
 await t.test('B43 Availability and resolved Incident do not confirm missing critical scope',async()=>{const f=await preparationFixture(h),shared={bookingId:f.bid,provider:f.conf.b.provider,b:{detail:f.o.detail}}as any,a=await availabilityFixture(h,shared);await a.apply(await a.command('query',{coverage:{...a.coverage,dates:[f.date],quantity:'1'},source:a.source,happenedAt:'2026-09-28T10:00:00Z',content:'SYNTHETIC actual question'}));await a.apply(await a.receive({coverage:{...a.coverage,dates:[f.date],quantity:'1'}}));await a.apply(await a.verify());const i=await incidentFixture(h,shared);for(const q of [await i.detect()])await h.incidents.apply(await h.auth(),write,q);await h.incidents.apply(await h.auth(),write,await i.manage());await h.incidents.apply(await h.auth(),write,await i.resolve());await f.pay();const r=(await f.run(await f.command())).result;assert.equal(r.phase,'En confirmación con proveedores');assert.ok(r.missing.some(x=>x.startsWith('critical:')));});
 await t.test('B43 actual capacity Hold survives conversion independently of confirmation',async()=>{const f=await holdFixture(h);await f.apply(await f.grant());await f.apply(await f.check());const b=await f.convert();await f.apply(await f.link(b.bookingId,b.detail.services[0]!.id));const p=await preparationCommands(h,b.bookingId),manifest=await Promise.all(b.detail.services.map(x=>p.classify(x.id)));assert.equal((await p.run(await p.command(manifest))).result.phase,'En confirmación con proveedores');assert.equal((await h.observer`select count(*)n from crm_private.b04_confirmations where booking_id=${b.bookingId}::uuid`)[0]!.n,'0');});
 await t.test('B47 current ordinary API reevaluates10→6 days; explicit isolated clock fault injection only',async()=>{const f=await preparationFixture(h);await f.confirm();await f.pay();await f.run(await f.command());const old=String((await h.observer`select pg_get_functiondef('crm_api.booking_preparation_read(bytea,bytea,bytea,bytea,bytea)'::regprocedure) d`)[0]!.d),instant=futureCivil(4)+'T12:00:00+02:00';await h.migration.unsafe(old.replaceAll('clock_timestamp()',"'"+instant+"'::timestamptz"));try{const r=(await f.see())!;assert.equal(r.historicalPhase,'Confirmada operativamente');assert.equal(r.phase,'Parcialmente confirmada');assert.equal(r.applicable,false);assert.equal(r.economics[0]!.daysBefore,6);assert.equal(r.history.length,1);console.log('B47 TECHNICAL TIME FAULT',JSON.stringify({instant,history:r.historicalPhase,current:r.phase}));}finally{await h.migration.unsafe(old);}assert.equal((await f.see())!.phase,'Confirmada operativamente');});
 await t.test('B50 foreign critical scope/evidence and schedule do not grant an effect',async()=>{const a=await preparationFixture(h),b=await preparationFixture(h);const wrong=await a.command('evaluate',{criticalScopes:[await b.classify()]});await assert.rejects(a.run(wrong),/DENIED/);await assert.rejects(a.run({...await a.command(),evidenceId:(await b.command()).evidenceId}));const q=await a.command('evaluate',{economicException:{reason:'SYNTHETIC wrong booking',scopeIds:[b.o.q.scheduleId!],evidenceId:await a.proof('SYNTHETIC invalid exception')}});await assert.rejects((await a.approval(q)).execute());assert.equal((await a.see())!.revision,0);});
 await t.test('B11/B12/B13/B14 received or proposed or verified but unassigned money is no coverage',async()=>{for(const stage of ['receive','propose','verify']){const f=await preparationFixture(h);await f.confirm();await f.pay('500.00',stage);const r=(await f.run(await f.command())).result;assert.equal(r.phase,'Parcialmente confirmada');assert.ok(r.missing.some(x=>x.startsWith('economy:')));assert.equal(((r.economics[0]!.coverage as {verifiedAmount:string}[])[0]!).verifiedAmount,'0.00');}});
 await t.test('B49 disabled actor cannot read or replay and cannot reactivate activity',async()=>{const f=await preparationFixture(h),q=await f.command();await f.run(q);const auth=await h.auth();await h.migration`select crm_api.set_actor_enabled(${h.actorId}::uuid,false,'ready')`;const snapshot=()=>h.observer`select to_jsonb(x) d from crm_private.identification_epochs x order by epoch_id`,before=await snapshot();try{await assert.rejects(h.preparation.read(auth,read,f.bid));await assert.rejects(h.preparation.apply(auth,write,q));assert.deepEqual(await snapshot(),before);assert.equal((await h.observer`select count(*)n from crm_private.b04_preparation_operations where booking_id=${f.bid}::uuid`)[0]!.n,'1');}finally{await h.migration`select crm_api.set_actor_enabled(${h.actorId}::uuid,true,'ready')`;}});
}finally{await h.close();}});
