import {test}from'node:test';import assert from'node:assert/strict';
import {isolatedPreparation,read,write}from'../support/h4-booking-preparation-isolated.ts';
import {preparationFixture}from'../support/h4-booking-preparation-fixtures.ts';
import {cancelFixture,businessSnapshot,observed}from'../support/h4-booking-preparation-f23-fixtures.ts';
import {writeFile}from'node:fs/promises';
import {invoiceFixture}from'../support/h3-invoice-fixtures.ts';
import {confirmationFixture}from'../support/h4-confirmation-fixtures.ts';
import {preparationCommands}from'../support/h4-booking-preparation-fixtures.ts';
import {quantityFixture}from'../support/h2-quantities-fixtures.ts';
import {modificationFixture}from'../support/h4-modification-fixtures.ts';
const h=await isolatedPreparation('crm_h4021_f23_repro',58300);
const records:unknown[]=[];
async function remember(label:string,f:Awaited<ReturnType<typeof preparationFixture>>){const ordinary=await h.booking.read(await h.auth(),read,f.bid),preparation=await f.see(),snapshot=await businessSnapshot(h);const value={label,bookingId:f.bid,ordinary,preparation,snapshot};records.push(value);console.log('F23 ORDINARY READERS',label,JSON.stringify({ordinary,preparation}));return value;}
try{
test('F23 C01 A applied total cancellation without preparation history reads Cancelada',async()=>{const f=await preparationFixture(h),c=await cancelFixture(h,f);await c.applySequential();const v=await remember('A',f);assert.equal((v.ordinary as any).booking.state,'Cancelada');assert.equal(v.preparation!.phase as string,'Cancelada');assert.equal(v.preparation!.applicable,false);assert.equal(v.preparation!.history.length,0);});
test('F23 C02 B historical Confirmada then applied cancellation retains historical proof and current Cancelada',async()=>{const f=await preparationFixture(h);await f.confirm();await f.pay();await f.run(await f.command());const old=(await f.see())!,c=await cancelFixture(h,f);await c.applySequential();const v=await remember('B',f);assert.equal((v.ordinary as any).booking.state,'Cancelada');assert.equal(v.preparation!.historicalPhase,'Confirmada operativamente');assert.deepEqual(v.preparation!.history,old.history);assert.equal(v.preparation!.applicable,false);assert.equal(v.preparation!.phase as string,'Cancelada');});
test('F23 C03 C new evaluate current cancelled material cannot record preparation transition',async()=>{const f=await preparationFixture(h),c=await cancelFixture(h,f);await c.applySequential();const q=await f.command('evaluate',{criticalScopes:[]}),before=await businessSnapshot(h),r=await observed('C evaluate current empty active scope',()=>f.run(q));await remember('C after attempted evaluation',f);assert.equal(r.ok,false,'cancelled operational origin must reject new evaluation');assert.deepEqual(await businessSnapshot(h),before);});
test('F23 C04 D start cannot reactivate cancelled Booking, including upstream guard outcome',async()=>{const f=await preparationFixture(h),c=await cancelFixture(h,f);await c.applySequential();const q=await f.command('start',{criticalScopes:[]}),before=await businessSnapshot(h),r=await observed('D start',()=>f.run(q));assert.equal(r.ok,false);assert.deepEqual(await businessSnapshot(h),before);assert.equal((await h.booking.read(await h.auth(),read,f.bid)as any).booking.state,'Cancelada');});
test('F23 C05 E exact HA TTE and economic exception cannot dispense cancelled origin',async()=>{const f=await preparationFixture(h),c=await cancelFixture(h,f);await c.applySequential();const q=await f.command('evaluate',{criticalScopes:[],origin:'ai',economicException:await f.exception()}),a=await f.approval(q),before=await businessSnapshot(h),r=await observed('E exact HA TTE after cancellation',()=>a.execute());await remember('E after exact approval',f);assert.equal(r.ok,false);assert.deepEqual(await businessSnapshot(h),before);assert.equal((await h.observer`select count(*) n from crm_ha.reservations where reservation_id=${a.reserve}`)[0]!.n,'0');});
test('F23 C06 F partial cancellation preserves independent live service, not total Cancelada',async()=>{const invoice=await invoiceFixture(h),conf=await confirmationFixture(h,invoice),p=await preparationCommands(h,invoice.bookingId);await conf.apply(await conf.register());await conf.apply(await conf.evaluate());const cs=[await p.classify(invoice.b.detail.services[0]!.id),await p.classify(invoice.b.detail.services[1]!.id,null,false)];await p.run(await p.command(cs));const c=await cancelFixture(h,{bid:invoice.bookingId,conf,o:{detail:invoice.b.detail}},true);await c.applySequential();const ordinary=await h.booking.read(await h.auth(),read,invoice.bookingId)as any;assert.notEqual(ordinary.booking.state,'Cancelada');assert.equal(ordinary.booking.detail.services[0].cancelled,false);assert.equal(ordinary.booking.detail.services[1].cancelled,true);assert.equal((await conf.assess())!.usable,true);assert.notEqual((await p.read())!.phase as string,'Cancelada');await p.run(await p.command([cs[0]!]));assert.equal((await p.read())!.phase,'Parcialmente confirmada');console.log('F23 F PARTIAL ORDINARY',JSON.stringify({ordinary,current:await p.read(),modification:await c.m.see()}));});
test('F23 C06 independent N1 remains live when N2 is legitimately cancelled',async()=>{const x=await quantityFixture(h);await h.booking.apply(await h.auth(),write,x.q);const provider=await h.cat('provider',{name:'SYNTHETIC actual lodging source'}),shared={bookingId:x.q.bookingId,b:{detail:x.detail},provider}as Parameters<typeof confirmationFixture>[1],conf=await confirmationFixture(h,shared,2),m=await modificationFixture(h,conf),lodging=x.detail.services[2]!,n1=lodging.nights[0]!,n2=lodging.nights[1]!;await m.run(await m.request([{id:m.partId,scope:{kind:'night',id:n2.id,serviceId:lodging.id},expectedScopeRevision:1,desired:{cancelled:true},aspects:['cancellation'],dependencies:[]}]));await m.run(await m.evaluate());await m.run(await m.approve());await m.run(await m.apply());const ordinary=await h.booking.read(await h.auth(),read,x.q.bookingId)as any;assert.notEqual(ordinary.booking.state,'Cancelada');assert.equal(ordinary.booking.detail.services[2].nights[0].cancelled,false);assert.equal(ordinary.booking.detail.services[2].nights[1].cancelled,true);const p=await preparationCommands(h,x.q.bookingId),cs=[await p.classify(x.detail.services[0]!.id),await p.classify(x.detail.services[1]!.id),await p.classify(lodging.id,n1.id)];await p.run(await p.command(cs));const v=(await p.read())!;assert.notEqual(v.phase,'Cancelada');assert.ok(v.coverage.some(c=>(c.scope as {nightId:string|null}).nightId===n1.id));assert.ok(!v.coverage.some(c=>(c.scope as {nightId:string|null}).nightId===n2.id));console.log('F23 NIGHT PARTIAL ORDINARY',JSON.stringify({ordinary,current:v,modification:await m.see()}));});
test('F23 C07 G authorized durable replay after cancellation never applies new transition',async()=>{const f=await preparationFixture(h);await f.confirm();await f.pay();const q=await f.command(),r=await f.run(q),c=await cancelFixture(h,f);await c.applySequential();const before=await businessSnapshot(h),replay=await f.run(q);assert.equal(replay.replayed,true);assert.deepEqual(replay.result,r.result);assert.deepEqual(await businessSnapshot(h),before);const v=await remember('G replay',f);assert.equal(v.preparation!.phase as string,'Cancelada');assert.equal(v.preparation!.history.length,1);});
test('F23 C08 cancelled old critical scope denied upstream does not refute current read/evaluate defect',async()=>{const f=await preparationFixture(h),c=await cancelFixture(h,f);await c.applySequential();const q=await f.command(),before=await businessSnapshot(h),r=await observed('C old critical cancelled scope',()=>f.run(q));assert.equal(r.ok,false);assert.deepEqual(await businessSnapshot(h),before);});
}finally{
 const {after}=await import('node:test');after(async()=>{if(process.env.H4014_CAPTURE_DIR)await writeFile(process.env.H4014_CAPTURE_DIR+'/f23-ordinary-snapshots.json',JSON.stringify(records,null,2)+'\n');await h.close();});
}
