import {before,after,test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID as uid} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {isolatedOffer,offerMigration,write,read} from '../support/h2-offer-isolated.ts';
import {decideOfferValidity} from '../../src/domain/offer-lifecycle.ts';
import {H2005OfferAdapter,type OfferCommand} from '../../src/infrastructure/postgres/h2-offer-adapter.ts';
import {H0005PostgresAdapter} from '../../src/infrastructure/postgres/h0-005-adapter.ts';
import {verifyAuth} from '../../src/application/verified-auth.ts';
import {createF1Issuer,encodeF1Fields} from '../../src/infrastructure/postgres/f1-codec.ts';
import {createF2Issuer} from '../../src/infrastructure/postgres/f2-codec.ts';
import {issueTrustedContext} from '../../src/application/trusted-context.ts';
import {postgresF1Binding} from '../../src/infrastructure/postgres/transaction.ts';
let h:Awaited<ReturnType<typeof isolatedOffer>>,oldBefore:unknown,oldAfter:unknown,aclBefore:unknown,aclAfter:unknown;
const now=()=>new Date(Date.now()-1).toISOString();
async function snap(tables?:string[]){const data:Record<string,unknown>={};for(const t of tables??['b03_offer_issuances','b03_offer_operations','b03_offer_history','b03_proposals','b03_preparations','b03_proposal_versions','b03_proposal_modalities','b03_proposal_lines','b03_opportunities','b03_history','b03_operations','identity_codes','identity_code_counters','b07_records','b07_links']) data[t]=(await h.observer.unsafe(`select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]') data from crm_private.${t} t`))[0]!.data;return data;}
async function acl(){return {
 tables:await h.observer`select c.oid,c.relname,c.relacl::text,c.relowner::regrole::text,c.relrowsecurity,c.relforcerowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='crm_private' and c.relkind='r' and c.relname not like 'b03_offer_%' order by c.oid`,
 functions:await h.observer`select p.oid,p.proacl::text,md5(pg_get_functiondef(p.oid)) hash from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('crm_api','crm_f1','crm_f2','crm_private') and p.proname not like 'offer_%' order by p.oid`,
 policies:await h.observer`select c.relname,p.polname,p.polroles::text,pg_get_expr(p.polqual,p.polrelid) q,pg_get_expr(p.polwithcheck,p.polrelid) w from pg_policy p join pg_class c on c.oid=p.polrelid where c.relname not like 'b03_offer_%' order by c.relname,p.polname`,
 roles:await h.observer`select rolname,rolsuper,rolbypassrls,rolcreaterole,rolcreatedb from pg_roles order by rolname`,
 schemas:await h.observer`select nspname,nspacl::text from pg_namespace where nspname like 'crm_%' order by nspname`,
 columns:await h.observer`select c.relname,a.attname,a.attacl::text from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='crm_private' and c.relkind='r' and c.relname not like 'b03_offer_%' and a.attnum>0 order by c.relname,a.attnum`,
 members:await h.observer`select roleid::regrole::text,member::regrole::text,admin_option,inherit_option,set_option from pg_auth_members order by roleid,member`
};}
async function fixture(unknownCost=false){
 const service=await h.cat('service',{name:'H2006 SYNTHETIC excursion',nature:'external'}),unit=await h.cat('unit',{name:'H2006 group unit',definition:'whole fixed group'}),form=await h.cat('pricing_form',{name:'H2006 fixed',definition:'fixed group'});
 const tariff=await h.com('tariff',{label:'H2006 retained source',price_state:'confirmed',amount:'900.00',cost_state:unknownCost?'unknown':'confirmed',...(unknownCost?{}:{cost_amount:'700.00'}),vat_treatment:'included',unit_revision_id:unit.revision,pricing_form_revision_id:form.revision},service);
 const opp=h.input({sourceRef:'H2006 SYNTHETIC direct',reason:'three verified minima'});await h.adapter.apply(await h.auth(),write,opp);
 const mid=uid(),line=uid(),content={scope:'H2006 exact group',terms:{version:'H2006 T1',text:'H2006 existing conditions',sourceRef:'H2006 retained terms'},pending:[],modalities:[{id:mid,name:'H2006 A',participants:10,independent:true,selectable:true,conditions:'H2006 agreed modality',finalPersonPrice:'100.01',manualReason:'H2006 human price',definitive:!unknownCost,lines:[{id:line,serviceRevisionId:service.revision,unitRevisionId:unit.revision,tariffRevisionId:tariff.revision,quantity:'1',included:true,independent:false,selectable:false,date:'2026-10-20',datePending:false,priceBasis:'fixed' as const,costMaterial:true,sourceRef:'H2006 quantity'}]}]};
 const secondMid=uid(),secondLine=uid();content.modalities.push({...content.modalities[0]!,id:secondMid,name:'H2006 B',participants:5,lines:[{...content.modalities[0]!.lines[0]!,id:secondLine}]});
 const proposalId=uid(),versionId=uid(),c={action:'prepare' as const,operationId:uid(),proposalId,opportunityId:opp.targetId,expectedRevision:0,expectedOpportunityRevision:1,sourceRef:'H2006 source',reason:'H2006 preparation',content};
 await h.proposal.apply(await h.auth(),write,c);await h.proposal.apply(await h.auth(),write,{...c,action:'fix',operationId:uid(),versionId,content:undefined,expectedRevision:1});
 const recipientId=uid();await h.identities.apply(await h.auth(),write,{action:'create_entity',operationId:uid(),targetId:recipientId,kind:'contact',expectedVersion:0,sourceRef:'H2006 manual identity',evidenceRef:'H2006 identity proof',reason:'H2006 identity',verified:true,displayName:'H2006 SYNTHETIC RESPONSIBLE'});
 await h.identities.apply(await h.auth(),write,{action:'designate',operationId:uid(),targetId:uid(),relatedId:recipientId,contextId:opp.targetId,kind:'primary_contact',expectedVersion:0,sourceRef:'H2006 responsible designation',evidenceRef:'H2006 responsibility proof',reason:'H2006 context role',verified:true});
 const q=async(change:Partial<OfferCommand>={}):Promise<OfferCommand>=>({action:'intent',operationId:uid(),proposalId,opportunityId:opp.targetId,versionId,expectedRevision:Number((await h.observer`select revision from crm_private.b03_proposals where proposal_id=${proposalId}::uuid`)[0]!.revision),expectedOpportunityRevision:Number((await h.observer`select revision from crm_private.b03_opportunities where opportunity_id=${opp.targetId}::uuid`)[0]!.revision),sourceRef:'H2006 source',reason:'H2006 act',coverage:content.scope,at:now(),recipientId,channel:'manual',...change});
 return {service,unit,tariff,opp,mid,line,secondMid,secondLine,content,c,proposalId,versionId,recipientId,q};
}
type Fixture=Awaited<ReturnType<typeof fixture>>;
async function proof(f:Fixture,claim:string,coverage:string,at:string,certainty='reviewed'){
 const e=h.req('evidence',{claim,coverage,certainty,source_kind:'manual'},f.opp.targetId);await h.evidence.apply(await h.auth(),write,{...e,coverage,occurredAt:at});return e.targetId;
}
async function issue(f:Fixture,short=false,days?:number){const at=now(),limits=[] as {aspect:'availability';until:string;evidenceId:string}[];
 if(short){const until=new Date(Date.now()+50).toISOString();limits.push({aspect:'availability',until,evidenceId:await proof(f,`offer:limit:${f.versionId}:availability:${until}`,f.content.scope,at)});}
 const evidenceId=await proof(f,`offer:issue:${f.versionId}:${at}:${days??7}`,f.content.scope,at),q=await f.q({action:'issue',at,issuance:{issuedAt:at,...(days?{days}:{}),limits},evidenceId});const r=await h.offer.apply(await h.auth(),write,q);return {q,r};}
async function issued(short=false,unknown=false){const f=await fixture(unknown);await issue(f,short);return f;}
async function reviews(f:Fixture,actId:string,at:string,coverage=f.content.scope,actKind='send'){const evidence:Record<string,string>={};for(const aspect of ['prices','availability','conditions','capacity']) evidence[aspect]=await proof(f,`offer:review:${f.versionId}:${actId}:${actKind}:${aspect}`,coverage,at);return evidence;}
async function sending(f:Fixture,coverage=f.content.scope){const at=now(),actId=uid(),reviewEvidence=await reviews(f,actId,at,coverage);
 const e=await proof(f,`offer:sent:${f.versionId}:${actId}:${f.recipientId}:manual`,coverage,at),com=h.req('communication',{direction:'outgoing',channel:'manual',recipient_ref:f.recipientId,coverage,initial_fact:'none',proposal_version_ref:f.versionId},f.opp.targetId);
 await h.evidence.apply(await h.auth(),write,{...com,coverage,occurredAt:at});const fact=h.req('communication_fact',{fact_kind:'sent',evidence_id:e,party_ref:f.recipientId,coverage},f.opp.targetId);
 await h.evidence.apply(await h.auth(),write,{...fact,originalId:com.targetId,coverage,occurredAt:at});return f.q({action:'send',actId,actKind:'send',at,reviewEvidence,communicationId:com.targetId,factId:fact.targetId,coverage});}
async function rejection(f:Fixture,kind:'version'|'modality'|'line'='modality') {const partId=kind==='version'?f.versionId:kind==='line'?f.line:f.mid,coverage=kind==='version'?f.content.scope:partId,at=now();
 const evidenceId=await proof(f,`offer:reject:${f.versionId}:${partId}:${f.recipientId}:desconocido`,coverage,at),com=h.req('communication',{direction:'incoming',channel:'manual',sender_ref:f.recipientId,coverage,initial_fact:'received',proposal_version_ref:f.versionId},f.opp.targetId);await h.evidence.apply(await h.auth(),write,{...com,coverage,occurredAt:at});return f.q({action:'reject',partKind:kind,partId,recipientId:f.recipientId,lossReason:'desconocido',communicationId:com.targetId,evidenceId,coverage,at});}
async function reject(q:OfferCommand,raw=false){const before=await snap();await assert.rejects(raw?rawApply({...q}):h.offer.apply(await h.auth(),write,q));assert.deepEqual(await snap(),before);}
async function rawApply(input:Record<string,unknown>,forgedScope=false,badSig=false){const auth=await h.auth(),f1=createF1Issuer(h.f1),f2=createF2Issuer(h.f2);return h.runtime.begin(async tx=>{
 const r=(await tx`select actor_id::text,admin_scope,access_generation::text,epoch_id::text from crm_api.f2_lookup(${auth.subject}::uuid,${auth.sessionId!}::uuid)`)[0]!,binding=await postgresF1Binding(tx),scope=forgedScope?'FORGED':r.admin_scope;
 const q=encodeF1Fields(['CRM-H2-OFFER1',JSON.stringify(input)]),ctx=issueTrustedContext({identityId:'H2006 independent signer',identityKind:'technical',purpose:'h1-evidence',scope,requestId:uid(),serverTime:now()}),human=f2(auth,{actorId:r.actor_id,scope,accessGeneration:r.access_generation,sessionId:auth.sessionId!,epochId:r.epoch_id},binding,'evidence_write',q,write),technical=f1(ctx,binding,'C03',q,{resource:'evidence',action:'write_evidence'});
 return tx.unsafe('select crm_api.offer_apply($1,$2,$3,$4,$5)',[human.payload,badSig?Buffer.alloc(32):human.mac,technical.payload,technical.mac,q]);});}
async function state(f:Fixture){return (await h.observer`select state,revision from crm_private.b03_opportunities where opportunity_id=${f.opp.targetId}::uuid`)[0]!;}
async function observed(f:Fixture){return await h.offer.read(await h.auth(),read,f.proposalId,f.versionId) as any;}
async function fault(table:string,q:OfferCommand){const before=await snap();await h.admin.unsafe(`create function crm_private.h2006_fault() returns trigger language plpgsql as $$ begin raise exception 'H2006_INJECTED';end $$;create trigger h2006_fault before insert on crm_private.${table} for each row execute function crm_private.h2006_fault()`);try{await assert.rejects(h.offer.apply(await h.auth(),write,q));assert.deepEqual(await snap(),before);}finally{await h.admin.unsafe(`drop trigger h2006_fault on crm_private.${table};drop function crm_private.h2006_fault()`);}}
before(async()=>{
 h=await isolatedOffer('crm_h2_006',55475,true);const f=await fixture();await proof(f,'H2006 pre-migration evidence',f.content.scope,now());
 await h.evidence.apply(await h.auth(),write,h.req('communication',{direction:'incoming',channel:'manual',sender_ref:f.recipientId,coverage:'synthetic-scope',initial_fact:'received'},f.opp.targetId));
 await h.tasks.apply(await h.auth(),write,{action:'receive',operationId:uid(),taskId:uid(),expectedRevision:0,identity:{causeKind:'review',causeId:uid(),contextKind:'opportunity',contextId:f.opp.targetId,scopeRef:'synthetic-scope',relatedKind:null,relatedId:null,effect:'review-only'},material:{title:'H2006 prior task',deadline:{kind:'unknown',reason:'pending'},priority:{kind:'pending',reason:'pending'},sourceRef:'H2006 prior',sourceVersion:'v1',triggerRef:'manual',triggerVersion:'v1'},reason:'H2006 prior'});
 const tables=(await h.observer`select c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='crm_private' and c.relkind='r' order by c.relname`).map(x=>x.relname as string);oldBefore=await snap(tables);aclBefore=await acl();await h.migration.unsafe(await readFile(new URL(`../../supabase/migrations/${offerMigration}`,import.meta.url),'utf8'));oldAfter=await snap(tables);aclAfter=await acl();
});after(async()=>{await h?.close();});
test('R01 default seven days/configuration',async()=>{const f=await fixture(),{q,r}=await issue(f);assert.equal(Date.parse(String(r.result.effectiveUntil))-Date.parse(q.at),7*86400000);const g=await fixture(),x=await issue(g,false,3);assert.equal(Date.parse(String(x.r.result.effectiveUntil))-Date.parse(x.q.at),3*86400000);assert.equal(decideOfferValidity({issuedAt:'2026-10-01T10:00:00Z',limits:[]},'2026-10-08T10:00:01Z').allowed,false);});
test('R02 most restrictive material limit',async()=>{const f=await fixture(),{q,r}=await issue(f,true);assert.equal(Date.parse(String(r.result.effectiveUntil)),Date.parse(q.issuance!.limits[0]!.until));});
test('R03 limit/source guards',async()=>{const f=await fixture(),at=now(),e=await proof(f,`offer:issue:${f.versionId}:${at}:7`,f.content.scope,at);await reject(await f.q({action:'issue',at,evidenceId:e,issuance:{issuedAt:at,limits:[{aspect:'availability',until:'2026-10-20T10:00:00Z',evidenceId:uid()}]}}));await reject(await f.q({action:'issue',at,evidenceId:uid(),issuance:{issuedAt:at,limits:[]}}));});
test('R04 inside/outside expiry without rejection',async()=>{const f=await issued(true);await new Promise(r=>setTimeout(r,60));const r=await h.offer.apply(await h.auth(),write,await f.q({action:'evaluate'}));assert.equal(r.result.expired,true);assert.equal(r.result.rejected,false);assert.equal((await state(f)).state,'Propuesta en preparación');const g=await issued();assert.equal((await h.offer.apply(await h.auth(),write,await g.q({action:'evaluate'}))).result.pending,false);});
test('R05 uncertainty evidence and missing source',async()=>{const f=await issued(),at=now(),e=await proof(f,`offer:uncertain:${f.versionId}`,f.content.scope,at);assert.equal((await h.offer.apply(await h.auth(),write,await f.q({action:'evaluate',at,evidenceId:e}))).result.pending,true);await reject(await f.q({action:'evaluate',evidenceId:uid()}));});
test('R06 act revalidation preserves original',async()=>{const f=await issued(true);await new Promise(r=>setTimeout(r,60));const before=(await observed(f)).issuance,at=now(),actId=uid(),reviewEvidence=await reviews(f,actId,at,f.content.scope,'accept');const r=await h.offer.apply(await h.auth(),write,await f.q({action:'revalidate',at,actId,actKind:'accept',reviewEvidence}));assert.equal(r.result.acceptanceCreated,false);assert.deepEqual((await observed(f)).issuance,before);});
test('R07 each material review guard',async()=>{const f=await issued(),at=now(),actId=uid(),reviewEvidence=await reviews(f,actId,at);for(const aspect of ['prices','availability','conditions','capacity']){const e={...reviewEvidence};delete e[aspect];await reject(await f.q({action:'revalidate',at,actId,actKind:'send',reviewEvidence:e}),true);}const e=await proof(f,`offer:review:${f.versionId}:${actId}:send:prices`,f.content.scope,at,'candidate');await reject(await f.q({action:'revalidate',at,actId,actKind:'send',reviewEvidence:{...reviewEvidence,prices:e}}));});
test('R08 exact act scope/time/version revalidation',async()=>{const f=await issued(true);await new Promise(r=>setTimeout(r,60));const q=await sending(f);await h.offer.apply(await h.auth(),write,{...q,action:'revalidate'});for(const change of [{actId:uid()},{at:new Date(Date.parse(q.at)+1).toISOString()},{coverage:f.mid},{versionId:uid()},{actKind:'accept' as const}]) await reject({...q,...change,operationId:uid(),expectedRevision:q.expectedRevision+1});});
test('R09 no silent reissue/new validity',async()=>{const f=await fixture(),x=await issue(f);await reject({...x.q,operationId:uid(),expectedRevision:3,issuance:{...x.q.issuance!,days:30}});await reject({...x.q,operationId:uid(),expectedRevision:3,issuance:{...x.q.issuance!,issuedAt:now()}});});
test('R10 new condition requires T01 replacement retains v1',async()=>{const f=await issued(),v1=await h.proposal.read(await h.auth(),read,f.proposalId,'internal',f.versionId),old=(await observed(f)).issuance;const p=await f.q();await h.proposal.apply(await h.auth(),write,{...f.c,operationId:uid(),expectedRevision:p.expectedRevision,expectedOpportunityRevision:p.expectedOpportunityRevision,baseVersionId:f.versionId,reviewed:true,content:{...f.content,terms:{...f.content.terms,version:'H2006 T2',text:'H2006 new offered validity: 3 days'}}});const versionId=uid();await h.proposal.apply(await h.auth(),write,{...f.c,content:undefined,action:'fix',operationId:uid(),versionId,expectedRevision:p.expectedRevision+1});const v2=await h.proposal.read(await h.auth(),read,f.proposalId,'internal',versionId) as any;assert.equal(v2.replaces_version_id,f.versionId);assert.deepEqual(await h.proposal.read(await h.auth(),read,f.proposalId,'internal',f.versionId),v1);assert.deepEqual((await observed(f)).issuance,old);await reject(await f.q({action:'send',actId:uid()}));});
test('R11 intent not sent or received',async()=>{const f=await issued(),r=await h.offer.apply(await h.auth(),write,await f.q());assert.equal(r.result.sent,false);assert.equal(r.result.pendingExternal,true);assert.equal((await state(f)).state,'Propuesta en preparación');});
test('R12 real manual send exact commercial effects',async()=>{const f=await issued(),q=await sending(f),r=await h.offer.apply(await h.auth(),write,q);assert.equal(r.result.sent,true);assert.equal(r.result.received,false);assert.equal(r.result.acceptanceCreated,false);assert.equal((await state(f)).state,'Propuesta enviada');assert.equal((await observed(f)).events.filter((e:any)=>e.action==='send').length,1);});
test('R13 every send guard invalidated',async()=>{const f=await issued(),q=await sending(f);for(const change of [{factId:uid()},{communicationId:uid()},{recipientId:uid()},{channel:'email'},{versionId:uid()},{at:new Date(Date.parse(q.at)-1).toISOString()},{coverage:f.mid},{expectedRevision:999},{opportunityId:uid()},{actId:uid()}])await reject({...q,...change,operationId:uid()},true);for(const aspect of ['prices','availability','conditions','capacity']){const r={...q.reviewEvidence};delete r[aspect];await reject({...q,operationId:uid(),reviewEvidence:r});}});
test('R14 approval/intention/AI not send',async()=>{const f=await issued(),q=await sending(f);await reject({...q,origin:'ai'});await reject({...q,factId:undefined});await reject({...q,authorizationRef:uid()} as OfferCommand,true);});
test('R15 expired no review blocks',async()=>{const f=await issued(true);await new Promise(r=>setTimeout(r,60));await reject(await sending(f));});
test('R16 expired act review permits exact send not extension',async()=>{const f=await issued(true);await new Promise(r=>setTimeout(r,60));const original=(await observed(f)).issuance,q=await sending(f);await h.offer.apply(await h.auth(),write,{...q,action:'revalidate'});await h.offer.apply(await h.auth(),write,{...q,operationId:uid(),expectedRevision:q.expectedRevision+1});assert.deepEqual((await observed(f)).issuance,original);});
test('R17 unknown material costs retained not zero',async()=>{const f=await issued(false,true),v=await h.proposal.read(await h.auth(),read,f.proposalId,'internal') as any;assert.equal(v.economics[0].components[0].cost,null);assert.ok(v.economics[0].blockers.length>0);await h.offer.apply(await h.auth(),write,await f.q());const q=await sending(f);await h.offer.apply(await h.auth(),write,q);assert.equal((await state(f)).state,'Propuesta enviada');const a=await fixture(true);await assert.rejects(h.proposal.apply(await h.auth(),write,{...a.c,operationId:uid(),expectedRevision:2,expectedOpportunityRevision:2,baseVersionId:a.versionId,reviewed:true,content:{...a.content,modalities:[{...a.content.modalities[0]!,definitive:true}]}}).then(async()=>h.proposal.apply(await h.auth(),write,{...a.c,action:'fix',operationId:uid(),versionId:uid(),content:undefined,expectedRevision:3})));});
test('R18 rejection modality no whole loss',async()=>{const f=await issued(),r=await h.offer.apply(await h.auth(),write,await rejection(f));assert.equal(r.result.opportunityLost,false);assert.equal(r.result.partId,f.mid);assert.equal((await state(f)).state,'Propuesta en preparación');await h.offer.apply(await h.auth(),write,await sending(f,f.secondMid));assert.equal((await state(f)).state,'Propuesta enviada');assert.equal((await observed(f)).events.filter((e:any)=>e.action==='reject').length,1);});
test('R19 rejection version/line retains exact history',async()=>{for(const kind of ['version','line'] as const){const f=await issued(),q=await rejection(f,kind);await h.offer.apply(await h.auth(),write,q);assert.equal((await observed(f)).events[1].result.partKind,kind);}});
test('R20 each rejection guard removed',async()=>{const f=await issued(),q=await rejection(f);for(const change of [{lossReason:''},{partId:uid()},{partKind:undefined},{recipientId:uid()},{evidenceId:uid()},{communicationId:uid()},{channel:'email'},{coverage:f.content.scope},{at:now()}])await reject({...q,...change,operationId:uid()},true);});
test('R21 read/silence/nonselection never acceptance/rejection',async()=>{const f=await issued();for(const action of ['read','silence','accept','reject_without_selection'])await reject({...await f.q(),action:action as never},true);const r=await rejection(f);await reject({...r,evidenceId:uid()});assert.equal((await observed(f)).events.filter((e:any)=>e.action==='reject').length,0);});
test('R22 rejected scope cannot reuse without current review',async()=>{const f=await issued();await h.offer.apply(await h.auth(),write,await rejection(f,'version'));const q=await sending(f);await reject(q);await h.offer.apply(await h.auth(),write,{...q,action:'revalidate'});await h.offer.apply(await h.auth(),write,{...q,operationId:uid(),expectedRevision:q.expectedRevision+1});assert.equal((await observed(f)).events.filter((e:any)=>e.action==='reject').length,1);});
test('R23 no positive Acceptance/Ganada/economy operations',async()=>{const f=await issued();for(const action of ['accept','win','book','pay','confirm_provider'])await reject({...await f.q(),action:action as never},true);await assert.rejects(h.runtime`update crm_private.b03_opportunities set state='Aceptada / Ganada' where opportunity_id=${f.opp.targetId}::uuid`);});
test('R24 direct ordinary SQL denies update/delete/insert',async()=>{for(const role of ['crm_h0_runtime','anon','authenticated']){const sql=h.connect(role);for(const table of ['b03_offer_issuances','b03_offer_operations','b03_offer_history']){await assert.rejects(sql.unsafe(`delete from crm_private.${table}`),/permission denied/);await assert.rejects(sql.unsafe(`insert into crm_private.${table} default values`),/permission denied/);await assert.rejects(sql.unsafe(`update crm_private.${table} set admin_scope='FORGED'`),/permission denied/);}}});
test('R25 FORCE RLS ownership and minimum ACL',async()=>{const rows=await h.observer`select c.relname,c.relrowsecurity,c.relforcerowsecurity,c.relowner::regrole::text owner from pg_class c where c.relname in ('b03_offer_issuances','b03_offer_operations','b03_offer_history')`;assert.equal(rows.length,3);assert.ok(rows.every(r=>r.relrowsecurity&&r.relforcerowsecurity&&r.owner==='crm_h0_f2_owner'));assert.equal((await h.observer`select rolsuper or rolbypassrls bad from pg_roles where rolname='crm_h0_runtime'`)[0]!.bad,false);});
test('R26 absent context no writes',async()=>{const before=await snap();await assert.rejects(h.runtime.unsafe('select crm_api.offer_apply(null,null,null,null,null)'));assert.deepEqual(await snap(),before);});
test('R27 forged scope or signature no writes',async()=>{const f=await issued(),q=await f.q(),before=await snap();await assert.rejects(rawApply({...q},true));await assert.rejects(rawApply({...q},false,true));assert.deepEqual(await snap(),before);});
test('R28 disabled actor read/write/replay denied',async()=>{const f=await issued(),q=await f.q();await h.offer.apply(await h.auth(),write,q);const before=await snap();await h.admin`update crm_private.crm_actors set enabled=false where actor_id=${h.actorId}::uuid`;try{await assert.rejects(h.offer.apply(await h.auth(),write,q));await assert.rejects(observed(f));}finally{await h.admin`update crm_private.crm_actors set enabled=true where actor_id=${h.actorId}::uuid`;}assert.deepEqual(await snap(),before);});
test('R29 no provisioned actor and ordinary API role',async()=>{const f=await issued(),stranger=await verifyAuth({verify:async()=>({subject:uid(),sessionId:uid(),passwordVerified:true,mfaVerified:true})},uid());await assert.rejects(h.offer.apply(stranger,write,await f.q()));await assert.rejects(h.connect('authenticated').unsafe('select crm_api.offer_apply(null,null,null,null,null)'));});
test('R30 prewrite fault atomic',async()=>{const f=await fixture(),at=now(),e=await proof(f,`offer:issue:${f.versionId}:${at}:7`,f.content.scope,at);await fault('b03_offer_issuances',await f.q({action:'issue',at,evidenceId:e,issuance:{issuedAt:at,limits:[]}}));});
test('R31 late fault rolls back send/Commercial/history/result',async()=>{const f=await issued();await fault('b03_offer_history',await sending(f));});
test('R32 lost postcommit response and equivalent replay',async()=>{const f=await issued(),q=await sending(f);await h.offer.apply(await h.auth(),write,q);try{throw new Error('H2006_LOST_RESPONSE');}catch{}const before=await snap(),r=await h.offer.apply(await h.auth(),write,q);assert.equal(r.replayed,true);assert.deepEqual(await snap(),before);await reject({...q,operationId:uid(),expectedRevision:q.expectedRevision+1,expectedOpportunityRevision:q.expectedOpportunityRevision+1});});
test('R33 changed replay is conflict',async()=>{const f=await issued(),q=await f.q();await h.offer.apply(await h.auth(),write,q);await reject({...q,reason:'DIFFERENT'});});
test('R34 concurrent sessions both orders one winner',async()=>{const access=new H0005PostgresAdapter(h.connect('crm_h0_runtime'),h.f1,h.f2),first=await verifyAuth({verify:async()=>({subject:h.subject,passwordVerified:true,mfaVerified:true})},uid()),session=(await access.establish(first)).sessionId,auth=await verifyAuth({verify:async()=>({subject:h.subject,sessionId:session,passwordVerified:true,mfaVerified:true})},uid()),other=new H2005OfferAdapter(h.connect('crm_h0_runtime'),h.f1,h.f2);for(const reverse of [false,true]){const f=await issued(),a=await f.q(),b={...a,operationId:uid(),reason:'other authorized session'};const calls=reverse?[other.apply(auth,write,b),h.offer.apply(await h.auth(),write,a)]:[h.offer.apply(await h.auth(),write,a),other.apply(auth,write,b)];const results=await Promise.allSettled(calls);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);}});
test('R35 independent connection sees append history/results/exact refs',async()=>{const f=await issued(),q=await sending(f);await h.offer.apply(await h.auth(),write,q);const rows=await h.observer`select o.action,o.event,h.normative_ids from crm_private.b03_offer_operations o join crm_private.b03_offer_history h on h.history_id=o.operation_id where o.version_id=${f.versionId}::uuid order by o.recorded_at`;assert.equal(rows.length,2);assert.equal(rows[1]!.event.factId,q.factId);assert.deepEqual(rows[1]!.normative_ids,['SM-PV-03','SM-OP-05','SM-CO-04']);});
test('R36 migration preserves every prior row and ACL',()=>{assert.deepEqual(oldAfter,oldBefore);assert.deepEqual(aclAfter,aclBefore);});
test('R37 empty full chain native PG17',async()=>{await h.admin.unsafe('create database crm_h2_006_empty owner crm_h0_migration');const m=h.connect('crm_h0_migration','crm_h2_006_empty'),boot=h.connect('h2_bootstrap','crm_h2_006_empty');await h.applyChain(m,boot,offerMigration);assert.equal((await m`select count(*)::int n from crm_private.b03_offer_operations`)[0]!.n,0);assert.equal((await m`select count(*)::int n from pg_class where relname='b03_offer_issuances' and relforcerowsecurity`)[0]!.n,1);});
test('R38 published migrations bytewise unchanged',()=>{assert.equal(execFileSync('git',['diff','bccdc93e23a8f34d21e7358503dfdf3489302993','--','supabase/migrations/202609*','supabase/migrations/20261001081941_h2_commercial_progress.sql','supabase/migrations/20261001115235_h2_proposal_versions.sql'],{encoding:'utf8'}),'');});
test('R39 dimensions separate and no future objects',async()=>{assert.equal((await h.observer`select count(*)::int n from crm_private.b03_opportunities where state='Aceptada / Ganada'`)[0]!.n,0);assert.equal((await h.observer`select count(*)::int n from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='crm_private' and c.relkind='r' and (relname like '%acceptance%' or relname like '%booking%' or relname like '%payment%' or relname like '%refund%' or relname like '%provider_confirmation%')`)[0]!.n,0);});

test('R40 aggregate send must include rejected modality review',async()=>{const f=await issued();await h.offer.apply(await h.auth(),write,await rejection(f,'modality'));const q=await sending(f);await reject(q);await h.offer.apply(await h.auth(),write,{...q,action:'revalidate'});await h.offer.apply(await h.auth(),write,{...q,operationId:uid(),expectedRevision:q.expectedRevision+1});assert.equal((await observed(f)).events.filter((e:any)=>e.action==='reject').length,1);});

test('R41 attributable rejection requires responsible context identity',async()=>{const f=await issued();const stranger=uid();await h.identities.apply(await h.auth(),write,{action:'create_entity',operationId:uid(),targetId:stranger,kind:'contact',expectedVersion:0,sourceRef:'H2006 other identity',evidenceRef:'H2006 other identity proof',reason:'H2006 other context',verified:true,displayName:'H2006 UNRELATED'});await reject(await rejection({...f,recipientId:stranger}));});

test('R42 missing/null/typed revisions cannot bypass concurrency',async()=>{const f=await issued();const q=await f.q();for(const change of [{expectedRevision:null},{expectedOpportunityRevision:null},{expectedRevision:'3'},{expectedOpportunityRevision:'2'}])await reject({...q,...change} as unknown as OfferCommand,true);});
