import{cancelFixture}from'../support/h4-booking-preparation-f23-fixtures.ts';import{requirementFixture}from'../support/h4-requirement-fixtures.ts';import{H4001RequirementAdapter}from'../../src/infrastructure/postgres/h4-requirement-adapter.ts';
import{test}from'node:test';import assert from'node:assert/strict';import{randomUUID as uid}from'node:crypto';
import{isolatedReality,read,write}from'../support/h4-reality-isolated.ts';import{realityFixture}from'../support/h4-reality-fixtures.ts';import{observeReality}from'../support/h4-reality-observation.ts';import{H0005PostgresAdapter}from'../../src/infrastructure/postgres/h0-005-adapter.ts';import{H4022OperationalRealityAdapter}from'../../src/infrastructure/postgres/h4-operational-reality-adapter.ts';import{H4020BookingPreparationAdapter}from'../../src/infrastructure/postgres/h4-booking-preparation-adapter.ts';import{H4011ModificationAdapter}from'../../src/infrastructure/postgres/h4-modification-adapter.ts';import{H4009ConfirmationAdapter}from'../../src/infrastructure/postgres/h4-confirmation-adapter.ts';import{H4003IncidentAdapter}from'../../src/infrastructure/postgres/h4-incident-adapter.ts';import{modificationFixture}from'../support/h4-modification-fixtures.ts';import{incidentFixture}from'../support/h4-incident-fixtures.ts';import{verifyAuth}from'../../src/application/verified-auth.ts';
test('H4-023 real roots F2 both independent sessions both orders and overlapping business units',async t=>{const h=await isolatedReality('crm_h4023_races',58501);try{const login=h.connect('crm_h0_runtime'),access=new H0005PostgresAdapter(login,h.f1,h.f2),subject=h.subject,sessionId=(await access.establish(await verifyAuth({verify:async()=>({subject,passwordVerified:true,mfaVerified:true})},uid()))).sessionId,auth2=()=>verifyAuth({verify:async()=>({subject,sessionId,passwordVerified:true,mfaVerified:true})},uid()),sql2=h.connect('crm_h0_runtime'),real2=new H4022OperationalRealityAdapter(sql2,h.f1,h.f2),prep2=new H4020BookingPreparationAdapter(sql2,h.f1,h.f2),mod2=new H4011ModificationAdapter(sql2,h.f1,h.f2),conf2=new H4009ConfirmationAdapter(sql2,h.f1,h.f2),inc2=new H4003IncidentAdapter(sql2,h.f1,h.f2),req2=new H4001RequirementAdapter(sql2,h.f1,h.f2);
 for(const order of [[0,1],[1,0]])for(const kind of ['same','key-material','disjoint','overlap','cancel','finish','finish-change','confirmation','HA','preparation','incident','requirement','preparation-finish','preparation-cancel','HA-change','incident-perform']as const)await t.test(kind+' order '+order,async()=>{const r=await realityFixture(h,!['HA','HA-change'].includes(kind));const dataFor=async(start:string,amount:string)=>{const q=await r.command('perform');return r.attest({...q,data:{...q.data,scopes:[{...r.scopes[0]!,start,amount}]}});};
 let q=await r.command('start'),other:any,jobs:(()=>Promise<unknown>)[]=[];let m:any,i:any,a:any,req:any;
 if(['same','key-material','disjoint','overlap','cancel','finish'].includes(kind)){await r.run(q);q=await dataFor('0','0.5');if(kind==='same')other={...q,operationId:uid()};if(kind==='key-material')other=await r.attest({...q,data:{...q.data,scopes:[{...r.scopes[0]!,amount:'0.75'}]}});if(kind==='disjoint')other=await dataFor('0.5','0.5');if(kind==='overlap')other=await dataFor('0.25','0.5');if(kind==='finish')other=await r.command('finish');
 if(kind==='cancel'){m=await modificationFixture(h,r.f.conf);await m.run(await m.request([{id:m.partId,scope:m.scope,expectedScopeRevision:1,desired:{cancelled:true},aspects:['cancellation'],dependencies:[]}]));await m.run(await m.evaluate());await m.run(await m.approve());q=await r.exceptional();q=await r.attest({...q,data:{...q.data,scopes:[{...r.scopes[0]!,amount:'0.5'}]}});other=await m.apply();}
 }
 if(kind==='confirmation')other=await r.f.conf.review();if(kind==='preparation')other=await r.f.command();if(kind==='HA'){q=await r.exceptional();q=await r.attest({...q,origin:'ai'});a=await r.approval(q);other=await r.f.command();}
 if(kind==='incident'){i=await incidentFixture(h,undefined,{bookingId:r.f.bid,serviceId:r.scopes[0]!.serviceId});await h.incidents.apply(await h.auth(),write,await i.detect());q=await r.command('start');other=await i.resolve();}

 if(kind==='finish-change'){await r.run(await r.command('start'));await r.run(await r.command('perform'));m=await modificationFixture(h,r.f.conf);const c=r.f.o.detail.services[0]!.contributions[0]!;await m.run(await m.request([{id:m.partId,scope:{kind:'contribution',id:c.id,serviceId:r.scopes[0]!.serviceId},expectedScopeRevision:1,desired:{quantity:'2'},aspects:['quantity'],dependencies:[]}]));await m.run(await m.evaluate());await m.run(await m.approve());q=await r.command('finish');other=await m.apply();}
 if(kind==='requirement'){req=await requirementFixture(h,{bookingId:r.f.bid,b:{detail:r.f.o.detail}}as any);other=await req.need();q=await r.command('start');}
 if(kind==='preparation-finish'){await r.run(await r.command('start'));await r.run(await r.command('perform'));q=await r.command('finish');other=await r.f.command();}
 if(kind==='preparation-cancel'){m=await cancelFixture(h,r.f);q=await m.command();other=await r.f.command();}
 if(kind==='HA-change'){m=await modificationFixture(h,r.f.conf);await m.run(await m.request());await m.run(await m.evaluate());await m.run(await m.approve());q=await r.exceptional();q=await r.attest({...q,origin:'ai'});a=await r.approval(q);other=await m.apply();}
 if(kind==='incident-perform'){await r.run(await r.command('start'));i=await incidentFixture(h,undefined,{bookingId:r.f.bid,serviceId:r.scopes[0]!.serviceId});const j=await incidentFixture(h,undefined,{bookingId:r.f.bid,serviceId:r.scopes[0]!.serviceId});await h.incidents.apply(await h.auth(),write,await i.detect());await h.incidents.apply(await h.auth(),write,await j.detect());q=await r.command('perform');other=await i.resolve();}
 jobs=[async()=>kind==='preparation-cancel'?h.modifications.apply(await h.auth(),write,q as any):a?a.execute():r.run(q),async()=>kind==='cancel'||kind==='HA-change'||kind==='finish-change'?mod2.apply(await auth2(),write,other):kind==='confirmation'?conf2.apply(await auth2(),write,other):kind==='preparation'||kind==='HA'||kind==='preparation-finish'||kind==='preparation-cancel'?prep2.apply(await auth2(),write,other):kind==='incident'||kind==='incident-perform'?inc2.apply(await auth2(),write,other):kind==='requirement'?req2.apply(await auth2(),write,other):real2.apply(await auth2(),write,other)];
 const result=await observeReality(h,r.f.bid,jobs,order,[h.sessionId,sessionId],kind==='finish-change'?'opportunity':'preparation');const first=result[0]!,second=result[1]!,by=(n:number)=>result[order.indexOf(n)]!;console.log('H4-023 NORMATIVE RACE',JSON.stringify({kind,order,result}));
 if(kind==='same'){assert.ok(first.ok&&second.ok);assert.equal((await r.see())!.facts.length,1);assert.equal((await r.see())!.scopes[0]!.performed,'0.5');}
 if(kind==='key-material'){assert.equal(first.ok,true);assert.equal(second.ok,false);assert.match(second.error!,/E2/);assert.equal((await r.see())!.facts.length,1);}
 if(kind==='disjoint'||kind==='overlap'){assert.equal(first.ok,true);assert.equal(second.ok,false);const retry=await dataFor(kind==='disjoint'?(order[0]===0?'0.5':'0'):(order[0]===0?'0.25':'0'),kind==='disjoint'?'0.5':'0.5');if(kind==='disjoint'){await r.run(retry);assert.equal((await r.see())!.scopes[0]!.performed,'1');}else await assert.rejects(r.run(retry),/OVERLAP/);}
 if(kind==='cancel'){assert.equal(by(1).ok,true);assert.equal(by(0).ok,order[0]===0);assert.equal((await r.see())!.phase,'En curso');if(order[0]===0){assert.equal((await r.see())!.scopes[0]!.performed,'0.5');assert.equal((await r.see())!.scopes[0]!.cancelled,'0.5');}}
 if(kind==='finish'){assert.equal(by(0).ok,true);assert.equal(by(1).ok,false);assert.equal((await r.see())!.phase,'En curso');await assert.rejects(r.run(await r.command('finish')),/FINISH/);}
 if(kind==='confirmation'){assert.equal(by(1).ok,true);assert.equal(by(0).ok,order[0]===0);assert.equal((await r.f.conf.assess())!.usable,false);assert.equal((await r.f.see())!.phase,order[0]===0?'En curso':'En confirmación con proveedores');}
 if(kind==='preparation'){assert.equal(by(0).ok,true);assert.equal(by(1).ok,order[0]===1);assert.equal((await r.f.see())!.phase,'En curso');}
 if(kind==='HA'){assert.equal(by(0).ok,true);assert.equal(by(1).ok,order[0]===1);assert.equal((await r.see())!.phase,'En curso');assert.equal((await r.f.conf.assess()),null);}
 if(kind==='incident'){assert.equal(by(1).ok,true);assert.equal(by(0).ok,order[0]===0);assert.equal((await r.see())!.incidents.length,0);if(order[0]===1){await r.run(await r.command('start'));}assert.equal((await r.see())!.phase,'En curso');}

 if(kind==='finish-change'){assert.equal(by(0).ok,true);assert.equal(by(1).ok,false);assert.match(by(1).error!,/PRIOR_PERFORMANCE/);assert.equal((await r.see())!.phase,'Finalizada');}
 if(kind==='requirement'){assert.equal(by(1).ok,true);assert.equal(by(0).ok,order[0]===0);assert.equal((await r.f.see())!.phase,order[0]===0?'En curso':'Parcialmente confirmada');}
 if(kind==='preparation-finish'){assert.equal(by(0).ok,true);assert.equal(by(1).ok,false);assert.equal((await r.f.see())!.phase,'Finalizada');}
 if(kind==='preparation-cancel'){assert.equal(by(0).ok,true);assert.equal(by(1).ok,order[0]===1);assert.equal((await r.f.see())!.phase,'Cancelada');}
 if(kind==='HA-change'){assert.equal(by(0).ok,order[0]===0);assert.equal(by(1).ok,order[0]===1);if(order[0]===1){await assert.rejects(a.execute(),/CONFLICT|DENIED/);assert.equal((await r.see())!.facts.length,0);}else assert.equal((await r.see())!.phase,'En curso');}
 if(kind==='incident-perform'){assert.equal(by(1).ok,true);assert.equal(by(0).ok,order[0]===0);assert.equal((await r.see())!.incidents.length,1);assert.equal((await r.f.see())!.phase,'En curso');}
 });await t.test('independent Bookings proceed while another actual root remains blocked',async()=>{const a=await realityFixture(h),b=await realityFixture(h),aq=await a.command('start'),bq=await b.command('start'),barrier=h.connect('crm_h0_migration');await barrier.unsafe('begin');await barrier`select pg_advisory_xact_lock(hashtextextended(${'booking-preparation:'+a.f.bid},0))`;const pending=a.run(aq);try{let waiting:any[]=[];for(let k=0;k<250;k++){waiting=await h.admin`select pid,backend_xid::text xid,pg_blocking_pids(pid) blockers from pg_stat_activity where usename='crm_h0_runtime'and wait_event_type='Lock'`;if(waiting.length)break;await new Promise(r=>setTimeout(r,10));}assert.equal(waiting.length,1);let completed=false;const work=real2.apply(await auth2(),write,bq).then(x=>{completed=true;return x;});await Promise.race([work,new Promise(resolve=>setTimeout(resolve,2000))]);assert.equal(completed,true,'independent scope progresses before blocked root release');assert.equal((await h.admin`select count(*)n from pg_stat_activity where pid=${waiting[0].pid} and wait_event_type='Lock'`)[0]!.n,'1');console.log('H4-023 INDEPENDENT ROOT',JSON.stringify({blocked:a.f.bid,proceeded:b.f.bid,waiting,sessions:[h.sessionId,sessionId]}));await work;}finally{await barrier.unsafe('rollback');await pending;await barrier.end();}});await sql2.end();await login.end();}finally{await h.close();}});
