// Frozen normative oracle 60848d0. Literals, not product-generated expected.
import assert from 'node:assert/strict';import {test} from 'node:test';import {randomUUID as uid,createHash} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';import {spawnSync} from 'node:child_process';
import {isolatedSuplido,suplidoMigration,write,read} from '../support/h3-suplido-isolated.ts';
import {suplidoFixture,syntheticDocumentaryFacts,type SuplidoCommand} from '../support/h3-suplido-fixtures.ts';
import {H3009SuplidoAdapter} from '../../src/infrastructure/postgres/h3-suplido-adapter.ts';
import {assessSuplido} from '../../src/domain/managed-client-funds.ts';
import {verifyAuth} from '../../src/application/verified-auth.ts';
import {issueTrustedContext} from '../../src/application/trusted-context.ts';
import {canonicalCommercial} from '../../src/domain/commercial-progress.ts';
import {createF1Issuer,encodeF1Fields} from '../../src/infrastructure/postgres/f1-codec.ts';
import {createF2Issuer} from '../../src/infrastructure/postgres/f2-codec.ts';
import {postgresF1Binding} from '../../src/infrastructure/postgres/transaction.ts';
import {classifyServerEvent} from '../../src/application/verified-interaction.ts';
type H=Awaited<ReturnType<typeof isolatedSuplido>>;type F=Awaited<ReturnType<typeof suplidoFixture>>;
const tables=['b05_suplidos','b05_suplido_operations','b05_suplido_revisions'];
async function forged(h:H,input:SuplidoCommand,kind:'f1'|'f2'|'scope'){
 const auth=await h.auth();return h.runtime.begin(async tx=>{
  const row=(await tx`select actor_id::text,admin_scope,access_generation::text,epoch_id::text from crm_api.f2_lookup(${auth.subject}::uuid,${auth.sessionId!}::uuid)`)[0]!;
  const binding=await postgresF1Binding(tx),q=encodeF1Fields(['CRM-H3-SUPLIDO1',canonicalCommercial(input)]);
  const context=issueTrustedContext({identityId:'h3-suplido-server',identityKind:'technical',purpose:'h1-evidence',scope:kind==='scope'?'SYNTHETIC-OTHER-SCOPE':row.admin_scope,requestId:uid(),serverTime:new Date().toISOString()});
  const human=createF2Issuer(h.f2)(auth,{actorId:row.actor_id,scope:row.admin_scope,accessGeneration:row.access_generation,sessionId:auth.sessionId!,epochId:row.epoch_id},binding,'evidence_write',q,write);
  const tech=createF1Issuer(h.f1)(context,binding,'C03',q,{resource:'evidence',action:'write_evidence'});
  return tx.unsafe('select crm_api.suplido_apply($1,$2,$3,$4,$5)',[human.payload,kind==='f2'?Buffer.alloc(32):human.mac,tech.payload,kind==='f1'?Buffer.alloc(32):tech.mac,q]);
 });
}

async function apply(h:H,q:SuplidoCommand){return h.suplidos.apply(await h.auth(),write,q);}
async function staged(h:H){const f=await suplidoFixture(h);await apply(h,await f.open());return f;}
async function view(f:F):Promise<any>{return f.see();}
async function deny(h:H,f:F,q:SuplidoCommand){const before=await f.see();await assert.rejects(apply(h,q));assert.deepEqual(await f.see(),before);}
async function change(h:H,f:F,q:SuplidoCommand,changes:Record<string,unknown>){return f.attest({...q,...changes} as SuplidoCommand);}
async function inventory(target:H){return {tables:await target.observer`select c.oid,c.relname,c.relowner,c.relacl::text,c.relrowsecurity,c.relforcerowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('crm_private','crm_api','crm_f1','crm_f2') and c.relkind in ('r','p','v','S') order by c.oid`,funcs:await target.observer`select p.oid,p.proname,p.proowner,p.proacl::text,pg_get_functiondef(p.oid) def from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('crm_private','crm_api','crm_f1','crm_f2') order by p.oid`,policies:await target.observer`select oid,polname,polrelid,polroles::text,pg_get_expr(polqual,polrelid) qual,pg_get_expr(polwithcheck,polrelid) ck from pg_policy order by oid`,triggers:await target.observer`select oid,pg_get_triggerdef(oid) def from pg_trigger order by oid`,roles:await target.observer`select rolname,rolsuper,rolinherit,rolcreaterole,rolcreatedb,rolcanlogin,rolbypassrls from pg_roles order by rolname`};}
async function economy(h:H){const ts=(await h.observer`select tablename from pg_tables where schemaname='crm_private' and (tablename like 'b05_%' or tablename like 'b04_%') and tablename not in ('b05_provider_invoices','b05_invoice_operations','b05_invoice_revisions','b05_invoice_documents','b05_suplidos','b05_suplido_operations','b05_suplido_revisions') order by tablename`).map(r=>r.tablename as string);return snapshots(h,ts);}
async function snapshots(h:H,names:string[]){const out:Record<string,unknown>={};for(const t of names)out[t]=(await h.observer.unsafe(`select coalesce(jsonb_agg(x order by x::text),'[]'::jsonb) value from (select to_jsonb(t) x from crm_private.${t} t) z`))[0]!.value;return out;}
async function trigger(h:H,table:string,deferred=false){await h.admin.unsafe(`create function crm_private.h3010_fault() returns trigger language plpgsql as $$begin raise exception 'SYNTHETIC_SUPLIDO_FAULT';end$$;create ${deferred?'constraint ':''}trigger h3010_fault ${deferred?'after':'before'} insert on crm_private.${table} ${deferred?'deferrable initially deferred ':''}for each row execute function crm_private.h3010_fault()`);}
async function clear(h:H,table:string){await h.admin.unsafe(`drop trigger h3010_fault on crm_private.${table};drop function crm_private.h3010_fault()`);}

async function race(h:H,f:F,q:SuplidoCommand,same=false){const sql=h.connect('crm_h0_runtime'),other=new H3009SuplidoAdapter(sql,h.f1,h.f2);const results=await Promise.allSettled([apply(h,q),other.apply(await h.auth(),write,same?q:{...q,operationId:uid()})]);assert.equal(results.filter(x=>x.status==='fulfilled').length,same?2:1);assert.equal((await f.see())!.revision,q.expectedRevision+1);}
async function attachFunds(h:H,f:F,amount='300.00'){const q=await f.assign(amount);await apply(h,await f.fundsCommand([q.allocationId!]));return q;}
async function seededResolved(h:H,f:F){
 // Migration fixture only: synthetic historical assessment, never an API command nor a real payment.
 const s=await view(f),op=uid(),q=await f.command('evaluate'),rev=s.revision+1;
 const next={...s,revision:rev,status:'Documentalmente resuelto',evaluation:{state:'Documentalmente resuelto',syntheticOnly:true,basis:syntheticDocumentaryFacts()},pending:[],followUpIds:[]};delete next.history;
 await h.migration.begin(async tx=>{
  await tx`insert into crm_private.b05_suplido_operations values(${op}::uuid,${f.suplidoId}::uuid,${h.scope},${h.actorId}::uuid,'SYNTHETIC-TEST-DOUBLE',${JSON.stringify({id:f.suplidoId,replayed:false,result:next})}::jsonb,${rev},clock_timestamp())`;
  await tx`insert into crm_private.b05_suplido_revisions values(${f.suplidoId}::uuid,${rev},${h.scope},${op}::uuid,'evaluate',${JSON.stringify({syntheticOnly:true})}::jsonb,${JSON.stringify(s)}::jsonb,${JSON.stringify(next)}::jsonb,${h.actorId}::uuid,${q.evidenceId}::uuid,'SYNTHETIC prior documentary assessment','SYNTHETIC C02 test double',${f.at}::timestamptz,clock_timestamp())`;
 });return next;
}
const cases:Record<string,(h:H)=>Promise<void>>={
 R01:async h=>{const f=await staged(h),s=await view(f);assert.equal(s.status,'Gestión abierta');for(const k of ['funds','invoice','payment','reconciliation','mandate'])assert.equal(s.components[k],null);assert.deepEqual(s.pending,['payment','outgoing_reconciliation','invoice']);assert.equal(s.followUpIds.length,2);},
 R02:async h=>{const f=await suplidoFixture(h);await deny(h,f,await change(h,f,await f.open(),{basis:{...f.basis,clientId:null}}));},
 R03:async h=>{const f=await suplidoFixture(h);await deny(h,f,await change(h,f,await f.open(),{basis:{...f.basis,providerRevisionId:null}}));},
 R04:async h=>{const f=await suplidoFixture(h);for(const serviceId of [null,uid()])await deny(h,f,await change(h,f,await f.open(),{basis:{...f.basis,serviceId}}));},
 R05:async h=>{const f=await suplidoFixture(h);for(const amounts of [{expectedAmount:null,confirmedAmount:null},{expectedAmount:1,confirmedAmount:null},{expectedAmount:'1.001',confirmedAmount:null},{expectedAmount:null}])await deny(h,f,await change(h,f,await f.open(),{basis:{...f.basis,...amounts}}));},
 R06:async h=>{const f=await suplidoFixture(h);await deny(h,f,await change(h,f,await f.open(),{sourceRef:null}));await deny(h,f,await change(h,f,await f.open(),{basis:{...f.basis,sourceRef:null}}));},
 R07:async h=>{const f=await suplidoFixture(h,'700.00','500.00','internal'),before=await economy(h);await deny(h,f,await f.open());assert.deepEqual(await economy(h),before);assert.equal((await h.observer`select nature from crm_private.b04_services where service_id=${f.basis.serviceId}::uuid`)[0]!.nature,'internal');},
 R08:async h=>{const f=await staged(h),s=await view(f);assert.equal(s.components.amount.expected,'500.00');assert.equal(s.components.amount.confirmed,null);assert.equal(s.basisApplied.provider.revision_id,f.basis.providerRevisionId);assert.equal(s.basisApplied.client.identity_id,f.basis.clientId);},
 R09:async h=>{const f=await staged(h),before=(await view(f)).components;await apply(h,await f.command('component',{component:'amount',confirmedAmount:'600.00'}));const s=await view(f);assert.equal(s.components.amount.expected,'500.00');assert.equal(s.components.amount.confirmed,'600.00');for(const k of ['funds','invoice','payment','reconciliation','mandate'])assert.deepEqual(s.components[k],before[k]);assert.equal(s.history[0].after.components.amount.confirmed,null);},
 R10:async h=>{const f=await staged(h);for(const action of ['mandate_from_acceptance','mandate_from_funds','mandate_from_human_approval'])await deny(h,f,await change(h,f,await f.command('evaluate'),{action}));assert.equal((await view(f)).components.mandate,null);},
 R11:async h=>{const f=await staged(h),m=await f.mandate();await apply(h,await f.command('component',{component:'mandate',mandate:m}));const s=await view(f);assert.deepEqual(s.components.mandate,m);assert.equal(s.components.payment,null);assert.equal(s.status,'Gestión abierta');},
 R12:async h=>{const f=await staged(h),m=await f.mandate();for(const k of ['id','version','content','acceptanceRef','acceptedBy','acceptedAt','evidenceId'])await deny(h,f,await change(h,f,await f.command('component',{component:'mandate',mandate:m}),{mandate:{...m,[k]:null}}));await deny(h,f,await f.command('component',{component:'mandate',mandate:{...m,evidenceId:f.funds.sourceEvidenceId}}));},
 R13:async h=>{const f=await staged(h);await attachFunds(h,f);const s=await view(f);assert.deepEqual(s.funding,{due:'500.00',identified:'300.00',remaining:'200.00',excess:'0.00',ownFinancingInferred:false});assert.equal(s.components.funds.assigned,'300.00');assert.equal(s.components.funds.availableForPurpose,'300.00');assert.equal(s.status,'Gestión abierta');},
 R14:async h=>{const f=await staged(h);await attachFunds(h,f,'600.00');const s=await view(f);assert.equal(s.funding.excess,'100.00');assert.equal(s.funding.remaining,'0.00');assert.equal((await f.funds.see()).summary.assigned,'600.00');assert.equal(s.components.payment,null);},
 R15:async h=>{const f=await staged(h),q=await f.funds.assign('300.00','0.00',{bookingId:f.bookingId,purpose:'managed_client_funds',serviceId:f.basis.serviceId,reference:'SYNTHETIC expected plan'});await h.allocations.apply(await h.auth(),write,{...await f.funds.attest({...q,action:'plan'})});await apply(h,await f.fundsCommand([q.allocationId!]));const s=await view(f);assert.equal(s.components.funds.assigned,'0.00');assert.equal(s.components.funds.usable,'0.00');assert.equal(s.funding.remaining,'500.00');},
 R16:async h=>{const f=await staged(h),g=await staged(h),q=await g.assign();await deny(h,f,await f.fundsCommand([q.allocationId!]));const fee=await f.assign('200.00','0.00','fee');await deny(h,f,await f.fundsCommand([fee.allocationId!]));},
 R17:async h=>{const f=await staged(h),q=await attachFunds(h,f);await apply(h,await f.fundsCommand([q.allocationId!]));assert.equal((await view(f)).components.funds.assigned,'300.00');await deny(h,f,await f.fundsCommand([q.allocationId!,q.allocationId!]));},
 R18:async h=>{const f=await staged(h),q=await f.assign(),q2=await f.assign('200.00','300.00');await apply(h,await f.fundsCommand([q.allocationId!,q2.allocationId!]));const inc=await f.funds.discrepancy(4,'0.00','100.00');await h.payments.apply(await h.auth(),write,inc);await apply(h,await f.command('evaluate'));const s=await view(f);assert.equal(s.components.funds.assigned,'500.00');assert.equal(s.components.funds.usable,'400.00');assert.equal(s.components.funds.suspended,'100.00');},
 R19:async h=>{const f=await staged(h);await attachFunds(h,f);await f.assign('200.00','300.00','fee');const s=await view(f),ledger=await f.funds.see();assert.equal(s.components.funds.assigned,'300.00');assert.equal((ledger.summary.byPurpose as any).fee.assigned,'200.00');assert.equal(ledger.summary.assigned,'500.00');assert.equal(s.components.mandate,null);assert.equal(s.components.payment,null);},
 R20:async h=>{const f=await staged(h);await attachFunds(h,f);await apply(h,await f.command('evaluate'));const s=await view(f);assert.ok(s.pending.includes('invoice'));assert.ok(s.pending.includes('payment'));assert.equal(s.components.invoice,null);assert.equal((await f.funds.see()).summary.consumed,'0.00');},
 R21:async h=>{const f=await staged(h),before=(await view(f)).components;await apply(h,await f.attachInvoice());const s=await view(f);assert.equal(s.components.invoice.status,'Vinculada');for(const k of ['funds','payment','reconciliation','mandate','amount'])assert.deepEqual(s.components[k],before[k]);},
 R22:async h=>{for(const stage of [2,3]){const f=await staged(h);await apply(h,await f.attachInvoice(stage));await apply(h,await f.command('evaluate'));assert.ok((await view(f)).pending.includes('invoice'));assert.equal((await view(f)).components.invoice.status,stage===2?'Recibida':'Revisada');}},
 R23:async h=>{const f=await staged(h),g=await staged(h);await g.attachInvoice();await deny(h,f,await f.command('component',{component:'invoice',invoiceId:g.invoice.invoiceId}));const other=await h.cat('provider',{name:'SYNTHETIC wrong provider'});const bad=await f.attachInvoice(1,{providerRevisionId:other.revision});await deny(h,f,bad);},
 R24:async h=>{const facts=syntheticDocumentaryFacts(),a=assessSuplido({...facts,invoice:null});assert.equal(a.state,'Gestión abierta');assert.ok(a.pending.includes('invoice'));const f=await staged(h);await deny(h,f,await change(h,f,await f.command('evaluate'),{providerPayment:facts.payment}));const s=await view(f);assert.ok(s.pending.includes('invoice'));assert.equal(s.followUpIds.length,2);},
 R25:async h=>{const f=await staged(h);await apply(h,await f.attachInvoice());await apply(h,await f.command('evaluate'));const s=await view(f);assert.equal(s.status,'Gestión abierta');assert.ok(s.pending.includes('payment'));assert.equal(s.components.payment,null);assert.equal((await f.funds.see()).summary.consumed,'0.00');},
 R26:async h=>{const f=await staged(h);const before=(await view(f)).components;await apply(h,await f.command('component',{component:'reconciliation',reconciliationId:f.funds.p.reconciliationId!}));const s=await view(f);assert.equal(s.components.reconciliation.direction,'incoming');assert.equal(s.components.reconciliation.supplierPaymentVerified,false);for(const k of ['funds','payment','invoice','mandate','amount'])assert.deepEqual(s.components[k],before[k]);assert.ok(s.pending.includes('outgoing_reconciliation'));},
 R27:async h=>{const f=await staged(h),g=await staged(h);await deny(h,f,await f.command('component',{component:'reconciliation',reconciliationId:g.funds.p.reconciliationId!}));const i=await f.funds.discrepancy(4,'0.00','100.00');await h.payments.apply(await h.auth(),write,i);await deny(h,f,await f.command('component',{component:'reconciliation',reconciliationId:f.funds.p.reconciliationId!}));},
 R28:async()=>{const f=syntheticDocumentaryFacts(),r=assessSuplido(f);assert.equal(r.state,'Documentalmente resuelto');assert.deepEqual(r.pending,[]);assert.deepEqual(r.basis,f);},
 R29:async()=>{const f=syntheticDocumentaryFacts();for(const key of ['invoice','payment','reconciliation','amount'])assert.equal(assessSuplido({...f,[key]:null}).state,'Gestión abierta');assert.equal(assessSuplido({...f,invoice:{...f.invoice!,linked:false}}).state,'Gestión abierta');for(const aspect of ['clientId','providerId','serviceId'])assert.equal(assessSuplido({...f,invoice:{...f.invoice!,[aspect]:'OTHER'}}).state,'Gestión abierta');},
 R30:async()=>{const f=syntheticDocumentaryFacts();for(const key of ['invoice','payment','reconciliation'] as const){const result=assessSuplido({...f,[key]:{...f[key],amount:'499.99'}});assert.equal(result.state,'Gestión abierta');assert.ok(result.pending.includes(key));assert.equal(f[key]!.amount,'500.00');}},
 R31:async h=>{const f=await staged(h);const before=await economy(h);assert.equal(assessSuplido(syntheticDocumentaryFacts()).state,'Documentalmente resuelto');for(const action of ['close_booking','commercial_closure','operational_closure','economic_closure','provider_confirmation'])await deny(h,f,await change(h,f,await f.command('evaluate'),{action}));assert.deepEqual(await economy(h),before);},
 R32:async h=>{const f=await staged(h);await attachFunds(h,f);await seededResolved(h,f);const before=(await view(f)).components;await apply(h,await f.command('discrepancy',{component:'invoice',incidentId:uid()}));const s=await view(f);assert.equal(s.status,'Revisión');assert.ok(s.pending.includes('difference:invoice'));assert.deepEqual(s.components.funds,before.funds);assert.equal(s.history[2].after.status,'Documentalmente resuelto');},
 R33:async h=>{const f=await staged(h),a=await f.assign(),b=await f.assign('200.00','300.00');await apply(h,await f.fundsCommand([a.allocationId!,b.allocationId!]));await apply(h,await f.attachInvoice());const before=(await view(f)).components.invoice;await apply(h,await f.command('discrepancy',{component:'funds',incidentId:uid(),affectedAllocationIds:[a.allocationId!]}));const s=await view(f);assert.equal(s.funding.identified,'200.00');assert.deepEqual(s.components.invoice,before);assert.equal(s.components.funds.assigned,'500.00');},
 R34:async h=>{for(const component of ['payment','reconciliation','obligation'] as const){const f=await staged(h);await attachFunds(h,f);const before=(await view(f)).components;await apply(h,await f.command('discrepancy',{component,incidentId:uid()}));assert.deepEqual((await view(f)).components,before);assert.ok((await view(f)).pending.includes('difference:'+component));}},
 R35:async h=>{const f=await staged(h),q=await f.command('discrepancy',{component:'invoice',incidentId:uid()});for(const k of ['sourceRef','reason','evidenceId','component','incidentId']){const bad=await change(h,f,q,{[k]:null});await deny(h,f,k==='evidenceId'?{...bad,evidenceId:null} as never:bad);}await deny(h,f,await f.command('discrepancy',{component:'funds',incidentId:uid()}));},
 R36:async h=>{const f=await staged(h),i=uid();await apply(h,await f.command('discrepancy',{component:'invoice',incidentId:i}));await apply(h,await f.command('resolve',{component:'invoice',incidentId:i}));const s=await view(f);assert.equal(s.status,'Gestión abierta');assert.equal(s.differences[0].resolved,true);assert.equal(s.history[1].after.differences[0].resolved,false);assert.ok(s.differences[0].resolutionEvidenceId);},
 R37:async h=>{const f=await staged(h);await apply(h,await f.attachInvoice());for(const action of ['mark_provider_paid','execute_programmed_payment'])await deny(h,f,await change(h,f,await f.command('evaluate'),{action}));await deny(h,f,await f.command('component',{component:'payment'}));assert.equal((await view(f)).components.payment,null);},
 R38:async h=>{const f=await staged(h);await attachFunds(h,f);for(const action of ['recognize_own_revenue','recognize_own_cost','recognize_managed_total_as_fee'])await deny(h,f,await change(h,f,await f.command('evaluate'),{action}));},
 R39:async h=>{const f=await staged(h);await attachFunds(h,f);for(const action of ['derive_contractual_right','refund_from_balance','cancel_from_paid_amount'])await deny(h,f,await change(h,f,await f.command('evaluate'),{action}));},
 R40:async h=>{const f=await staged(h);await apply(h,await f.attachInvoice());for(const action of ['emit_legal_invoice','assign_fiscal_number','create_fiscal_series','validate_vat','override_P16_with_human_approval'])await deny(h,f,await change(h,f,await f.command('evaluate'),{action}));},
 R41:async h=>{const f=await staged(h),a=await f.assign(),invoice=await f.attachInvoice(),before=await economy(h);await apply(h,await f.fundsCommand([a.allocationId!]));await apply(h,invoice);await apply(h,await f.command('component',{component:'reconciliation',reconciliationId:f.funds.p.reconciliationId!}));await apply(h,await f.command('evaluate'));assert.deepEqual(await economy(h),before);},
 R42:async h=>{const f=await suplidoFixture(h),q=await f.open();await apply(h,q);const before=await f.see();assert.equal((await apply(h,q)).replayed,true);assert.deepEqual(await f.see(),before);},
 R43:async h=>{const f=await staged(h),q=await f.open(),r=await apply(h,q);assert.equal(r.replayed,true);assert.equal(r.id,f.suplidoId);assert.equal((await view(f)).history.length,1);},
 R44:async h=>{const f=await suplidoFixture(h),q=await f.open();await apply(h,q);await deny(h,f,{...q,reason:'different material'});await deny(h,f,await change(h,f,await f.open(),{basis:{...f.basis,expectedAmount:'501.00'}}));},
 R45:async h=>{const f=await staged(h),a=await f.assign(),commands=[await f.fundsCommand([a.allocationId!])];for(const q of commands){await apply(h,q);const s=await f.see();assert.equal((await apply(h,q)).replayed,true);assert.deepEqual(await f.see(),s);}for(const action of ['evaluate','discrepancy'] as const){const q=await f.command(action,action==='discrepancy'?{component:'invoice',incidentId:uid()}:{});await apply(h,q);const s=await f.see();assert.equal((await apply(h,q)).replayed,true);assert.deepEqual(await f.see(),s);}assert.equal((await h.observer`select count(*)::int n from crm_private.b07_pending_tasks where identity->>'causeId'=${f.suplidoId}`)[0]!.n,2);},
 R46:async h=>{const f=await staged(h),q=await f.command('evaluate');await apply(h,q);const fake=await verifyAuth({verify:async()=>({subject:uid(),sessionId:uid(),passwordVerified:true,mfaVerified:true})},uid());await assert.rejects(h.suplidos.apply(fake,write,q));await deny(h,f,{...q,bookingId:uid()});},
 R47:async h=>{const f=await staged(h),q=await f.command('evaluate');await apply(h,q);const s=await f.see();assert.equal((await apply(h,q)).replayed,true);assert.deepEqual(await f.see(),s);},
 R48:async h=>{for(const same of [true,false]){const f=await suplidoFixture(h),q=await f.open();if(same)await race(h,f,q,true);else{const other=new H3009SuplidoAdapter(h.connect('crm_h0_runtime'),h.f1,h.f2);const results=await Promise.all([apply(h,q),other.apply(await h.auth(),write,{...q,operationId:uid()})]);assert.equal(results[0]!.id,results[1]!.id);}assert.equal((await view(f)).history.length,1);}const f=await suplidoFixture(h),q=await f.open(),second=new H3009SuplidoAdapter(h.connect('crm_h0_runtime'),h.f1,h.f2),q2=await f.attest({...q,operationId:uid(),suplidoId:uid()});const r=await Promise.all([apply(h,q),second.apply(await h.auth(),write,q2)]);assert.equal(r[0]!.id,r[1]!.id);assert.equal((await view(f)).history.length,1);},
 R49:async h=>{for(const reverse of [false,true]){const f=await staged(h),q=await f.assign(),a=await f.fundsCommand([q.allocationId!]),b=await f.fundsCommand([q.allocationId!]),other=new H3009SuplidoAdapter(h.connect('crm_h0_runtime'),h.f1,h.f2);const first=reverse?b:a,last=reverse?a:b,r=await Promise.allSettled([apply(h,first),other.apply(await h.auth(),write,last)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal((await view(f)).components.funds.assigned,'300.00');}},
 R50:async h=>{const f=await staged(h),q=await f.attachInvoice();await race(h,f,q);assert.equal((await view(f)).components.invoice.status,'Vinculada');},
 R51:async h=>{const f=await staged(h);await race(h,f,await f.command('evaluate'));const g=await staged(h);await race(h,g,await g.command('evaluate'),true);},
 R52:async h=>{const f=await staged(h);await attachFunds(h,f);await apply(h,await f.attachInvoice());const q=await f.command('evaluate'),sql=h.connect('crm_h0_migration');let unlock!:()=>void,ready!:()=>void;const wait=new Promise<void>(r=>unlock=r),locked=new Promise<void>(r=>ready=r);const tx=sql.begin(async t=>{await t`select pg_advisory_xact_lock(hashtextextended(${`invoice-root:${f.invoice.invoiceId}`},0))`;await t`select pg_advisory_xact_lock(hashtextextended(${`payment-root:${f.funds.paymentId}`},0))`;ready();await wait;});await locked;
 const pending=apply(h,q);try{let waiting=false;for(let n=0;n<100&&!waiting;n++){waiting=(await h.observer`select exists(select 1 from pg_locks where locktype='advisory' and not granted) x`)[0]!.x;if(!waiting)await new Promise(r=>setTimeout(r,10));}assert.equal(waiting,true);}finally{unlock();}await tx;await pending;
 const corrected=await f.invoice.attest({...await f.invoice.correct(),bookingId:f.bookingId,expectedRevision:4,affectedServiceIds:[f.basis.serviceId],affectedRecipientId:f.basis.clientId,affectedAmount:'500.00'});await h.invoices.apply(await h.auth(),write,corrected);await apply(h,await f.command('evaluate'));assert.ok((await view(f)).pending.includes('invoice'));
 const i=await f.funds.discrepancy(4,'0.00','100.00');await h.payments.apply(await h.auth(),write,i);await apply(h,await f.command('evaluate'));assert.equal((await view(f)).components.funds.usable,'200.00');},
 R53:async h=>{const f=await staged(h),a=await f.command('evaluate'),b=await f.command('discrepancy',{component:'invoice',incidentId:uid()}),other=new H3009SuplidoAdapter(h.connect('crm_h0_runtime'),h.f1,h.f2);const r=await Promise.allSettled([apply(h,a),other.apply(await h.auth(),write,b)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);if((await view(f)).differences.length===0)await apply(h,await f.command('discrepancy',{component:'invoice',incidentId:uid()}));assert.equal((await view(f)).status,'Revisión');},
 R54:async h=>{const f=await staged(h);for(const action of ['component','evaluate','discrepancy','resolve'] as const)await deny(h,f,await f.command(action,{expectedRevision:0,...(action==='component'?{component:'amount' as const,confirmedAmount:'501.00'}:action==='evaluate'?{}:{component:'invoice' as const,incidentId:uid()})}));},
 R55:async h=>{const f=await staged(h),q=await f.command('evaluate'),key='SYNTHETIC-H3010-COMMIT-GATE';await h.admin.unsafe(`create function crm_private.h3010_visible() returns trigger language plpgsql as $$begin if new.suplido_id='${f.suplidoId}'::uuid then perform pg_advisory_xact_lock(hashtextextended('${key}',0));end if;return new;end$$;create trigger h3010_visible after insert on crm_private.b05_suplido_revisions for each row execute function crm_private.h3010_visible()`);
 let unlock!:()=>void,ready!:()=>void;const gate=new Promise<void>(r=>unlock=r),start=new Promise<void>(r=>ready=r),sql=h.connect('crm_h0_migration');const tx=sql.begin(async t=>{await t`select pg_advisory_xact_lock(hashtextextended(${key},0))`;ready();await gate;});await start;const pending=apply(h,q);try{let waiting=false;for(let n=0;n<100&&!waiting;n++){waiting=(await h.observer`select exists(select 1 from pg_locks where locktype='advisory' and not granted) x`)[0]!.x;if(!waiting)await new Promise(r=>setTimeout(r,10));}assert.equal(waiting,true);assert.equal((await h.observer`select max(revision)::int n from crm_private.b05_suplido_revisions where suplido_id=${f.suplidoId}::uuid`)[0]!.n,1);}finally{unlock();}await tx;await pending;await h.admin.unsafe('drop trigger h3010_visible on crm_private.b05_suplido_revisions;drop function crm_private.h3010_visible()');assert.equal((await view(f)).revision,2);},
 R56:async h=>{const f=await suplidoFixture(h);await trigger(h,'b05_suplidos');try{await deny(h,f,await f.open());}finally{await clear(h,'b05_suplidos');}},
 R57:async h=>{const f=await suplidoFixture(h),q=await f.open(),names=[...tables,'b07_pending_tasks','b07_operations','b07_history'],before=await snapshots(h,names);await trigger(h,'b05_suplido_revisions');try{await deny(h,f,q);assert.deepEqual(await snapshots(h,names),before);}finally{await clear(h,'b05_suplido_revisions');}},
 R58:async h=>{const f=await staged(h),q=await f.command('component',{component:'amount',confirmedAmount:'600.00'});await trigger(h,'b05_suplido_revisions');try{await deny(h,f,q);}finally{await clear(h,'b05_suplido_revisions');}},
 R59:async h=>{const f=await staged(h),q=await f.command('evaluate');await trigger(h,'b05_suplido_operations');try{await deny(h,f,q);}finally{await clear(h,'b05_suplido_operations');}},
 R60:async h=>{const f=await staged(h),q=await f.command('discrepancy',{component:'invoice',incidentId:uid()});await trigger(h,'b05_suplido_revisions');try{await deny(h,f,q);}finally{await clear(h,'b05_suplido_revisions');}},
 R61:async h=>{const f=await suplidoFixture(h),q=await f.open(),before=await snapshots(h,[...tables,'b07_pending_tasks','b07_history','b07_operations']);await trigger(h,'b07_history');try{await deny(h,f,q);assert.deepEqual(await snapshots(h,[...tables,'b07_pending_tasks','b07_history','b07_operations']),before);}finally{await clear(h,'b07_history');}},
 R62:async h=>{const f=await staged(h),q=await f.command('evaluate'),before=await snapshots(h,tables);await trigger(h,'b05_suplido_operations',true);try{await deny(h,f,q);assert.deepEqual(await snapshots(h,tables),before);}finally{await clear(h,'b05_suplido_operations');}},
 R63:async h=>{const f=await staged(h),q=await f.command('evaluate');await assert.rejects(h.runtime`select crm_api.suplido_apply(null,null,null,null,null)`);for(const k of ['f1','f2','scope'] as const)await assert.rejects(forged(h,q,k));for(const role of ['anon','authenticated'])await assert.rejects(h.connect(role)`select crm_api.suplido_apply(null,null,null,null,null)`);await assert.rejects(h.suplidos.apply({subject:h.subject} as never,write,q));await assert.rejects(h.suplidos.apply(await h.auth(),classifyServerEvent('background-job'),q));await h.admin`alter table crm_private.crm_actors disable trigger all`;await h.admin`update crm_private.crm_actors set enabled=false where actor_id=${h.actorId}::uuid`;try{await assert.rejects(apply(h,q));}finally{await h.admin`update crm_private.crm_actors set enabled=true where actor_id=${h.actorId}::uuid`;await h.admin`alter table crm_private.crm_actors enable trigger all`;}await deny(h,f,await f.attest(q,'candidate'));await deny(h,f,await change(h,f,q,{origin:'ai'}));},
 R64:async h=>{for(const table of tables){for(const sql of [`insert into crm_private.${table} default values`,`update crm_private.${table} set admin_scope=admin_scope`,`delete from crm_private.${table}`])await assert.rejects(h.runtime.unsafe(sql));await assert.rejects(h.migration.unsafe(`update crm_private.${table} set admin_scope=admin_scope`));}},
 R65:async h=>{const f=await staged(h);assert.equal(await h.suplidos.read(await h.auth(),read,f.suplidoId,uid()),null);for(const k of ['reference','amount','provider','filename','private_ref','otherClientId'])await deny(h,f,await change(h,f,await f.command('evaluate'),{[k]:'SYNTHETIC OTHER'}));await h.admin`alter table crm_private.b05_suplidos disable trigger all`;await h.admin`update crm_private.b05_suplidos set admin_scope='OTHER-SYNTHETIC' where suplido_id=${f.suplidoId}::uuid`;try{assert.equal(await f.see(),null);await assert.rejects(apply(h,await f.command('evaluate')));}finally{await h.admin`update crm_private.b05_suplidos set admin_scope=${h.scope} where suplido_id=${f.suplidoId}::uuid`;await h.admin`alter table crm_private.b05_suplidos enable trigger all`;}},
 R66:async h=>{const files=(await readdir(new URL('../../supabase/migrations/',import.meta.url))).filter(x=>x.endsWith('.sql')).sort();assert.equal(files.filter(x=>x<=suplidoMigration).length,35);for(const file of files.filter(x=>x<suplidoMigration)){assert.equal(await readFile(new URL('../../supabase/migrations/'+file,import.meta.url),'utf8'),spawnSync('git',['show',`2471d044662026d52bf63b7d5064fb924d4f8127:supabase/migrations/${file}`],{encoding:'utf8'}).stdout);}const t=await h.observer`select c.relname,c.relrowsecurity,c.relforcerowsecurity,r.rolname owner from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_roles r on r.oid=c.relowner where n.nspname='crm_private' and c.relname=any(${tables})`;assert.equal(t.length,3);for(const r of t){assert.equal(r.relrowsecurity,true);assert.equal(r.relforcerowsecurity,true);assert.equal(r.owner,'crm_h0_f2_owner');}for(const r of await h.observer`select rolcanlogin,rolbypassrls,rolsuper from pg_roles where rolname in ('crm_h0_f2_owner','crm_h0_f2_executor')`){assert.equal(r.rolcanlogin,false);assert.equal(r.rolbypassrls,false);assert.equal(r.rolsuper,false);}const funcs=await h.observer`select p.proname,p.prosecdef,p.proconfig,has_function_privilege('crm_h0_runtime',p.oid,'EXECUTE') runtime from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.proname like 'suplido_%' and n.nspname in ('crm_api','crm_private')`;assert.equal(funcs.length,6);for(const f of funcs){assert.ok(f.proconfig.includes('search_path=pg_catalog, pg_temp'));assert.equal(f.runtime,['suplido_apply','suplido_read'].includes(f.proname));}assert.equal((await h.observer`select count(*)::int n from pg_policies where tablename=any(${tables})`)[0]!.n,6);assert.equal((await h.observer`select count(*)::int n from pg_trigger tg join pg_class c on c.oid=tg.tgrelid where c.relname=any(${tables}) and tg.tgname='suplido_immutable'`)[0]!.n,3);assert.equal((await h.observer`select count(*)::int n from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where p.proname like 'suplido_%' and n.nspname in ('crm_api','crm_private') and a.grantee=0 and a.privilege_type='EXECUTE'`)[0]!.n,0);},
 R67:async()=>{const h=await isolatedSuplido('crm_h3_010_up',55712,true);try{const f=await suplidoFixture(h),a=await f.assign('300.00');await h.allocations.apply(await h.auth(),write,await f.funds.consume(a,'80.00'));await f.attachInvoice();const doc=(await h.invoices.read(await h.auth(),read,f.invoice.invoiceId,f.bookingId))!.document!,ctx={contextKind:'booking' as const,contextId:f.invoice.bookingId,purpose:'provider-invoice-documentary'},bytes=await h.objects.download(await h.auth(),read,doc.objectVersionId,ctx),catalog=await inventory(h),names=(await h.observer`select tablename from pg_tables where schemaname='crm_private' order by tablename`).map(r=>r.tablename as string),before=await snapshots(h,names);await h.migration.unsafe(await readFile(new URL('../../supabase/migrations/'+suplidoMigration,import.meta.url),'utf8'));assert.deepEqual(await snapshots(h,names),before);const after=await inventory(h);for(const key of ['tables','funcs','policies','triggers'] as const){const ids=new Set(catalog[key].map(r=>r.oid));assert.deepEqual(Array.from(after[key].filter(r=>ids.has(r.oid))),Array.from(catalog[key]));}assert.deepEqual(after.roles,catalog.roles);assert.deepEqual(await h.objects.download(await h.auth(),read,doc.objectVersionId,ctx),bytes);await apply(h,await f.open());await apply(h,await f.fundsCommand([a.allocationId!]));assert.equal((await f.funds.see()).summary.consumed,'80.00');assert.equal((await view(f)).components.funds.availableForPurpose,'220.00');}finally{await h.close();}},
 R68:async()=>{const h=await isolatedSuplido('crm_h3_010_rb',55713,true);try{const before=await inventory(h),sql=await readFile(new URL('../../supabase/migrations/'+suplidoMigration,import.meta.url),'utf8');await assert.rejects(h.migration.unsafe(sql.replace(/commit;\s*$/,"do $$begin raise exception 'SYNTHETIC_MIGRATION_FAULT';end$$;commit;")));await h.migration.unsafe('rollback');assert.deepEqual(await inventory(h),before);assert.equal((await h.observer`select count(*)::int n from pg_tables where tablename=any(${tables})`)[0]!.n,0);}finally{await h.close();}},
 R69:async()=>{const e=await readFile(new URL('../../specs/001-core-crm/expected-TSK-H3-009-010.md',import.meta.url));assert.equal((e.toString().match(/^\|R\d+/gm)??[]).length,69);assert.equal(createHash('sha256').update(e).digest('hex'),createHash('sha256').update(spawnSync('git',['show','60848d0:specs/001-core-crm/expected-TSK-H3-009-010.md']).stdout).digest('hex'));for(const word of ['H3-012','H5-014','H6-005','STOP tras010','Provider Payment solo doble sintético'])assert.ok(e.toString().includes(word));}
};
test('H3-010 independent frozen normative matrix',async t=>{const h=await isolatedSuplido('crm_h3_010',55710);try{for(const [id,run] of Object.entries(cases))await t.test(id,()=>run(h));}finally{await h.close();}});
