/** Independent normative assertions: expected frozen in 88bf5f4; no product decision oracle. */
import {test,before,after} from 'node:test';import assert from 'node:assert/strict';
import {randomUUID as uid} from 'node:crypto';import {readFile,readdir} from 'node:fs/promises';import {spawnSync} from 'node:child_process';
import {isolatedRequirement,requirementMigration,requirementTables as tables,write,read} from '../support/h4-requirement-isolated.ts';
import {requirementFixture,type H} from '../support/h4-requirement-fixtures.ts';
import {invoiceFixture} from '../support/h3-invoice-fixtures.ts';
import {quantityFixture,nominalFixture} from '../support/h2-quantities-fixtures.ts';
import {H4001RequirementAdapter} from '../../src/infrastructure/postgres/h4-requirement-adapter.ts';
import type {RequirementCommand,RequirementBasis} from '../../src/domain/document-requirement.ts';
let h:H,shared:Awaited<ReturnType<typeof invoiceFixture>>;
type F=Awaited<ReturnType<typeof requirementFixture>>;
const apply=async(q:RequirementCommand)=>h.requirements.apply(await h.auth(),write,q);
const fixture=()=>requirementFixture(h,shared);
async function staged(level=1){const f=await fixture();if(level)await apply(await f.need());if(level>=2)await apply(await f.receive());if(level>=3)await apply(await f.review());return f;}
async function snapshots(x:H,names=tables){const out:Record<string,unknown>={};for(const name of names)out[name]=(await x.observer.unsafe(`select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]') d from crm_private.${name} t`))[0]!.d;return out;}
async function inventory(x:H){return {
 tables:Array.from(await x.observer`select c.oid,c.relname,c.relowner,c.relacl,c.relrowsecurity,c.relforcerowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname like 'crm%' and c.relkind in ('r','p') order by c.oid`),
 functions:Array.from(await x.observer`select p.oid,p.proname,p.proowner,p.proacl,p.proconfig,p.prosecdef from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname like 'crm%' order by p.oid`),
 policies:Array.from(await x.observer`select oid,polrelid,polname,polroles,polqual::text,polwithcheck::text from pg_policy order by oid`),
 triggers:Array.from(await x.observer`select oid,tgrelid,tgname,tgfoid,tgenabled from pg_trigger where not tgisinternal order by oid`),
 roles:Array.from(await x.observer`select oid,rolname,rolsuper,rolcanlogin,rolbypassrls,rolcreaterole,rolcreatedb from pg_roles order by oid`)};}
async function deny(q:RequirementCommand){const old=await snapshots(h);await assert.rejects(apply(q));assert.deepEqual(await snapshots(h),old);}
async function change(f:F,basis:RequirementBasis={...f.basis,context:{...f.basis.context,version:'2'}}){return f.command('change',{basis});}
async function fault(table:string,after=false,deferred=false){await h.admin.unsafe(`create function crm_private.h4002_fault() returns trigger language plpgsql as $$begin raise exception 'SYNTHETIC_H4_FAULT';end$$;create ${deferred?'constraint ':''}trigger h4002_fault ${after||deferred?'after':'before'} insert on crm_private.${table} ${deferred?'deferrable initially deferred':''} for each row execute function crm_private.h4002_fault()`);}
async function clear(table:string){await h.admin.unsafe(`drop trigger h4002_fault on crm_private.${table};drop function crm_private.h4002_fault()`);}
async function failed(table:string,q:RequirementCommand,after=false,deferred=false){await fault(table,after,deferred);try{await deny(q);}finally{await clear(table);}}
async function race(q:RequirementCommand,r:RequirementCommand){const second=new H4001RequirementAdapter(h.connect('crm_h0_runtime'),h.f1,h.f2);const results=await Promise.allSettled([apply(q),second.apply(await h.auth(),write,r)]);assert.ok(results.some(x=>x.status==='fulfilled'));return results;}
async function corrected(f:F){const old=(await f.see())!.document!;return f.command('change',{basis:f.basis,document:await f.document({},old.documentId)});}
before(async()=>{h=await isolatedRequirement('crm_h4002',56002);shared=await invoiceFixture(h);});after(async()=>{await h?.close();});
const cases:Record<string,()=>Promise<void>>={
 R01:async()=>{const f=await staged();const s=(await f.see())!;assert.equal(s.status,'Pendiente');assert.equal(s.document,null);assert.equal(s.review,null);assert.equal(s.history.length,1);},
 R02:async()=>{const f=await fixture();await apply(await f.need({basis:{...f.basis,context:{...f.basis.context,value:'unregulated'}}}));assert.equal((await f.see())!.status,'No aplica');},
 R03:async()=>{for(const path of ['rule','sourceRef','purpose','scope','conditionKey']){const f=await fixture(),b=structuredClone(f.basis) as unknown as Record<string,unknown>;if(path==='rule'||path==='scope')delete b[path];else delete (b.rule as Record<string,unknown>)[path];await deny(await f.need({basis:b as unknown as RequirementBasis}));}},
 R04:async()=>{const f=await staged();assert.deepEqual((await f.see())!.basis.rule.requiredFields,[]);assert.equal(shared.b.detail.participants.length,0);assert.equal((await h.observer`select count(*)::int n from crm_private.b04_participants where booking_id=${f.bookingId}::uuid`)[0]!.n,0);},
 R05:async()=>{const b=await quantityFixture(h),q=await nominalFixture(h,b);await h.booking.apply(await h.auth(),write,q);const house=b.detail.services[2]!,n1=house.nights[0]!,n2=house.nights[1]!;
 const f=await fixture(),basis:RequirementBasis={...f.basis,rule:{...f.basis.rule,scopeKind:'night'},scope:{serviceId:house.id,nightId:n2.id,action:'prepare'}};await apply(await f.need({bookingId:q.bookingId,basis}));await apply(await f.command('no_apply',{bookingId:q.bookingId,expectedRevision:1,context:{...basis.context,value:'unregulated'}}));await apply(await f.command('change',{bookingId:q.bookingId,expectedRevision:2,basis:{...basis,context:{...basis.context,version:'N2-changed-date'}}}));
 const ns=await h.observer`select n.night_id,sum(c.attendees)::int n from crm_private.b04_nights n join crm_private.b04_night_occupancies o using(night_id) join crm_private.b04_contributions c using(contribution_id) where c.booking_id=${q.bookingId}::uuid group by n.night_id`;assert.equal(ns.find(x=>x.night_id===n1.id)!.n,12);assert.equal(ns.find(x=>x.night_id===n2.id)!.n,10);assert.equal((await h.observer`select count(*)::int n from crm_private.b04_participants where booking_id=${q.bookingId}::uuid`)[0]!.n,4);const assignments=await h.observer`select night_id from crm_private.b04_assignments where service_id=${house.id}::uuid`;assert.equal(assignments.length,4);assert.ok(assignments.every(x=>x.night_id===n1.id));assert.ok(!JSON.stringify(q.detail).includes('rooms'));},
 R06:async()=>{for(const documentType of ['DNI','lista nominal','permiso','declaración','bono','factura','condiciones','otro configurado']){const f=await fixture();await apply(await f.need({basis:{...f.basis,rule:{...f.basis.rule,documentType}}}));assert.equal((await f.see())!.basis.rule.documentType,documentType);}},
 R07:async()=>{const f=await staged(2),s=(await f.see())!;assert.equal(s.status,'Recibido');assert.equal(s.review,null);assert.ok((s.document as unknown as {provenance:unknown}).provenance);assert.equal((await h.observer`select state from crm_private.b07_object_versions where version_id=${s.document!.objectVersionId}::uuid`)[0]!.state,'stored');},
 R08:async()=>{const f=await staged();await deny(await f.command('receive',{document:{documentId:uid(),objectVersionId:uid(),ruleVersion:'V1',purpose:f.basis.rule.purpose,coverage:[f.basis.scope]}}));await deny(await f.command('receive'));},
 R09:async()=>{const f=await staged(2);await deny(await f.attest({...await f.receive((await f.see())!.document!),status:'Revisado'} as RequirementCommand));assert.equal((await f.see())!.status,'Recibido');},
 R10:async()=>{const f=await staged(2),s=await f.see(),q={action:'receive' as const,operationId:uid(),taskId:uid(),expectedRevision:0,identity:{causeKind:'review',causeId:f.requirementId,contextKind:'other',contextId:f.requirementId,scopeRef:'SYNTHETIC documentary followup',relatedKind:null,relatedId:null,effect:'review-only'},material:{title:'SYNTHETIC pending documentary work',deadline:{kind:'unknown' as const,reason:'unverified'},priority:{kind:'pending' as const,reason:'unverified'},sourceRef:'SYNTHETIC',sourceVersion:'1',triggerRef:'manual' as const,triggerVersion:'1'},reason:'SYNTHETIC'};await h.tasks.apply(await h.auth(),write,q);await assert.rejects(h.tasks.apply(await h.auth(),write,{...q,action:'complete',operationId:uid(),expectedRevision:1} as never));assert.deepEqual(await f.see(),s);},
 R11:async()=>{const f=await staged(2);const s1=await h.requirements.evaluate(await h.auth(),read,f.bookingId,f.basis.scope,f.basis.rule.purpose);assert.equal(s1.allowed,false);assert.ok(s1.pending.some(x=>x.requirementId===f.requirementId&&x.missing==='review'));const s2=await h.requirements.evaluate(await h.auth(),read,f.bookingId,{...f.basis.scope,serviceId:shared.b.detail.services[1]!.id},f.basis.rule.purpose);assert.equal(s2.allowed,true);assert.equal(s2.pending.length,0);},
 R12:async()=>{const f=await staged(3),s=(await f.see())!;assert.equal(s.status,'Revisado');assert.ok(s.review!.actorId);assert.ok(s.review!.evidenceId);assert.equal((await h.requirements.evaluate(await h.auth(),read,f.bookingId,f.basis.scope,f.basis.rule.purpose)).pending.some(x=>x.requirementId===f.requirementId),false);},
 R13:async()=>{const f=await staged(2);await apply(await f.review({checks:{content:false,version:true,scope:true,purpose:true}}));assert.equal((await f.see())!.status,'Incidencia');assert.deepEqual((await f.see())!.review!.differences,['content']);},
 R14:async()=>{const f=await staged();await apply(await f.receive(await f.document({ruleVersion:'V0'})));await apply(await f.review());assert.equal((await f.see())!.status,'Incidencia');assert.deepEqual((await f.see())!.review!.differences,['version']);},
 R15:async()=>{const f=await staged();await apply(await f.receive(await f.document({coverage:[{...f.basis.scope,serviceId:shared.b.detail.services[1]!.id}]})));await apply(await f.review());assert.deepEqual((await f.see())!.review!.differences,['scope']);},
 R16:async()=>{const f=await staged();await apply(await f.receive(await f.document({purpose:'different-authorized-purpose'})));await apply(await f.review());assert.deepEqual((await f.see())!.review!.differences,['purpose']);},
 R17:async()=>{const f=await staged(2);await deny(await f.command('review'));await deny(await f.attest(await f.review(),'candidate'));for(const key of ['content','version','scope','purpose']){const q=await f.review();const checks={...q.checks} as Record<string,unknown>;delete checks[key];await deny(await f.attest({...q,checks} as RequirementCommand));}},
 R18:async()=>{const f=await staged(2);await apply(await f.review({checks:{content:false,version:true,scope:true,purpose:true}}));await apply(await f.review());assert.equal((await f.see())!.status,'Revisado');assert.equal(((await f.see())!.history[2]!.after as {status:string}).status,'Incidencia');},
 R19:async()=>{for(const level of [1,2,3,4]){const f=await staged(Math.min(level,3));if(level===4){const x=await staged(2);await apply(await x.review({checks:{content:false,version:true,scope:true,purpose:true}}));await apply(await x.command('no_apply',{context:{...x.basis.context,value:'unregulated'}}));assert.equal((await x.see())!.status,'No aplica');}else{await apply(await f.command('no_apply',{context:{...f.basis.context,value:'unregulated'}}));assert.equal((await f.see())!.status,'No aplica');assert.equal((await f.see())!.history.length,level+1);}}},
 R20:async()=>{const f=await staged(2);await deny(await f.command('no_apply',{context:f.basis.context}));await deny(await f.attest({...await f.command('no_apply',{context:f.basis.context}),humanApprovalId:uid()} as RequirementCommand));assert.equal((await f.see())!.status,'Recibido');},
 R21:async()=>{const f=await staged(3),old=(await f.see())!;await apply(await change(f,{...f.basis,rule:{...f.basis.rule,version:'V2',requiredFields:['new-required-scope']}}));const s=(await f.see())!;assert.equal(s.status,'Pendiente');assert.equal(s.document,null);assert.deepEqual(s.history[2]!.after,old.history[2]!.after);assert.equal((s.history[2]!.after as {basis:RequirementBasis}).basis.rule.version,'V1');},
 R22:async()=>{const f=await staged(3),document=(await f.see())!.document!;await apply(await f.command('change',{basis:{...f.basis,rule:{...f.basis.rule,version:'V2',requiredFields:['changed-content']}},document:{documentId:document.documentId,objectVersionId:document.objectVersionId,ruleVersion:document.ruleVersion,purpose:document.purpose,coverage:document.coverage}}));assert.equal((await f.see())!.status,'Recibido');await apply(await f.review());assert.deepEqual((await f.see())!.review!.differences,['version']);},
 R23:async()=>{const f=await staged(3),other=await staged(3),old=await other.see(),scope={...f.basis.scope,serviceId:shared.b.detail.services[1]!.id};await apply(await f.command('change',{basis:{...f.basis,scope},document:await f.document({coverage:[scope]})}));assert.equal((await f.see())!.status,'Recibido');assert.deepEqual(await other.see(),old);},
 R24:async()=>{const f=await staged(3);await apply(await f.command('change',{basis:{...f.basis,context:{...f.basis.context,version:'2'}},discrepancy:'SYNTHETIC scope discrepancy'}));assert.equal((await f.see())!.status,'Incidencia');},
 R25:async()=>{const f=await staged(3);await deny(await f.command('change',{basis:f.basis}));await deny(await f.attest({...await change(f),reason:''}));await deny(await f.attest({...await change(f),sourceRef:''}));},
 R26:async()=>{const f=await staged(3),old=(await f.see())!,bytes=await h.objects.download(await h.auth(),read,old.document!.objectVersionId!,{contextKind:'booking',contextId:f.bookingId,purpose:'provider-invoice-documentary'});await apply(await corrected(f));const s=(await f.see())!;assert.equal(s.status,'Recibido');assert.equal(s.review,null);assert.deepEqual(s.history[2]!.after,old.history[2]!.after);assert.deepEqual(await h.objects.download(await h.auth(),read,old.document!.objectVersionId!,{contextKind:'booking',contextId:f.bookingId,purpose:'provider-invoice-documentary'}),bytes);assert.equal((await h.observer`select corrects_id from crm_private.b07_records where record_id=${s.document!.documentId}::uuid`)[0]!.corrects_id,old.document!.documentId);},
 R27:async()=>{const f=await staged(3),g=await fixture();const basis={...g.basis,scope:{...g.basis.scope,serviceId:shared.b.detail.services[1]!.id}};await apply(await g.need({basis}));const d=(await f.see())!.document!;await apply(await g.receive({documentId:d.documentId,objectVersionId:d.objectVersionId,ruleVersion:d.ruleVersion,purpose:d.purpose,coverage:d.coverage}));await apply(await g.review());assert.equal((await g.see())!.status,'Incidencia');},
 R28:async()=>{const f=await staged(),g=await fixture(),scope={...g.basis.scope,serviceId:shared.b.detail.services[1]!.id};await apply(await g.need({basis:{...g.basis,scope}}));const d=await f.document({coverage:[f.basis.scope,scope]});await apply(await f.receive(d));await apply(await g.receive(d));await apply(await f.review());await apply(await g.review());assert.equal((await f.see())!.status,'Revisado');assert.equal((await g.see())!.status,'Revisado');},
 R29:async()=>{const f=await staged(2);await deny(await f.attest({...await f.review(),recommendation:'Alta'} as RequirementCommand));assert.equal((await f.see())!.status,'Recibido');},
 R30:async()=>{const f=await staged(2),p=await h.requirements.evaluate(await h.auth(),read,f.bookingId,f.basis.scope,f.basis.rule.purpose);const own=p.pending.find(x=>x.requirementId===f.requirementId)!;assert.deepEqual(Object.keys(own).sort(),['missing','requirementId','scope']);for(const forbidden of ['documentId','objectVersionId','private_ref','actorId','filename','cost','participantName','admin_scope'])assert.ok(!JSON.stringify(p).includes(forbidden));},
 R31:async()=>{const sql=await readFile(new URL('../../supabase/migrations/'+requirementMigration,import.meta.url),'utf8'),ts=await readFile(new URL('../../src/domain/document-requirement.ts',import.meta.url),'utf8');for(const forbidden of ['interval','delete from','audio','retention','consent','public_url'])assert.ok(!sql.includes(forbidden));assert.ok(!ts.includes('extractedData'));assert.ok(sql.includes("d.material->>'relation'<>'original'"));},
 R32:async()=>{const f=await staged();const q=await f.need({requirementId:uid()});const r=await apply(q);assert.equal(r.id,f.requirementId);assert.equal((await f.see())!.history.length,1);assert.equal((await apply(q)).id,f.requirementId);},
 R33:async()=>{const f=await staged(2),d=(await f.see())!.document!;await apply(await f.receive({documentId:d.documentId,objectVersionId:d.objectVersionId,ruleVersion:d.ruleVersion,purpose:d.purpose,coverage:d.coverage}));assert.equal((await f.see())!.history.length,2);},
 R34:async()=>{const f=await fixture(),q=await f.need();await apply(q);await apply(q);assert.equal((await f.see())!.history.length,1);},
 R35:async()=>{const f=await fixture(),q=await f.need();await apply(q);await deny({...q,reason:'different material'});},
 R36:async()=>{const f=await staged(3);await apply(await f.review());assert.equal((await f.see())!.history.length,3);},
 R37:async()=>{const f=await staged();const context={...f.basis.context,value:'unregulated'};await apply(await f.command('no_apply',{context}));await apply(await f.command('no_apply',{context}));assert.equal((await f.see())!.history.length,2);},
 R38:async()=>{const f=await fixture(),q=await f.need();await apply(q);const s=await f.see();const result=await apply(q);assert.equal(result.replayed,true);assert.deepEqual(await f.see(),s);},
 R39:async()=>{const f=await staged(),g=await staged(),d1=await f.document(),d2=await g.document();assert.notEqual(d1.documentId,d2.documentId);assert.notEqual(d1.objectVersionId,d2.objectVersionId);await apply(await f.receive(d1));await apply(await g.receive(d2));assert.notEqual((await f.see())!.document!.documentId,(await g.see())!.document!.documentId);},
 R40:async()=>{const f=await fixture(),q=await f.need(),r=await f.need({requirementId:uid()});const rs=await race(q,r);assert.equal(rs.filter(x=>x.status==='fulfilled').length,2);assert.equal((await f.see())!.history.length,1);assert.equal((await h.observer`select count(*)::int n from crm_private.b07_requirements where initial_basis->'rule'->>'id'=${f.basis.rule.id}`)[0]!.n,1);},
 R41:async()=>{const f=await staged(),d=await f.document(),q=await f.receive(d),r=await f.receive(d),rs=await race(q,r);assert.equal(rs.filter(x=>x.status==='fulfilled').length,1);assert.equal((await f.see())!.history.length,2);assert.equal((await h.observer`select count(*)::int n from crm_private.b07_requirement_documents where requirement_id=${f.requirementId}::uuid`)[0]!.n,1);},
 R42:async()=>{const f=await staged(2),rs=await race(await f.review(),await f.review({checks:{content:false,version:true,scope:true,purpose:true}}));assert.equal(rs.filter(x=>x.status==='fulfilled').length,1);assert.equal((await f.see())!.history.length,3);},
 R43:async()=>{const f=await staged(3);await race(await f.review(),await change(f));const s=(await f.see())!;assert.equal(s.status,'Pendiente');assert.equal(s.review,null);assert.equal(s.history.length,4);},
 R44:async()=>{const f=await staged();await apply(await f.command('no_apply',{context:{...f.basis.context,value:'unregulated'}}));await race(await f.command('no_apply',{context:{...f.basis.context,value:'unregulated'}}),await change(f));assert.equal((await f.see())!.status,'Pendiente');},
 R45:async()=>{const f=await staged(3),rs=await race(await corrected(f),await corrected(f));assert.equal(rs.filter(x=>x.status==='fulfilled').length,1);assert.equal((await f.see())!.history.length,4);},
 R46:async()=>{const f=await staged(2);await deny(await f.review({expectedRevision:1}));assert.equal((await f.see())!.status,'Recibido');},
 R47:async()=>{const f=await fixture();await failed('b07_requirements',await f.need());},
 R48:async()=>{const f=await fixture();await failed('b07_requirements',await f.need(),true);},
 R49:async()=>{const f=await staged();await failed('b07_requirement_documents',await f.receive(),true);},
 R50:async()=>{const f=await staged(2);await failed('b07_requirement_revisions',await f.review(),true);},
 R51:async()=>{const f=await staged(2);await failed('b07_requirement_revisions',await f.review({checks:{content:false,version:true,scope:true,purpose:true}}));},
 R52:async()=>{const f=await staged(2);await failed('b07_requirement_revisions',await f.command('no_apply',{context:{...f.basis.context,value:'unregulated'}}));},
 R53:async()=>{const f=await staged(3);await failed('b07_requirement_revisions',await change(f));},
 R54:async()=>{const f=await fixture();await failed('b07_requirement_operations',await f.need(),true,true);},
 R55:async()=>{for(const name of ['requirement_read','requirement_apply'])await assert.rejects(h.runtime.unsafe(`select crm_api.${name}('fake'::bytea,'fake'::bytea,'fake'::bytea,'fake'::bytea,'fake'::bytea)`));},
 R56:async()=>{for(const mode of ['actor','session']){const u=await isolatedRequirement('crm_h4002_'+mode,mode==='actor'?56005:56006);try{const f=await requirementFixture(u);await u.requirements.apply(await u.auth(),write,await f.need());const q=await f.need();if(mode==='actor')await u.admin`update crm_private.crm_actors set enabled=false where actor_id=${u.actorId}::uuid`;else await u.admin`update crm_private.crm_sessions set revoked_at=clock_timestamp() where session_id=${u.sessionId}::uuid`;await assert.rejects(f.see());await assert.rejects(u.requirements.apply(await u.auth(),write,q));}finally{await u.close();}}},
 R57:async()=>{const f=await staged(2);assert.equal(await h.requirements.read(await h.auth(),read,f.requirementId,uid()),null);assert.equal(await h.requirements.read(await h.auth(),read,uid(),f.bookingId),null);await deny(await f.need({bookingId:uid()}));await deny(await f.receive({...await f.document(),documentId:uid()}));await deny(await f.need({basis:{...f.basis,scope:{...f.basis.scope,serviceId:uid()}}}));},
 R58:async()=>{for(const role of ['crm_h0_runtime','anon','authenticated']){const db=h.connect(role);for(const table of tables)for(const sql of [`select * from crm_private.${table}`,`delete from crm_private.${table}`,`update crm_private.${table} set admin_scope='fake'`,`insert into crm_private.${table} default values`])await assert.rejects(db.unsafe(sql));}},
 R59:async()=>{const f=await staged();for(const table of tables){await assert.rejects(h.migration.unsafe(`update crm_private.${table} set admin_scope=admin_scope`));await assert.rejects(h.migration.unsafe(`delete from crm_private.${table}`));}assert.equal((await f.see())!.history.length,1);},
 R60:async()=>{const rows=await h.observer`select c.relname,c.relrowsecurity,c.relforcerowsecurity,r.rolname owner from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_roles r on r.oid=c.relowner where n.nspname='crm_private' and c.relname=any(${tables})`;assert.equal(rows.length,5);for(const r of rows){assert.equal(r.relrowsecurity,true);assert.equal(r.relforcerowsecurity,true);assert.equal(r.owner,'crm_h0_f2_owner');}const funcs=await h.observer`select p.proname,p.proconfig,has_function_privilege('crm_h0_runtime',p.oid,'EXECUTE') runtime from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.proname like 'requirement_%' and n.nspname in ('crm_api','crm_private')`;assert.equal(funcs.length,5);for(const r of funcs){assert.ok(r.proconfig.includes('search_path=pg_catalog, pg_temp'));assert.equal(r.runtime,['requirement_apply','requirement_read'].includes(r.proname));}assert.equal((await h.observer`select count(*)::int n from pg_policies where schemaname='crm_private' and tablename=any(${tables})`)[0]!.n,10);assert.equal((await h.observer`select count(*)::int n from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where p.proname like 'requirement_%' and a.grantee=0`)[0]!.n,0);},
 R61:async()=>{assert.equal((await h.observer`select count(*)::int n from pg_tables where schemaname='crm_private' and tablename=any(${tables})`)[0]!.n,5);},
 R62:async()=>{const u=await isolatedRequirement('crm_h4002_upgrade',56003,true);try{const f=await invoiceFixture(u),d=await f.document();await u.invoices.apply(await u.auth(),write,await f.need());await u.invoices.apply(await u.auth(),write,await f.receive(d));await u.invoices.apply(await u.auth(),write,await f.review());const names=(await u.observer`select tablename from pg_tables where schemaname='crm_private'`).map(x=>x.tablename as string),old=await snapshots(u,names),catalog=await inventory(u);await u.migration.unsafe(await readFile(new URL('../../supabase/migrations/'+requirementMigration,import.meta.url),'utf8'));assert.deepEqual(await snapshots(u,names),old);const current=await inventory(u);for(const k of ['tables','functions','policies','triggers'] as const){const ids=new Set(catalog[k].map(x=>x.oid));assert.deepEqual(current[k].filter(x=>ids.has(x.oid)),catalog[k]);}assert.deepEqual(current.roles,catalog.roles);const g=await requirementFixture(u,f);await u.requirements.apply(await u.auth(),write,await g.need());assert.equal((await g.see())!.status,'Pendiente');}finally{await u.close();}},
 R63:async()=>{const u=await isolatedRequirement('crm_h4002_rollback',56004,true);try{const sql=await readFile(new URL('../../supabase/migrations/'+requirementMigration,import.meta.url),'utf8');await assert.rejects(u.migration.unsafe(sql.replace(/commit;\s*$/,`do $$begin raise exception 'SYNTHETIC_DDL_FAULT';end$$;commit;`)));await u.migration.unsafe('rollback');assert.equal((await u.observer`select count(*)::int n from pg_tables where schemaname='crm_private' and tablename=any(${tables})`)[0]!.n,0);await u.migration.unsafe(sql);assert.equal((await u.observer`select count(*)::int n from pg_tables where schemaname='crm_private' and tablename=any(${tables})`)[0]!.n,5);}finally{await u.close();}},
 R64:async()=>{const db=await h.connect('crm_h0_runtime').reserve();try{await assert.rejects(db.unsafe(await readFile(new URL('../../supabase/migrations/'+requirementMigration,import.meta.url),'utf8')));}finally{await db.unsafe('rollback');await db.release();}},
 R65:async()=>{const names=(await readdir(new URL('../../supabase/migrations/',import.meta.url))).filter(x=>x.endsWith('.sql')&&x<=requirementMigration).sort();assert.equal(names.length,38);assert.equal(names.filter(x=>x<requirementMigration).length,37);for(const file of [...names.filter(x=>x<requirementMigration).map(x=>'supabase/migrations/'+x),'supabase/operations/20261002225221_crm_supabase_daily_health.sql','tests/operations/supabase-health.test.mjs','docs/SUPABASE-KEEPALIVE.md']){const base=spawnSync('git',['show','bcb69fcb4fd508a34bde1a3fbc40b4dc653291c3:'+file],{encoding:'utf8'});assert.equal(base.status,0);assert.equal(await readFile(new URL('../../'+file,import.meta.url),'utf8'),base.stdout);}},
 R66:async()=>{const expected=await readFile(new URL('../../specs/001-core-crm/expected-TSK-H4-001-002.md',import.meta.url),'utf8');assert.equal((expected.match(/^\|R\d+/gm)??[]).length,68);const frozen=spawnSync('git',['show','88bf5f4:specs/001-core-crm/expected-TSK-H4-001-002.md'],{encoding:'utf8'});assert.equal(frozen.stdout,expected);},
 R67:async()=>{const f=await staged();await deny(await f.need({origin:'ai'}));await deny(await f.attest({...await f.need(),origin:null} as unknown as RequirementCommand));await deny(await f.attest(await f.need(),'candidate'));await deny(await f.attest({...await f.need(),basis:{...f.basis,context:{...f.basis.context,sourceRef:''}}}));await deny(await f.attest({...await f.need(),basis:{...f.basis,rule:{...f.basis.rule,indispensable:null}}} as unknown as RequirementCommand));},
 R68:async()=>{const expected=await readFile(new URL('../../specs/001-core-crm/expected-TSK-H4-001-002.md',import.meta.url),'utf8');for(const text of ['H4-003+','021/023','H5-014','DM-PENDING-005','Production'])assert.ok(expected.includes(text));}
};
for(const [id,run] of Object.entries(cases))test(id,run);
