/** Minimal reproducers preserve original failures, never rewrite the expected. */
import {test,before,after} from 'node:test';import assert from 'node:assert/strict';
import {randomUUID as uid} from 'node:crypto';import {readFile,readdir} from 'node:fs/promises';
import {isolatedPayment,write,read,paymentMigration} from '../support/h3-payment-isolated.ts';
import {paymentFixture} from '../support/h3-payment-fixtures.ts';
import type {PaymentCommand} from '../../src/infrastructure/postgres/h3-payment-adapter.ts';
import {createF1Issuer,encodeF1Fields} from '../../src/infrastructure/postgres/f1-codec.ts';import {createF2Issuer} from '../../src/infrastructure/postgres/f2-codec.ts';
import {issueTrustedContext} from '../../src/application/trusted-context.ts';import {postgresF1Binding} from '../../src/infrastructure/postgres/transaction.ts';
import {canonicalCommercial} from '../../src/domain/commercial-progress.ts';import {obligationMigration} from '../support/h3-obligation-isolated.ts';
let h:Awaited<ReturnType<typeof isolatedPayment>>;
before(async()=>{h=await isolatedPayment('crm_h3_004_original',55685,true);await h.migration.unsafe(await readFile(new URL('../fixtures/h3-004/first-product.sql.txt',import.meta.url),'utf8'));});
after(async()=>{await h?.close();});
async function apply(q:PaymentCommand){return h.payments.apply(await h.auth(),write,q);}
async function raw(input:PaymentCommand){const auth=await h.auth();return h.runtime.begin(async tx=>{
 const row=(await tx`select actor_id::text,admin_scope,access_generation::text,epoch_id::text from crm_api.f2_lookup(${auth.subject}::uuid,${auth.sessionId!}::uuid)`)[0]!,binding=await postgresF1Binding(tx),identity={actorId:row.actor_id,scope:row.admin_scope,sessionId:auth.sessionId!,accessGeneration:row.access_generation,epochId:row.epoch_id};
 const q=encodeF1Fields(['CRM-H3-PAYMENT1',canonicalCommercial(input)]),t=createF1Issuer(h.f1)(issueTrustedContext({identityId:'H3004 historical reproducer',identityKind:'technical',purpose:'h1-evidence',scope:h.scope,requestId:uid(),serverTime:new Date().toISOString()}),binding,'C03',q,{resource:'evidence',action:'write_evidence'}),a=createF2Issuer(h.f2)(auth,identity,binding,'evidence_write',q,write);
 return tx`select crm_api.payment_apply(${a.payload},${a.mac},${t.payload},${t.mac},${q}) r`;
});}
test('F01 historical ACC005 shared evidence field rejected by first product',async()=>{const f=await paymentFixture(h),shared=(await h.observer`select evidence_id::text id from crm_private.b03_acceptances where acceptance_id=${f.f.b.acceptanceId}::uuid`)[0]!.id;
 await h.evidence.apply(await h.auth(),write,{action:'link',operationId:uid(),targetId:uid(),originalId:shared,contextKind:'other',contextId:f.paymentId,coverage:f.paymentId,sourceRef:'SYNTHETIC same advance',purpose:'SYNTHETIC independent receipt review',reason:'SYNTHETIC common proof'});
 await assert.rejects(apply(await f.attest({...f.detect,presentedEvidenceId:shared})),/PAYMENT_INPUT_INVALID/);
});
test('F02 historical C03/G6 repeated receipt hits ambiguous SQL operator',async t=>{const f=await paymentFixture(h);await apply(f.detect);const q=await f.receive();await apply(q);await assert.rejects(raw({...q,operationId:uid()}),(e:unknown)=>{const m=e instanceof Error?e.message:'';t.diagnostic(m);return /operator is not unique|operator does not exist/.test(m);});assert.equal((await h.payments.read(await h.auth(),read,f.paymentId))!.receipts.length,1);});
test('F03 verifier guard helper reinstated removed evidence; corrected removal really denies',async()=>{const f=await paymentFixture(h),q={...f.detect};delete (q as unknown as Record<string,unknown>).evidenceId;const restored=await f.attest(q);assert.ok(restored.evidenceId);await apply(restored);const p=await f.propose(1),missing={...p};delete (missing as unknown as Record<string,unknown>).evidenceId;await assert.rejects(raw(missing));});
test('F04 verifier passed Opportunity as Booking argument; exact Booking and states work',async()=>{const f=await paymentFixture(h);assert.equal(await h.booking.read(await h.auth(),read,f.f.b.opportunityId),null);const r=await h.booking.read(await h.auth(),read,f.f.b.bookingId) as {booking:{state:string}};assert.equal(r.booking.state,'Pendiente de preparación');});
test('F05 verifier second human violates approved singleton; unprovisioned identity remains denied',async()=>{await assert.rejects(h.migration`insert into crm_private.crm_actors(actor_id,auth_subject,enabled,admin_scope) values(${uid()}::uuid,${uid()}::uuid,true,${h.scope})`,/singleton/);assert.equal((await h.observer`select count(*)::int n from crm_private.crm_actors`)[0]!.n,1);});
test('F06 verifier pinned connection prevents own setup; independent inspector observes actual locks',async()=>{const lock=h.connect('h2_bootstrap'),stats=h.connect('h2_bootstrap');let release!:()=>void,held!:()=>void;const ready=new Promise<void>(r=>held=r),unlock=new Promise<void>(r=>release=r);const b=lock.begin(async tx=>{await tx`select pg_advisory_xact_lock(hashtextextended('F06_SYNTHETIC',0))`;held();await unlock;});await ready;let done=false;const queued=lock`select 1 n`.then(()=>{done=true;});try{await new Promise(r=>setTimeout(r,20));assert.equal(done,false);assert.ok((await stats`select count(*)::int n from pg_stat_activity where usename='h2_bootstrap' and state='idle in transaction'`)[0]!.n>=1);}finally{release();await b;await queued;}assert.equal(done,true);});
test('F07 historical inventory sees extra forward migration while frozen base remains31',async()=>{const files=(await readdir(new URL('../../supabase/migrations',import.meta.url))).filter(f=>f.endsWith('.sql'));assert.equal(files.filter(f=>f>obligationMigration).length,1);assert.equal(files.filter(f=>f<=obligationMigration).length,31);assert.equal(files.filter(f=>f>obligationMigration)[0],paymentMigration);const current=await readFile(new URL('./postgres-h3-002.test.ts',import.meta.url),'utf8');assert.ok(current.includes('files.filter(x=>x<=obligationMigration).length,31'));});

test('F08 original historical reproducer counted32 global migrations instead of its31',async()=>{const files=(await readdir(new URL('../../supabase/migrations',import.meta.url))).filter(f=>f.endsWith('.sql'));assert.equal(files.length,32);assert.throws(()=>assert.equal(files.length,31),/32 !== 31/);const historical=files.filter(f=>f<=obligationMigration);assert.equal(historical.length,31);assert.throws(()=>assert.equal(historical.length,30),/31 !== 30/);const source=await readFile(new URL('./postgres-h3-002-defects.test.ts',import.meta.url),'utf8');assert.ok(source.includes("x<='20261002233922_h3_expected_obligations.sql'"));});
