/** Independent verifier against 75 expected cases frozen in034ddc0 before product. */
import {test,before,after} from 'node:test';import assert from 'node:assert/strict';
import {randomUUID as uid} from 'node:crypto';import {readFile,readdir} from 'node:fs/promises';import {execFileSync} from 'node:child_process';
import {isolatedAllocation,allocationMigration,read,write} from '../support/h3-allocation-isolated.ts';
import {allocationFixture,type AllocationCommand} from '../support/h3-allocation-fixtures.ts';
import {paymentFixture} from '../support/h3-payment-fixtures.ts';
import {H3005AllocationAdapter} from '../../src/infrastructure/postgres/h3-allocation-adapter.ts';
import {H3003PaymentAdapter,type PaymentCommand} from '../../src/infrastructure/postgres/h3-payment-adapter.ts';
import {H0005PostgresAdapter} from '../../src/infrastructure/postgres/h0-005-adapter.ts';import {verifyAuth} from '../../src/application/verified-auth.ts';
import {createF1Issuer,encodeF1Fields} from '../../src/infrastructure/postgres/f1-codec.ts';import {createF2Issuer} from '../../src/infrastructure/postgres/f2-codec.ts';
import {issueTrustedContext} from '../../src/application/trusted-context.ts';import {postgresF1Binding} from '../../src/infrastructure/postgres/transaction.ts';
import {canonicalCommercial} from '../../src/domain/commercial-progress.ts';import {allocationCalculation} from '../../src/domain/payment-allocation.ts';import {reconstructCalculation,type Allocation} from '../../src/domain/exact-money.ts';
let h:Awaited<ReturnType<typeof isolatedAllocation>>;type F=Awaited<ReturnType<typeof allocationFixture>>;
const tables=['b05_allocations','b05_allocation_revisions','b05_allocation_acts','b05_fund_operations','b05_fund_revisions','b05_fund_history','b05_coverage_evaluations','b05_fund_distributions'];
async function snapshot(target=h){const out:Record<string,unknown>={};for(const t of tables)out[t]=(await target.observer.unsafe(`select coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]') d from crm_private.${t} x`))[0]!.d;return out;}
const apply=async(q:AllocationCommand)=>h.allocations.apply(await h.auth(),write,q);
const pay=async(q:PaymentCommand)=>h.payments.apply(await h.auth(),write,q);
async function neg(q:AllocationCommand,raw=false,pattern?:RegExp){const old=await snapshot();if(pattern)await assert.rejects(raw?rawApply(q):apply(q),pattern);else await assert.rejects(raw?rawApply(q):apply(q));assert.deepEqual(await snapshot(),old);}
async function rawApply(input:unknown,scope=h.scope,bad=false,reading=false){const auth=await h.auth();return h.runtime.begin(async tx=>{
 const row=(await tx`select actor_id::text,admin_scope,access_generation::text,epoch_id::text from crm_api.f2_lookup(${auth.subject}::uuid,${auth.sessionId!}::uuid)`)[0]!,binding=await postgresF1Binding(tx),identity={actorId:row.actor_id,scope:row.admin_scope,sessionId:auth.sessionId!,accessGeneration:row.access_generation,epochId:row.epoch_id};
 const q=encodeF1Fields([reading?'CRM-H3-ALLOCATION-READ1':'CRM-H3-ALLOCATION1',canonicalCommercial(input)]),t=createF1Issuer(h.f1)(issueTrustedContext({identityId:'H3006 independent verifier',identityKind:'technical',purpose:'h1-evidence',scope,requestId:uid(),serverTime:new Date().toISOString()}),binding,reading?'C01':'C03',q,{resource:'evidence',action:reading?'read_evidence':'write_evidence'}),a=createF2Issuer(h.f2)(auth,identity,binding,reading?'evidence_read':'evidence_write',q,reading?read:write);
 return tx.unsafe(`select crm_api.${reading?'allocation_read':'allocation_apply'}($1,$2,$3,$4,$5) r`,[a.payload,bad?Buffer.alloc(32):a.mac,t.payload,t.mac,q]);
});}
async function session(){const sql=h.connect('crm_h0_runtime'),a=new H0005PostgresAdapter(sql,h.f1,h.f2),initial=await verifyAuth({verify:async()=>({subject:h.subject,passwordVerified:true,mfaVerified:true})},uid()),sid=(await a.establish(initial)).sessionId,auth=await verifyAuth({verify:async()=>({subject:h.subject,sessionId:sid,passwordVerified:true,mfaVerified:true})},uid());const aa=new H3005AllocationAdapter(sql,h.f1,h.f2),pp=new H3003PaymentAdapter(sql,h.f1,h.f2);return {apply:(q:AllocationCommand)=>aa.apply(auth,write,q),pay:(q:PaymentCommand)=>pp.apply(auth,write,q),read:(pid:string)=>aa.read(auth,read,pid)};}
async function assigned(amount='100.00',total=amount,destination?:Partial<F['destination']>){const f=await allocationFixture(h,total,total),q=await f.assign(amount,'0.00',{...f.destination,...destination});await apply(q);return {f,q};}
async function consumed(amount='20.00'){const {f,q}=await assigned('100.00'),c=await f.consume(q,amount);await apply(c);const act=(await f.see()).acts.find(x=>x.kind==='consume')!;return {f,q,c,act};}
async function distribution(total='100.00',weights=['1','1','1']){const f=await allocationFixture(h,total,total),parts=weights.map((weight,i)=>({id:uid(),order:i,weight,reconciliationId:f.p.reconciliationId!,expectedReconciliationRevision:2,destination:{...f.destination,reference:['A','B','C'][i]!}})),q=await f.command('distribute',{distributionId:uid(),start:'0.00',total,parts});await apply(q);return {f,q,parts};}
async function right(f:F,q:AllocationCommand,kind='modification',amount=q.amount??q.total??'100.00'){
 const b={kind,amount,originalRef:f.f.q.scheduleId!,sourceRef:'SYNTHETIC contractual component determined before funds',version:'1'};
 const hash=(await h.observer`select encode(crm_crypto.digest(convert_to(${JSON.stringify(b)}::text::jsonb::text,'UTF8'),'sha256'),'hex') hash`)[0]!.hash;
 const evidenceId=await f.proof(f.paymentId,`fund-right:${hash}`);return f.attest({...q,cause:kind,economicBasis:{...b,evidenceId}} as AllocationCommand);
}
async function fault(table:string,q:AllocationCommand,deferred=false){await h.admin.unsafe("create function crm_private.h3006_fault() returns trigger language plpgsql as $$begin raise exception 'H3006_INJECTED_FAULT';end$$;");await h.admin.unsafe(deferred?`create constraint trigger h3006_fault after insert on crm_private.${table} deferrable initially deferred for each row execute function crm_private.h3006_fault()`:`create trigger h3006_fault before insert on crm_private.${table} for each row execute function crm_private.h3006_fault()`);try{await neg(q);}finally{await h.admin.unsafe(`drop trigger h3006_fault on crm_private.${table}`);await h.admin.unsafe('drop function crm_private.h3006_fault()');}}
async function inventory(target=h){return {tables:await target.observer`select c.oid,c.relname,c.relowner,c.relacl::text,c.relrowsecurity,c.relforcerowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('crm_private','crm_api','crm_f1','crm_f2') and c.relkind in ('r','p','v','S') order by c.oid`,funcs:await target.observer`select p.oid,p.proname,p.proowner,p.proacl::text,pg_get_functiondef(p.oid) def from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('crm_private','crm_api','crm_f1','crm_f2') order by p.oid`,policies:await target.observer`select oid,polname,polrelid,polroles::text,pg_get_expr(polqual,polrelid) qual,pg_get_expr(polwithcheck,polrelid) ck from pg_policy order by oid`,triggers:await target.observer`select oid,pg_get_triggerdef(oid) def from pg_trigger order by oid`,roles:await target.observer`select rolname,rolsuper,rolinherit,rolcreaterole,rolcreatedb,rolcanlogin,rolbypassrls from pg_roles order by rolname`};}
async function priorData(target=h){const out:Record<string,unknown>={};for(const {tablename:t} of await target.observer`select tablename from pg_tables where schemaname='crm_private' and not(tablename=any(${tables})) order by tablename`)out[t]=(await target.observer.unsafe(`select coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]') d from crm_private.${t} x`))[0]!.d;return out;}
before(async()=>{h=await isolatedAllocation('crm_h3_006',55687);});after(async()=>{await h?.close();});
test('R01 Expected cannot create funds or coverage',async()=>{const f=await allocationFixture(h,'500.00','500.00','none');assert.equal(await h.allocations.read(await h.auth(),read,f.paymentId),null);const e=await h.obligations.evaluate(await h.auth(),read,f.f.b.bookingId,f.f.q.scheduleId!,'2026-10-12T10:00:00Z');assert.ok(e!.every(x=>x.verifiedAmount==='0.00'&&x.state==='pending'));});
test('R02 detected cannot allocate verified funds',async()=>{const f=await allocationFixture(h,'500.00','500.00','detected');await neg(await f.assign());assert.equal((await f.see()).summary.received,null);});
test('R03 receipt without correspondence cannot cover',async()=>{const f=await allocationFixture(h,'500.00','500.00','received');await neg(await f.assign());assert.equal((await f.see()).summary.available,'0.00');});
test('R04 proposed Reconciliation cannot cover',async()=>{const f=await allocationFixture(h,'500.00','500.00','proposed');await neg(await f.assign());assert.equal((await f.see()).coverage[0]!.verifiedAmount,'0.00');});
test('R05 planned Allocation no reservation consumption or coverage',async()=>{const f=await allocationFixture(h,'500.00','500.00','proposed'),q=await f.assign('200.00');await apply(await f.attest({...q,action:'plan'}));const r=await f.see();assert.equal(r.summary.planned,'200.00');assert.equal(r.summary.assigned,'0.00');assert.equal(r.summary.consumed,'0.00');assert.equal(r.coverage[0]!.verifiedAmount,'0.00');await neg(await f.consume(q));});
test('R06 partial coverage200 of obligation500',async()=>{const {f}=await assigned('200.00','500.00'),r=await f.see();assert.equal(r.coverage[0]!.state,'partial');assert.equal(r.coverage[0]!.verifiedAmount,'200.00');assert.equal(r.coverage[0]!.remaining,'300.00');const e=await h.obligations.evaluate(await h.auth(),read,f.f.b.bookingId,f.f.q.scheduleId!,'2026-10-12T10:00:00Z');assert.equal(e![0]!.verifiedAmount,'200.00');});
test('R07 complete coverage preserves Booking and provider independence',async()=>{const {f}=await assigned('500.00'),r=await f.see();assert.equal(r.coverage[0]!.state,'complete');assert.equal(r.coverage[0]!.remaining,'0.00');const b=await h.booking.read(await h.auth(),read,f.f.b.bookingId);assert.equal((b as {booking:{state:string}}).booking.state,'Pendiente de preparación');});
test('R08 multiple real payments cover one obligation without1to1',async()=>{const a=await allocationFixture(h,'200.00','200.00'),qa=await a.assign();await apply(qa);const b=await allocationFixture(h,'300.00','300.00','none');await pay(await b.paymentAttest({...b.detect,detection:{...b.detect.detection!,bookingId:a.f.b.bookingId}} as never));await pay(await b.receive());const pb=await b.paymentAttest({...await b.propose(2,'300.00'),bookingId:a.f.b.bookingId,scheduleId:a.f.q.scheduleId!} as never);await pay(pb);await pay(await b.verify(pb));await apply(await b.attest({...await b.assign('300.00','0.00',a.destination),reconciliationId:pb.reconciliationId}));const r=await a.see();assert.equal(r.coverage[0]!.verifiedAmount,'500.00');assert.equal((r.coverage[0]!.portions as unknown[]).length,2);assert.equal((await b.see()).summary.received,'300.00');});
test('R09 one payment multiple disjoint obligation destinations',async()=>{const f=await allocationFixture(h,'500.00','200.00'),p=await f.paymentAttest({...await f.propose(4,'300.00','200.00'),slot:'balance'} as never);await pay(p);await pay(await f.verify(p,5));await apply(await f.assign('200.00'));const q=await f.assign('300.00','200.00',{...f.destination,slot:'balance',reference:'SYNTHETIC balance'});await apply(await f.attest({...q,reconciliationId:p.reconciliationId}));const r=await f.see();assert.deepEqual(r.coverage.map(x=>x.verifiedAmount),['200.00','300.00']);assert.equal(r.summary.assigned,'500.00');});
test('R10 unassigned unresolved300 cannot fund another purpose automatically',async()=>{const f=await allocationFixture(h,'500.00','200.00');await apply(await f.assign('200.00'));const r=await f.see();assert.equal(r.summary.unassigned,'300.00');assert.equal(r.summary.available,'0.00');assert.equal(r.summary.consumed,'0.00');assert.equal(r.allocations.length,1);});
test('R11 managed funds and Fee distinct no output mandate own income',async()=>{const f=await allocationFixture(h,'100.00','100.00');await apply(await f.assign('60.00','0.00',{...f.destination,purpose:'managed_client_funds',reference:'SYNTHETIC external destination'}));await apply(await f.assign('40.00','60.00',{...f.destination,purpose:'fee',reference:'SYNTHETIC Fee destination'}));const r=await f.see();assert.deepEqual(Object.keys(r.summary.byPurpose as object).sort(),['fee','managed_client_funds']);assert.equal(r.summary.representedReturned,'0.00');assert.equal(r.summary.externalReturned,null);const g=await allocationFixture(h,'100.00','100.00'),destination={bookingId:g.f.b.bookingId,purpose:'managed_client_funds' as const,reference:'SYNTHETIC destination with no obligation allocation'};await apply(await g.assign('100.00','0.00',destination));assert.equal((await g.see()).coverage[0]!.verifiedAmount,'0.00');assert.equal((await g.see()).summary.assigned,'100.00');});
test('R12 cross Booking client or service destinations denied',async()=>{const f=await allocationFixture(h),other=await allocationFixture(h);for(const destination of [{...f.destination,bookingId:other.f.b.bookingId},{...f.destination,serviceId:other.f.detail.services[0]!.id},{...f.destination,scheduleId:other.f.q.scheduleId!}])await neg(await f.assign('100.00','0.00',destination));});
test('R13 each destination portion amount purpose source evidence guard fails without side effect',async()=>{const f=await allocationFixture(h),q=await f.assign('100.00');for(const key of ['destination','amount','start','reconciliationId','expectedReconciliationRevision','sourceRef','reason','at','evidenceId']){const input={...q};delete(input as unknown as Record<string,unknown>)[key];await neg(await f.attest(input),true);}for(const key of ['bookingId','purpose','reference','scheduleId','slot']){const input={...q,destination:{...q.destination!}};delete(input.destination as unknown as Record<string,unknown>)[key];await neg(await f.attest(input),true);}});
test('R14 no reviewed authorized assertion no checked Allocation',async()=>{const f=await allocationFixture(h),q=await f.assign();await neg(await f.attest(q,'candidate','communication'));await neg({...q,evidenceId:f.detect.evidenceId});await neg({...q,authorized:true} as AllocationCommand,true);});
test('R15 only200 of500 reconciled does not allow other300',async()=>{const f=await allocationFixture(h,'500.00','200.00');await neg(await f.assign('300.00','200.00'));assert.equal((await f.see()).coverage[0]!.remaining,'500.00');});
test('R16 overlap second allocation cannot count twice',async()=>{const {f}=await assigned('80.00','100.00');await neg(await f.assign('30.00','70.00'));assert.equal((await f.see()).summary.assigned,'80.00');});
test('R17 overlapping forecasts do not consume verified funds',async()=>{const f=await allocationFixture(h),a=await f.assign('80.00');await apply(await f.attest({...a,action:'plan'}));const b=await f.assign('80.00');await apply(await f.attest({...b,action:'plan'}));assert.equal((await f.see()).summary.assigned,'0.00');await neg(await f.consume(a));});
test('R18 verifying forecast adds linked act once and atomic coverage',async()=>{const f=await allocationFixture(h,'100.00','100.00','proposed'),q=await f.assign();await apply(await f.attest({...q,action:'plan'}));await pay(await f.verify(f.p));const r=await f.see();await apply(await f.attest({...q,action:'verify',operationId:uid(),expectedRevision:r.revision,expectedPaymentRevision:r.paymentRevision,expectedReconciliationRevision:2}));const s=await f.see();assert.equal(s.allocations.length,1);assert.equal(s.allocations[0]!.status,'verified');assert.equal(s.acts.length,2);assert.equal(s.coverage[0]!.verifiedAmount,'100.00');});
test('R19 AI may plan cannot verify consume correct without human authority',async()=>{const f=await allocationFixture(h),q=await f.assign('100.00');await apply(await f.attest({...q,action:'plan',origin:'ai'},'candidate','communication'));for(const action of ['assign','verify','consume','reverse','rectify'] as const){const r=await f.see();await neg(await f.attest({...q,action,origin:'ai',expectedRevision:r.revision}));}});
test('R20 internal80 consumed assigned100 leaves20 for its purpose no bank output',async()=>{const {f,q}=await assigned(),c=await f.consume(q,'80.00');await apply(c);const r=await f.see(),purpose=(r.summary.byPurpose as Record<string,Record<string,string>>).obligation!;assert.equal(r.summary.consumed,'80.00');assert.equal(purpose.availableForPurpose,'20.00');assert.equal(r.summary.available,'0.00');assert.equal(r.coverage[0]!.verifiedAmount,'100.00');});
test('R21 no consumption without checked Allocation',async()=>{const f=await allocationFixture(h),q=await f.assign('100.00');await neg(await f.consume(q));await apply(await f.attest({...q,action:'plan'}));await neg(await f.consume(q));});
test('R22 second80 on consumed80 out100 fails no negative',async()=>{const {f,q}=await consumed('80.00');await neg(await f.consume(q,'80.00'));assert.equal((await f.see()).summary.consumed,'80.00');});
test('R23 consumption for another purpose rejected',async()=>{const {f,q}=await assigned();await neg(await f.attest({...await f.consume(q,'80.00'),destination:{...q.destination!,purpose:'fee'}}));});
test('R24 read and replay never consume again',async()=>{const {f,c}=await consumed('80.00'),old=await f.see();await f.see();assert.equal((await apply(c)).replayed,true);assert.deepEqual(await f.see(),old);});
test('R25 discrepancy100 of assigned200 leaves100 current coverage original200',async()=>{const f=await allocationFixture(h,'500.00','200.00');await apply(await f.assign('200.00'));await pay(await f.discrepancy(4,'0.00','100.00',f.p.reconciliationId));const r=await f.see();assert.equal(r.summary.received,'500.00');assert.equal(r.summary.assigned,'200.00');assert.equal(r.summary.usableAssigned,'100.00');assert.equal(r.coverage[0]!.verifiedAmount,'100.00');assert.equal(r.allocations[0]!.amount,'200.00');const allocationId=r.allocations[0]!.id as string;await neg(await f.command('consume',{allocationId,amount:'100.00',start:'0.00',destination:f.destination}));await apply(await f.command('consume',{allocationId,amount:'100.00',start:'100.00',destination:f.destination}));assert.equal((await f.see()).summary.usableConsumed,'100.00');});
test('R26 doubts over unrelated300 do not invalidate checked200',async()=>{const f=await allocationFixture(h,'500.00','200.00');await apply(await f.assign('200.00'));await pay(await f.discrepancy(4,'200.00','300.00'));assert.equal((await f.see()).coverage[0]!.verifiedAmount,'200.00');await neg(await f.assign('300.00','200.00'));});
test('R27 human resolution restores scope only once',async()=>{const {f}=await assigned(),i=await f.discrepancy(4,'0.00','40.00');await pay(i);assert.equal((await f.see()).coverage[0]!.verifiedAmount,'60.00');const q=await f.paymentAttest({action:'resolve',operationId:uid(),paymentId:f.paymentId,expectedRevision:5,sourceRef:'SYNTHETIC verified source',reason:'SYNTHETIC resolved',at:f.at,evidenceId:uid(),incidentId:i.incidentId,sourceEvidenceId:f.sourceEvidenceId} as never);await pay(q as never);const r=await f.see();assert.equal(r.coverage[0]!.verifiedAmount,'100.00');assert.equal(r.summary.assigned,'100.00');});
test('R28 discrepancy material evidence cause portion guards preserved',async()=>{const {f}=await assigned(),q=await f.discrepancy(4);for(const key of ['reason','evidenceId','start','amount','sourceRef']){const input={...q};delete(input as unknown as Record<string,unknown>)[key];const old=await snapshot();await assert.rejects(pay(key==='evidenceId'?input:await f.paymentAttest(input as never) as never));assert.deepEqual(await snapshot(),old);}});
test('R29 linked Allocation rectification preserves original before after',async()=>{const {f,q}=await assigned(),r=await f.assign('90.00');await apply(await f.attest({...r,action:'rectify',originalAllocationId:q.allocationId,cause:'correction'}));const s=await f.see();assert.equal(s.allocations.find(x=>x.id===q.allocationId)!.status,'reversed');assert.equal(s.allocations.find(x=>x.id===r.allocationId)!.originalRef,q.allocationId);assert.equal(s.coverage[0]!.verifiedAmount,'90.00');assert.equal(s.acts.length,3);});
test('R30 missingD019 blocks dependent cancellation only independent valid can continue',async()=>{const f=await allocationFixture(h,'100.00','100.00'),q=await f.assign('80.00');for(const cause of ['cancellation','refund','new_obligation','modification'] as const)await neg(await f.attest({...q,cause}));await apply(q);assert.equal((await f.see()).summary.assigned,'80.00');});
test('R31 prior reviewed reproducibleD019 authorizes exactly determined effect',async()=>{const f=await allocationFixture(h,'100.00','100.00'),q=await right(f,await f.assign('80.00'));await apply(q);assert.equal((await f.see()).summary.assigned,'80.00');const event=(await h.observer`select event from crm_private.b05_fund_operations where operation_id=${q.operationId}::uuid`)[0]!.event;assert.equal(event.economicBasis.amount,'80.00');});
test('R32 D019 each basis field wrong scope unreviewed and mismatched amount rejects',async()=>{const f=await allocationFixture(h,'100.00','100.00'),q=await right(f,await f.assign('80.00'));for(const key of ['kind','amount','originalRef','sourceRef','version','evidenceId']){const input={...q,economicBasis:{...q.economicBasis!}};delete(input.economicBasis as unknown as Record<string,unknown>)[key];await neg(await f.attest(input));}for(const key of ['kind','originalRef','sourceRef','version']){const economicBasis={...q.economicBasis!,[key]:null} as unknown as NonNullable<AllocationCommand['economicBasis']>;const value=Object.fromEntries(Object.entries(economicBasis).filter(([k])=>k!=='evidenceId'));const hash=(await h.observer`select encode(crm_crypto.digest(convert_to(${JSON.stringify(value)}::text::jsonb::text,'UTF8'),'sha256'),'hex') hash`)[0]!.hash;const evidenced={...economicBasis,evidenceId:await f.proof(f.paymentId,`fund-right:${hash}`)};await neg(await f.attest({...q,economicBasis:evidenced}));}await neg(await f.attest({...q,amount:'81.00'}));await neg(await f.attest({...q,economicBasis:{...q.economicBasis!,evidenceId:f.detect.evidenceId}}));});
test('R33 reversal reduces coverage keeps original obligation no new debt',async()=>{const {f}=await assigned(),old=await h.obligations.read(await h.auth(),read,f.f.b.bookingId,f.f.q.scheduleId!),act=(await f.see()).acts[0]!;await apply(await f.reverse(act.act_id as string));const r=await f.see();assert.equal(r.summary.assigned,'0.00');assert.equal(r.coverage[0]!.remaining,'500.00');const current=await h.obligations.read(await h.auth(),read,f.f.b.bookingId,f.f.q.scheduleId!);assert.deepEqual(current!.original,old!.original);assert.deepEqual(current!.history,old!.history);});
test('R34 PM08 advance500.01 reversal exact-500.01 historical bank remains',async()=>{const f=await allocationFixture(h,'500.01','500.01','verified','1000.02');await apply(await f.assign());const act=(await f.see()).acts[0]!;await apply(await f.reverse(act.act_id as string));const r=await f.see();assert.equal(r.acts[1]!.signed_amount,'-500.01');assert.equal(r.acts[1]!.original_act_id,act.act_id);assert.equal(r.summary.received,'500.01');assert.equal(r.summary.available,'500.01');});
test('R35 PM08 internal signed-20 reversal+20 without external output',async()=>{const {f,act}=await consumed();await apply(await f.reverse(act.act_id as string));const r=await f.see();assert.equal(r.acts.find(x=>x.original_act_id===act.act_id)!.signed_amount,'20.00');assert.equal(r.summary.consumed,'0.00');assert.equal(r.summary.received,'100.00');});
test('R36 PM11 persisted33.34/33.33/33.33 residualA sum100',async()=>{const {f}=await distribution(),r=await f.see(),c=r.distributions[0]!.calculation,a=c.output as Allocation;assert.deepEqual(a.parts.map(p=>p.amount),['33.34','33.33','33.33']);assert.deepEqual(a.parts.map(p=>p.residualCents),['1','0','0']);assert.equal(r.summary.assigned,'100.00');assert.deepEqual(reconstructCalculation(c),c.output);});
test('R37 PM12 exact internals remainders and final0.01/0.01/0.03',async()=>{const {f}=await distribution('0.05',['1','1','2']),r=await f.see(),a=r.distributions[0]!.calculation.output as Allocation;assert.deepEqual(a.parts.map(p=>p.internal.decimal),['0.0125','0.0125','0.025']);assert.deepEqual(a.parts.map(p=>p.fullCents),['1','1','2']);assert.deepEqual(a.parts.map(p=>p.remainder.decimal),['0.0025','0.0025','0.005']);assert.deepEqual(a.parts.map(p=>p.amount),['0.01','0.01','0.03']);assert.equal(r.summary.assigned,'0.05');});
test('R38 PM13 persisted negative inversions preserve magnitude order',async()=>{for(const [total,weights,expected] of [['100.00',['1','1','1'],['-33.34','-33.33','-33.33']],['0.05',['1','1','2'],['-0.01','-0.01','-0.03']]] as const){const {f,q,parts}=await distribution(total,[...weights]);await apply(await f.command('reverse_distribution',{distributionId:q.distributionId,total:'-'+total,parts}));const r=await f.see(),c=r.distributions[1]!.calculation;assert.deepEqual((c.output as Allocation).parts.map(p=>p.amount),expected);assert.equal(r.summary.assigned,'0.00');assert.equal(r.summary.received,total);assert.deepEqual(reconstructCalculation(c),c.output);}});
test('R39 missing legitimate total bases weights order fail closed',async()=>{const f=await allocationFixture(h,'100.00','100.00'),parts=[{id:uid(),order:0,weight:'1',reconciliationId:f.p.reconciliationId!,expectedReconciliationRevision:2,destination:f.destination}],q=await f.command('distribute',{distributionId:uid(),start:'0.00',total:'100.00',parts});for(const change of [{total:undefined},{parts:undefined},{parts:[{...parts[0]!,weight:'0'}]},{parts:[parts[0]!,{...parts[0]!,id:uid()}]}])await neg(await f.attest({...q,...change}));});
test('R40 historical split survives current policy changes odd cents',async()=>{const {f}=await distribution('0.03'),old=await f.see();await h.obligations.apply(await h.auth(),write,await f.f.attest({...f.f.publish,operationId:uid(),expectedRevision:1,policyVersion:2}));const r=await f.see();assert.deepEqual(r,old);assert.deepEqual((r.distributions[0]!.calculation.output as Allocation).parts.map(p=>p.amount),['0.01','0.01','0.01']);});
test('R41 definitive number float negative or bad scale rejected raw too',async()=>{const f=await allocationFixture(h),q=await f.assign();for(const amount of [100,'100.001','-100.00','NaN'])await neg(await f.attest({...q,amount} as AllocationCommand),true);});
test('R42 same operation equivalent keyorder replay no duplicate Allocation consume coverage adjustment',async()=>{const {f,q}=await assigned(),r=await f.see();const reversed=Object.fromEntries(Object.entries(q).reverse()) as unknown as AllocationCommand;assert.equal((await apply(reversed)).replayed,true);assert.deepEqual(await f.see(),r);const c=await f.consume(q,'20.00');await apply(c);const old=await f.see();assert.equal((await apply(c)).replayed,true);assert.deepEqual(await f.see(),old);const act=old.acts.find(x=>x.kind==='consume')!,v=await f.reverse(act.act_id as string);await apply(v);const final=await f.see();assert.equal((await apply(v)).replayed,true);assert.deepEqual(await f.see(),final);});
test('R43 same key changed material E2 original remains',async()=>{const {f,q}=await assigned();await neg(await f.attest({...q,amount:'99.00'}),false,/E2/);});
test('R44 lost committed response timeout retry recognizes durable effect',async()=>{const f=await allocationFixture(h,'100.00','100.00'),q=await f.assign('80.00');await apply(q);const r=await apply(q);assert.equal(r.replayed,true);assert.equal((await f.see()).history.length,1);assert.equal((await f.see()).summary.assigned,'80.00');});
test('R45 replay unauthorized actor scope denied',async()=>{const {f,q}=await assigned();const old=await snapshot();await assert.rejects(rawApply(q,'FORGED_SCOPE'));await assert.rejects(rawApply(q,h.scope,true));const auth=await verifyAuth({verify:async()=>({subject:uid(),sessionId:uid(),passwordVerified:true,mfaVerified:true})},uid());await assert.rejects(h.allocations.apply(auth,write,q));assert.deepEqual(await snapshot(),old);assert.equal((await f.see()).summary.assigned,'100.00');});
async function concurrent(q1:AllocationCommand,q2:AllocationCommand|PaymentCommand,mixed=false){
 const other=await session(),stats=h.connect('h2_bootstrap');let release!:()=>void,held!:()=>void;const ready=new Promise<void>(r=>held=r),unlock=new Promise<void>(r=>release=r);
 const blocker=h.admin.begin(async tx=>{await tx`select pg_advisory_xact_lock(hashtextextended(${'payment-root:'+q1.paymentId},0))`;held();await unlock;});await ready;
 const results=Promise.allSettled([apply(q1),mixed?other.pay(q2 as PaymentCommand):other.apply(q2 as AllocationCommand)]);
 try{let waiting=false;for(let i=0;i<250;i++){const r=(await stats`select count(*)::int n from pg_stat_activity where wait_event_type='Lock' and (query like '%crm_api.allocation_apply%' or query like '%crm_api.payment_apply%')`)[0]!;if(r.n>=2){waiting=true;break;}await new Promise(r=>setTimeout(r,10));}assert.ok(waiting,'independent sessions overlap under existing F2 and shared payment-root locks');}finally{release();await blocker;}return results;
}
function one(r:PromiseSettledResult<unknown>[]){assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(r.filter(x=>x.status==='rejected').length,1);}
test('R46 stale funds payment schedule revisions never overwrite',async()=>{const {f,q}=await assigned('80.00','100.00');await neg(await f.attest({...q,operationId:uid(),allocationId:uid()}),false,/E2/);const current=await f.assign('20.00','80.00');await neg(await f.attest({...current,expectedPaymentRevision:3}),false,/E2/);await neg(await f.attest({...current,expectedScheduleRevision:0}));for(const expectedScheduleRevision of [null,'1',1.5])await neg(await f.attest({...current,expectedScheduleRevision} as AllocationCommand),true);assert.equal((await f.see()).summary.assigned,'80.00');});
for(const [id,order] of [['R47','A→B'],['R48','B→A']] as const)test(`${id} ${order}80 then80 shared100 with no initial child`,async()=>{const f=await allocationFixture(h,'100.00','100.00');assert.equal((await f.see()).allocations.length,0);const a=await f.assign('80.00','0.00',{...f.destination,reference:order[0]!}),b=await f.assign('80.00','0.00',{...f.destination,reference:order[2]!});await apply(a);await neg(b);assert.equal((await f.see()).summary.assigned,'80.00');assert.equal((await f.see()).summary.unassigned,'20.00');assert.equal((await f.see()).acts.length,1);});
test('R49 real concurrent80/80 same and different destinations no existing child',async()=>{for(const different of [false,true]){const f=await allocationFixture(h,'100.00','100.00'),a=await f.assign('80.00'),b=await f.assign('80.00','0.00',{...f.destination,reference:different?'SYNTHETIC B':f.destination.reference});one(await concurrent(a,b));const r=await f.see();assert.equal(r.summary.assigned,'80.00');assert.equal(r.allocations.length,1);assert.equal(r.acts.length,1);assert.equal(r.summary.unassigned,'20.00');const t=await assigned(),ca=await t.f.consume(t.q,'80.00'),cb=await t.f.consume(t.q,'80.00');one(await concurrent(ca,cb));assert.equal((await t.f.see()).summary.consumed,'80.00');assert.equal(((await t.f.see()).summary.byPurpose as Record<string,Record<string,string>>).obligation!.availableForPurpose,'20.00');}});
test('R50 same key concurrent one effect plus replay',async()=>{const f=await allocationFixture(h,'100.00','100.00'),q=await f.assign('80.00'),r=await concurrent(q,q);assert.ok(r.every(x=>x.status==='fulfilled'));assert.equal(r.filter(x=>x.status==='fulfilled'&&x.value.replayed).length,1);assert.equal((await f.see()).acts.length,1);const c=await f.consume(q,'80.00'),cr=await concurrent(c,c);assert.ok(cr.every(x=>x.status==='fulfilled'));assert.equal((await f.see()).summary.consumed,'80.00');});
test('R51 competing different obligations cannot move shared portion arbitrarily',async()=>{const f=await allocationFixture(h,'100.00','100.00'),a=await f.assign('80.00'),b=await f.assign('80.00','0.00',{...f.destination,slot:'balance',reference:'SYNTHETIC other obligation'});one(await concurrent(a,b));assert.equal((await f.see()).summary.assigned,'80.00');assert.equal((await f.see()).coverage[1]!.verifiedAmount,'0.00');});
async function pair(){const a=await allocationFixture(h,'300.00','300.00'),b=await allocationFixture(h,'300.00','300.00','none');await pay(await b.paymentAttest({...b.detect,detection:{...b.detect.detection!,bookingId:a.f.b.bookingId}}));await pay(await b.receive());const p=await b.paymentAttest({...await b.propose(2,'300.00'),bookingId:a.f.b.bookingId,scheduleId:a.f.q.scheduleId!});await pay(p);await pay(await b.verify(p));return {a,b,qa:await a.assign(),qb:await b.attest({...await b.assign('300.00','0.00',a.destination),reconciliationId:p.reconciliationId})};}
test('R52 two movement roots concurrent same obligation do not overcover500',async()=>{const {a,qa,qb}=await pair();one(await concurrent(qa,qb));assert.equal((await a.see()).coverage[0]!.verifiedAmount,'300.00');});
test('R53 competing linked modifications both orders one revision wins',async()=>{for(const reverse of [false,true]){const {f,q}=await assigned(),a=await f.attest({...await f.assign('90.00'),action:'rectify',originalAllocationId:q.allocationId,cause:'correction'}),b=await f.attest({...await f.assign('80.00'),action:'rectify',originalAllocationId:q.allocationId,cause:'correction'});one(await concurrent(reverse?b:a,reverse?a:b));const r=await f.see();assert.equal(r.allocations.filter(x=>x.status==='verified').length,1);assert.equal(r.allocations.filter(x=>x.status==='reversed').length,1);assert.equal(r.acts.length,3);}});
test('R54 concurrent reversal once preserves original exact opposite',async()=>{const {f,act}=await consumed(),a=await f.reverse(act.act_id as string),b={...a,operationId:uid()};one(await concurrent(a,b));assert.equal((await f.see()).summary.consumed,'0.00');assert.equal((await f.see()).acts.filter(x=>x.original_act_id===act.act_id).length,1);});
test('R55 Allocation vs Customer Payment discrepancy and rectification serialized same root',async()=>{for(const rectifying of [false,true]){const f=await allocationFixture(h,'100.00','100.00');let p:PaymentCommand;if(rectifying){const i=await f.discrepancy(4,'0.00','40.00',f.p.reconciliationId);await pay(i);p=await f.rectify(f.p,i,5,'100.00');}else p=await f.discrepancy(4,'0.00','40.00',f.p.reconciliationId);const q=await f.assign('60.00','40.00'),r=await concurrent(q,p,true);assert.ok(r.some(x=>x.status==='fulfilled'));const current=await f.see();assert.ok(['0.00','60.00'].includes(current.coverage[0]!.verifiedAmount as string));assert.equal(current.summary.received,'100.00');assert.ok(Number(current.summary.usableAssigned)<=60);}});
test('R56 independent reader before COMMIT sees complete preceding state',async()=>{const f=await allocationFixture(h,'100.00','100.00'),q=await f.assign('80.00'),other=await session(),stats=h.connect('h2_bootstrap'),lock=h.connect('h2_bootstrap');let release!:()=>void,held!:()=>void;const ready=new Promise<void>(r=>held=r),unlock=new Promise<void>(r=>release=r);
 await h.admin.unsafe("create function crm_private.h3006_wait() returns trigger language plpgsql as $$begin perform pg_advisory_xact_lock(hashtextextended('H3006_VISIBILITY',0));return new;end$$;create trigger h3006_wait before insert on crm_private.b05_fund_history for each row execute function crm_private.h3006_wait();");
 const blocker=lock.begin(async tx=>{await tx`select pg_advisory_xact_lock(hashtextextended('H3006_VISIBILITY',0))`;held();await unlock;});await ready;const work=other.apply(q);let reading:ReturnType<typeof h.allocations.read>|undefined;
 try{let waiting=false;for(let i=0;i<250;i++){if((await stats`select count(*)::int n from pg_stat_activity where wait_event_type='Lock' and query like '%crm_api.allocation_apply%'`)[0]!.n>0){waiting=true;break;}await new Promise(r=>setTimeout(r,10));}assert.ok(waiting);assert.equal((await h.observer`select count(*)::int n from crm_private.b05_allocations where payment_id=${f.paymentId}::uuid`)[0]!.n,0);const auth=await h.auth();reading=h.allocations.read(auth,read,f.paymentId);}finally{release();await blocker;try{await work;assert.equal((await reading)!.summary.assigned,'80.00');}finally{await h.admin.unsafe('drop trigger h3006_wait on crm_private.b05_fund_history;drop function crm_private.h3006_wait()');}}
});
test('R57 failure before first Allocation write rolls unit back',async()=>{const f=await allocationFixture(h),q=await f.assign();await fault('b05_allocations',q);await apply(q);});
test('R58 failure between Allocation revision history and operation rolls all back',async()=>{for(const t of ['b05_allocation_revisions','b05_allocation_acts','b05_fund_revisions','b05_fund_operations','b05_fund_history']){const f=await allocationFixture(h),q=await f.assign();await fault(t,q);await apply(q);}});
test('R59 failure after derived coverage rolls all dependencies back',async()=>{const f=await allocationFixture(h),q=await f.assign();await fault('b05_coverage_evaluations',q);await apply(q);});
test('R60 consume failure no isolated consumed portion',async()=>{for(const t of ['b05_allocation_acts','b05_fund_history']){const {f,q}=await assigned(),c=await f.consume(q);await fault(t,c);assert.equal((await f.see()).summary.consumed,'0.00');}});
test('R61 correction reversal failure preserves original and coverage',async()=>{for(const action of ['reverse','rectify'] as const){const {f,q}=await assigned(),r=action==='reverse'?await f.reverse((await f.see()).acts[0]!.act_id as string):await f.attest({...await f.assign('90.00'),action,originalAllocationId:q.allocationId,cause:'correction'});await fault('b05_fund_history',r);assert.equal((await f.see()).summary.assigned,'100.00');}});
test('R62 failure middle of distribution no first destination durable',async()=>{const f=await allocationFixture(h,'100.00','100.00'),parts=['A','B','C'].map((reference,order)=>({id:uid(),order,weight:'1',reconciliationId:f.p.reconciliationId!,expectedReconciliationRevision:2,destination:{...f.destination,reference}})),q=await f.command('distribute',{distributionId:uid(),start:'0.00',total:'100.00',parts});await h.admin.unsafe("create function crm_private.h3006_middle() returns trigger language plpgsql as $$begin if new.start_amount>0 then raise exception 'H3006_MIDDLE';end if;return new;end$$;create trigger h3006_middle before insert on crm_private.b05_allocations for each row execute function crm_private.h3006_middle();");try{await neg(q);}finally{await h.admin.unsafe('drop trigger h3006_middle on crm_private.b05_allocations;drop function crm_private.h3006_middle()');}await apply(q);assert.equal((await f.see()).allocations.length,3);});
test('R63 deferred COMMIT failure no durable result retry succeeds',async()=>{const f=await allocationFixture(h),q=await f.assign();await fault('b05_fund_operations',q,true);await apply(q);assert.equal((await f.see()).acts.length,1);});
test('R64 absent forged disabled MFA-less contexts fail closed',async()=>{const f=await allocationFixture(h),q=await f.assign();await assert.rejects(h.runtime`select crm_api.allocation_apply(null,null,null,null,null)`);await assert.rejects(h.allocations.read({subject:'forged'} as never,read,f.paymentId));const auth=await verifyAuth({verify:async()=>({subject:h.subject,sessionId:uid(),passwordVerified:true,mfaVerified:false})},uid());await assert.rejects(h.allocations.apply(auth,write,q));await h.migration`update crm_private.crm_actors set enabled=false where actor_id=${h.actorId}::uuid`;try{await assert.rejects(apply(q));await assert.rejects(f.see());}finally{await h.migration`update crm_private.crm_actors set enabled=true where actor_id=${h.actorId}::uuid`;}});
test('R65 direct DML append-only ownership no runtime economic CRUD',async()=>{const old=await snapshot();for(const t of tables){for(const role of ['crm_h0_runtime','anon','authenticated']){const sql=h.connect(role);for(const query of [`select * from crm_private.${t}`,`delete from crm_private.${t}`,`update crm_private.${t} set admin_scope='forged'`,`insert into crm_private.${t} default values`,`truncate crm_private.${t}`])await assert.rejects(sql.unsafe(query));}await assert.rejects(h.admin.begin(async tx=>{await tx.unsafe('set local role crm_h0_f2_executor');await tx.unsafe(`delete from crm_private.${t}`);}));await assert.rejects(h.admin.unsafe(`update crm_private.${t} set admin_scope=admin_scope`));}assert.deepEqual(await snapshot(),old);});
test('R66 exact scoped read no economic enumeration or third-party projection',async()=>{const {f}=await assigned();await assert.rejects(rawApply({paymentId:f.paymentId},'FORGED_SCOPE',false,true));for(const x of [{reference:'SYNTHETIC'}, {amount:'100.00'}, {paymentId:f.paymentId,bookingId:uid()}])await assert.rejects(rawApply(x,h.scope,false,true));assert.equal(await h.allocations.read(await h.auth(),read,uid()),null);const r=await f.see();assert.ok(!JSON.stringify(r).match(/bank_account|iban|margin|commission|profit/));});
test('R67 owners ACL RLS FORCE RLS explicit search_path checked',async()=>{for(const t of tables){const r=(await h.observer`select c.relrowsecurity,c.relforcerowsecurity,c.relowner::regrole::text owner from pg_class c where c.oid=${'crm_private.'+t}::regclass`)[0]!;assert.equal(r.owner,'crm_h0_f2_owner');assert.ok(r.relrowsecurity&&r.relforcerowsecurity);assert.equal((await h.observer`select count(*)::int n from pg_policy where polrelid=${'crm_private.'+t}::regclass`)[0]!.n,2);}const roles=await h.observer`select rolsuper,rolbypassrls,rolcanlogin,rolname from pg_roles where rolname in ('crm_h0_f2_executor','crm_h0_f2_owner','crm_h0_runtime')`;assert.ok(roles.every(x=>!x.rolsuper&&!x.rolbypassrls));assert.ok(roles.filter(x=>x.rolname!=='crm_h0_runtime').every(x=>!x.rolcanlogin));const fns=await h.observer`select p.prosecdef,p.proconfig::text,p.proowner::regrole::text owner,has_function_privilege('anon',p.oid,'execute') anonymous from pg_proc p where p.proname in ('allocation_apply','allocation_read')`;assert.equal(fns.length,2);assert.ok(fns.every(x=>x.prosecdef&&x.owner==='crm_h0_f2_executor'&&!x.anonymous&&x.proconfig.includes('pg_catalog, pg_temp')));});
test('R68 fresh install33 migrations coherent all8 allocation tables present',async()=>{assert.equal((await readdir('supabase/migrations')).filter(x=>x.endsWith('.sql')).length,33);assert.equal((await h.observer`select count(*)::int n from pg_tables where schemaname='crm_private' and tablename=any(${tables})`)[0]!.n,8);});
test('R69 populatedH3-004 upgrade preserves all old data objects and ACL',async()=>{const u=await isolatedAllocation('crm_h3_006_upgrade',55688,true);try{const f=await paymentFixture(u);await u.payments.apply(await u.auth(),write,f.detect);await u.payments.apply(await u.auth(),write,await f.receive());const old=await priorData(u),i=await inventory(u);await u.migration.unsafe(await readFile(`supabase/migrations/${allocationMigration}`,'utf8'));assert.deepEqual(await priorData(u),old);const a=await inventory(u);for(const k of ['tables','funcs','policies','triggers'] as const){const ids=new Set(i[k].map(x=>x.oid));const after=Array.from(a[k].filter(x=>ids.has(x.oid))),before=Array.from(i[k]);if(k==='funcs'){for(let n=0;n<before.length;n++)if(before[n]!.proname==='obligation_read'){assert.notEqual(after[n]!.def,before[n]!.def);after[n]={...after[n]!,def:before[n]!.def};}}assert.deepEqual(after,before);}assert.deepEqual(a.roles,i.roles);}finally{await u.close();}});
test('R70 failed migration rollback restores preceding schema grants roles',async()=>{const u=await isolatedAllocation('crm_h3_006_rollback',55689,true);try{const i=await inventory(u),sql=await readFile(`supabase/migrations/${allocationMigration}`,'utf8');await assert.rejects(u.migration.unsafe(sql.replace(/commit;\s*$/,'select 1/0;commit;')));await u.migration.unsafe('rollback');assert.deepEqual(await inventory(u),i);}finally{await u.close();}});
test('R71 optional roles absent installs without PUBLIC grant',async()=>{const u=await isolatedAllocation('crm_h3_006_no_roles',55690,true);try{await u.admin.unsafe('drop owned by anon;drop owned by authenticated;drop role anon;drop role authenticated');await u.migration.unsafe(await readFile(`supabase/migrations/${allocationMigration}`,'utf8'));assert.equal((await u.observer`select count(*)::int n from pg_tables where schemaname='crm_private' and tablename=any(${tables})`)[0]!.n,8);}finally{await u.close();}});
test('R72 forbidden paid implicit funding and rights from funds rejected',async()=>{const f=await allocationFixture(h),q=await f.assign('100.00');for(const extra of [{paid:true},{funding:'own'},{economicRight:'cancelled50percent'}])await neg(await f.attest({...q,...extra}),true);});
test('R73 allocation consumption not invoice ProviderPayment mandate Booking',async()=>{const {f}=await consumed('80.00');assert.equal((await h.booking.read(await h.auth(),read,f.f.b.bookingId) as {booking:{state:string}}).booking.state,'Pendiente de preparación');assert.equal((await f.see()).summary.externalReturned,null);});
test('R74 full Refund deposit Provider Payment commands unavailable',async()=>{const f=await allocationFixture(h),q=await f.assign();for(const action of ['refund','provider_payment','execute_deposit'])await neg(await f.attest({...q,action} as AllocationCommand),true);assert.equal((await f.see()).summary.representedReturned,'0.00');});
test('R75 exact32 prior migrations expected health-check preserved future absent',async()=>{const base='db37469a901d7543ae10e2ce42a95824b33d24ce',files=(await readdir('supabase/migrations')).filter(x=>x.endsWith('.sql')&&x<allocationMigration);assert.equal(files.length,32);for(const f of files){const path='supabase/migrations/'+f;assert.deepEqual(await readFile(path),execFileSync('git',['show',`${base}:${path}`]));}const paths=execFileSync('git',['ls-tree','-r','--name-only',base],{encoding:'utf8'}).split('\n').filter(p=>/health|KEEPALIVE|expected-TSK-H3-00[13]-00[24]|evidence-TSK-H3-00[1-4]/.test(p));for(const p of paths)assert.deepEqual(await readFile(p),execFileSync('git',['show',`${base}:${p}`]));assert.deepEqual(await readFile('specs/001-core-crm/expected-TSK-H3-005-006.md'),execFileSync('git',['show','034ddc0:specs/001-core-crm/expected-TSK-H3-005-006.md']));const names=(await h.observer`select tablename from pg_tables where schemaname='crm_private'`).map(x=>x.tablename);assert.ok(!names.some(t=>/refund|provider_payment|invoice|deposit_execution/.test(t)));});
