import {test,before,after} from 'node:test';import assert from 'node:assert/strict';
import {isolatedCancellation,read,write,cancellationTables} from '../support/h4-cancellation-isolated.ts';
import {cancellationFixture} from '../support/h4-cancellation-fixtures.ts';
let h:Awaited<ReturnType<typeof isolatedCancellation>>;before(async()=>{h=await isolatedCancellation();});after(async()=>{await h?.close();});
test('H4-014 independent C02/C03/C04 AC-033 base200 at7/3/2 civil days',async()=>{for(const [at,right,retention] of [['2026-10-13T23:00:00+02:00','200.00','0.00'],['2026-10-17T23:00:00+02:00','100.00','100.00'],['2026-10-18T01:00:00+02:00','0.00','200.00']]){const f=await cancellationFixture(h,{amount:'200.00'}),q=await f.command();const facts={...q.facts!,at:at!};const r=await f.run(await f.command({at,facts}));assert.equal(r.result.computed.right,right);assert.equal(r.result.computed.retention,retention);}});
import {randomUUID as uid} from 'node:crypto';
import {civilReference,localDate,zoneEvidence} from '../../src/domain/civil-time.ts';
import {determineCancellation,pendingCancellationRight} from '../../src/domain/cancellation-right.ts';
import type {CancellationCommand} from '../../src/infrastructure/postgres/h4-cancellation-adapter.ts';
const facts=(q:CancellationCommand,change:Record<string,unknown>)=>({...q.facts!,...change});
for(const cause of ['provider','huescaventura','no_show','late','alcohol_drugs','safety'] as const)test('H4-014 C01/C06 exact accredited cause '+cause,async()=>{const f=await cancellationFixture(h,{amount:'200.00'}),q=await f.command();const r=await f.run(await f.command({facts:facts(q,{cause})}));assert.equal(r.result.computed.right,['provider','huescaventura'].includes(cause)?'200.00':'0.00');assert.equal(r.result.computed.retention,['provider','huescaventura'].includes(cause)?'0.00':'200.00');assert.equal((await h.observer`select count(*)::int n from crm_private.b06_cancellation_applications where determination_id=${f.did}::uuid`)[0]!.n,0);});
test('H4-014 C01/C05 non-refundable only explicit accepted clause, provider100 regardless',async()=>{const f=await cancellationFixture(h,{amount:'200.00',terms:'D011; SYNTHETIC NONREFUNDABLE expressly communicated and accepted'}),q=await f.command(),clause='SYNTHETIC NONREFUNDABLE',eid=await f.conf.proof('cancellation:nonrefundable:'+await f.conf.hash({acceptanceId:f.b.acceptanceId,terms:f.b.terms,clause}),f.b.bookingId);for(const cause of ['voluntary','provider'] as const){const r=await f.run(await f.command({expectedRevision: cause==='provider'?1:0,facts:facts(q,{cause,nonRefundable:{clause,evidenceId:eid}})}));assert.equal(r.result.computed.right,cause==='voluntary'?'0.00':'200.00');}const other=await cancellationFixture(h,{amount:'200.00'}),oq=await other.command();await assert.rejects(other.run(await other.command({facts:facts(oq,{nonRefundable:{clause,evidenceId:eid}})})),/ACCEPTANCE_REQUIRED/);assert.equal(await other.see(),null);});
test('H4-014 C09/C10 AC040 pending base then explicit administrator attribution local only',async()=>{const f=await cancellationFixture(h,{scopeKind:'service'}),q=await f.command();await f.applyOperational();const pending=await f.command({expectedModificationRevision:(await f.m.see())!.revision,expectedScopeToken:await f.token(),facts:facts(q,{base:await f.base(null)})});const r=await f.run(pending);assert.equal(r.result.computed.status,'pending');assert.equal(r.result.computed.right,null);assert.equal(r.result.computed.missing.includes('base:D019'),true);const after=await f.run(await f.command({expectedRevision:1,facts:facts(q,{cause:'provider',base:await f.base('200.00')})}));assert.equal(after.result.computed.right,'200.00');assert.equal((await f.see()).history.length,2);assert.equal((await f.m.see())!.progress,'Aplicada');assert.equal((await f.m.see() as any).economic.status,'pending');});
test('H4-014 C07 PM07 fixed900 partial participant never implicitly prorated',async()=>{const f=await cancellationFixture(h,{amount:'900.00',scopeKind:'service'}),q=await f.command();const r=await f.run(await f.command({facts:facts(q,{base:await f.base(null,'fixed')})}));assert.equal(r.result.computed.status,'pending');assert.equal(r.result.computed.right,null);const row=(await h.observer`select snapshot->>'final_person_price' price from crm_private.b04_modalities where booking_id=${f.b.bookingId}::uuid limit 1`)[0]!;assert.equal(row.price,'900.00');await assert.rejects(f.run(await f.command({expectedRevision:1,facts:facts(q,{base:{kind:'fixed',amount:'75.00',count:1,start:0,components:[]}})})),/ADMIN_BASE_REQUIRED/);});
test('H4-014 C08 AC039 modalityB120 uses first own22 at4days, no average or dateA20',async()=>{const f=await cancellationFixture(h,{amount:'120.00',index:1}),q=await f.command(),at='2026-10-18T12:00:00+02:00';const r=await f.run(await f.command({at,facts:facts(q,{at})}));assert.equal(r.result.computed.temporal.reference.date,'2026-10-22');assert.equal(r.result.computed.temporal.daysBefore,4);assert.equal(r.result.computed.retention,'60.00');await assert.rejects(f.run(await f.command({expectedRevision:1,facts:facts(q,{reference:{...q.facts!.reference!,date:localDate('2026-10-20')}})})),/REFERENCE_REQUIRED/);});
for(const [kind,index,dates,expected] of [['booking',0,['2026-10-20','2026-10-22'],'2026-10-20'],['modality',1,['2026-10-20','2026-10-22'],'2026-10-22'],['night',1,['2026-10-20','2026-10-23'],'2026-10-23']] as const)test('H4-014 C11 AC041 legitimate '+kind+' reference '+expected,async()=>{const f=await cancellationFixture(h,{scopeKind:kind,index,night:kind==='night',dates:[...dates]}),q=await f.command();const base=kind==='modality'?q.facts!.base:await f.base('200.00');const r=await f.run(await f.command({facts:facts(q,{base})}));assert.equal(r.result.computed.temporal.reference.date,expected);});
for(const at of ['2026-10-13T00:01:00+02:00','2026-10-13T23:59:59+02:00','2026-10-17T00:01:00+02:00','2026-10-17T23:59:59+02:00','2026-10-17T21:59:59Z'])test('H4-014 C12 AC042 full civil day '+at,async()=>{const f=await cancellationFixture(h,{amount:'200.00'}),q=await f.command();const r=await f.run(await f.command({at,facts:facts(q,{at})}));assert.equal(r.result.computed.right,at.includes('-13')?'200.00':'100.00');});
test('H4-014 C12 explicit non-Madrid zone changes date only; no universal environment default',async()=>{const f=await cancellationFixture(h,{amount:'200.00'}),q=await f.command(),at='2026-10-14T02:00:00Z',reference={...q.facts!.reference!,zone:zoneEvidence('America/New_York','SYNTHETIC accepted applicable zone','1')};const r=await f.run(await f.command({at,facts:facts(q,{at,reference})}));assert.equal(r.result.computed.temporal.actDate,'2026-10-13');assert.equal(r.result.computed.right,'200.00');});
for(const [key,change] of [['G01 cause',{cause:null}],['G05 base',{base:{kind:'component',amount:null,count:1,start:0,components:[]}}],['G06 reference',{reference:null}]] as const)test('H4-014 '+key+' removed gives explicit E3 pending, no amount0',async()=>{const f=await cancellationFixture(h),q=await f.command();const r=await f.run(await f.command({facts:facts(q,change)}));assert.equal(r.result.computed.status,'pending');assert.equal(r.result.computed.right,null);assert.equal(r.result.computed.calculation,null);assert.equal(r.result.applied,false);});
const guards:[string,(q:CancellationCommand)=>CancellationCommand][]=[
 ['G02 policy version',q=>({...q,facts:facts(q,{policy:{...q.facts!.policy,version:''}})})],
 ['G02 policy rule',q=>({...q,facts:facts(q,{policy:{...q.facts!.policy,rule:'unapproved_rule' as any}})})],
 ['G03 accepted terms',q=>({...q,facts:facts(q,{policy:{...q.facts!.policy,terms:{text:'unaccepted'}}})})],
 ['G04 actual cancelled part',q=>({...q,partId:uid()})],
 ['G07 zone provenance',q=>({...q,facts:facts(q,{reference:{...q.facts!.reference,zone:{zone:'Europe/Madrid',sourceRef:'',version:'1'}}})})],
 ['G08 reviewed evidence',q=>({...q,evidenceId:uid()})],
 ['G10 amount never group average',q=>({...q,facts:facts(q,{base:{...q.facts!.base,amount:'50.00'}})})],
 ['G10 participation scope count',q=>({...q,facts:facts(q,{base:{...q.facts!.base,count:2}})})],
 ['G10 wrong modality',q=>({...q,facts:facts(q,{base:{...q.facts!.base,modalityId:uid()}})})],
 ['G11 stale material token',q=>({...q,expectedScopeToken:'obsolete'})],
 ['G11 stale modification',q=>({...q,expectedModificationRevision:0})],
 ['G33 sensitive AI origin',q=>({...q,origin:'ai'})]
];
for(const [id,remove] of guards)test('H4-014 '+id+' individually rejected with no root/history/effect',async()=>{const f=await cancellationFixture(h),q=await f.command(),bad=remove(q);const value=id.includes('evidence')?bad:await f.attest(bad);await assert.rejects(f.run(value));assert.equal(await f.see(),null);});
test('H4-014 C26 equivalent operation/new operationId no material duplication; changed material E2',async()=>{const f=await cancellationFixture(h),q=await f.command();await f.run(q);assert.equal((await f.run(q)).replayed,true);assert.equal((await f.run(await f.attest({...q,operationId:uid()}))).replayed,true);assert.equal((await f.see()).history.length,1);await assert.rejects(f.run(await f.attest({...q,reason:'SYNTHETIC distinct material'})),/E2/);await assert.rejects(f.run(await f.attest({...q,operationId:uid(),determinationId:uid()})),/PORTION_CONFLICT/);});
import {cancellationSchedule,cancellationApplication} from '../support/h4-cancellation-fixtures.ts';
async function appliedFixture(){const f=await cancellationFixture(h);const s=await cancellationSchedule(h,f);await f.applyOperational();await f.run(await f.command());const original=(await h.obligations.read(await h.auth(),read,f.b.bookingId,s.sid))!.current.snapshot.parts;const parts=original.map(p=>({...p,amount:p.slot==='initial'?'50.00':'100.01'}));const q=await cancellationApplication(h,f,s.sid,parts);return {f,s,original,parts,q};}
test('H4-014 C19 SM-EP04 internal legitimate obligation adjustment after exact right, no money move',async()=>{const x=await appliedFixture(),before=(await h.observer`select count(*)::int n from crm_private.b05_payment_operations`)[0]!.n;const r=await x.f.run(x.q);assert.equal(r.result.applied,true);assert.equal(r.result.application.movementExecuted,false);const old=(await h.obligations.read(await h.auth(),read,x.f.b.bookingId,x.s.sid))!;assert.equal(old.current.snapshot.parts.find(p=>p.slot==='initial')!.amount,'50.00');assert.equal(old.original.find(p=>p.slot==='initial')!.amount,'100.01');assert.equal((await h.observer`select count(*)::int n from crm_private.b05_payment_operations`)[0]!.n,before);assert.equal((await x.f.run(x.q)).replayed,true);assert.equal((await x.f.run(await x.f.attest({...x.q,operationId:uid()}))).replayed,true);assert.equal((await x.f.see()).history.length,2);});
for(const [id,remove] of [
 ['G12 wrong obligation',(q:any)=>({...q,adjustment:{...q.adjustment,scheduleId:uid()}})],
 ['G14 amount not legitimate',(q:any)=>({...q,adjustment:{...q.adjustment,parts:q.adjustment.parts.map((p:any)=>({...p,amount:'0.00'}))}})],
 ['G15 exact economic approval',(q:any)=>({...q,adjustment:{...q.adjustment,approvalEvidenceId:uid()}})],
 ['G16 schedule revision',(q:any)=>({...q,adjustment:{...q.adjustment,expectedRevision:0}})],
 ['G18 different effect',(q:any)=>({...q,adjustment:{...q.adjustment,parts:q.adjustment.parts.map((p:any)=>({...p,due:{kind:'before_confirmation'}}))}})]
 ] as [string,(q:any)=>any][])test('H4-014 SM-EP04 '+id+' individually rejected with obligations unchanged',async()=>{const x=await appliedFixture(),before=await h.obligations.read(await h.auth(),read,x.f.b.bookingId,x.s.sid);await assert.rejects(x.f.run(await x.f.attest(remove(x.q))));assert.deepEqual(await h.obligations.read(await h.auth(),read,x.f.b.bookingId,x.s.sid),before);assert.equal((await x.f.see()).revision,1);});
test('H4-014 G09 Admin decision must be a real case record, exact proof, components and motive',async()=>{const f=await cancellationFixture(h,{scopeKind:'service'}),q=await f.command(),base=await f.base('200.00');for(const removed of ['recordId','evidenceId','reason','components']){const b:any=structuredClone(base);if(removed==='components')b.components=[];else delete b.administratorDecision[removed];await assert.rejects(f.run(await f.command({facts:facts(q,{base:b})})));assert.equal(await f.see(),null);}});
import {allocationFixture} from '../support/h3-allocation-fixtures.ts';
for(const [stage,received,correspondence,assigned] of [['none','0.00','0.00',false],['received','40.00','40.00',false],['verified','100.00','100.00',false],['verified','100.00','100.00',true]] as const)test('H4-014 C18 real H3 funds '+stage+'/'+assigned+' cannot change contractual right',async()=>{const a=await allocationFixture(h,received,correspondence,stage,'200.00');if(assigned)await h.allocations.apply(await h.auth(),write,await a.assign());const f=await cancellationFixture(h,{existing:a.f,amount:'200.00'}),q=await f.command();const r=await f.run(q);assert.equal(r.result.computed.right,'100.00');assert.equal(r.result.computed.retention,'100.00');const before=await h.allocations.read(await h.auth(),read,a.paymentId);await f.run(q);assert.deepEqual(await h.allocations.read(await h.auth(),read,a.paymentId),before);});
test('H4-014 C20 SM-RC02 admitted cancellation basis resolves real determination and old bases cannot bypass it',async()=>{const a=await allocationFixture(h,'100.00','100.00','verified','200.00'),f=await cancellationFixture(h,{existing:a.f,amount:'200.00'});await f.run(await f.command());const initial=await a.assign('100.00');const basis={kind:'cancellation' as const,amount:'100.00',originalRef:f.did,sourceRef:'SYNTHETIC durable D019',version:'h4-d011-d019-d020-d023-v1'};const eid=await a.proof(a.paymentId,'fund-right:'+await f.conf.hash(basis));const q=await a.attest({...initial,cause:'cancellation',economicBasis:{...basis,evidenceId:eid}});await h.allocations.apply(await h.auth(),write,q);assert.equal((await a.see()).summary.assigned,'100.00');const g=await allocationFixture(h,'100.00','100.00','verified','200.00'),b={...basis,originalRef:g.f.q.scheduleId!},be=await g.proof(g.paymentId,'fund-right:'+await f.conf.hash(b));await assert.rejects(h.allocations.apply(await h.auth(),write,await g.attest({...await g.assign('100.00'),cause:'cancellation',economicBasis:{...b,evidenceId:be}})),e=>e instanceof Error&&e.message==='ALLOCATION_DENIED');});
test('H4-014 C15 PM06 pure fixed right with existing B07 manual statement facts, Refund integration explicitly not accredited',async()=>{const f=await cancellationFixture(h),r=await f.run(await f.command());assert.equal(r.result.computed.right,'50.01');const record=await f.conf.record(),proof=await f.conf.proof('SYNTHETIC accredited customer outflow20.00; original:'+record,f.b.bookingId);const observed=(await h.observer`select material from crm_private.b07_records where record_id=${proof}::uuid`)[0]!.material;assert.equal(observed.claim,'SYNTHETIC accredited customer outflow20.00; original:'+record);assert.equal(pendingCancellationRight(r.result.computed.right,['20.00']),'30.01');assert.equal((await f.see()).applied,false);assert.equal((await h.observer`select count(*)::int n from crm_private.b06_cancellation_applications where determination_id=${f.did}::uuid`)[0]!.n,0);console.log('PM06 arithmetic and synthetic B07 fact only; no Refund authorization/execution integration accredited.');});
for(const role of ['crm_h0_runtime','anon','authenticated'])test('H4-014 C25 '+role+' direct CRUD and helper execution denied',async()=>{for(const table of cancellationTables)for(const query of [`select * from crm_private.${table}`,`update crm_private.${table} set admin_scope='fake'`,`delete from crm_private.${table}`,`insert into crm_private.${table} default values`])await assert.rejects(h.connect(role).unsafe(query));await assert.rejects(h.connect(role).unsafe("select crm_private.cancellation_computed('{}','{}')"));});
test('H4-014 C25 FORCE RLS owners privileges and explicit safe search_path',async()=>{for(const table of cancellationTables){const r=(await h.observer`select relrowsecurity,relforcerowsecurity,pg_get_userbyid(relowner) owner from pg_class where oid=${'crm_private.'+table}::regclass`)[0]!;assert.equal(r.relrowsecurity,true);assert.equal(r.relforcerowsecurity,true);assert.equal(r.owner,'crm_h0_f2_owner');}const role=(await h.observer`select rolsuper,rolbypassrls from pg_roles where rolname='crm_h0_runtime'`)[0]!;assert.equal(role.rolsuper,false);assert.equal(role.rolbypassrls,false);for(const p of await h.observer`select p.proname,p.proconfig,has_function_privilege('crm_h0_runtime',p.oid,'EXECUTE') access from pg_proc p where p.proname like 'cancellation_%'`){assert.ok((p.proconfig as string[]).includes('search_path=pg_catalog, pg_temp'));assert.equal(p.access,['cancellation_read','cancellation_apply'].includes(String(p.proname)));}assert.equal((await h.observer`select count(*)::int n from pg_proc p cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where p.proname like 'cancellation_%' and a.grantee=0`)[0]!.n,0);});
test('H4-014 C24 no cross-booking/evidence disclosure or enumeration; minimal C06',async()=>{const f=await cancellationFixture(h),other=await cancellationFixture(h);await f.run(await f.command());for(const did of [f.did,uid()])assert.equal(await h.cancellations.read(await h.auth(),read,other.b.bookingId,did),null);const q=await f.command();await assert.rejects(f.run(await f.attest({...q,bookingId:other.b.bookingId})));await assert.rejects(f.run({...q,operationId:uid(),evidenceId:(await other.command()).evidenceId}));const projection=JSON.stringify(await h.cancellations.read(await h.auth(),read,f.b.bookingId,f.did,'right'));for(const key of ['sourceRef','evidenceId','original','cost','margin','participantName','actorId','components','terms'])assert.equal(projection.includes(key),false);});
test('H4-014 C23 fake/missing envelopes cannot admit C01 or C03',async()=>{for(const api of ['read','apply'])await assert.rejects(h.runtime.unsafe(`select crm_api.cancellation_${api}(${Array(5).fill("'fake'::bytea").join(',')})`));const f=await cancellationFixture(h),q=await f.command();await assert.rejects(h.cancellations.apply({} as any,write,q),/AUTH_REQUIRED/);await assert.rejects(h.cancellations.apply(await h.auth(),{} as any,q),/AUTH_REQUIRED/);assert.equal(await f.see(),null);});
for(const mode of ['actor','session'])test('H4-014 C23 '+mode+' revoked prevents read write and replay',async()=>{const u=await isolatedCancellation('crm_f14_'+mode,mode==='actor'?56830:56831);try{const f=await cancellationFixture(u),q=await f.command();await f.run(q);const auth=await u.auth();if(mode==='actor')await u.admin`update crm_private.crm_actors set enabled=false where actor_id=${u.actorId}::uuid`;else await u.admin`update crm_private.crm_sessions set revoked_at=clock_timestamp() where session_id=${u.sessionId}::uuid`;await assert.rejects(u.cancellations.read(auth,read,f.b.bookingId,f.did));await assert.rejects(u.cancellations.apply(auth,write,q));}finally{await u.close();}});
test('H4-014 C25 append-only determination and economic approval are immutable',async()=>{const x=await appliedFixture();await x.f.run(x.q);const f=x.f;for(const t of cancellationTables)await assert.rejects(h.migration.unsafe(`update crm_private.${t} set admin_scope='false' where determination_id='${f.did}'`));});
import {modificationFixture} from '../support/h4-modification-fixtures.ts';
const snap=async(u=h,names=cancellationTables)=>Object.fromEntries(await Promise.all(names.map(async name=>[name,(await u.observer.unsafe(`select to_jsonb(x)::text value from crm_private.${name} x order by to_jsonb(x)::text`)).map(x=>x.value)])));
const delay=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function overlap(f:Awaited<ReturnType<typeof cancellationFixture>>,jobs:(()=>Promise<any>)[],order=[0,1]){
 const blocker=h.connect('crm_h0_migration');await blocker.unsafe('begin');await blocker`select pg_advisory_xact_lock(hashtextextended(${f.b.opportunityId},31))`;
 const pending:Promise<any>[]=[];try{for(let i=0;i<order.length;i++){pending.push(jobs[order[i]!]!().then(value=>({ok:true,value}),error=>({ok:false,error:error.message})));let observed=0;for(let n=0;n<100;n++){observed=Number((await h.admin`select count(*)::int n from pg_stat_activity where usename='crm_h0_runtime' and wait_event_type='Lock'`)[0]!.n);if(observed>=i+1)break;await delay(10);}console.log('H4-014 observed PostgreSQL lock overlap',order,'queued',i+1,'sessions',observed);assert.ok(observed>=i+1);}await blocker.unsafe('rollback');return await Promise.all(pending);}finally{await blocker.unsafe('rollback');}}
for(const order of [[0,1],[1,0]])test('H4-014 C27 competing determinations with actual independent PG sessions '+order,async()=>{const f=await cancellationFixture(h,{amount:'200.00'}),q=await f.command(),b=await f.command({facts:facts(q,{cause:'provider'})});const r=await overlap(f,[()=>f.run(q),()=>f.run(b)],order);assert.equal(r.filter(x=>x.ok).length,1);assert.match(r.find(x=>!x.ok)!.error,/REVISION_CONFLICT:E2/);assert.equal((await f.see()).computed.right,order[0]===0?'100.00':'200.00');assert.equal((await f.see()).history.length,1);});
for(const order of [[0,1],[1,0]])test('H4-014 C27 equivalent concurrent replay independent sessions '+order,async()=>{const f=await cancellationFixture(h),q=await f.command();const r=await overlap(f,[()=>f.run(q),()=>f.run(q)],order);assert.equal(r.filter(x=>x.ok).length,2);assert.equal((await f.see()).history.length,1);assert.equal(r.filter(x=>x.value.replayed).length,1);});
for(const order of [[0,1],[1,0]])test('H4-014 C28 determination versus applied actual service date change '+order,async()=>{const f=await cancellationFixture(h,{amount:'200.00'}),q=await f.command(),change=await modificationFixture(h,f.conf);await change.run(await change.request([{id:change.partId,scope:change.scope,expectedScopeRevision:1,desired:{date:'2026-10-22'},aspects:['date'],dependencies:[]} ]));await change.run(await change.evaluate());await change.run(await change.approve());const apply=await change.apply();const before=await h.booking.read(await h.auth(),read,f.b.bookingId),r=await overlap(f,[()=>f.run(q),()=>change.run(apply)],order);if(order[0]===1){assert.equal(r.find(x=>!x.ok)!.error,'CANCELLATION_REVISION_CONFLICT:E2');assert.equal(await f.see(),null);}else{assert.equal(r.every(x=>x.ok),true);assert.equal((await h.cancellations.read(await h.auth(),read,f.b.bookingId,f.did,'right')).currentlyApplicable,false);}const current:any=await h.booking.read(await h.auth(),read,f.b.bookingId);assert.equal(current.booking.detail.services[0].date,'2026-10-22');assert.deepEqual(current.booking.accepted_detail,(before as any).booking.accepted_detail??(before as any).booking.detail);const next=await f.command({expectedRevision:order[0]===0?1:0,expectedScopeToken:await f.token(),facts:facts(q,{reference:{...q.facts!.reference!,date:localDate('2026-10-22')}})});const updated=await f.run(next);assert.equal(updated.result.computed.temporal.daysBefore,5);assert.equal(updated.result.computed.temporal.reference.date,'2026-10-22');});
for(const order of [[0,1],[1,0]])test('H4-014 C27 different exact obligation approvals compete no overwrite '+order,async()=>{const x=await appliedFixture(),alt=x.original.map(p=>({...p,amount:p.slot==='balance'?'50.00':'100.01'})),q2=await cancellationApplication(h,x.f,x.s.sid,alt);const r=await overlap(x.f,[()=>x.f.run(x.q),()=>x.f.run(q2)],order);assert.equal(r.filter(x=>x.ok).length,1);assert.equal(r.filter(x=>!x.ok).length,1);assert.equal((await x.f.see()).history.length,2);assert.equal((await h.observer`select count(*)::int n from crm_private.b06_cancellation_applications where determination_id=${x.f.did}::uuid`)[0]!.n,1);});
for(const table of ['b06_cancellation_determinations','b06_cancellation_operations','b06_cancellation_revisions'])test('H4-014 C29 injected write '+table+' exact rollback then retry',async()=>{const f=await cancellationFixture(h),q=await f.command(),before=await snap();await h.admin.unsafe("create function crm_private.f14_fault() returns trigger language plpgsql as $$begin raise exception 'SYNTHETIC_F14_WRITE_FAULT';end$$");await h.admin.unsafe(`create trigger f14_fault before insert on crm_private.${table} for each row execute function crm_private.f14_fault()`);try{await assert.rejects(f.run(q));assert.deepEqual(await snap(),before);}finally{await h.admin.unsafe(`drop trigger f14_fault on crm_private.${table}`);await h.admin.unsafe('drop function crm_private.f14_fault()');}await f.run(q);assert.equal((await f.see()).revision,1);});
for(const table of ['b05_schedule_revisions','b05_obligation_adjustments','b05_obligation_operations','b05_obligation_history','b06_cancellation_applications','b06_cancellation_operations','b06_cancellation_revisions'])test('H4-014 C29 dependent '+table+' rollback all obligation coverage history result',async()=>{const x=await appliedFixture(),names=[...cancellationTables,'b05_schedule_revisions','b05_obligation_adjustments','b05_obligation_operations','b05_obligation_history','b05_coverage_evaluations'],before=await snap(h,names),reader=await h.obligations.read(await h.auth(),read,x.f.b.bookingId,x.s.sid);await h.admin.unsafe("create function crm_private.f14_fault() returns trigger language plpgsql as $$begin raise exception 'SYNTHETIC_F14_DEPENDENT_FAULT';end$$");await h.admin.unsafe(`create trigger f14_fault before insert on crm_private.${table} for each row execute function crm_private.f14_fault()`);try{await assert.rejects(x.f.run(x.q));assert.deepEqual(await snap(h,names),before);assert.deepEqual(await h.obligations.read(await h.auth(),read,x.f.b.bookingId,x.s.sid),reader);}finally{await h.admin.unsafe(`drop trigger f14_fault on crm_private.${table}`);await h.admin.unsafe('drop function crm_private.f14_fault()');}await x.f.run(x.q);assert.equal((await x.f.see()).applied,true);});
test('H4-014 C29 deferred real COMMIT failure exact rollback and valid retry',async()=>{const x=await appliedFixture(),names=[...cancellationTables,'b05_schedule_revisions','b05_obligation_adjustments','b05_obligation_history','b05_coverage_evaluations'],before=await snap(h,names);await h.admin.unsafe("create function crm_private.f14_commit_fault() returns trigger language plpgsql as $$begin raise exception 'SYNTHETIC_F14_COMMIT_FAULT';end$$");await h.admin.unsafe('create constraint trigger f14_commit_fault after insert on crm_private.b06_cancellation_operations deferrable initially deferred for each row execute function crm_private.f14_commit_fault()');try{await assert.rejects(x.f.run(x.q));assert.deepEqual(await snap(h,names),before);}finally{await h.admin.unsafe('drop trigger f14_commit_fault on crm_private.b06_cancellation_operations');await h.admin.unsafe('drop function crm_private.f14_commit_fault()');}await x.f.run(x.q);assert.equal((await x.f.see()).applied,true);});
import {H4013CancellationAdapter} from '../../src/infrastructure/postgres/h4-cancellation-adapter.ts';
test('H4-014 C30 response lost strictly after real COMMIT recover durable result without second effect',async()=>{const x=await appliedFixture();const lost={begin:async(options:any,work:any)=>{await h.runtime.begin(options,work);throw new Error('SYNTHETIC_RESPONSE_LOST_AFTER_REAL_COMMIT');}} as unknown as typeof h.runtime;const adapter=new H4013CancellationAdapter(lost,h.f1,h.f2);await assert.rejects(adapter.apply(await h.auth(),write,x.q));assert.equal((await x.f.see()).applied,true);const before=await snap();assert.equal((await x.f.run(x.q)).replayed,true);assert.deepEqual(await snap(),before);});
import {providerPaymentFixture} from '../support/h3-provider-payment-fixtures.ts';
test('H4-014 C01/C18 real H3 accredited provider outgoing20 cannot reduce client right200',async()=>{const p=await providerPaymentFixture(h,'100.00','20.00');await h.providerPayments.apply(await h.auth(),write,await p.open());const f=await cancellationFixture(h,{existing:p.su.funds.f,scopeKind:'service'}),q=await f.command(),decision=await f.command({facts:facts(q,{cause:'provider',base:await f.base('200.00')})});assert.equal((await f.run(decision)).result.computed.right,'200.00');const a=await p.assign('20.00');await h.providerPayments.apply(await h.auth(),write,await p.movement([await p.portion(a)],'20.00'));assert.equal((await p.view())!.paid,'20.00');const after=await f.run(await f.command({expectedRevision:1,facts:decision.facts}));assert.equal(after.result.computed.right,'200.00');assert.equal(after.result.computed.retention,'0.00');});
test('H4-014 C17 historical executed economic decision preserved after new cause evaluation, no automatic debt/refund',async()=>{const x=await appliedFixture();await x.f.run(x.q);const reader=await h.obligations.read(await h.auth(),read,x.f.b.bookingId,x.s.sid),q=await x.f.command(),r=await x.f.run(await x.f.command({expectedRevision:2,facts:facts(q,{cause:'provider'})}));assert.equal(r.result.computed.right,'100.01');assert.equal(r.result.applied,false);assert.equal(r.result.previousApplication.scheduleRevision,2);assert.deepEqual(await h.obligations.read(await h.auth(),read,x.f.b.bookingId,x.s.sid),reader);assert.equal((await x.f.see()).history.length,3);});
test('H4-014 C24 structured component trace refuses unnecessary personal fields',async()=>{const f=await cancellationFixture(h),q=await f.command();await assert.rejects(f.run(await f.command({facts:facts(q,{base:{...q.facts!.base,components:[{name:'SYNTHETIC not needed',dni:'SYNTHETIC forbidden extraction'}]}})})),/COMPONENTS_REQUIRED/);assert.equal(await f.see(),null);});
test('H4-014 C16 overlapping determinations rejected; disjoint participation portions continue without duplicate right',async()=>{const f=await cancellationFixture(h,{count:3}),q=await f.command();await f.run(await f.command({facts:facts(q,{base:{...q.facts!.base,count:2,start:0}})}));await assert.rejects(f.run(await f.command({determinationId:uid(),facts:facts(q,{base:{...q.facts!.base,count:2,start:1}})})),/PORTION_CONFLICT/);const next=await f.run(await f.command({determinationId:uid(),facts:facts(q,{base:{...q.facts!.base,count:1,start:2}})}));assert.equal(next.result.computed.right,'50.01');assert.equal((await f.see()).computed.right,'100.02');assert.equal((await h.observer`select count(*)::int n from crm_private.b06_cancellation_determinations where booking_id=${f.b.bookingId}::uuid`)[0]!.n,2);});
test('H4-014 G13/G14 pending determination cannot authorize any obligation effect',async()=>{const f=await cancellationFixture(h),s=await cancellationSchedule(h,f);await f.applyOperational();const q=await f.command();await f.run(await f.command({facts:facts(q,{cause:null})}));const before=await h.obligations.read(await h.auth(),read,f.b.bookingId,s.sid);await assert.rejects(f.run(await cancellationApplication(h,f,s.sid,before!.current.snapshot.parts)),/DETERMINATION_REQUIRED/);assert.deepEqual(await h.obligations.read(await h.auth(),read,f.b.bookingId,s.sid),before);});
for(const guard of ['client','provider','constraints'])test('H4-014 G29/G30/G4 SM-MO05 missing '+guard+' proof cannot approve or determine economic effect',async()=>{const f=await cancellationFixture(h);await f.m.run(await f.m.evaluate());const q=await f.m.approve(),data:any=structuredClone(q.data);delete data.proofs[f.m.partId][guard];await assert.rejects(f.m.run(await f.m.attest({...q,data})));assert.equal((await f.m.see())!.progress,'En evaluación');});
test('H4-014 C16/C28 S2 modality remains applicable after S1 date changes; no parent-wide invalidation',async()=>{const a=await cancellationFixture(h),b=await cancellationFixture(h,{existing:{f:a.f,b:a.b,detail:a.detail},index:1});await a.run(await a.command());await b.run(await b.command());const m=await modificationFixture(h,a.conf);await m.run(await m.request([{id:m.partId,scope:m.scope,expectedScopeRevision:1,desired:{date:'2026-10-22'},aspects:['date'],dependencies:[]} ]));await m.run(await m.evaluate());await m.run(await m.approve());await m.run(await m.apply());assert.equal((await h.cancellations.read(await h.auth(),read,a.b.bookingId,a.did,'right')).currentlyApplicable,false);assert.equal((await h.cancellations.read(await h.auth(),read,b.b.bookingId,b.did,'right')).currentlyApplicable,true);assert.equal((await b.see()).computed.temporal.reference.date,'2026-10-22');});
test('H4-014 C16 parent participation and same-service component cannot create competing rights',async()=>{const a=await cancellationFixture(h),b=await cancellationFixture(h,{existing:{f:a.f,b:a.b,detail:a.detail},scopeKind:'service'});await a.run(await a.command());const q=await b.command();await assert.rejects(b.run(await b.command({facts:facts(q,{base:await b.base('100.01')})})),/PORTION_CONFLICT/);assert.equal(await b.see(),null);});
test('H4-014 C07 PM07 explicit legitimate fixed900 remains900 without dividing by participants',async()=>{const f=await cancellationFixture(h,{amount:'900.00',count:12,scopeKind:'service'}),q=await f.command();const r=await f.run(await f.command({facts:facts(q,{cause:'provider',base:await f.base('900.00','fixed')})}));assert.equal(r.result.computed.baseTotal,'900.00');assert.equal(r.result.computed.right,'900.00');assert.equal(r.result.computed.retention,'0.00');assert.equal(r.result.facts.base.count,1);});
test('H4-014 C13 express accepted reference only its scoped contract, not arbitrary date or other modality',async()=>{const f=await cancellationFixture(h,{amount:'200.00',terms:'D011 voluntary; SYNTHETIC A explicit contractual reference 2026-10-24'}),q=await f.command(),reference={...q.facts!.reference!,date:localDate('2026-10-24'),basis:'express_contract' as const};assert.equal((await f.run(await f.command({facts:facts(q,{reference})}))).result.computed.right,'200.00');for(const ref of [{...reference,date:localDate('2026-10-30')},{...reference,scopeId:f.f.other}])await assert.rejects(f.run(await f.command({expectedRevision:1,facts:facts(q,{reference:ref})})),/REFERENCE_REQUIRED/);assert.equal((await f.see()).history.length,1);});
for(const order of [[0,1],[1,0]])test('H4-014 C27 distinct identities competing overlapping participation rights '+order,async()=>{const f=await cancellationFixture(h,{count:3}),q=await f.command(),a=await f.command({facts:facts(q,{base:{...q.facts!.base,count:2,start:0}})}),b=await f.command({determinationId:uid(),facts:facts(q,{base:{...q.facts!.base,count:2,start:1}})});const r=await overlap(f,[()=>f.run(a),()=>f.run(b)],order);assert.equal(r.filter(x=>x.ok).length,1);assert.match(r.find(x=>!x.ok)!.error,/PORTION_CONFLICT:E2/);assert.equal((await h.observer`select count(*)::int n from crm_private.b06_cancellation_determinations where booking_id=${f.b.bookingId}::uuid`)[0]!.n,1);});
for(const [guard,change] of [
 ['G19 authorized reviewed source',(q:any)=>({...q,evidenceId:uid()})],
 ['G20 reconstructible portion',(q:any)=>({...q,start:'90.00',amount:'20.00'})],
 ['G21 actual destination',(q:any)=>({...q,destination:{...q.destination,bookingId:uid()}})],
 ['G22 no overassignment',(q:any)=>({...q,amount:'100.01'})],
 ['G24 uncertain reconciliation',(q:any)=>({...q,expectedReconciliationRevision:1})]
] as [string,(q:any)=>any][])test('H4-014 SM-RC02 '+guard+' individually removed on current45 with durable D019 basis',async()=>{const a=await allocationFixture(h,'100.00','100.00','verified','200.00'),f=await cancellationFixture(h,{existing:a.f,amount:'200.00'});await f.run(await f.command());const basis={kind:'cancellation' as const,amount:'100.00',originalRef:f.did,sourceRef:'SYNTHETIC durable D019',version:'h4-d011-d019-d020-d023-v1'},eid=await a.proof(a.paymentId,'fund-right:'+await f.conf.hash(basis)),q=await a.attest({...await a.assign('100.00'),cause:'cancellation',economicBasis:{...basis,evidenceId:eid}}),bad=change(q),before=await a.see();await assert.rejects(h.allocations.apply(await h.auth(),write,guard.startsWith('G19')?bad:await a.attest(bad)));assert.deepEqual(await a.see(),before);});
test('H4-014 G17 SM-EP04 missing decision evidence preserves whole obligation and determination',async()=>{const x=await appliedFixture(),before=await h.obligations.read(await h.auth(),read,x.f.b.bookingId,x.s.sid);await assert.rejects(x.f.run({...x.q,evidenceId:uid()}));assert.deepEqual(await h.obligations.read(await h.auth(),read,x.f.b.bookingId,x.s.sid),before);assert.equal((await x.f.see()).revision,1);});

test('H4-014 C16 distinct actual H2 modality prices never mixed; per-participation rights sum after materialization',async()=>{const a=await cancellationFixture(h,{count:3,amount:'100.01',otherAmount:'120.00'}),b=await cancellationFixture(h,{existing:{f:a.f,b:a.b,detail:a.detail},index:1,count:3,amount:'120.00'});const x=await a.run(await a.command()),y=await b.run(await b.command());assert.equal(x.result.computed.right,'150.03');assert.equal(y.result.computed.right,'180.00');assert.equal(x.result.computed.baseTotal,'300.03');assert.equal(y.result.computed.baseTotal,'360.00');assert.equal((await h.observer`select count(*)::int n from crm_private.b04_participants where booking_id=${a.b.bookingId}::uuid`)[0]!.n,0);assert.notEqual(x.result.facts.base.modalityId,y.result.facts.base.modalityId);assert.equal(x.result.facts.base.amount,'100.01');assert.equal(y.result.facts.base.amount,'120.00');});

test('H4-014 G32 approved operation without application fact cannot apply economic obligation effect',async()=>{const f=await cancellationFixture(h),s=await cancellationSchedule(h,f);await f.m.run(await f.m.evaluate());await f.m.run(await f.m.approve());await f.run(await f.command());const before=await h.obligations.read(await h.auth(),read,f.b.bookingId,s.sid),parts=before!.current.snapshot.parts.map(p=>({...p,amount:p.slot==='initial'?'50.00':'100.01'}));await assert.rejects(f.run(await cancellationApplication(h,f,s.sid,parts)),/OPERATIONAL_APPLICATION_REQUIRED/);assert.deepEqual(await h.obligations.read(await h.auth(),read,f.b.bookingId,s.sid),before);assert.equal((await f.m.see())!.progress,'Aprobada');assert.equal((await f.see()).revision,1);});
test('H4-014 C22 first determination obtains legitimate basis through ordinary authorized C01, no privileged token preparation',async()=>{const f=await cancellationFixture(h,{amount:'120.00',index:1});assert.equal(await f.see(),null);const basis=await h.cancellations.basis(await h.auth(),read,f.b.bookingId,f.scope);assert.equal(basis.referenceDate,'2026-10-22');assert.equal(basis.participation.amount,'120.00');assert.equal(basis.participation.quantity,1);assert.equal(basis.acceptedVersion,f.b.versionId);assert.deepEqual(basis.terms,f.b.terms);const q=await f.command({expectedScopeToken:basis.scopeToken});assert.equal((await f.run(q)).result.computed.right,'60.00');const text=JSON.stringify(basis);for(const key of ['cost','margin','participantName','original','actorId'])assert.equal(text.includes(key),false);});
test('H4-014 C24 C01 basis cannot cross service scopes or expose alien/unknown Booking',async()=>{const a=await cancellationFixture(h),b=await cancellationFixture(h);for(const id of [b.detail.services[0]!.id,uid()])await assert.rejects(h.cancellations.basis(await h.auth(),read,a.b.bookingId,{kind:'service',id}),/CANCELLATION_DENIED/);assert.equal(await h.cancellations.basis(await h.auth(),read,uid(),a.scope),null);await assert.rejects(h.cancellations.basis({} as any,read,a.b.bookingId,a.scope),/AUTH_REQUIRED/);});
