// Independent normative oracle: literal outcomes from frozen expected-TSK-H3-007-008.
import assert from 'node:assert/strict';import {test} from 'node:test';import {randomUUID as uid} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';import {spawnSync} from 'node:child_process';
import {isolatedInvoice,invoiceMigration,write,read} from '../support/h3-invoice-isolated.ts';
import {invoiceFixture,type InvoiceCommand} from '../support/h3-invoice-fixtures.ts';
import {allocationFixture} from '../support/h3-allocation-fixtures.ts';
import {H3007InvoiceAdapter} from '../../src/infrastructure/postgres/h3-invoice-adapter.ts';
import {verifyAuth} from '../../src/application/verified-auth.ts';
import {issueTrustedContext} from '../../src/application/trusted-context.ts';
import {canonicalCommercial} from '../../src/domain/commercial-progress.ts';
import {createF1Issuer,encodeF1Fields} from '../../src/infrastructure/postgres/f1-codec.ts';
import {createF2Issuer} from '../../src/infrastructure/postgres/f2-codec.ts';
import {postgresF1Binding} from '../../src/infrastructure/postgres/transaction.ts';
import {classifyServerEvent} from '../../src/application/verified-interaction.ts';
type H=Awaited<ReturnType<typeof isolatedInvoice>>;type F=Awaited<ReturnType<typeof invoiceFixture>>;
const tables=['b05_provider_invoices','b05_invoice_operations','b05_invoice_revisions','b05_invoice_documents'];
async function forged(h:H,input:InvoiceCommand,kind:'f1'|'f2'|'scope'){
 const auth=await h.auth();return h.runtime.begin(async tx=>{
  const row=(await tx`select actor_id::text,admin_scope,access_generation::text,epoch_id::text from crm_api.f2_lookup(${auth.subject}::uuid,${auth.sessionId!}::uuid)`)[0]!;
  const binding=await postgresF1Binding(tx),q=encodeF1Fields(['CRM-H3-INVOICE1',canonicalCommercial(input)]);
  const context=issueTrustedContext({identityId:'h3-invoice-server',identityKind:'technical',purpose:'h1-evidence',scope:kind==='scope'?'SYNTHETIC-OTHER-SCOPE':row.admin_scope,requestId:uid(),serverTime:new Date().toISOString()});
  const human=createF2Issuer(h.f2)(auth,{actorId:row.actor_id,scope:row.admin_scope,accessGeneration:row.access_generation,sessionId:auth.sessionId!,epochId:row.epoch_id},binding,'evidence_write',q,write);
  const tech=createF1Issuer(h.f1)(context,binding,'C03',q,{resource:'evidence',action:'write_evidence'});
  return tx.unsafe('select crm_api.invoice_apply($1,$2,$3,$4,$5)',[human.payload,kind==='f2'?Buffer.alloc(32):human.mac,tech.payload,kind==='f1'?Buffer.alloc(32):tech.mac,q]);
 });
}

async function apply(h:H,q:InvoiceCommand){return h.invoices.apply(await h.auth(),write,q);}
async function staged(h:H,stage=1){const f=await invoiceFixture(h);if(stage>=1)await apply(h,await f.need());if(stage>=2)await apply(h,await f.receive());if(stage>=3)await apply(h,await f.review());if(stage>=4)await apply(h,await f.link());return f;}
async function deny(h:H,f:F,q:InvoiceCommand){const before=await f.state();await assert.rejects(apply(h,q));assert.deepEqual(await f.state(),before);}
async function change(h:H,f:F,q:InvoiceCommand,changes:Record<string,unknown>){return f.attest({...q,...changes} as InvoiceCommand);}
async function inventory(target:H){return {tables:await target.observer`select c.oid,c.relname,c.relowner,c.relacl::text,c.relrowsecurity,c.relforcerowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('crm_private','crm_api','crm_f1','crm_f2') and c.relkind in ('r','p','v','S') order by c.oid`,funcs:await target.observer`select p.oid,p.proname,p.proowner,p.proacl::text,pg_get_functiondef(p.oid) def from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('crm_private','crm_api','crm_f1','crm_f2') order by p.oid`,policies:await target.observer`select oid,polname,polrelid,polroles::text,pg_get_expr(polqual,polrelid) qual,pg_get_expr(polwithcheck,polrelid) ck from pg_policy order by oid`,triggers:await target.observer`select oid,pg_get_triggerdef(oid) def from pg_trigger order by oid`,roles:await target.observer`select rolname,rolsuper,rolinherit,rolcreaterole,rolcreatedb,rolcanlogin,rolbypassrls from pg_roles order by rolname`};}
async function economy(h:H){const ts=(await h.observer`select tablename from pg_tables where schemaname='crm_private' and (tablename like 'b05_%' or tablename like 'b04_%') and tablename not in ('b05_provider_invoices','b05_invoice_operations','b05_invoice_revisions','b05_invoice_documents') order by tablename`).map(r=>r.tablename as string);return snapshots(h,ts);}
async function snapshots(h:H,names:string[]){const out:Record<string,unknown>={};for(const t of names)out[t]=(await h.observer.unsafe(`select coalesce(jsonb_agg(x order by x::text),'[]'::jsonb) value from (select to_jsonb(t) x from crm_private.${t} t) z`))[0]!.value;return out;}
async function trigger(h:H,table:string,deferred=false){await h.admin.unsafe(`create function crm_private.h3008_fault() returns trigger language plpgsql as $$begin raise exception 'SYNTHETIC_INVOICE_FAULT';end$$;create ${deferred?'constraint ':''}trigger h3008_fault ${deferred?'after':'before'} insert on crm_private.${table} ${deferred?'deferrable initially deferred ':''}for each row execute function crm_private.h3008_fault()`);}
async function clear(h:H,table:string){await h.admin.unsafe(`drop trigger h3008_fault on crm_private.${table};drop function crm_private.h3008_fault()`);}
async function race(h:H,f:F,q:InvoiceCommand,same=false){
 const sql=h.connect('crm_h0_runtime'),second=new H3007InvoiceAdapter(sql,h.f1,h.f2);const other=same?q:{...q,operationId:uid()};
 const results=await Promise.allSettled([apply(h,q),second.apply(await h.auth(),write,other)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,same?2:1);assert.equal((await f.state())!.revision,q.expectedRevision+1);
}
const cases:Record<string,(h:H)=>Promise<void>>={
 R01:async h=>{const f=await staged(h);const s=(await f.state())!;assert.equal(s.status,'Pendiente');assert.equal(s.document,null);assert.equal(s.review,null);assert.equal(s.link,null);const g=await invoiceFixture(h),q=await g.need();await apply(h,await g.attest({...q,basis:{...g.basis,amount:null}}));assert.equal((await g.state())!.status,'Pendiente');assert.equal((await g.state())!.basis.amount,null);await apply(h,await g.receive());await deny(h,g,await g.review());await apply(h,await g.attest({...await g.review(),comparisonBasis:g.basis}));assert.equal((await g.state())!.status,'Revisada');assert.equal((await g.state())!.basis.amount,null);await apply(h,await g.link());assert.equal((await g.state())!.status,'Vinculada');},
 R02:async h=>{const f=await invoiceFixture(h),q=await f.need();await deny(h,f,await change(h,f,q,{basis:{...f.basis,serviceIds:[]}}));},
 R03:async h=>{const f=await invoiceFixture(h),q=await f.need();await deny(h,f,await change(h,f,q,{basis:{...f.basis,providerRevisionId:null}}));},
 R04:async h=>{const f=await invoiceFixture(h),q=await f.need();await deny(h,f,await change(h,f,q,{basis:{...f.basis,recipientId:null}}));},
 R05:async h=>{const f=await invoiceFixture(h,'internal'),q=await f.need(),before=await economy(h);await deny(h,f,q);assert.deepEqual(await economy(h),before);assert.equal((await h.observer`select nature from crm_private.b04_services where service_id=${f.basis.serviceIds[0]}::uuid`)[0]!.nature,'internal');},
 R06:async h=>{const f=await staged(h);const q=await f.receive();await apply(h,q);const s=(await f.state())!;assert.equal(s.status,'Recibida');assert.equal(s.document?.documentId,q.document?.documentId);assert.equal(s.history.length,2);},
 R07:async h=>{const f=await staged(h),q=await f.receive();await deny(h,f,await change(h,f,q,{document:{...q.document,objectVersionId:uid()}}));},
 R08:async h=>{const f=await staged(h),q=await f.receive();await deny(h,f,await change(h,f,q,{sourceRef:null}));},
 R09:async h=>{const f=await staged(h),q=await f.receive();await deny(h,f,await change(h,f,q,{document:{...q.document,issuerRevisionId:null}}));},
 R10:async h=>{const f=await staged(h),q=await f.receive();await deny(h,f,await change(h,f,q,{document:{...q.document,recipientId:null}}));},
 R11:async h=>{const f=await staged(h),q=await f.receive();for(const amount of [null,'','1.001',1.5,'-0.00'])await deny(h,f,await change(h,f,q,{document:{...q.document,amount}}));},
 R12:async h=>{const f=await staged(h),q=await f.receive();for(const serviceIds of [null,[],[uid()]])await deny(h,f,await change(h,f,q,{document:{...q.document,serviceIds}}));},
 R13:async h=>{const f=await staged(h,2),s=(await f.state())!;assert.equal(s.status,'Recibida');assert.equal(s.review,null);assert.equal(s.link,null);},
 R14:async h=>{const f=await staged(h,2);await apply(h,await f.review());const s=(await f.state())!;assert.equal(s.status,'Revisada');assert.deepEqual(s.review?.differences,[]);assert.equal(s.review?.actorId,h.actorId);assert.equal(s.link,null);},
 R15:async h=>{const f=await staged(h),other=await invoiceFixture(h);const d=await f.document({recipientId:other.basis.recipientId});await apply(h,await f.receive(d));await apply(h,await f.review());assert.equal((await f.state())!.status,'Incidencia');assert.deepEqual((await f.state())!.review?.differences,['recipient']);assert.equal((await f.state())!.document?.recipientId,d.recipientId);await deny(h,f,await f.link());},
 R16:async h=>{const f=await staged(h),d=await f.document({amount:'101.00'});await apply(h,await f.receive(d));await apply(h,await f.review());const s=(await f.state())!;assert.equal(s.status,'Incidencia');assert.equal(s.document?.amount,'101.00');assert.equal(s.basis.amount,'100.01');assert.deepEqual(s.review?.differences,['amount']);for(const amount of ['0.00','-20.00']){const g=await staged(h);await apply(h,await g.receive(await g.document({amount})));await apply(h,await g.review());assert.equal((await g.state())!.document?.amount,amount);assert.equal((await g.state())!.status,'Incidencia');}},
 R17:async h=>{const f=await staged(h),other=await h.cat('provider',{name:'SYNTHETIC wrong issuer'});await apply(h,await f.receive(await f.document({issuerRevisionId:other.revision})));await apply(h,await f.review());assert.deepEqual((await f.state())!.review?.differences,['provider']);assert.equal((await f.state())!.status,'Incidencia');},
 R18:async h=>{const f=await staged(h);await apply(h,await f.receive(await f.document({serviceIds:[f.basis.serviceIds[0]!]})));await apply(h,await f.review());assert.deepEqual((await f.state())!.review?.differences,['scope']);assert.equal((await f.state())!.status,'Incidencia');},
 R19:async h=>{const f=await staged(h,2),q=await f.review();for(const k of ['provider','recipient','amount','scope'])await deny(h,f,await change(h,f,q,{checks:{...q.checks,[k]:false}}));for(const k of ['checks','reason'])await deny(h,f,await change(h,f,q,{[k]:null}));await deny(h,f,{...q,evidenceId:null} as unknown as InvoiceCommand);},
 R20:async h=>{const f=await staged(h,3);await apply(h,await f.link());const s=(await f.state())!;assert.equal(s.status,'Vinculada');assert.equal(s.link?.documentaryOnly,true);assert.deepEqual(s.link?.portions,f.portions);},
 R21:async h=>{const f=await staged(h,2);await deny(h,f,await f.link());},
 R22:async h=>{const f=await staged(h,3);await deny(h,f,await change(h,f,await f.link(),{sourceRef:null}));assert.equal((await f.state())!.status,'Revisada');},
 R23:async h=>{const f=await staged(h,4),s=(await f.state())!;assert.equal((s.link?.portions as unknown[]).length,2);assert.equal(s.document?.amount,'100.01');assert.equal((await h.observer`select count(*)::int n from crm_private.b05_invoice_documents where invoice_id=${f.invoiceId}::uuid`)[0]!.n,1);},
 R24:async h=>{const f=await staged(h,3);for(const portions of [null,[],f.portions.map(x=>({...x,sourceRef:null}))])await deny(h,f,await change(h,f,await f.link(),{portions}));},
 R25:async h=>{const f=await staged(h,3);for(const portions of [f.portions.map(x=>({...x,amount:'100.01'})),f.portions.map(x=>({...x,serviceId:f.basis.serviceIds[0]}))])await deny(h,f,await change(h,f,await f.link(),{portions}));},
 R26:async h=>{const f=await staged(h,3),other=await staged(h);await deny(h,f,await change(h,f,await f.link(),{bookingId:other.bookingId}));await deny(h,f,await change(h,f,await f.link(),{portions:[{...f.portions[0],serviceId:other.basis.serviceIds[0]},f.portions[1]]}));},
 R27:async h=>{const f=await staged(h,4),before=(await f.state())!;await apply(h,await f.correct(await f.document({},before.document!.documentId)));const s=(await f.state())!;assert.equal(s.status,'Incidencia');assert.equal(s.link,null);assert.equal(s.review,null);assert.deepEqual(s.history[3]!.after,before.history[3]!.after);assert.notEqual(s.document?.documentId,before.document?.documentId);},
 R28:async h=>{const f=await staged(h,4),old=(await f.state())!.document!;const d=await f.document({},old.documentId);await apply(h,await f.correct(d));await apply(h,await f.review());await apply(h,await f.link());const s=(await f.state())!;assert.equal(s.status,'Vinculada');assert.equal(s.link?.documentId,d.documentId);assert.equal(s.history.length,7);assert.equal((await h.observer`select corrects_id::text ref from crm_private.b07_records where record_id=${d.documentId}::uuid`)[0]!.ref,old.documentId);},
 R29:async h=>{const f=await staged(h,4),q=await f.correct();for(const k of ['sourceRef','reason','affectedRecipientId','affectedAmount','affectedServiceIds'])await deny(h,f,await change(h,f,q,{[k]:null}));},
 R30:async h=>{const f=await staged(h,4),doc=(await f.state())!.document;await apply(h,await f.correct());assert.equal((await f.state())!.status,'Incidencia');assert.deepEqual((await f.state())!.document,doc);await deny(h,f,await f.link());},
 R31:async h=>{const f=await staged(h,4);await deny(h,f,await change(h,f,await f.link(),{action:'mark_provider_paid'}));},
 R32:async h=>{const f=await staged(h,2);await deny(h,f,await change(h,f,await f.review(),{action:'execute_programmed_payment'}));},
 R33:async h=>{const f=await staged(h);await deny(h,f,await change(h,f,await f.receive(),{providerPayment:{status:'programmed'}}));assert.equal((await f.state())!.status,'Pendiente');},
 R34:async h=>{const f=await staged(h);await apply(h,await f.receive());await apply(h,await f.review());await apply(h,await f.link());assert.equal((await f.state())!.status,'Vinculada');assert.equal((await h.observer`select state from crm_private.b04_bookings where booking_id=${f.bookingId}::uuid`)[0]!.state,'Pendiente de preparación');},
 R35:async h=>{const f=await staged(h,4);for(const action of ['emit_legal_invoice','assign_fiscal_number','validate_vat'])await deny(h,f,await change(h,f,await f.link(),{action}));},
 R36:async h=>{const f=await staged(h,4);await deny(h,f,await change(h,f,await f.link(),{action:'accept_mandate'}));assert.ok(!(JSON.stringify((await f.state())!.link).includes('mandate')));},
 R37:async h=>{const f=await invoiceFixture(h),before=await economy(h);await apply(h,await f.need());await apply(h,await f.receive());await apply(h,await f.review());await apply(h,await f.link());for(const action of ['allocate','consume','receive_funds','cover_obligation'])await deny(h,f,await change(h,f,await f.link(),{action}));assert.deepEqual(await economy(h),before);},
 R38:async h=>{const f=await staged(h,1),q=await f.receive();await apply(h,q);const s=await f.state();const result=await apply(h,q);assert.equal(result.replayed,true);assert.deepEqual(await f.state(),s);for(const next of [f.review,f.link,()=>f.correct()]){const act=await next();await apply(h,act);const state=await f.state();assert.equal((await apply(h,act)).replayed,true);assert.deepEqual(await f.state(),state);}},
 R39:async h=>{const f=await staged(h),q=await f.receive();await apply(h,q);await deny(h,f,{...q,reason:'different material'});},
 R40:async h=>{const f=await staged(h),q=await f.receive();await apply(h,q);const before=await f.state();const repeated=await f.command('receive',{document:q.document});const r=await apply(h,repeated);assert.equal(r.replayed,true);assert.deepEqual(await f.state(),before);},
 R41:async h=>{const f=await staged(h,2),q=await f.review();await apply(h,q);const before=await f.state();assert.equal((await apply(h,q)).replayed,true);assert.deepEqual(await f.state(),before);},
 R42:async h=>{const f=await staged(h),q=await f.receive();await apply(h,q);const fake=await verifyAuth({verify:async()=>({subject:uid(),sessionId:uid(),passwordVerified:true,mfaVerified:true})},uid());await assert.rejects(h.invoices.apply(fake,write,q));await deny(h,f,{...q,bookingId:uid()});},
 R43:async h=>{const f=await staged(h),q=await f.receive();await race(h,f,q,true);const g=await staged(h);await race(h,g,await g.receive());const n=await invoiceFixture(h),q1=await n.need(),q2=await n.attest({...q1,operationId:uid(),invoiceId:uid()});const other=new H3007InvoiceAdapter(h.connect('crm_h0_runtime'),h.f1,h.f2);const results=await Promise.all([apply(h,q1),other.apply(await h.auth(),write,q2)]);assert.equal(results[0]!.id,results[1]!.id);const state=await h.invoices.read(await h.auth(),read,results[0]!.id,n.bookingId);assert.equal(state!.history.length,1);assert.equal(state!.status,'Pendiente');},
 R44:async h=>{const f=await staged(h,2);await race(h,f,await f.review());},
 R45:async h=>{const f=await staged(h,3);await race(h,f,await f.link());},
 R46:async h=>{const f=await staged(h,4);await race(h,f,await f.correct());},
 R47:async h=>{const f=await staged(h,2);for(const action of ['review','link','correct'] as const){const q=action==='review'?await f.review():action==='link'?await f.link():await f.correct();await deny(h,f,{...q,expectedRevision:0});}},
 R48:async h=>{const f=await staged(h,2),q=await f.review(),before=(await f.state())!;const gateKey='SYNTHETIC-H3008-before-commit';
 await h.admin.unsafe(`create function crm_private.h3008_visibility() returns trigger language plpgsql as $$begin if new.invoice_id='${f.invoiceId}'::uuid then perform pg_advisory_xact_lock(hashtextextended('${gateKey}',0));end if;return new;end$$;create trigger h3008_visibility after insert on crm_private.b05_invoice_revisions for each row execute function crm_private.h3008_visibility()`);
 let unlock!:()=>void;let ready!:()=>void;const gate=new Promise<void>(r=>unlock=r),started=new Promise<void>(r=>ready=r);const locker=h.connect('crm_h0_migration');const tx=locker.begin(async t=>{await t`select pg_advisory_xact_lock(hashtextextended(${gateKey},0))`;ready();await gate;});await started;const pending=apply(h,q);
 try{let waiting=false;for(let n=0;n<100&&!waiting;n++){waiting=(await h.observer`select exists(select 1 from pg_locks where locktype='advisory' and not granted) x`)[0]!.x;if(!waiting)await new Promise(r=>setTimeout(r,10));}assert.equal(waiting,true);const visible=(await h.observer`select after_data from crm_private.b05_invoice_revisions where invoice_id=${f.invoiceId}::uuid order by revision desc limit 1`)[0]!.after_data;assert.equal(visible.status,before.status);assert.equal(visible.revision,before.revision);}finally{unlock();}await tx;await pending;
 await h.admin.unsafe('drop trigger h3008_visibility on crm_private.b05_invoice_revisions;drop function crm_private.h3008_visibility()');assert.equal((await f.state())!.status,'Revisada');},
 R49:async h=>{const f=await invoiceFixture(h),q=await f.need();await trigger(h,'b05_provider_invoices');try{await deny(h,f,q);}finally{await clear(h,'b05_provider_invoices');}},
 R50:async h=>{const f=await invoiceFixture(h),q=await f.need(),before=await snapshots(h,tables);await trigger(h,'b05_invoice_revisions');try{await deny(h,f,q);assert.deepEqual(await snapshots(h,tables),before);}finally{await clear(h,'b05_invoice_revisions');}},
 R51:async h=>{const f=await staged(h,2),q=await f.review();await trigger(h,'b05_invoice_revisions');try{await deny(h,f,q);}finally{await clear(h,'b05_invoice_revisions');}},
 R52:async h=>{const f=await staged(h,3),q=await f.link();await trigger(h,'b05_invoice_operations');try{await deny(h,f,q);}finally{await clear(h,'b05_invoice_operations');}},
 R53:async h=>{const f=await staged(h,4),q=await f.correct(await f.document({},(await f.state())!.document!.documentId)),before=await snapshots(h,tables);await trigger(h,'b05_invoice_revisions');try{await deny(h,f,q);assert.deepEqual(await snapshots(h,tables),before);}finally{await clear(h,'b05_invoice_revisions');}},
 R54:async h=>{const f=await staged(h),q=await f.receive(),before=await snapshots(h,tables);await trigger(h,'b05_invoice_operations',true);try{await deny(h,f,q);assert.deepEqual(await snapshots(h,tables),before);}finally{await clear(h,'b05_invoice_operations');}},
 R55:async h=>{const f=await staged(h),q=await f.receive();await assert.rejects(h.runtime`select crm_api.invoice_apply(null,null,null,null,null)`);for(const kind of ['f1','f2','scope'] as const)await assert.rejects(forged(h,q,kind));for(const role of ['anon','authenticated'])await assert.rejects(h.connect(role)`select crm_api.invoice_apply(null,null,null,null,null)`);await assert.rejects(h.invoices.apply({subject:h.subject} as never,write,q));await assert.rejects(h.invoices.apply(await h.auth(),classifyServerEvent('background-job'),q));await h.admin`alter table crm_private.crm_actors disable trigger all`;await h.admin`update crm_private.crm_actors set enabled=false where actor_id=${h.actorId}::uuid`;try{await assert.rejects(apply(h,q));}finally{await h.admin`update crm_private.crm_actors set enabled=true where actor_id=${h.actorId}::uuid`;await h.admin`alter table crm_private.crm_actors enable trigger all`;}},
 R56:async h=>{for(const table of tables){for(const sql of [`insert into crm_private.${table} default values`,`update crm_private.${table} set admin_scope=admin_scope`,`delete from crm_private.${table}`])await assert.rejects(h.runtime.unsafe(sql));await assert.rejects(h.migration.unsafe(`update crm_private.${table} set admin_scope=admin_scope`));}},
 R57:async h=>{const f=await staged(h,4);assert.equal(await h.invoices.read(await h.auth(),read,f.invoiceId,uid()),null);for(const k of ['reference','amount','provider','filename'])await deny(h,f,await change(h,f,await f.link(),{[k]:'SYNTHETIC other scope'}));await h.admin`alter table crm_private.b05_provider_invoices disable trigger all`;await h.admin`update crm_private.b05_provider_invoices set admin_scope='other-synthetic-scope' where invoice_id=${f.invoiceId}::uuid`;try{assert.equal(await f.state(),null);await assert.rejects(apply(h,await f.command('review')));}finally{await h.admin`update crm_private.b05_provider_invoices set admin_scope=${h.scope} where invoice_id=${f.invoiceId}::uuid`;await h.admin`alter table crm_private.b05_provider_invoices enable trigger all`; }},
 R58:async h=>{const rows=await h.observer`select c.relname,c.relrowsecurity,c.relforcerowsecurity,r.rolname owner from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_roles r on r.oid=c.relowner where n.nspname='crm_private' and c.relname=any(${tables})`;assert.equal(rows.length,4);for(const r of rows){assert.equal(r.relrowsecurity,true);assert.equal(r.relforcerowsecurity,true);assert.equal(r.owner,'crm_h0_f2_owner');}const roles=await h.observer`select rolname,rolcanlogin,rolbypassrls,rolsuper from pg_roles where rolname in ('crm_h0_f2_owner','crm_h0_f2_executor')`;for(const r of roles){assert.equal(r.rolcanlogin,false);assert.equal(r.rolbypassrls,false);assert.equal(r.rolsuper,false);}const funcs=await h.observer`select p.proname,p.prosecdef,p.proconfig,has_function_privilege('crm_h0_runtime',p.oid,'EXECUTE') runtime from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.proname like 'invoice_%' and n.nspname in ('crm_api','crm_private')`;assert.equal(funcs.length,6);for(const f of funcs){assert.ok(f.proconfig.includes('search_path=pg_catalog, pg_temp'));assert.equal(f.runtime,f.proname==='invoice_apply'||f.proname==='invoice_read');}const policies=await h.observer`select count(*)::int n from pg_policies where schemaname='crm_private' and tablename=any(${tables})`;assert.equal(policies[0]!.n,8);const triggers=await h.observer`select count(*)::int n from pg_trigger tg join pg_class c on c.oid=tg.tgrelid where c.relname=any(${tables}) and tg.tgname='invoice_immutable'`;assert.equal(triggers[0]!.n,4);const publicAcl=await h.observer`select count(*)::int n from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where p.proname like 'invoice_%' and n.nspname in ('crm_api','crm_private') and a.grantee=0 and a.privilege_type='EXECUTE'`;assert.equal(publicAcl[0]!.n,0);},
 R59:async h=>{const f=await staged(h,4),s=(await f.state())!,doc=s.document!,ctx={contextKind:'booking' as const,contextId:f.bookingId,purpose:'provider-invoice-documentary'};const bytes=await h.objects.download(await h.auth(),read,doc.objectVersionId,ctx);assert.match(new TextDecoder().decode(bytes),/SYNTHETIC invoice/);assert.equal((await h.observer`select count(*)::int n from crm_private.b07_object_versions where document_id=${doc.documentId}::uuid`)[0]!.n,1);assert.ok(!JSON.stringify(s).includes('private_ref'));},
 R60:async h=>{const files=(await readdir(new URL('../../supabase/migrations/',import.meta.url))).filter(x=>x.endsWith('.sql')).sort();assert.equal(files.filter(x=>x<=invoiceMigration).length,34);for(const file of files.filter(x=>x<invoiceMigration)){const live=await readFile(new URL('../../supabase/migrations/'+file,import.meta.url),'utf8');const original=spawnSync('git',['show',`ac10866027f08d43a708a22f3238d684a1ffc100:supabase/migrations/${file}`],{encoding:'utf8'});assert.equal(original.status,0);assert.equal(live,original.stdout);}assert.equal((await h.observer`select count(*)::int n from pg_tables where schemaname='crm_private' and tablename=any(${tables})`)[0]!.n,4);},
 R61:async()=>{const u=await isolatedInvoice('crm_h3_008_upgrade',55703,true);try{const old=await allocationFixture(u,'100.00','100.00'),assign=await old.assign('80.00');await u.allocations.apply(await u.auth(),write,assign);await u.allocations.apply(await u.auth(),write,await old.consume(assign));const doc=await invoiceFixture(u),original=await doc.document(),ctx={contextKind:'booking' as const,contextId:doc.bookingId,purpose:'provider-invoice-documentary'},bytes=await u.objects.download(await u.auth(),read,original.objectVersionId,ctx),catalog=await inventory(u);const names=(await u.observer`select tablename from pg_tables where schemaname='crm_private' order by tablename`).map(r=>r.tablename as string),before=await snapshots(u,names);await u.migration.unsafe(await readFile(new URL('../../supabase/migrations/'+invoiceMigration,import.meta.url),'utf8'));assert.deepEqual(await snapshots(u,names),before);const after=await inventory(u);for(const key of ['tables','funcs','policies','triggers'] as const){const ids=new Set(catalog[key].map(r=>r.oid));assert.deepEqual(Array.from(after[key].filter(r=>ids.has(r.oid))),Array.from(catalog[key]));}assert.deepEqual(after.roles,catalog.roles);assert.deepEqual(await u.objects.download(await u.auth(),read,original.objectVersionId,ctx),bytes);const f=await staged(u,4);assert.equal((await f.state())!.status,'Vinculada');assert.equal((await old.see()).summary.consumed,'80.00');}finally{await u.close();}},
 R62:async()=>{const u=await isolatedInvoice('crm_h3_008_rollback',55704,true);try{const initial=await inventory(u);const sql=await readFile(new URL('../../supabase/migrations/'+invoiceMigration,import.meta.url),'utf8');await assert.rejects(u.migration.unsafe(sql.replace(/commit;\s*$/,"do $$begin raise exception 'SYNTHETIC_MIGRATION_FAULT';end$$;commit;")));await u.migration.unsafe('rollback');assert.deepEqual(await inventory(u),initial);assert.equal((await u.observer`select count(*)::int n from pg_tables where schemaname='crm_private' and tablename=any(${tables})`)[0]!.n,0);}finally{await u.close();}},
 R63:async()=>{const expected=await readFile(new URL('../../specs/001-core-crm/expected-TSK-H3-007-008.md',import.meta.url),'utf8');assert.equal((expected.match(/^\|R\d+/gm)??[]).length,65);for(const text of ['H3-009+','H3-012','H5-014/016','H6-007','sin hosted ni Production'])assert.ok(expected.includes(text));},
 R64:async h=>{const f=await staged(h,2);await deny(h,f,await change(h,f,await f.review(),{origin:'ai'}));await deny(h,f,await f.attest(await f.review(),'candidate'));},
 R65:async h=>{const f=await staged(h,4);await apply(h,await f.correct());const s=(await f.state())!;for(const row of s.history){assert.equal(row.actorId,h.actorId);assert.ok(row.evidenceId);assert.ok(row.sourceRef);assert.ok(row.reason);assert.ok(row.at);}assert.equal(s.history.length,5);assert.equal((s.history[3]!.after as Record<string,unknown>).status,'Vinculada');}
};
test('H3-008 independent frozen normative matrix',async t=>{const h=await isolatedInvoice('crm_h3_008',55702);try{for(const [id,run] of Object.entries(cases))await t.test(id,()=>run(h));}finally{await h.close();}});
