import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {randomUUID as uid} from 'node:crypto';
import {isolatedRequirement,write,read,requirementMigration} from '../support/h4-requirement-isolated.ts';import {requirementFixture} from '../support/h4-requirement-fixtures.ts';
function applyFunction(sql:string){const start=sql.indexOf('create function crm_api.requirement_apply'),end=sql.indexOf('create function crm_api.requirement_read');return sql.slice(start,end).replace('create function','create or replace function');}
test('H4-002-F01 reproducer: independent new-scope original; frozen defective function rejects, current accepts',async()=>{
 const h=await isolatedRequirement('crm_h4002_f01',56007);try{const f=await requirementFixture(h);for(const q of [await f.need()])await h.requirements.apply(await h.auth(),write,q);await h.requirements.apply(await h.auth(),write,await f.receive());await h.requirements.apply(await h.auth(),write,await f.review());const scope={...f.basis.scope,serviceId:f.b.b.detail.services[1]!.id},q=await f.command('change',{basis:{...f.basis,scope},document:await f.document({coverage:[scope]})}),old=await f.see();
 await h.admin.unsafe(applyFunction(await readFile(new URL('../fixtures/h4-002/first-product.sql.txt',import.meta.url),'utf8')));await assert.rejects(h.requirements.apply(await h.auth(),write,q),/REQUIREMENT_ORIGINAL_REQUIRED/);assert.deepEqual(await f.see(),old);
 await h.admin.unsafe(applyFunction(await readFile(new URL('../../supabase/migrations/'+requirementMigration,import.meta.url),'utf8')));await h.requirements.apply(await h.auth(),write,q);assert.equal((await f.see())!.status,'Recibido');assert.deepEqual((await f.see())!.history[2]!.after,old!.history[2]!.after);
 }finally{await h.close();}
});
test('H4-002-F02 reproducer: evaluation origin expected revision zero; semantic duplicate reuses need',async()=>{
 const h=await isolatedRequirement('crm_h4002_f02',56008);try{const f=await requirementFixture(h);await h.requirements.apply(await h.auth(),write,await f.need());const bad=await f.need({requirementId:uid(),expectedRevision:1});await assert.rejects(h.requirements.apply(await h.auth(),write,bad));const q=await f.need({requirementId:uid()});assert.equal((await h.requirements.apply(await h.auth(),write,q)).id,f.requirementId);assert.equal((await h.requirements.apply(await h.auth(),write,q)).id,f.requirementId);assert.equal((await f.see())!.history.length,1);}finally{await h.close();}
});
test('H4-002-F03 reproducer: actual session table, revoked session never reads Requirement',async()=>{
 const h=await isolatedRequirement('crm_h4002_f03',56009);try{const f=await requirementFixture(h);await h.requirements.apply(await h.auth(),write,await f.need());await assert.rejects(h.admin.unsafe('select * from crm_private.session_epochs'));await h.admin`update crm_private.crm_sessions set revoked_at=clock_timestamp() where session_id=${h.sessionId}::uuid`;await assert.rejects(f.see());}finally{await h.close();}
});
test('H4-002-F04 reproducer: migration denial rollback on reserved connection preserves future runtime reads',async()=>{
 const h=await isolatedRequirement('crm_h4002_f04',56010);try{const f=await requirementFixture(h);await h.requirements.apply(await h.auth(),write,await f.need());const db=await h.connect('crm_h0_runtime').reserve();try{await assert.rejects(db.unsafe(await readFile(new URL('../../supabase/migrations/'+requirementMigration,import.meta.url),'utf8')));}finally{await db.unsafe('rollback');await db.release();}assert.equal((await f.see())!.status,'Pendiente');assert.ok(await h.requirements.evaluate(await h.auth(),read,f.bookingId,f.basis.scope,f.basis.rule.purpose));}finally{await h.close();}
});
test('H4-002-F08 reproducer: 38 current migrations do not invalidate frozen 37/36 H3 boundaries',async()=>{
 const {readdir}=await import('node:fs/promises'),{ownEconomicsMigration}=await import('../support/h3-own-economics-isolated.ts'),{providerPaymentMigration}=await import('../support/h3-provider-payment-isolated.ts');const files=(await readdir(new URL('../../supabase/migrations',import.meta.url))).filter(x=>x.endsWith('.sql')&&x<=requirementMigration);assert.equal(files.length,38);assert.throws(()=>assert.equal(files.length,37));assert.equal(files.filter(x=>x<=ownEconomicsMigration).length,37);assert.equal(files.filter(x=>x<=providerPaymentMigration).length,36);
 for(const file of ['postgres-h3-014.test.ts','postgres-h3-014-defects.test.ts'])assert.ok((await readFile(new URL('./'+file,import.meta.url),'utf8')).includes('<=ownEconomicsMigration'));
});
