// Synthetic contract setup reused from H2-010; contains no expected oracle.
import {randomUUID as uid} from 'node:crypto';
import {bookingFixture} from './h2-booking-fixtures.ts';
import {now} from './h2-acceptance-fixtures.ts';
import {write,type isolatedBooking} from './h2-booking-isolated.ts';
import type {BookingCommand} from '../../src/infrastructure/postgres/h2-booking-adapter.ts';
import type {BookingDetail} from '../../src/domain/booking-conversion.ts';
type H=Awaited<ReturnType<typeof isolatedBooking>>;
export async function quantityFixture(h:H){
 const b=await bookingFixture(h,'total',false),unit=b.f.content.modalities[0]!.lines[0]!.unitRevisionId,form=await h.cat('pricing_form',{name:'SYNTHETIC fixed',definition:'fixed'});
 const serviceRefs:{svc:{id:string;revision:string};tariff:{id:string;revision:string}}[]=[];
 for(const name of ['Rafting','Cena','Casa completa']){const svc=await h.cat('service',{name:`SYNTHETIC ${name}`,nature:'external'}),tariff=await h.com('tariff',{label:'SYNTHETIC',price_state:'confirmed',amount:'900.00',cost_state:'confirmed',cost_amount:'700.00',vat_treatment:'included',unit_revision_id:unit,pricing_form_revision_id:form.revision},svc);serviceRefs.push({svc,tariff});}
 const modalities=[10,2].map((participants,i)=>({id:uid(),name:i?'B':'A',participants,independent:true,selectable:true,conditions:'SYNTHETIC',finalPersonPrice:'100.01',manualReason:'SYNTHETIC',definitive:true,lines:[...[{kind:0,date:'2026-10-20'}].filter(()=>i===0),{kind:1,date:'2026-10-20'},{kind:2,date:'2026-10-20'},...[{kind:2,date:'2026-10-21'}].filter(()=>i===0)].map(x=>({id:uid(),serviceRevisionId:serviceRefs[x.kind]!.svc.revision,unitRevisionId:unit,tariffRevisionId:serviceRefs[x.kind]!.tariff.revision,quantity:'1',included:true,independent:false,selectable:false,date:x.date,datePending:false,priceBasis:'fixed' as const,costMaterial:true,sourceRef:'SYNTHETIC explicit contribution'}))}));
 const content={scope:'SYNTHETIC AC017 accepted scope',terms:b.f.content.terms,pending:[],modalities},proposalId=uid(),versionId=uid(),opp=b.q.opportunityId;
 const revision=async()=>({expectedRevision:Number((await h.observer`select revision from crm_private.b03_proposals where proposal_id=${proposalId}::uuid`)[0]?.revision??0),expectedOpportunityRevision:Number((await h.observer`select revision from crm_private.b03_opportunities where opportunity_id=${opp}::uuid`)[0]!.revision)});
 const cmd={action:'prepare' as const,operationId:uid(),proposalId,opportunityId:opp,...await revision(),sourceRef:'SYNTHETIC',reason:'SYNTHETIC',content};await h.proposal.apply(await h.auth(),write,cmd);await h.proposal.apply(await h.auth(),write,{...cmd,action:'fix',operationId:uid(),versionId,content:undefined,...await revision()});
 const proof=async(claim:string,at=now())=>b.f.proof(claim,content.scope,at),issued=now();await h.offer.apply(await h.auth(),write,{action:'issue',operationId:uid(),proposalId,opportunityId:opp,versionId,...await revision(),sourceRef:'SYNTHETIC',reason:'SYNTHETIC',coverage:content.scope,at:issued,issuance:{issuedAt:issued,limits:[]},evidenceId:await proof(`offer:issue:${versionId}:${issued}:7`,issued)});
 const acceptanceId=uid(),at=now(),r={action:'register' as const,operationId:uid(),acceptanceId,proposalId,opportunityId:opp,versionId,...await revision(),sourceRef:'SYNTHETIC',reason:'SYNTHETIC',coverage:content.scope,at,accepterId:b.f.accepterId,designationId:b.f.designationId,channel:'phone',terms:content.terms,authorityEvidenceId:await proof(`acceptance:authority:${versionId}:${b.f.accepterId}:${b.f.designationId}`,at),evidenceId:await proof(`acceptance:agree:${versionId}:${acceptanceId}:${b.f.accepterId}:phone`,at)};await h.acceptance.apply(await h.auth(),write,r);
 const reviewEvidence:Record<string,string>={};for(const aspect of ['prices','availability','conditions','capacity'])reviewEvidence[aspect]=await proof(`offer:review:${versionId}:${acceptanceId}:accept:${aspect}`,at);
 await h.acceptance.apply(await h.auth(),write,{action:'verify',operationId:uid(),acceptanceId,proposalId,opportunityId:opp,versionId,...await revision(),sourceRef:'SYNTHETIC',reason:'SYNTHETIC',coverage:content.scope,at,reviewEvidence,won:true});
 const services=serviceRefs.map(({svc},kind)=>{const contributions=modalities.flatMap(m=>m.lines.filter(l=>l.serviceRevisionId===svc.revision).map(l=>({id:uid(),lineId:l.id,modalityId:m.id,quantity:l.quantity,attendees:m.participants,certainty:'estimated' as const})));return {id:uid(),serviceRevisionId:svc.revision,nature:'external' as const,variant:null,provider:null,place:null,schedule:null,contributions,nights:kind===2?['2026-10-20','2026-10-21'].map(date=>({id:uid(),date,contributionIds:contributions.filter(c=>modalities.flatMap(m=>m.lines).find(l=>l.id===c.lineId)!.date===date).map(c=>c.id)})):[]};});
 const detail:BookingDetail={services,participants:[],assignments:[]};const detailProof=async(d:BookingDetail)=>{const hash=(await h.observer`select encode(crm_crypto.digest(convert_to(${JSON.stringify(d)}::text::jsonb::text,'UTF8'),'sha256'),'hex') hash`)[0]!.hash;return proof(`booking:detail:${acceptanceId}:${hash}`);};
 const q:BookingCommand={operationId:uid(),bookingId:uid(),opportunityId:opp,proposalId,versionId,acceptanceId,coverage:content.scope,terms:content.terms,...await revision(),sourceRef:'SYNTHETIC AC017',reason:'SYNTHETIC',evidenceId:await detailProof(detail),detail,route:'normal'};
 return {q,detail,detailProof,proof};
}
export async function nominalFixture(h:H,b:Awaited<ReturnType<typeof quantityFixture>>,count=4){const d=structuredClone(b.detail),service=d.services[2]!,night=service.nights[0]!;const necessity=await b.proof(`booking:nominal:${b.q.acceptanceId}:${service.id}:${night.id}`);for(let i=0;i<count;i++){const id=uid(),e=await b.proof(`booking:participant:${b.q.acceptanceId}:${id}`);(d.participants as unknown[]).push({id,name:`SYNTHETIC Participant ${i}`,contactId:null,evidenceId:e,sourceRef:'SYNTHETIC identity proof'});(d.assignments as unknown[]).push({participantId:id,serviceId:service.id,nightId:night.id,necessity:'SYNTHETIC accommodation scoped requirement',evidenceId:necessity});}return {...b.q,detail:d,evidenceId:await b.detailProof(d)};}
