import {randomUUID as uid} from 'node:crypto';
import {invoiceFixture} from './h3-invoice-fixtures.ts';
import {isolatedConfirmation,read,write} from './h4-confirmation-isolated.ts';
import type {ConfirmationCommand} from '../../src/domain/provider-confirmation.ts';
export type H=Awaited<ReturnType<typeof isolatedConfirmation>>;
export async function confirmationFixture(h:H,shared?:Awaited<ReturnType<typeof invoiceFixture>>,index=0,nature:'internal'|'external'='external'){
 const b=shared??await invoiceFixture(h,nature),confirmationId=uid(),bookingId=b.bookingId,service=b.b.detail.services[index]!,at=new Date().toISOString(),unit=await h.cat('unit',{name:'SYNTHETIC capacity unit',definition:'capacity independent of charging or nominal list'});
 const base={operationId:uid(),targetId:uid(),kind:'offering' as const,expectedVersion:0,sourceRef:'SYNTHETIC source relationship',evidenceRef:'SYNTHETIC relationship',reason:'SYNTHETIC'};
 let offeringRevisionId:string|null=null;
 if(service.nature==='external'){const serviceItem=String((await h.observer`select item_id::text id from crm_private.catalog_revisions where revision_id=${service.serviceRevisionId}::uuid`)[0]!.id);await h.catalog.apply(await h.auth(),write,{...base,action:'create_item',parentId:b.provider.id,relatedId:serviceItem});offeringRevisionId=(await h.catalog.apply(await h.auth(),write,{...base,operationId:uid(),action:'publish_version',parentId:b.provider.revision,relatedId:service.serviceRevisionId,definition:{conditions:'SYNTHETIC provider offering, no confirmation inferred'}})).id;}
 const source={kind:service.nature==='internal'?'internal':'provider',id:service.nature==='internal'?h.actorId:b.provider.revision,offeringRevisionId,counterpart:'SYNTHETIC named responsible counterpart',channel:service.nature==='internal'?'internal-record':'phone'};
 const priorApplication=(await h.observer`select application_id::text id from crm_private.catalog_applications where subject_ref=${service.id}::uuid order by recorded_at desc,application_id desc limit 1`)[0];const catalogApplicationId=priorApplication?String(priorApplication.id):uid();if(!priorApplication)await h.catalog.apply(await h.auth(),write,{action:'fix_application',operationId:uid(),targetId:catalogApplicationId,kind:'application',parentId:service.id,revisionIds:[service.serviceRevisionId],expectedVersion:0,sourceRef:'SYNTHETIC reviewed applicable configuration',evidenceRef:'SYNTHETIC minimal known manifest',reason:'SYNTHETIC known capacity and no invented restrictions'});
 // Independent SQL reconstructs accepted snapshots; not a product helper oracle.
 const rows=await h.observer`select c.contribution_id::text id,c.source_snapshot source,m.snapshot modality from crm_private.b04_contributions c join crm_private.b04_modalities m on m.booking_id=c.booking_id and m.modality_id=c.modality_id where c.service_id=${service.id}::uuid order by c.contribution_id`;
 const terms=(await h.observer`select terms from crm_private.b04_bookings where booking_id=${bookingId}::uuid`)[0]!.terms;
 const coverage={serviceId:service.id,nightId:null,contributionId:null,serviceRevisionId:service.serviceRevisionId,serviceRevision:1,bookingRevision:1,variant:service.variant,date:'2026-10-20',time:'12:30:00+02:00',quantity:'12',unitRevisionId:unit.revision,commercialBasis:{terms,contributions:rows.map(r=>({id:r.id,source:r.source,modality:r.modality}))},conditions:'SYNTHETIC exact agreed conditions'};
 const state=async()=>h.confirmations.read(await h.auth(),read,confirmationId,bookingId);
 const proof=async(claim:string,id:string=confirmationId,certainty='reviewed')=>{const q=h.req('evidence',{claim,coverage:id,certainty,source_kind:'manual'},id,'other');await h.evidence.apply(await h.auth(),write,{...q,occurredAt:at,coverage:id});return q.targetId;};
 const hash=async(value:unknown)=>String((await h.observer`select encode(crm_crypto.digest(convert_to(${JSON.stringify(value)}::text::jsonb::text,'UTF8'),'sha256'),'hex') hash`)[0]!.hash);
 const attest=async(q:ConfirmationCommand,certainty='reviewed')=>({...q,evidenceId:await proof(`confirmation:${q.action}:${await hash(Object.fromEntries(Object.entries(q).filter(([k,v])=>!['operationId','evidenceId'].includes(k)&&v!==undefined)))}`,q.confirmationId,certainty)});
 const command=async(action:ConfirmationCommand['action'],data:Record<string,unknown>,changes:Partial<ConfirmationCommand>={})=>attest({action,operationId:uid(),confirmationId,bookingId,expectedRevision:(await state())?.revision??0,expectedEvaluationRevision:Number((await h.observer`select coalesce(max(revision),0) rev from crm_private.b04_confirmation_evaluations where service_id=${service.id}::uuid`)[0]!.rev),sourceRef:'SYNTHETIC source exact manual review',reason:'SYNTHETIC normative act',at,evidenceId:uid(),data,...changes});
 const record=async(previous?:string)=>{const q=h.req('document',{relation:'original',content_ref:'SYNTHETIC manually recorded unequivocal call or source record',content_kind:'manual_record',storage_state:'reference_only'},bookingId,'booking');await h.evidence.apply(await h.auth(),write,{...q,correctsId:previous,occurredAt:at});return q.targetId;};
 const register=async(changes:Record<string,unknown>={})=>command('register',{factId:uid(),recordId:await record(),source,happenedAt:'2026-10-01T10:00:00Z',content:'SYNTHETIC reserved exact12 on date and12:30; conditions explicit',certainty:'confirmed',coverage,...changes},{expectedRevision:0});
 const evaluate=async(changes:Record<string,unknown>={})=>{const c=changes.coverage??(await state())?.fact.coverage??coverage;const app=(await h.observer`select to_jsonb(a) app from crm_private.catalog_applications a where application_id=${catalogApplicationId}::uuid`)[0]!.app;const ch=await hash(c);return command('evaluate',{coverage:c,catalogApplicationId,eligibilityProofId:await proof(`confirmation:eligibility:${await hash({coverage:c,application:app})}`,service.id),scopeProofId:await proof(`confirmation:scope:${ch}`,service.id),agreementProofId:await proof(`confirmation:time:${ch}`,service.id),dependencies:[],...changes});};
 const review=async(changes:Record<string,unknown>={})=>command('review',{recordId:await record(),cause:'SYNTHETIC source correction required',before:(await state())!.fact,after:{quantity:'16'},aspects:['quantity','capacity'],dependencies:[(await state())!.fact.coverage],result:'pending',...changes});
 const rectify=async(changes:Record<string,unknown>={})=>{const v=(await state())!;return command('rectify',{...v.fact,factId:uid(),recordId:await record(v.fact.recordId as string),happenedAt:'2026-10-02T10:00:00Z',...changes});};
 const run=async(q:ConfirmationCommand)=>h.confirmations.apply(await h.auth(),write,q);
 const assess=async()=>h.confirmations.assess(await h.auth(),read,confirmationId,bookingId);
 return {b,confirmationId,bookingId,service,source,catalogApplicationId,coverage,unit,at,state,proof,hash,attest,command,record,register,evaluate,review,rectify,apply:run,assess};
}
