import {randomUUID as uid} from 'node:crypto';
import {invoiceAcceptanceFixture} from './h3-invoice-booking-fixtures.ts';
import {isolatedHold,read,write} from './h4-hold-isolated.ts';
import type {HoldCommand,HoldPart} from '../../src/domain/capacity-hold.ts';
import type {BookingDetail} from '../../src/domain/booking-conversion.ts';
export type H=Awaited<ReturnType<typeof isolatedHold>>;
export async function holdFixture(h:H,expiresAt:string|null=null){
 const f=await invoiceAcceptanceFixture(h,false,true),holdId=uid(),opportunityId=f.opp.targetId,provider=await h.cat('provider',{name:'SYNTHETIC temporal capacity authority'}),unit=await h.cat('unit',{name:'SYNTHETIC capacity persons',definition:'capacity independent of group charging'}),at=new Date().toISOString();
 const part:HoldPart={id:uid(),versionId:f.versionId,lineId:f.line,serviceRevisionId:f.content.modalities[0]!.lines[0]!.serviceRevisionId,variantRevisionId:null,date:'2026-10-20',quantity:'12',unitRevisionId:unit.revision,conditions:'SYNTHETIC temporary capacity only',expiresAt};
 const see=async()=>h.holds.read(await h.auth(),read,holdId,opportunityId);
 const attest=async(q:HoldCommand,certainty='reviewed')=>{const value=Object.fromEntries(Object.entries(q).filter(([k,v])=>!['operationId','evidenceId'].includes(k)&&v!==undefined));const hash=(await h.observer`select encode(crm_crypto.digest(convert_to(${JSON.stringify(value)}::text::jsonb::text,'UTF8'),'sha256'),'hex') hash`)[0]!.hash;const proof=h.req('evidence',{claim:`hold:${q.action}:${hash}`,coverage:q.holdId,certainty,source_kind:'manual'},q.holdId,'other');await h.evidence.apply(await h.auth(),write,{...proof,occurredAt:q.at,coverage:q.holdId});return {...q,evidenceId:proof.targetId};};
 const command=async(action:HoldCommand['action'],data:Record<string,unknown>,change:Partial<HoldCommand>={})=>attest({action,holdId,opportunityId,operationId:uid(),expectedRevision:(await see())?.revision??0,expectedOpportunityRevision:(await f.revisions()).expectedOpportunityRevision,sourceRef:'SYNTHETIC provider manual source',reason:'SYNTHETIC temporal fact',at,evidenceId:uid(),data,...change});
 const record=async()=>{const q=h.req('document',{relation:'original',content_ref:'SYNTHETIC private manual record',content_kind:'synthetic-text',storage_state:'reference_only'},opportunityId);await h.evidence.apply(await h.auth(),write,q);return q.targetId;};
 const grant=async(changes:Record<string,unknown>={})=>command('grant',{providerRevisionId:provider.revision,externalRef:uid(),factId:uid(),recordId:await record(),happenedAt:'2026-10-01T10:00:00Z',certainty:'granted',parts:[part],replacesHoldId:null,...changes});
 const check=async(changes:Record<string,unknown>={})=>command('check',{partIds:[part.id],providerRevisionId:provider.revision,recordId:await record(),happenedAt:at,actionAt:at,actionUntil:at,authority:true,conditionsMet:true,basis:'SYNTHETIC provider current exact action check',...changes});
 const near=async(changes:Record<string,unknown>={})=>command('near',{partIds:[part.id],evaluatedAt:at,advance:{seconds:60,sourceRef:'SYNTHETIC fixture configured lead',version:'SYNTHETIC1'},...changes});
 const invalidate=async(changes:Record<string,unknown>={})=>command('invalidate',{partIds:[part.id],cause:'SYNTHETIC coverage doubt',result:'uncertain',before:(await see())!.parts,after:{uncertainty:'SYNTHETIC external conflicting news'},dependencies:[part.id],...changes});
 const sent=async()=>{const c=h.req('communication',{direction:'outgoing',channel:'synthetic-manual',recipient_ref:provider.revision,coverage:holdId,initial_fact:'none'},opportunityId);await h.evidence.apply(await h.auth(),write,{...c,occurredAt:at});const proof=h.req('evidence',{claim:'SYNTHETIC exact transmission observed in local double',coverage:holdId,certainty:'reviewed',source_kind:'manual'},opportunityId);await h.evidence.apply(await h.auth(),write,{...proof,occurredAt:at});const fact=h.req('communication_fact',{fact_kind:'sent',evidence_id:proof.targetId,party_ref:provider.revision,coverage:holdId},opportunityId);await h.evidence.apply(await h.auth(),write,{...fact,originalId:c.targetId,occurredAt:at});return fact.targetId;};
 const request=async(changes:Record<string,unknown>={})=>command('request',{partIds:[part.id],decision:'SYNTHETIC Administrator decision to request release',communicationFactId:await sent(),sentAt:at,providerRevisionId:provider.revision,basis:'SYNTHETIC exact sent request scope',...changes});
 const selection=(quantity='4')=>({partId:part.id,quantity,unitRevisionId:unit.revision,date:part.date});
 const release=async(changes:Record<string,unknown>={})=>command('release',{selections:[selection()],factId:uid(),recordId:await record(),happenedAt:at,providerRevisionId:provider.revision,authority:true,unequivocal:true,certainty:'released',basis:'SYNTHETIC provider unequivocally released4',...changes});
 const extend=async(changes:Record<string,unknown>={})=>{const extAt=new Date(Math.max(Date.parse(at),...(await see())!.parts.map(p=>Date.parse(p.lastFactAt)))+1).toISOString();return command('extend',{selections:[{...selection('12'),expiresAt:new Date(Date.parse(at)+86400000).toISOString(),conditions:'SYNTHETIC express extension terms'}],factId:uid(),recordId:await record(),happenedAt:extAt,providerRevisionId:provider.revision,authority:true,unequivocal:true,certainty:'extended',basis:'SYNTHETIC explicit provider extension',...changes},{at:extAt});};
 const prepareConversion=async()=>{const r=await f.register(),vq=await f.verification(r);await h.acceptance.apply(await h.auth(),write,vq);const detail:BookingDetail={services:f.content.modalities.map(m=>({id:uid(),serviceRevisionId:m.lines[0]!.serviceRevisionId,nature:'external',variant:null,provider:null,place:null,schedule:null,contributions:[{id:uid(),lineId:m.lines[0]!.id,modalityId:m.id,quantity:m.lines[0]!.quantity,attendees:m.participants,certainty:'estimated'}],nights:[]})),participants:[],assignments:[]};const hash=(await h.observer`select encode(crm_crypto.digest(convert_to(${JSON.stringify(detail)}::text::jsonb::text,'UTF8'),'sha256'),'hex') hash`)[0]!.hash;const q={operationId:uid(),bookingId:uid(),opportunityId,acceptanceId:r.acceptanceId,proposalId:f.proposalId,versionId:f.versionId,coverage:r.coverage,terms:f.content.terms,...await f.revisions(),sourceRef:'SYNTHETIC H2 real conversion',reason:'SYNTHETIC capacity continuity',evidenceId:await f.proof(`booking:detail:${r.acceptanceId}:${hash}`,r.coverage,new Date().toISOString()),detail,route:'normal' as const};return q;};
 const convert=async()=>{const q=await prepareConversion();await h.booking.apply(await h.auth(),write,q);return q;};
 const link=async(bookingId:string,serviceId:string,changes:Record<string,unknown>={})=>command('link',{partIds:[part.id],bookingId,serviceId,nightId:null,bookingRevision:1,serviceRevision:1,conditionsChecked:true,...changes});
 const apply=async(q:HoldCommand)=>h.holds.apply(await h.auth(),write,q);
 const assess=async(changes:Record<string,unknown>={})=>h.holds.evaluate(await h.auth(),read,holdId,opportunityId,{partId:part.id,actionAt:at,actionUntil:at,quantity:'12',unitRevisionId:unit.revision,date:part.date,...changes});
 return {f,holdId,opportunityId,provider,unit,part,at,state:see,attest,command,record,grant,check,near,invalidate,sent,request,selection,release,extend,prepareConversion,convert,link,apply,assess};
}
