-- TSK-H4-022/023 only: actual facts, current phase and existing cancellations.
begin;
do $$begin if current_user<>'crm_h0_migration'then raise exception 'REALITY_MIGRATION_AUTHORITY_REQUIRED';end if;end$$;
grant create on schema crm_private to crm_h0_f2_owner,crm_h0_f2_executor;
grant create on schema crm_api to crm_h0_f2_executor;
create table crm_private.b04_reality_operations(operation_id uuid primary key,booking_id uuid not null references crm_private.b04_bookings,admin_scope text not null,actor_id uuid not null references crm_private.crm_actors,fingerprint text not null,result jsonb not null,recorded_at timestamptz not null default clock_timestamp());
create table crm_private.b04_reality_events(fact_id uuid not null,revision bigint not null check(revision>0),booking_id uuid not null references crm_private.b04_bookings,admin_scope text not null,operation_id uuid not null unique references crm_private.b04_reality_operations deferrable initially deferred,action_kind text not null check(action_kind in('start','perform','finish','correct','review')),event jsonb not null,before_data jsonb,after_data jsonb not null,actor_id uuid not null references crm_private.crm_actors,evidence_id uuid not null references crm_private.b07_records,recorded_at timestamptz not null default clock_timestamp(),primary key(fact_id,revision));
create index reality_booking on crm_private.b04_reality_events(booking_id,admin_scope);
create table crm_private.b04_reality_approvals(reservation_id text primary key,operation_id uuid not null unique references crm_private.b04_reality_operations deferrable initially deferred,booking_id uuid not null references crm_private.b04_bookings,admin_scope text not null,material text not null);
do $$declare t text;begin foreach t in array array['b04_reality_operations','b04_reality_events','b04_reality_approvals']loop
 execute format('alter table crm_private.%I owner to crm_h0_f2_owner',t);execute format('alter table crm_private.%I enable row level security',t);execute format('alter table crm_private.%I force row level security',t);
 execute format('create policy reality_executor on crm_private.%I to crm_h0_f2_executor using(true)with check(true)',t);execute format('create policy reality_migration on crm_private.%I to crm_h0_migration using(true)with check(true)',t);
 execute format('grant select,insert on crm_private.%I to crm_h0_f2_executor,crm_h0_migration',t);execute format('revoke all on crm_private.%I from public,crm_h0_runtime,crm_h0_ha_tx',t);
 execute format('create trigger reality_immutable before update or delete on crm_private.%I for each row execute function crm_private.payment_immutable()',t);
end loop;end$$;
create function crm_private.reality_lock(bid uuid,s text)returns void language plpgsql volatile set search_path=pg_catalog,pg_temp as $$declare opp uuid;begin
 select opportunity_id into opp from crm_private.b04_bookings where booking_id=bid and admin_scope=s;if opp is null then raise exception 'REALITY_DENIED';end if;
 perform pg_advisory_xact_lock(hashtextextended(opp::text,31));perform pg_advisory_xact_lock(hashtextextended('requirement-booking:'||bid,0));perform pg_advisory_xact_lock(hashtextextended('availability-booking:'||bid,0));perform pg_advisory_xact_lock(hashtextextended('confirmation-booking:'||bid,0));perform pg_advisory_xact_lock(hashtextextended('modification-booking:'||bid,0));perform crm_private.booking_preparation_lock(bid);
end$$;
create function crm_private.reality_facts(bid uuid,s text)returns jsonb language sql stable set search_path=pg_catalog,pg_temp as $$
 select coalesce(jsonb_agg(v.after_data order by v.fact_id),'[]')from(select distinct on(fact_id)*from crm_private.b04_reality_events where booking_id=bid and admin_scope=s order by fact_id,revision desc)v where v.after_data->>'kind'='perform'
$$;
create function crm_private.reality_incidents(bid uuid,s text)returns jsonb language sql stable set search_path=pg_catalog,pg_temp as $$
 select coalesce(jsonb_agg(jsonb_build_object('id',i.incident_id,'revision',v.after_data->'revision','severity',v.after_data->'severity','scope',v.after_data->'impact'->'scope','effect',v.after_data->'impact'->'effect')order by i.incident_id),'[]')from crm_private.b07_incidents i cross join lateral(select after_data from crm_private.b07_incident_revisions where incident_id=i.incident_id order by revision desc limit 1)v where i.booking_id=bid and i.admin_scope=s and v.after_data->>'status'in('Abierta','En gestión')and v.after_data->'impact'->>'effect'in('operation','preparation')and v.after_data->'impact'->'material'='true'::jsonb
$$;
-- All contracted scopes including cancelled parts, using actual per-night occupancy.
create function crm_private.reality_scopes(bid uuid,s text)returns jsonb language plpgsql stable set search_path=pg_catalog,pg_temp as $$
declare v record;k jsonb;r jsonb:='[]';q numeric;p numeric;cancelled boolean;facts jsonb;f jsonb;sc jsonb;dim text;current jsonb;total numeric;begin
 facts:=crm_private.reality_facts(bid,s);
 for v in select *from crm_private.b04_services where booking_id=bid and admin_scope=s order by service_id loop
  for k in select jsonb_build_object('serviceId',v.service_id,'nightId',night_id,'contributionId',null)from crm_private.b04_nights where service_id=v.service_id
   union all select jsonb_build_object('serviceId',v.service_id,'nightId',null,'contributionId',bc.contribution_id)from crm_private.b04_contributions bc where bc.service_id=v.service_id and not exists(select 1 from crm_private.b04_nights where service_id=v.service_id)and(select count(distinct crm_private.modification_scope(jsonb_build_object('kind','contribution','id',c.contribution_id,'serviceId',v.service_id),bid,s)->>'date')from crm_private.b04_contributions c where c.service_id=v.service_id)>1
   union all select jsonb_build_object('serviceId',v.service_id,'nightId',null,'contributionId',null)where not exists(select 1 from crm_private.b04_nights where service_id=v.service_id)and(select count(distinct crm_private.modification_scope(jsonb_build_object('kind','contribution','id',c.contribution_id,'serviceId',v.service_id),bid,s)->>'date')from crm_private.b04_contributions c where c.service_id=v.service_id)<=1 loop
   dim:=case when k->'nightId'<>'null'::jsonb then 'attendees'else 'quantity'end;for f in select value from jsonb_array_elements(facts)loop for sc in select value from jsonb_array_elements(f->'scopes')loop if sc-array['dimension','start','amount']=k then dim:=sc->>'dimension';end if;end loop;end loop;
   cancelled:=coalesce((crm_private.modification_scope(jsonb_build_object('kind','service','id',v.service_id),bid,s)->>'cancelled')::boolean,false);
   if k->'nightId'<>'null'::jsonb then
    current:=crm_private.modification_scope(jsonb_build_object('kind','night','id',k->>'nightId','serviceId',v.service_id),bid,s);cancelled:=cancelled or(current->>'cancelled')::boolean;
    select sum((crm_private.modification_scope(jsonb_build_object('kind','contribution','id',bc.contribution_id,'serviceId',v.service_id),bid,s)->>dim)::numeric)into q from crm_private.b04_night_occupancies o join crm_private.b04_contributions bc using(contribution_id)where o.night_id=(k->>'nightId')::uuid and not(crm_private.modification_scope(jsonb_build_object('kind','contribution','id',bc.contribution_id,'serviceId',v.service_id),bid,s)->>'cancelled')::boolean;
    select sum(case when dim='attendees'then bc.attendees::numeric else bc.quantity end)into total from crm_private.b04_night_occupancies o join crm_private.b04_contributions bc using(contribution_id)where o.night_id=(k->>'nightId')::uuid;
   elsif k->'contributionId'<>'null'::jsonb then
    current:=crm_private.modification_scope(jsonb_build_object('kind','contribution','id',k->>'contributionId','serviceId',v.service_id),bid,s);q:=(current->>dim)::numeric;cancelled:=cancelled or(current->>'cancelled')::boolean;
    select case when dim='attendees'then attendees::numeric else quantity end into total from crm_private.b04_contributions where contribution_id=(k->>'contributionId')::uuid;
   else
    select sum((crm_private.modification_scope(jsonb_build_object('kind','contribution','id',bc.contribution_id,'serviceId',v.service_id),bid,s)->>dim)::numeric)into q from crm_private.b04_contributions bc where bc.service_id=v.service_id and not(crm_private.modification_scope(jsonb_build_object('kind','contribution','id',bc.contribution_id,'serviceId',v.service_id),bid,s)->>'cancelled')::boolean;
    select sum(case when dim='attendees'then attendees::numeric else quantity end)into total from crm_private.b04_contributions where service_id=v.service_id;
   end if;
   select coalesce(sum((x->>'amount')::numeric),0)into p from jsonb_array_elements(facts)factrow(value) cross join lateral jsonb_array_elements(factrow.value->'scopes')x where x-array['dimension','start','amount']=k;
   r:=r||jsonb_build_array(k||jsonb_build_object('dimension',dim,'contracted',trim_scale(total)::text,'current',trim_scale(coalesce(q,0))::text,'performed',trim_scale(p)::text,'cancelled',case when cancelled then trim_scale(greatest(coalesce(total,0)-p,0))::text else trim_scale(greatest(coalesce(total,0)-coalesce(q,0),0))::text end,'remaining',case when cancelled then '0'else trim_scale(greatest(coalesce(q,0)-p,0))::text end,'resolved',cancelled or(q is not null and p>=q),'cancellationApplied',cancelled));
  end loop;
 end loop;return r;
end$$;
create function crm_private.reality_final_basis(bid uuid,s text)returns text language sql stable set search_path=pg_catalog,pg_temp as $$select crm_private.booking_preparation_hash(jsonb_build_object('scopes',crm_private.reality_scopes(bid,s),'facts',crm_private.reality_facts(bid,s)))$$;
create function crm_private.reality_phase(bid uuid,s text)returns text language sql stable set search_path=pg_catalog,pg_temp as $$
 select case when (select after_data->>'finalizedBasis'from crm_private.b04_reality_events where booking_id=bid and admin_scope=s and action_kind='finish'order by recorded_at desc,operation_id desc limit 1)=crm_private.reality_final_basis(bid,s)and not exists(select 1 from jsonb_array_elements(crm_private.reality_scopes(bid,s))x where not(x->>'resolved')::boolean)and exists(select 1 from jsonb_array_elements(crm_private.reality_scopes(bid,s))x where(x->>'performed')::numeric>0)then 'Finalizada'when(crm_private.modification_scope(jsonb_build_object('kind','booking','id',bid),bid,s)->>'cancelled')::boolean and crm_private.reality_facts(bid,s)='[]'::jsonb then 'Cancelada'when crm_private.reality_facts(bid,s)<>'[]'::jsonb or exists(select 1 from crm_private.b04_reality_events where booking_id=bid and admin_scope=s and action_kind in('start','perform'))then 'En curso'else null end
$$;
create function crm_private.reality_material(bid uuid,s text)returns text language sql stable set search_path=pg_catalog,pg_temp as $$select crm_private.booking_preparation_hash(jsonb_build_object('inputs',crm_private.booking_preparation_inputs(bid,s),'facts',(select coalesce(jsonb_agg(to_jsonb(e)order by fact_id,revision),'[]')from crm_private.b04_reality_events e where booking_id=bid and admin_scope=s),'incidents',crm_private.reality_incidents(bid,s)))$$;
create function crm_private.reality_read_core(bid uuid,s text)returns jsonb language sql stable set search_path=pg_catalog,pg_temp as $$
 select jsonb_build_object('bookingId',bid,'revision',(select count(*)from crm_private.b04_reality_events where booking_id=bid and admin_scope=s),'phase',coalesce(crm_private.reality_phase(bid,s),case when(crm_private.modification_scope(jsonb_build_object('kind','booking','id',bid),bid,s)->>'cancelled')::boolean then 'Cancelada'else null end),'material',crm_private.reality_material(bid,s),'facts',crm_private.reality_facts(bid,s),'scopes',crm_private.reality_scopes(bid,s),'incidents',crm_private.reality_incidents(bid,s),'pending',(select coalesce(jsonb_agg('review:'||fact_id),'[]')from(select distinct on(fact_id)fact_id,after_data from crm_private.b04_reality_events where booking_id=bid and admin_scope=s order by fact_id,revision desc)v where jsonb_array_length(v.after_data->'data'->'review'->'pending')>0),'history',(select coalesce(jsonb_agg(jsonb_build_object('factId',fact_id,'revision',revision,'action',action_kind,'event',event,'before',before_data,'after',after_data,'actorId',actor_id,'evidenceId',evidence_id,'recordedAt',recorded_at)order by recorded_at,operation_id),'[]')from crm_private.b04_reality_events where booking_id=bid and admin_scope=s))
$$;
create function crm_private.reality_confirmed(bid uuid,s text,sc jsonb)returns boolean language sql stable set search_path=pg_catalog,pg_temp as $$
 select exists(select 1 from crm_private.b04_confirmations c cross join lateral(select after_data from crm_private.b04_confirmation_revisions where confirmation_id=c.confirmation_id order by revision desc limit 1)v cross join lateral(select crm_private.confirmation_current(v.after_data,bid,s)x)z where c.booking_id=bid and c.admin_scope=s and(z.x->>'usable')::boolean and v.after_data->'evaluation'->'coverage'->'serviceId'=sc->'serviceId'and v.after_data->'evaluation'->'coverage'->'nightId'=sc->'nightId'and v.after_data->'evaluation'->'coverage'->'contributionId'=sc->'contributionId')
$$;
create function crm_private.reality_prepared(bid uuid,s text)returns boolean language plpgsql stable set search_path=pg_catalog,pg_temp as $$declare inputs jsonb;st jsonb;a jsonb;begin
 inputs:=crm_private.booking_preparation_inputs(bid,s);select state into st from crm_private.b04_preparation_evaluations where booking_id=bid and admin_scope=s order by revision desc limit 1;
 a:=crm_private.booking_preparation_assess(inputs,coalesce(st->'command',jsonb_build_object('criticalScopes','[]'::jsonb)),bid,s,clock_timestamp(),exists(select 1 from crm_private.b04_preparation_approvals where booking_id=bid and admin_scope=s and material=crm_private.booking_preparation_material(inputs,bid,s)));
 return st->>'historicalPhase'='Confirmada operativamente'and coalesce((a->>'complete')::boolean,false);
end$$;
create function crm_private.reality_core(a jsonb,s text,actor uuid,sensitive boolean default false)returns jsonb language plpgsql volatile set search_path=pg_catalog,pg_temp as $$
declare bid uuid;op uuid;fid uuid;prev crm_private.b04_reality_operations;d jsonb;sc jsonb;scope jsonb;f jsonb;existing jsonb;old jsonb;state jsonb;r jsonb;phase text;rev bigint;fr bigint;fp text;proof text;source jsonb;review jsonb;part numeric;quantity numeric;task uuid;targets jsonb;kind text;cancelCorrection boolean:=false;begin
 if jsonb_typeof(a)is distinct from'object'or not(a?&array['action','operationId','factId','bookingId','expectedRevision','expectedMaterial','sourceRef','reason','at','evidenceId','data'])or a-array['action','operationId','factId','bookingId','expectedRevision','expectedMaterial','sourceRef','reason','at','evidenceId','data','origin']<>'{}'::jsonb
 or a->>'action'not in('start','perform','finish','correct','review')or coalesce(a->>'origin','manual')not in('manual','ai')or(coalesce(a->>'origin','manual')='ai'and not sensitive)or not coalesce(crm_private.invoice_text(a->'reason'),false)or not coalesce(crm_private.invoice_text(a->'sourceRef'),false)or not coalesce(crm_private.availability_time(a->'at'),false)or coalesce(a->>'expectedRevision','')!~'^[0-9]+$'then raise exception 'REALITY_INPUT_INVALID';end if;
 bid:=(a->>'bookingId')::uuid;op:=(a->>'operationId')::uuid;fid:=(a->>'factId')::uuid;perform crm_private.reality_lock(bid,s);fp:=crm_private.booking_preparation_hash(a);
 select *into prev from crm_private.b04_reality_operations where operation_id=op;if found then if prev.admin_scope<>s or prev.actor_id<>actor or prev.fingerprint<>fp then raise exception 'REALITY_REPLAY_CONFLICT:E2';end if;return prev.result||jsonb_build_object('replayed',true);end if;
 d:=a->'data';proof:=crm_private.booking_preparation_hash(a-array['operationId','evidenceId']);
 if not coalesce(crm_private.payment_evidence((a->>'evidenceId')::uuid,bid,s,'reality:'||(a->>'action')||':'||proof,(a->>'at')::timestamptz,true),false)or not exists(select 1 from crm_private.b07_records where record_id=(a->>'evidenceId')::uuid and recorded_by=actor)then raise exception 'REALITY_EVIDENCE_REQUIRED:E3';end if;
 if jsonb_typeof(d)is distinct from'object'or not(d?&array['scopes','moment','source','responsibleId','originalId','certainty','exceptional','review','correctsFactId','correctsRevision'])or d-array['scopes','moment','source','responsibleId','originalId','certainty','exceptional','review','correctsFactId','correctsRevision']<>'{}'::jsonb or jsonb_typeof(d->'scopes')is distinct from'array'or d->>'certainty'is distinct from'verified'or jsonb_typeof(d->'exceptional')is distinct from'boolean'or not coalesce(crm_private.incident_actor(d->'responsibleId',s),false)or not crm_private.confirmation_record((d->>'originalId')::uuid,bid,s)then raise exception 'REALITY_FACT_REQUIRED:E3';end if;
 if d->'moment'->>'kind'='instant'then if (d->'moment')-array['kind','value']<>'{}'::jsonb or not coalesce(crm_private.availability_time(d->'moment'->'value'),false)then raise exception 'REALITY_MOMENT_REQUIRED:E3';end if;
 elsif d->'moment'->>'kind'='civil'then if (d->'moment')-array['kind','value']<>'{}'::jsonb or coalesce(d->'moment'->>'value','')!~'^[0-9]{4}-[0-9]{2}-[0-9]{2}$'then raise exception 'REALITY_MOMENT_REQUIRED:E3';end if;perform(d->'moment'->>'value')::date;
 elsif d->'moment'->>'kind'='unknown'then if (d->'moment')-array['kind','reason']<>'{}'::jsonb or not coalesce(crm_private.invoice_text(d->'moment'->'reason'),false)or d->'review'='null'::jsonb then raise exception 'REALITY_MOMENT_REQUIRED:E3';end if;
 else raise exception 'REALITY_MOMENT_REQUIRED:E3';end if;
 select revision,after_data into fr,old from crm_private.b04_reality_events where fact_id=fid order by revision desc limit 1;
 if old is not null and(old->>'bookingId'<>bid::text or not exists(select 1 from crm_private.b04_reality_events where fact_id=fid and admin_scope=s))then raise exception 'REALITY_DENIED';end if;
 if a->>'action'not in('correct','review')and old is not null then
  if old->'data'is distinct from d or old->>'kind'<>a->>'action'or old->>'sourceRef'<>a->>'sourceRef'then raise exception 'REALITY_FACT_CONFLICT:E2';end if;
  select result into r from crm_private.b04_reality_operations where operation_id=(old->>'operationId')::uuid;r:=r||jsonb_build_object('replayed',true);insert into crm_private.b04_reality_operations values(op,bid,s,actor,fp,r,clock_timestamp());return r;
 end if;
 select count(*)into rev from crm_private.b04_reality_events where booking_id=bid and admin_scope=s;if rev<>(a->>'expectedRevision')::bigint or crm_private.reality_material(bid,s)is distinct from a->>'expectedMaterial'then raise exception 'REALITY_MATERIAL_CONFLICT:E2';end if;
 phase:=crm_private.reality_phase(bid,s);targets:=crm_private.reality_scopes(bid,s);existing:=crm_private.reality_facts(bid,s);
 review:=d->'review';if (d->>'exceptional')::boolean or a->>'action'in('correct','review')or review<>'null'::jsonb then
  if jsonb_typeof(review)is distinct from'object'or not(review?&array['responsibleId','basis','pending','incidentRequired','incidentIds','evidenceId'])or review-array['responsibleId','basis','pending','incidentRequired','incidentIds','evidenceId']<>'{}'::jsonb or not coalesce(crm_private.incident_actor(review->'responsibleId',s),false)or not coalesce(crm_private.invoice_text(review->'basis'),false)or jsonb_typeof(review->'pending')is distinct from'array'or jsonb_typeof(review->'incidentIds')is distinct from'array'or jsonb_typeof(review->'incidentRequired')is distinct from'boolean'or not coalesce(crm_private.payment_evidence((review->>'evidenceId')::uuid,bid,s,'reality:review:'||crm_private.booking_preparation_hash(review-'evidenceId'),(a->>'at')::timestamptz,true),false)then raise exception 'REALITY_REVIEW_REQUIRED:E3';end if;
  if (review->>'incidentRequired')::boolean and jsonb_array_length(review->'incidentIds')=0 then raise exception 'REALITY_INCIDENT_REQUIRED:E3';end if;
  for sc in select value from jsonb_array_elements(review->'incidentIds')loop if not exists(select 1 from jsonb_array_elements(crm_private.reality_incidents(bid,s))i where i->'id'=sc and(not(i->'scope'?'serviceId')or exists(select 1 from jsonb_array_elements(d->'scopes')x where x->'serviceId'=i->'scope'->'serviceId'and(not(i->'scope'?'nightId')or x->'nightId'=i->'scope'->'nightId'))))then raise exception 'REALITY_INCIDENT_REQUIRED:E3';end if;end loop;
 end if;
 if a->>'action'in('start','perform')then
  if phase in('Finalizada','Cancelada')or (phase is null and(crm_private.modification_scope(jsonb_build_object('kind','booking','id',bid),bid,s)->>'cancelled')::boolean)then raise exception 'REALITY_ORIGIN_REQUIRED:E3';end if;
  if a->>'action'='start'and phase is not null then raise exception 'REALITY_ORIGIN_REQUIRED:E3';end if;
  if not(d->>'exceptional')::boolean and((a->>'action'='start'and not coalesce(crm_private.reality_prepared(bid,s),false))or(a->>'action'='perform'and phase is distinct from'En curso'))then raise exception 'REALITY_CONFIRMATION_REQUIRED:E3';end if;
 end if;
 if a->>'action'in('correct','review')then
  if d->'correctsFactId'='null'::jsonb or d->'correctsRevision'='null'::jsonb or not(exists(select 1 from crm_private.b04_reality_events where fact_id=(d->>'correctsFactId')::uuid and revision=(d->>'correctsRevision')::bigint and booking_id=bid and admin_scope=s)or(a->>'action'in('review','correct')and exists(select 1 from crm_private.b06_modification_revisions mr join crm_private.b06_modifications m using(modification_id)where m.modification_id=(d->>'correctsFactId')::uuid and mr.revision=(d->>'correctsRevision')::bigint and m.booking_id=bid and m.admin_scope=s)))then raise exception 'REALITY_CORRECTION_REQUIRED:E3';end if;
  if a->>'action'='correct'and old is null and(d->>'exceptional')::boolean then
   select mr.after_data into old from crm_private.b06_modification_revisions mr join crm_private.b06_modifications m using(modification_id)where mr.modification_id=(d->>'correctsFactId')::uuid and mr.revision=(d->>'correctsRevision')::bigint and mr.action_kind='apply'and m.booking_id=bid and m.admin_scope=s;cancelCorrection:=old is not null and exists(select 1 from jsonb_array_elements(old->'parts')p where p->'applied'<>'null'::jsonb and p->'desired'->'cancelled'='true'::jsonb);
  end if;
  if a->>'action'='correct'and not cancelCorrection and(old is null or fid::text<>d->>'correctsFactId'or fr<>(d->>'correctsRevision')::bigint or old->>'kind'<>'perform')then raise exception 'REALITY_CORRECTION_REQUIRED:E3';end if;
 elsif d->'correctsFactId'<>'null'::jsonb or d->'correctsRevision'<>'null'::jsonb then raise exception 'REALITY_CORRECTION_REQUIRED:E3';end if;
 if a->>'action'<>'finish'and jsonb_array_length(d->'scopes')=0 then raise exception 'REALITY_SCOPE_REQUIRED:E3';end if;
 if a->>'action'='finish'then
  if phase is distinct from'En curso'or jsonb_array_length(d->'scopes')<>0 or not exists(select 1 from jsonb_array_elements(targets)x where(x->>'performed')::numeric>0)or exists(select 1 from jsonb_array_elements(targets)x where not(x->>'resolved')::boolean)or exists(select 1 from(select distinct on(fact_id)after_data from crm_private.b04_reality_events where booking_id=bid and admin_scope=s order by fact_id,revision desc)v where v.after_data->>'kind'='review'and jsonb_array_length(v.after_data->'data'->'review'->'pending')>0)then raise exception 'REALITY_FINISH_REQUIRED:E3';end if;
  if (d->'source')-array['kind','id']<>'{}'::jsonb or d->'source'->>'kind'<>'internal'or not coalesce(crm_private.incident_actor(d->'source'->'id',s),false)then raise exception 'REALITY_SOURCE_REQUIRED:E3';end if;
 end if;
 for sc in select value from jsonb_array_elements(d->'scopes')loop
  if sc-array['serviceId','nightId','contributionId','dimension','start','amount']<>'{}'::jsonb or not(sc?&array['serviceId','nightId','contributionId','dimension','start','amount'])or sc->>'dimension'not in('quantity','attendees') or coalesce(sc->>'start','')!~'^[0-9]+(\.[0-9]+)?$'or coalesce(sc->>'amount','')!~'^[0-9]+(\.[0-9]+)?$'or(sc->>'amount')::numeric<=0 or(sc->>'dimension'='attendees'and((sc->>'start')::numeric<>trunc((sc->>'start')::numeric)or(sc->>'amount')::numeric<>trunc((sc->>'amount')::numeric)))then raise exception 'REALITY_SCOPE_REQUIRED:E3';end if;
  scope:=null;select value into scope from jsonb_array_elements(targets)x where x-array['dimension','contracted','current','performed','cancelled','remaining','resolved','cancellationApplied']=sc-array['dimension','start','amount'];if scope is null then raise exception 'REALITY_DENIED';end if;
  if not coalesce(crm_private.modification_source(d->'source',bid,(sc->>'serviceId')::uuid,s),false)then raise exception 'REALITY_SOURCE_REQUIRED:E3';end if;
  if sc->'nightId'<>'null'::jsonb then select sum((crm_private.modification_scope(jsonb_build_object('kind','contribution','id',c.contribution_id,'serviceId',c.service_id),bid,s)->>(sc->>'dimension'))::numeric)into quantity from crm_private.b04_night_occupancies o join crm_private.b04_contributions c using(contribution_id)where o.night_id=(sc->>'nightId')::uuid;
  else select sum((crm_private.modification_scope(jsonb_build_object('kind','contribution','id',c.contribution_id,'serviceId',c.service_id),bid,s)->>(sc->>'dimension'))::numeric)into quantity from crm_private.b04_contributions c where c.service_id=(sc->>'serviceId')::uuid and(sc->'contributionId'='null'::jsonb or c.contribution_id=(sc->>'contributionId')::uuid)and not(crm_private.modification_scope(jsonb_build_object('kind','contribution','id',c.contribution_id,'serviceId',c.service_id),bid,s)->>'cancelled')::boolean;end if;
  if cancelCorrection then
   if not exists(select 1 from jsonb_array_elements(old->'parts')p where p->'applied'<>'null'::jsonb and p->'desired'->'cancelled'='true'::jsonb and(p->'scope'->>'kind'='booking'or(p->'scope'->>'kind'='service'and p->'scope'->'id'=sc->'serviceId')or(p->'scope'->>'kind'='night'and p->'scope'->'id'=sc->'nightId')or(p->'scope'->>'kind'='contribution'and p->'scope'->'id'=sc->'contributionId')))then raise exception 'REALITY_CORRECTION_REQUIRED:E3';end if;
   quantity:=(scope->>'contracted')::numeric;
  end if;
  if a->>'action'<>'review'and((sc->>'start')::numeric+(sc->>'amount')::numeric>quantity or quantity is null or((scope->>'cancellationApplied')::boolean and not(d->>'exceptional')::boolean))then raise exception 'REALITY_QUANTITY_REQUIRED:E3';end if;
  if a->>'action'='perform'and not(d->>'exceptional')::boolean and not coalesce(crm_private.reality_confirmed(bid,s,sc),false)then raise exception 'REALITY_CONFIRMATION_REQUIRED:E3';end if;
  if a->>'action'in('perform','correct')then
   for f in select value from jsonb_array_elements(existing)where value->>'factId'<>fid::text loop
    if exists(select 1 from jsonb_array_elements(f->'scopes')x where x-array['dimension','start','amount']=sc-array['dimension','start','amount']and(x->>'dimension'<>sc->>'dimension'or numrange((x->>'start')::numeric,(x->>'start')::numeric+(x->>'amount')::numeric,'[)')&&numrange((sc->>'start')::numeric,(sc->>'start')::numeric+(sc->>'amount')::numeric,'[)')))then raise exception 'REALITY_OVERLAP_REVIEW_REQUIRED:E2';end if;
   end loop;
   if exists(select 1 from jsonb_array_elements(d->'scopes')x where x<>sc and x-array['dimension','start','amount']=sc-array['dimension','start','amount']and(x->>'dimension'<>sc->>'dimension'or numrange((x->>'start')::numeric,(x->>'start')::numeric+(x->>'amount')::numeric,'[)')&&numrange((sc->>'start')::numeric,(sc->>'start')::numeric+(sc->>'amount')::numeric,'[)')))or(select count(*)from jsonb_array_elements(d->'scopes')x where x=sc)>1 then raise exception 'REALITY_OVERLAP_REVIEW_REQUIRED:E2';end if;
  end if;
 end loop;
 kind:=case when a->>'action'='correct'then 'perform'else a->>'action'end;
 state:=jsonb_build_object('factId',fid,'revision',coalesce(fr,0)+1,'bookingId',bid,'kind',kind,'operationId',op,'data',d,'scopes',d->'scopes','actorId',actor,'evidenceId',a->'evidenceId','sourceRef',a->'sourceRef','reason',a->'reason','recordedAt',clock_timestamp(),'approvalRequired',sensitive);if a->>'action'='finish'then state:=state||jsonb_build_object('finalizedBasis',crm_private.reality_final_basis(bid,s));end if;
 insert into crm_private.b04_reality_events values(fid,coalesce(fr,0)+1,bid,s,op,a->>'action',a,old,state,actor,(a->>'evidenceId')::uuid,clock_timestamp());
 insert into crm_private.b07_operations(operation_id,admin_scope,actor_id,fingerprint,result_ref)values(op,s,actor,fp,fid);
 insert into crm_private.b07_history(history_id,operation_id,subject_id,admin_scope,action_kind,before_state,after_state,reason,source_ref,occurred_at,actor_id)values(op,op,fid,s,'reality_'||(a->>'action'),old,state,a->>'reason',a->>'sourceRef',case when d->'moment'->>'kind'='instant'then(d->'moment'->>'value')::timestamptz else null end,actor);
 select result_ref into task from crm_private.booking_preparation_task_core(jsonb_build_object('action','receive','operationId',md5('reality-followup:'||op)::uuid,'taskId',fid,'expectedRevision',0,'purpose','pending-followup','identity',jsonb_build_object('causeKind','block','causeId',fid,'contextKind','booking','contextId',bid,'scopeRef',fid,'effect','operational-reality-review'),'material',jsonb_build_object('title','Revisar realidad y partes pendientes','deadline',jsonb_build_object('kind','unknown','reason','No consta fecha fijada'),'priority',jsonb_build_object('kind','pending','reason','Prioridad no configurada'),'sourceRef','SM-BK-06-11','sourceVersion','1','triggerRef','BR-TASK-005','triggerVersion','1'),'reason','Seguimiento de realidad por alcance'),actor,s);
 r:=jsonb_build_object('id',fid,'replayed',false,'result',crm_private.reality_read_core(bid,s));insert into crm_private.b04_reality_operations values(op,bid,s,actor,fp,r,clock_timestamp());return r;
end$$;
create function crm_api.reality_apply(f2p bytea,f2s bytea,f1p bytea,f1s bytea,q bytea)returns jsonb language plpgsql volatile security definer set search_path=pg_catalog,pg_temp as $$declare h text[];t text[];fs text[];r jsonb;begin
 h:=crm_f2.admit(f2p,f2s,q,'C03','write_evidence');t:=crm_f1.verify_envelope(f1p,f1s,q,'C03','evidence','write_evidence');if h[17]is distinct from t[14]then raise exception 'REALITY_DENIED';end if;fs:=crm_f1.fields(q);if cardinality(fs)<>2 or fs[1]<>'CRM-H4-REALITY1'then raise exception 'REALITY_INPUT_INVALID';end if;
 r:=crm_private.reality_core(fs[2]::jsonb,h[17],h[12]::uuid);perform crm_f2.verify(f2p,f2s,q,'C03','human_evidence','write_evidence');perform crm_f1.verify_envelope(f1p,f1s,q,'C03','evidence','write_evidence');return r;
end$$;
create function crm_api.reality_read(f2p bytea,f2s bytea,f1p bytea,f1s bytea,q bytea)returns jsonb language plpgsql volatile security definer set search_path=pg_catalog,pg_temp as $$declare h text[];t text[];fs text[];a jsonb;r jsonb;bid uuid;begin
 h:=crm_f2.admit(f2p,f2s,q,'C01','read_evidence');t:=crm_f1.verify_envelope(f1p,f1s,q,'C01','evidence','read_evidence');if h[17]is distinct from t[14]then raise exception 'REALITY_DENIED';end if;fs:=crm_f1.fields(q);if cardinality(fs)<>2 or fs[1]<>'CRM-H4-REALITY-READ1'then raise exception 'REALITY_INPUT_INVALID';end if;a:=fs[2]::jsonb;if not(a?'bookingId')or a-'bookingId'<>'{}'::jsonb then raise exception 'REALITY_INPUT_INVALID';end if;bid:=(a->>'bookingId')::uuid;
 if not exists(select 1 from crm_private.b04_bookings where booking_id=bid and admin_scope=h[17])then return null;end if;perform crm_private.booking_preparation_lock(bid);r:=crm_private.reality_read_core(bid,h[17]);perform crm_f2.verify(f2p,f2s,q,'C01','human_evidence','read_evidence');perform crm_f1.verify_envelope(f1p,f1s,q,'C01','evidence','read_evidence');return r;
end$$;
create function crm_api.reality_sensitive(f2p bytea,f2s bytea,f1p bytea,f1s bytea,q bytea,a jsonb)returns jsonb language plpgsql volatile security definer set search_path=pg_catalog,pg_temp as $$declare h text[];t text[];fs text[];part text[];res crm_ha.reservations;r jsonb;begin
 if session_user<>'crm_h0_ha_tx'then raise exception 'REALITY_TTE_REQUIRED';end if;h:=crm_f2.verify(f2p,f2s,q,'C03','human_core_probe','apply_probe_batch');t:=crm_f1.verify_envelope(f1p,f1s,q,'C03','human_approval','manage_effect');fs:=crm_f1.fields(q);if h[17]is distinct from t[14]or fs[1]<>'CRM-H0-M04'or fs[2]<>'reserve'then raise exception 'REALITY_TTE_REQUIRED';end if;
 select *into strict res from crm_ha.reservations where reservation_id=fs[3];select crm_f1.fields(material_payload)into part from crm_ha.parts where proposal_id=res.proposal_id and part_id=res.part_id;
 if part[3]<>'operational-reality'or part[5]::jsonb is distinct from a or part[6]<>'value'or part[7]is distinct from a->>'bookingId'or part[12]<>h[17]or part[13]<>'record-operational-reality'then raise exception 'REALITY_APPROVAL_MATERIAL_CHANGED';end if;
 r:=crm_private.reality_core(a,h[17],h[12]::uuid,true);if not exists(select 1 from crm_private.b04_reality_approvals where reservation_id=res.reservation_id)then insert into crm_private.b04_reality_approvals values(res.reservation_id,(a->>'operationId')::uuid,(a->>'bookingId')::uuid,h[17],crm_private.reality_material((a->>'bookingId')::uuid,h[17]));end if;perform crm_f2.verify(f2p,f2s,q,'C03','human_core_probe','apply_probe_batch');return r;
end$$;
create function crm_api.reality_finalize(command_id text)returns void language plpgsql volatile security definer set search_path=pg_catalog,pg_temp as $$declare x crm_private.b04_reality_approvals;begin
 if session_user<>'crm_h0_ha_tx'then raise exception 'REALITY_TTE_REQUIRED';end if;select *into x from crm_private.b04_reality_approvals where reservation_id=command_id;if not found then raise exception 'REALITY_FINAL_CHECK_REQUIRED';end if;
 if not exists(select 1 from crm_private.b04_reality_operations where operation_id=x.operation_id and xmin::text=pg_current_xact_id()::text)then return;end if;
 -- Replay remains a historical result; fresh effects already share the material lock.
 if crm_private.reality_material(x.booking_id,x.admin_scope)is distinct from x.material or not exists(select 1 from crm_private.b04_reality_events where operation_id=x.operation_id)then raise exception 'REALITY_FINAL_CHECK_FAILED';end if;
end$$;
-- Existing Modification remains the sole cancellation authority. Database facts cannot be omitted.
create function crm_private.reality_modification_guard(p jsonb,bid uuid,s text)returns jsonb language plpgsql stable set search_path=pg_catalog,pg_temp as $$declare facts jsonb;f jsonb;x jsonb;ids jsonb:='[]';sc jsonb;performed numeric:=0;total numeric:=0;begin
 if (crm_private.modification_scope(p->'scope',bid,s)->>'cancelled')::boolean and p->'desired'->'cancelled'='false'::jsonb then raise exception 'MODIFICATION_TERMINAL_ORIGIN_REQUIRED:E3';end if;facts:=crm_private.reality_facts(bid,s);if facts='[]'::jsonb then return '{}'::jsonb;end if;
 for f in select value from jsonb_array_elements(facts)loop for x in select value from jsonb_array_elements(f->'scopes')loop
 if p->'scope'->>'kind'='booking'or(p->'scope'->>'kind'='service'and p->'scope'->'id'=x->'serviceId')or(p->'scope'->>'kind'='night'and p->'scope'->'id'=x->'nightId')or(p->'scope'->>'kind'='contribution'and(p->'scope'->'id'=x->'contributionId'or exists(select 1 from crm_private.b04_contributions c where c.contribution_id=(p->'scope'->>'id')::uuid and c.service_id=(x->>'serviceId')::uuid)))then
 ids:=ids||jsonb_build_array(f->'factId');performed:=performed+(x->>'amount')::numeric;
 if p->'desired'?(x->>'dimension')and(p->'desired'->>(x->>'dimension'))::numeric<(x->>'start')::numeric+(x->>'amount')::numeric then raise exception 'MODIFICATION_PRIOR_PERFORMANCE_REQUIRED:E3';end if;
 if p->'desired'->'cancelled'='true'::jsonb and p->'scope'->>'kind'='booking'then raise exception 'MODIFICATION_PRIOR_PERFORMANCE_REQUIRED:E3';end if;
 end if;end loop;end loop;
 if ids='[]'::jsonb then return '{}'::jsonb;end if;if p->'scope'->>'kind'<>'booking'and crm_private.reality_service_state(bid,coalesce(p->'scope'->>'serviceId',p->'scope'->>'id')::uuid,s)='Ejecutado'then raise exception 'MODIFICATION_PRIOR_PERFORMANCE_REQUIRED:E3';end if;if p->'desired'?|array['date','schedule','place','provider','variant','capacity','conditions','unitRevisionId']then raise exception 'MODIFICATION_PRIOR_PERFORMANCE_REQUIRED:E3';end if;
 if p->'desired'->'cancelled'='true'::jsonb then
 for sc in select value from jsonb_array_elements(crm_private.reality_scopes(bid,s))loop
 if p->'scope'->>'kind'='service'and sc->'serviceId'=p->'scope'->'id'or p->'scope'->>'kind'='night'and sc->'nightId'=p->'scope'->'id'or p->'scope'->>'kind'='contribution'and sc->'contributionId'=p->'scope'->'id'then total:=total+(sc->>'current')::numeric;end if;end loop;
 if total>0 and performed>=total then raise exception 'MODIFICATION_PRIOR_PERFORMANCE_REQUIRED:E3';end if;
 end if;return jsonb_build_object('performanceRetained',ids,'cancelledRemainderOnly',p->'desired'->'cancelled'='true'::jsonb);
end$$;
create function crm_private.reality_service_state(bid uuid,sid uuid,s text)returns text language plpgsql stable set search_path=pg_catalog,pg_temp as $$declare scopes jsonb;p numeric;unresolved boolean;begin
 select coalesce(jsonb_agg(value),'[]'),coalesce(sum((value->>'performed')::numeric),0),coalesce(bool_or(not(value->>'resolved')::boolean),true)into scopes,p,unresolved from jsonb_array_elements(crm_private.reality_scopes(bid,s))where value->>'serviceId'=sid::text;
 if p>0 and not unresolved then return 'Ejecutado';end if;return null;
end$$;
create function crm_private.reality_projection(r jsonb,s text)returns jsonb language plpgsql stable set search_path=pg_catalog,pg_temp as $$declare bid uuid;sv jsonb;services jsonb:='[]';v jsonb;phase text;st text;begin
 if r is null then return null;end if;bid:=(r->'booking'->>'booking_id')::uuid;v:=crm_private.reality_read_core(bid,s);phase:=v->>'phase';
 for sv in select value from jsonb_array_elements(r->'booking'->'detail'->'services')loop
 st:=crm_private.reality_service_state(bid,(sv->>'id')::uuid,s);services:=services||jsonb_build_array(sv||jsonb_build_object('state',coalesce(st,sv->>'state'),'performance',(select coalesce(jsonb_agg(value),'[]')from jsonb_array_elements(v->'scopes')where value->'serviceId'=sv->'id'),'incidents',(select coalesce(jsonb_agg(value),'[]')from jsonb_array_elements(v->'incidents')where value->'scope'->'serviceId'=sv->'id' or not(value->'scope'?'serviceId'))));
 end loop;
 if phase is not null then r:=jsonb_set(r,'{booking,state}',to_jsonb(phase));end if;
 if v->'history'<>'[]'::jsonb or v->'incidents'<>'[]'::jsonb then r:=jsonb_set(r,'{booking,detail,services}',services);r:=r||jsonb_build_object('operationalReality',v);end if;return r;
end$$;
-- Declared deliberate adaptations: preserve existing OID/signature/owner/ACL/config.
do $$declare body text;before text;begin
 body:=pg_get_functiondef('crm_api.modification_apply(bytea,bytea,bytea,bytea,bytea,bytea,bytea,bytea,bytea,bytea)'::regprocedure);before:=body;
 body:=replace(body,'if p->''desired''->''cancelled''=''true''::jsonb and exists','if crm_private.reality_modification_guard(p,bid,s)=''{}''::jsonb and p->''desired''->''cancelled''=''true''::jsonb and exists');
 body:=replace(body,'x:=cur||(p->''desired'')||jsonb_build_object','x:=cur||(p->''desired'')||crm_private.reality_modification_guard(p,bid,s)||jsonb_build_object');if body=before then raise exception 'REALITY_MODIFICATION_ANCHOR_MISSING';end if;execute body;
 body:=pg_get_functiondef('crm_private.modification_cancelled(uuid,text)'::regprocedure);before:=body;body:=replace(body,'select exists','select crm_private.reality_facts(bid,s)=''[]''::jsonb and exists');if body=before then raise exception 'REALITY_CANCELLATION_ANCHOR_MISSING';end if;execute body;
 body:=pg_get_functiondef('crm_private.booking_preparation_core(jsonb,text,uuid,boolean)'::regprocedure);before:=body;body:=replace(body,'if coalesce((inputs#>>','if crm_private.reality_phase(bid,s)is not null then raise exception ''BOOKING_PREPARATION_ORIGIN_REQUIRED:E3'';end if;\n if coalesce((inputs#>>');if body=before then raise exception 'REALITY_PREPARATION_ANCHOR_MISSING';end if;execute replace(body,E'\\n',E'\n');
 body:=pg_get_functiondef('crm_api.booking_preparation_read(bytea,bytea,bytea,bytea,bytea)'::regprocedure);before:=body;body:=replace(body,'phase:=case when coalesce','phase:=case when crm_private.reality_phase(bid,hf[17])is not null then crm_private.reality_phase(bid,hf[17])when coalesce');if body=before then raise exception 'REALITY_READER_ANCHOR_MISSING';end if;
 body:=replace(body,'perform crm_f2.verify(f2p,f2s,q,''C01''','r:=r||jsonb_build_object(''operationalReality'',crm_private.reality_read_core(bid,hf[17]));perform crm_f2.verify(f2p,f2s,q,''C01''');execute body;
 body:=pg_get_functiondef('crm_api.booking_read(bytea,bytea,bytea,bytea,bytea)'::regprocedure);before:=body;body:=replace(body,'r:=crm_private.modification_projection(r,hf[17]);','perform crm_private.booking_preparation_lock((a->>''bookingId'')::uuid);r:=crm_private.reality_projection(crm_private.modification_projection(r,hf[17]),hf[17]);');if body=before then raise exception 'REALITY_BOOKING_READER_ANCHOR_MISSING';end if;execute body;
 body:=pg_get_functiondef('crm_private.booking_preparation_writer()'::regprocedure);before:=body;body:=replace(body,'elsif x?''modification_id''','elsif x?''incident_id'' then select array[booking_id]into ids from crm_private.b07_incidents where incident_id=(x->>''incident_id'')::uuid;\n elsif x?''modification_id''');if body=before then raise exception 'REALITY_INCIDENT_LOCK_ANCHOR_MISSING';end if;execute replace(body,E'\\n',E'\n');
end$$;
create trigger preparation_material_lock before insert on crm_private.b07_incident_revisions for each row execute function crm_private.booking_preparation_writer();
create trigger preparation_material_lock before insert on crm_private.b04_reality_events for each row execute function crm_private.booking_preparation_writer();
-- View keeps its original OID and columns; state is composed from actual resolved portions.
do $$declare body text;begin body:=pg_get_viewdef('crm_private.b04_current_services'::regclass,true);body:=replace(body,'CASE','CASE WHEN crm_private.reality_service_state(v.booking_id,v.service_id,v.admin_scope) IS NOT NULL THEN crm_private.reality_service_state(v.booking_id,v.service_id,v.admin_scope)');execute 'create or replace view crm_private.b04_current_services with(security_invoker=true) as '||body;end$$;
do $$declare f record;begin for f in select p.oid,n.nspname,p.proname from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in('crm_private','crm_api')and p.proname like'reality_%'loop
 execute format('alter function %s owner to %I',f.oid::regprocedure,case when f.nspname='crm_api'then 'crm_h0_f2_executor'else 'crm_h0_f2_owner'end);execute format('revoke all on function %s from public,crm_h0_runtime,crm_h0_ha_tx',f.oid::regprocedure);
 if f.proname in('reality_sensitive','reality_finalize')then execute format('grant execute on function %s to crm_h0_ha_tx',f.oid::regprocedure);elsif f.nspname='crm_api'then execute format('grant execute on function %s to crm_h0_runtime',f.oid::regprocedure);else execute format('grant execute on function %s to crm_h0_f2_executor,crm_h0_migration',f.oid::regprocedure);end if;
end loop;end$$;
revoke create on schema crm_private from crm_h0_f2_owner,crm_h0_f2_executor;revoke create on schema crm_api from crm_h0_f2_executor;
commit;
